wazuh/wazuh-packages

- rpms/specs/wazuh-manager-2.0.spec
Allow group write permissions so the API can properly remove agents
Fixes https://github.com/wazuh/wazuh/issues/116
> Fix Permissions for API

- debs/wazuh-agent/debian/changelog
- debs/wazuh-agent/debian/patches/SourceToDeb
The wazuh-agent package currently fails to upgrade from ossec-hids-agent
(and possibly others) because the "replace_manager_ip.sh" script is
missing from the /var/ossec/tmp/src/init directory. The Debian postinst
script attempts to call it but it's not there, so the postinst script
exits with an error status.
> Fix missing "replace_manager_ip.sh" script

- debs/wazuh-agent/debian/postinst
Related to Issue #16 Ubuntu deb package broken with nonexec /tmp
There is an malformed option for rm in the debian package for wazuh-agent. This causes unattended-updates to fail, as well as installing from apt-get || dselect leaves package in unconfigured state.
**Related issue**:      16
**Related PR**:          None
**Branch**:                 None
**Documentation**:   None
Do a fresh install of wazuh-agent 3.3.0 ( stretch Debian 9 )
Run dselect and update to wazuh-agent 3.3.1
dselect run fails on post-install configure process
Work around
exit dselect
rm -rf /tmp/wazuh-agent
rerun dselect and run install/configure
> 20180625 jhowe Fix postinstall/config for package upgrades

- debs/SPECS/3.6.0/wazuh-agent/debian/postrm
- debs/SPECS/3.6.0/wazuh-manager/debian/postrm
Hi team,
this PR solves #40. The `remove` option works fine but when you execute `apt-get purge wazuh-*****` in a Debian based OS with `systemd`, the purge option will fail.
This problem was caused by these lines: https://github.com/wazuh/wazuh-packages/blob/dfb98f72ddf32eae18f1ee879d6f2f191b674ffe/debs/SPECS/3.6.0/wazuh-manager/debian/postrm#L44-L48
Now it works fine.
Regards,
Braulio.
> Fix purge option for wazuh-manager and wazuh-agent packages

- debs/SPECS/3.6.1/wazuh-agent/debian/postinst
- debs/SPECS/3.6.1/wazuh-agent/debian/postrm
- debs/SPECS/3.6.1/wazuh-agent/debian/preinst
Now the Debian packages are using a new temporal folder to backup configuration files when upgrading, it just doing it just a security measure to prevent overwrites.
> 3.6.1 Debian specs: Prevent ossec.conf and client.keys overwrites.

- rpms/CentOS/6/i386/Dockerfile
- rpms/SPECS/3.6.1/wazuh-agent-3.6.1.spec
- rpms/SPECS/3.6.1/wazuh-api-3.6.1.spec
- rpms/SPECS/3.6.1/wazuh-manager-3.6.1.spec
Hi team,
this PR includes the new RPM specs for Wazuh 3.6.1. Also, this PR includes fixes for the following issues:
- Improved remove behavior when uninstalling the wazuh-api (#50).
- Delete the `ossec` users when uninstalling the package: (#45).
In addition, this commit https://github.com/wazuh/wazuh-packages/commit/af12a5ff568f8ca2eaf8499d1b54233dbefbbe0d fixes a problem when building the i386 Docker image used for building the i386 .rpm packages.
Regards,
Braulio.
> RPM specs for Wazuh 3.6.1

- rpms/SPECS/3.7.0/wazuh-agent-3.7.0.spec
- rpms/SPECS/3.7.0/wazuh-api-3.7.0.spec
- rpms/SPECS/3.7.0/wazuh-manager-3.7.0.spec
Hi team,
in this PR I made several improvements to the RPM specs of Wazuh (issue #21). Those improvements are:
- Use the `install.sh` script to build the packages.
- Remove all the files from `/tmp` and `/usr/share/wazuh-****`. Now all the files are stored inside of `/var/ossec` directory.
- Remove unnecessary lines from the RPM specs.
- Improved the %file section for each spec.
Best regards,
Braulio.
> Improve RPM specs for Wazuh v3.7.0

- debs/SPECS/3.7.0/wazuh-agent/debian/postrm
- debs/SPECS/3.7.0/wazuh-agent/debian/prerm
- debs/SPECS/3.7.0/wazuh-manager/debian/postrm
- debs/SPECS/3.7.0/wazuh-manager/debian/prerm
Hi team,
with the latest changes in the .deb packages to save the _conffiles_ of the package, if the `${DIR}\etc` is missing, the package will fail if you execute `apt remove wazuh-manager` or `apt remove wazuh-agent`.
This PR fix this error.
Regards,
Braulio.
> Avoid errors uninstalling the package when /var/ossec/etc is missing

- rpms/SPECS/3.7.0/wazuh-agent-3.7.0.spec
- rpms/SPECS/3.7.0/wazuh-manager-3.7.0.spec
Hi team,
this PR solves #72. In addition, I removed the output of some commands from the package to make it a cleaner installation.
Regards,
Braulio.
> Keep the content of the configuration files when downgrading from 3.7.0

- rpms/SPECS/3.7.0/wazuh-api-3.7.0.spec
Hi team,
this PR solves the issue https://github.com/wazuh/wazuh-api/issues/224. The caused of the problem was this line: https://github.com/wazuh/wazuh-packages/blob/df85f4028bc66238121f3be3eeaf82a2e41dae32/rpms/SPECS/3.7.0/wazuh-api-3.7.0.spec#L96-L99
After installing the new files from the new package, the wazuh-api service must be reloaded before executing `systemctl stop wazuh-api.service` or any other command, otherwise, the `stop` will fail.
What I've done, is to remove the `systemctl stop wazuh-api.service` line, execute the `systemctl daemon-reload` and then, restart the service.
Regards,
Braulio.
> Avoid errors when upgrading the Wazuh API from previous versions

- debs/SPECS/3.7.0/wazuh-api/debian/control
Hi team, 
this PR solves the issue #87. The fix consists on setting the wazuh-manager version using a range instead of setting to an exact version. This change allows the compatibility between package's revisions.
Regards,
Braulio.
> Fix Depends field for Wazuh API package

- rpms/SPECS/3.7.0/wazuh-agent-3.7.0.spec
- rpms/SPECS/3.7.0/wazuh-manager-3.7.0.spec
Getting rid of useless messages when uninstalling the packages.
> libsemanage.semanage_direct_remove_key: Removing last wazuh module (no other wazuh module exists at another priority).
The message prompts everytime the packages remove Wazuh SE module:
> semodule -r wazuh
> Silence SE module unload: Removing last wazuh module (no other wazuh module exists at another priority).

- rpms/SPECS/3.7.0/wazuh-agent-3.7.0.spec
- rpms/SPECS/3.7.0/wazuh-manager-3.7.0.spec
Hi team,
this PR offers a first solution to the issue #86. In Fedora 28, when systemd tries to read `/etc/systemd/system/wazuh-manager.service` or `/etc/systemd/system/wazuh-agent.service`, it fails because SELinux blocks `systemd`. 
The problem is caused by a wrong context in those files. So, the solution is to restore the context of the file using `restorecon`. This will set the correct context, allowing systemd to read the .service files.
BTW, the best solution is to change the directory of the .service files in DEB and RPM packages as you can see https://github.com/wazuh/wazuh-packages/pull/77#issuecomment-431381933 and #86 .
Regards,
Braulio.
> Fix wrong context of .service files in Fedora 28

- debs/SPECS/3.7.0/wazuh-agent/debian/postinst
- debs/SPECS/3.7.0/wazuh-agent/debian/postrm
- debs/SPECS/3.7.0/wazuh-agent/debian/preinst
- debs/SPECS/3.7.0/wazuh-agent/debian/rules
- debs/SPECS/3.7.0/wazuh-api/debian/postinst
- debs/SPECS/3.7.0/wazuh-api/debian/postrm
- debs/SPECS/3.7.0/wazuh-api/debian/preinst
- debs/SPECS/3.7.0/wazuh-api/debian/rules
- debs/SPECS/3.7.0/wazuh-manager/debian/postinst
- debs/SPECS/3.7.0/wazuh-manager/debian/postrm
- debs/SPECS/3.7.0/wazuh-manager/debian/preinst
- debs/SPECS/3.7.0/wazuh-manager/debian/rules
- rpms/SPECS/3.7.0/wazuh-agent-3.7.0.spec
- rpms/SPECS/3.7.0/wazuh-manager-3.7.0.spec
Hi team,
this PR solves two problems of the wazuh-api package:
1. The wazuh-api and wazuh-manager shared the `/var/ossec/tmp` directory to store the configuration files from both packages while they perform and upgrade. When the wazuh-manager finish its installation, it will be restarted and this action will delete all the files and directories stored in `/var/ossec/tmp`. This action destroys the configuration files of the wazuh-api.
2. There's a permissions problem with the wazuh-api package after upgrade from 3.2.x to 3.7.0 version. The script `restore-permissions.sh` is not executed, so the permissions can't be restored, and it is missing because it was destroyed due to the problem explained in 1. 
To solve these problems, I changed the directory where the configuration files are …
> 3.7 installation scripts

- rpms/SPECS/3.7.0/wazuh-agent-3.7.0.spec
- rpms/SPECS/3.7.0/wazuh-manager-3.7.0.spec
Hi team,
this PR fix a problem when upgrading the wazuh-manager and wazuh-agent packages if SELinux is installed and enabled in CentOS 5. The problem was that this check: https://github.com/wazuh/wazuh-packages/blob/2501b2d888479a0bc10073b3a63b82a9d563acc8/rpms/SPECS/3.7.0/wazuh-manager-3.7.0.spec#L412-L414 didn't work when upgrading the package because `gen_ossec.sh` is only loaded when you install the package for the first time.
The fix consists on loading this script always.
Regards,
Braulio.
> Fix SELinux check in CentOS 5

- debs/SPECS/3.7.1/wazuh-manager/debian/postinst
Hi, Team,
This PR solves the issue https://github.com/wazuh/wazuh/issues/1855. This is also related to the issue   https://github.com/wazuh/wazuh/issues/1314.
Best regards.
> Fix typo causing weird file name with a space at the end.

- debs/SPECS/3.7.1/wazuh-manager/debian/postinst
- rpms/SPECS/3.7.0/wazuh-manager-3.7.0.spec
Packages installation must be consistent with sources installation.
We were not removing essential templates files that are designed to be recreated with the new schema when the manager first starts.
It was causing more than one error related to SQL update and inserts after Wazuh upgrade.
install.sh
https://github.com/wazuh/wazuh/blob/master/src/init/wazuh/wazuh.sh#L44-L50
```
rm -f $DIRECTORY/var/db/global.db*
rm -f $DIRECTORY/var/db/.profile.db*
rm -f $DIRECTORY/var/db/.template.db*
rm -f $DIRECTORY/var/db/agents/*
```
> Removing .template.db 

- debs/SPECS/3.7.1/wazuh-manager/debian/postinst
- debs/SPECS/3.7.1/wazuh-manager/debian/preinst
- debs/SPECS/3.7.1/wazuh-manager/debian/rules
- rpms/SPECS/3.7.1/wazuh-manager-3.7.1.spec
Hi team,
this PR solves #100. Now, this option is included in the `rules` files in deb package and in the `%install` section of the RPM package. 
Regards,
Braulio.
> Add USER_CREATE_SSL_CERT option to maanger specs

- rpms/SPECS/3.7.1/wazuh-agent-3.7.1.spec
- rpms/SPECS/3.7.1/wazuh-manager-3.7.1.spec
Hi team,
this PR solves a problem when installing the v3.7.1 packages in CentOS 5. The solution consists of checking if the hosts is a CentOS/RHEL 5 and avoid the installation of the SELinux policy.
Regards,
Braulio.
> Avoid the installation of SELinux policy for CentOS 5

- rpms/SPECS/3.7.1/wazuh-agent-3.7.1.spec
- rpms/SPECS/3.7.1/wazuh-manager-3.7.1.spec
Hello team
This PR solve the Centos 5 version detection. 
Best regards,
> Fixed regex for Centos version detection in Wazuh Agent

- debs/SPECS/3.8.0/wazuh-manager/debian/postinst
- rpms/SPECS/3.8.0/wazuh-manager-3.8.0.spec
Hi team,
in Wazuh v3.8.0, the schema of the _Vulnerability detector_ db has changed, so the upgrade from previous versions to v3.8.0 will produce errors in this module. This PR removes the db and fix the problem.
Regards,
Braulio.
> Remove always Vuln-detector's db

- rpms/SPECS/3.8.1/wazuh-manager-3.8.1.spec
Hi team,
this PR avoids the creation of unnecessary files while upgrading the wazuh-manager using RPM package. 
Best regards,
Braulio.
> 3.8 improve upgrade

- debs/SPECS/3.8.2/wazuh-manager/debian/postinst
- debs/SPECS/3.9.0/wazuh-manager/debian/postinst
- rpms/SPECS/3.8.2/wazuh-manager-3.8.2.spec
- rpms/SPECS/3.9.0/wazuh-manager-3.9.0.spec
Hi team,
We fix on this PR the permission to security-eventchannel list from 770 to 640 and, audit-keys list from 644 to 640 on both systems RPM/DEB.
> Fix cdbs permission from 770 to 640

- rpms/SPECS/3.9.0/wazuh-agent-3.9.0.spec
- rpms/SPECS/3.9.0/wazuh-manager-3.9.0.spec
Hi team,
On this PR we fix a little issue with `configuration-assessment` folder owner and `ruleset` folder on agent that doesn't have right permissions.
Regards.
> Fix 3.9 RPM SPECs

- debs/SPECS/3.9.0/wazuh-agent/debian/rules
- debs/SPECS/3.9.0/wazuh-manager/debian/rules
Hello team
We modified the **rule** file in order to include all the templates candidate to be copied in the target OS installation. This PR solves https://github.com/wazuh/wazuh-packages/issues/110.
Best regards,
> Modified rules file for including all templates

- debs/SPECS/3.9.0/wazuh-api/debian/postrm
- debs/SPECS/3.9.0/wazuh-api/debian/prerm
Hello team
Regarding issue #121, we decided to remove the nullification of ps lines in order to have the change to see if something goes wrong with `ps` command. 
Best regards,
> Removed nullification of ps lines

- rpms/SPECS/3.9.0/wazuh-agent-3.9.0.spec
- rpms/SPECS/3.9.0/wazuh-manager-3.9.0.spec
Hi team,
this PR includes several fixes and improvements over the RPM packages. Here you can find the changes:
- https://github.com/wazuh/wazuh-packages/commit/a138db565c04591debe74d5dceef55b3e6c6073d: set the right permissions for `ruleset/sca` directory.
- https://github.com/wazuh/wazuh-packages/commit/409dff798af6cb7983a3b83c5f808b6ea1e8a3da: Rename the sca templates. This change comes from https://github.com/wazuh/wazuh/pull/2697/.
- https://github.com/wazuh/wazuh-packages/commit/a445f79c534b4e4124969002e4c9fc699b69d380 and https://github.com/wazuh/wazuh-packages/commit/fff2d8a9cc1ad6cea05757ac1daf291df4522402: fixed the support for OpenSUSE hosts.
Regards,
Braulio.
> Rename SLES policies folder and add support for OpenSUSE hosts

- rpms/SPECS/3.9.0/wazuh-agent-3.9.0.spec
Hi team,
this PR fixes the issue #137. The sca files will only be installed if their temporary directory exists. You can find more details about this fix in this comment: https://github.com/wazuh/wazuh-packages/issues/137#issuecomment-472978893.
Regards,
Braulio.
> Fix issues when reinstalling the wazuh-agent 3.9.0 rpm package

- debs/Debian/amd64/Dockerfile
- debs/Debian/i386/Dockerfile
Hi team,
This PR closes #145, we have changed Debian repositories due to end of support of stable repositories so, we have added to sources the repository `archives.debian.org` that contains some of the packages that we was using, we have also applied a static version of some packages to avoid errors on dependencies.
Regards.
> Fix Debian packages repository to build debian packages with archives

- rpms/SPECS/3.9.0/wazuh-manager-3.9.0.spec
Hi team,
this PR closes #146. The fix consists of a temporary rename of the conflicting files that will allow the package to restart the manager without errors and restore the name of conflicting files. You can read more details about this at #146. 
Best regards.
> Avoid duplicate ID errors while restarting the manager

- rpms/SPECS/3.9.0/wazuh-agent-3.9.0.spec
- rpms/SPECS/3.9.0/wazuh-manager-3.9.0.spec
Hi team, 
This PR closes #144. This issue is related to https://github.com/wazuh/wazuh/issues/2927 and resolves the problem at packaging level. To do this it was neccesary to remove `/queue/agents` references from rpms/SPECS/3.9.0/.
For the debian package generation it was not neccesary to make changes.
This was tested on:
Centos6, Centos7, fedora 22 to 29, suse12, ubuntu 14LTS, ubuntu 16LTS, ubuntu 18LTS, debian 8 and 9
Regards,
Daniel Folch.
> Removed unused directory /ossec/queue/agents from installation

- debs/SPECS/3.9.0/wazuh-agent/debian/postinst
- debs/SPECS/3.9.0/wazuh-agent/debian/rules
Hi team,
this PR closes #150 for Debian based hosts. The fix consists of adding all the SCA files and the `sca.files` templates, select the correct `sca.files` template for the current OS and install the files. Very similar to the solution added in https://github.com/wazuh/wazuh-packages/pull/130, but in Debian hosts. if you reinstall the package, the SCA files will be reinstalled.
This changes was tested in:
- Debian 7-9.
- Ubuntu 18.
Regards.
> Add new SCA files for Debian and Ubuntu hosts

- rpms/SPECS/3.9.0/wazuh-agent-3.9.0.spec
- rpms/SPECS/3.9.0/wazuh-manager-3.9.0.spec
Hi team,
This PR closes #152 by setting the right permissions, owner and group to:
- `ruleset/sca` directory.
- `ruleset/sca/*` files.
- `bin/update_ruleset` script.
> Fix wrong file permissions in RPM packages

- rpms/SPECS/3.9.0/wazuh-agent-3.9.0.spec
- rpms/build.sh
Hello team,
This PR closes #154. The fix consists of adding a conditional sentence that modifies the compilation flags depending on the architecture.
https://github.com/wazuh/wazuh-packages/blob/2de081d3fd90083b03e641bb814a6c0cc1763080/rpms/SPECS/3.9.0/wazuh-agent-3.9.0.spec#L53-L63
I have run the following tests:
Compilation
Installation 
Upgrade
Regards,
Daniel Folch
> Wazuh agent RPM package generation be adapted for i386 compilation

- debs/SPECS/3.9.0/wazuh-manager/debian/postinst
Hello team,
This PR closes #111. The fix consists of removing the line https://github.com/wazuh/wazuh-packages/blob/97150b3091368445db003ab9891c67c1d9e1f79b/debs/SPECS/3.9.0/wazuh-manager/debian/postinst#L108 because `wazuh-db` removes this file automatically.
I have done the following tests:
Compilation:
Instalation
Upgrade
Regards,
Daniel Folch
> .template.db must be removed by wazuh-db

- debs/SPECS/3.9.0/wazuh-manager/debian/postinst
Hello team
Thanks, @okynos for the commit, this PR pretends to fix the permissions discrepancies due to a Debian automatic overwrite permissions in the generation stage of the package. 
Best regards, 
Alberto R
> Fix python libraries and binaries permissions on postinstall in Manager

- rpms/SPECS/3.9.0/wazuh-agent-3.9.0.spec
- rpms/SPECS/3.9.0/wazuh-manager-3.9.0.spec
Hi team,
This PR closes #160. It consists of porting the changes from https://github.com/wazuh/wazuh-packages/pull/119 to v3.9.0 rpm specs.
Regards.
> Remove unncessary .rpmnew files after upgrading to v3.9.0

- debs/SPECS/3.9.1/wazuh-agent/debian/postinst
- debs/SPECS/3.9.1/wazuh-agent/debian/rules
Hi team,
this PR closes #172 by adding the sca.files for Ubuntu 14.04 and a new if/else block to set the proper path to that file in the post-install script.
Tested on:
- Ubuntu 12.04
- Ubuntu 14.04
- Ubuntu 18.04
Regards.
> Fix the installation of SCA files for Ubuntu 14.04

- rpms/SPECS/3.10.0/wazuh-agent-3.10.0.spec
- rpms/SPECS/3.10.0/wazuh-manager-3.10.0.spec
- rpms/SPECS/3.9.2/wazuh-agent-3.9.2.spec
- rpms/SPECS/3.9.2/wazuh-manager-3.9.2.spec
Hello team
This PR solves #180. 
Packages built: wazuh-agent & wazuh-manager x86_64
[Wazuh Manager 3.9.2](https://packages-dev.wazuh.com/warehouse/test/3.9/yum/wazuh-manager-3.9.2-redhat8.x86_64.rpm)
[Wazuh Manager 3.10](https://packages-dev.wazuh.com/warehouse/test/3.9/yum/wazuh-manager-3.10.0-redhat8.x86_64.rpm)
[Wazuh Agent 3.9.2](https://packages-dev.wazuh.com/warehouse/test/3.9/yum/wazuh-agent-3.9.2-redhat8.x86_64.rpm)
[Wazuh Agent 3.10](https://packages-dev.wazuh.com/warehouse/test/3.9/yum/wazuh-agent-3.10.0-redhat8.x86_64.rpm)
**Installation test**
**Upgrade test (3.10)**
**Uninstall test (3.9)**
> Fix Wazuh services RHEL 8

- debs/SPECS/3.10.0/wazuh-agent/debian/postinst
- debs/SPECS/3.10.0/wazuh-agent/debian/rules
- debs/SPECS/3.9.2/wazuh-agent/debian/postinst
- debs/SPECS/3.9.2/wazuh-agent/debian/rules
Hi team,
This PR closes #174. I've added this enhancement to v3.9.2 and v3.10.0 specs.
**Installation tests**
**Upgrade tests**
**Notes**
On Ubuntu 12.04 hosts, the upgrade from 3.9.1 to 3.9.2 or greater, you will find the following configuration and files:
```
root@bebb7f1f57dc:/# more /var/ossec/etc/ossec.conf
...
<sca>
<enabled>yes</enabled>
<scan_on_start>yes</scan_on_start>
<interval>12h</interval>
<skip_nfs>yes</skip_nfs>
<policies>
<policy>cis_debian_linux_rcl.yml</policy>
<policy>system_audit_rcl.yml</policy>
<policy>system_audit_ssh.yml</policy>
<policy>system_audit_pw.yml</policy>
</policies>
</sca>
...
root@bebb7f1f57dc:/# ls -1 /var/ossec/ruleset/sca/
cis_debian_linux_rcl.yml
cis_debianlinux7-8_L1_rcl.yml
cis_debianlinux7-8_L2_rcl.yml
system_audit_pw.yml
system_audit_rcl.yml …
```
> Add Ubuntu 12.04 specific policies

- debs/SPECS/3.10.0/wazuh-manager/debian/postinst
- rpms/SPECS/3.10.0/wazuh-manager-3.10.0.spec
|---|
|#183|
We discovered that we got an error message during **Wazuh manager installation in Ubuntu 18**.
~~~
Can't load /root/.rnd into RNG
139871618495552:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/root/.rnd
~~~
The error is due **OpenSSL version**, concretly **v1.1.1**. This error is fixed by OpenSSL in **v1.1.1a**.
Despite de error message, OpenSSL works well. It generates diferent keys and certificates values, so we have just **ignored the error message**.
At `wazuh-packages/debs/SPECS/3.10.0/wazuh-manager/debian/postinst` we have changed, for **debs** packages, **Generation auto-signed**, adding `2>/dev/null` when the key and certicate is created.
In the same way, we have changed …
> Fixed error message from openssl v1.1.1 debs and rpms packages

- debs/generate_debian_package.sh
- rpms/generate_rpm_package.sh
Hello team,
This PR closes #204.
We have added `exit 1` to docker build and docker run calls in order to receive the error code.
We have tested and it works as expected.
Regards.
> Added exit to docker build & docker run on rpm & deb

- debs/README.md
- debs/build.sh
- rpms/CentOS/6/i386/Dockerfile
- rpms/CentOS/6/x86_64/Dockerfile
- rpms/README.md
- rpms/SPECS/3.10.0/wazuh-agent-3.10.0.spec
- rpms/SPECS/3.10.0/wazuh-manager-3.10.0.spec
- rpms/SPECS/3.9.3/wazuh-agent-3.9.3.spec
- rpms/SPECS/3.9.3/wazuh-manager-3.9.3.spec
- rpms/build.sh
- rpms/generate_rpm_package.sh
Hi team,
This PR closes #201 by adding a feature to create deb packages with debugging symbols and _debuginfo_ rpm packages containing the debugging symbols from each binary.
Regards.
> Create deb and rpm packages with debugging symbols

- solaris/solaris10/generate_wazuh_packages.sh
- solaris/solaris10/pkginfo
Hello team,
This PR closes  #222, I have added a sed that changes the pkginfo file before creating the package:
https://github.com/wazuh/wazuh-packages/blob/7e78d1e481fde9fc76a0bf5e7b8b71a11dc5cddc/solaris/solaris10/generate_wazuh_packages.sh#L166
And changed the email in the pkginfo file.
Tested in:
Regards,
Daniel Folch
>  pkginfo not updated solaris10

- debs/SPECS/3.10.0/wazuh-agent/debian/postinst
- debs/SPECS/3.9.4/wazuh-agent/debian/postinst
- rpms/SPECS/3.10.0/wazuh-agent-3.10.0.spec
- rpms/SPECS/3.9.4/wazuh-agent-3.9.4.spec
Hi team,
This PR closes #229, #226. The .deb packages now include a check for Debian 10 that will install the generic SCA file for Debian based OS. RPM packages now include a check to improve the detection of the OS. If there aren't any SCA files for the host where the package is installed, the generic SCA files are installed.
Tests:
Regards.
> Fix missing SCA files on Debian 10 and RHEL 8

- ova/Libraries/elastic_functions.sh
- ova/Libraries/wazuh_functions.sh
- ova/generate_ova.sh
Hi team,
This PR closes #239. The vagrant halt command wasn't working properly because the vagrant user no longer exists on the box after running vagrant up. This forces vagrant to force the halt in the box which may cause errors like missing files.
Using `vagrant suspend` we can "stop" the box and create the OVA without generating errors.
Regards.
> Include Wazuh and Elastic repos in the OVA

- wpk/run.sh
|----------|
[3753](https://github.com/wazuh/wazuh/issues/3753)
At the moment, when we generate the packages WPK, the templates are deleted at the start of the funcion `clean` . This causses that, the policies SCA, aren't added to the packages. To resolve this problem, I am going to prevent that the  files `sca.files` are deleted of the folder `templates`. 
When we updates the agent with `upgrade_agents` we receive the next message at the instalation of the SCA policies
```
Stopping Wazuh...
Wait for success...
success
SCA policies not available for this OS version centos 7 6.
Starting Wazuh...
```
The message told us, that the templates of the SCA policies are not available. If we check the folder `/var/ossec/ruleset/sca` we can see:
```
ls -la /var/ossec/ruleset/sca/ …
```
> WPK don't add the templates

- solaris/solaris11/generate_wazuh_packages.sh
Hello team,
This PR closes #247, in this PR we are removing the dependencies of the Solaris 11 package.
These dependencies that are calculated here:
https://github.com/wazuh/wazuh-packages/blob/d5997c5aeb8d04a0f8eec8da0350ca2782b99d41/solaris/solaris11/generate_wazuh_packages.sh#L149-L150
Are not really needed, and make it impossible to install the package in older versions of Solaris 11 than the one where we build the package.
For this reason, we have decided to remove the dependencies.
I have tested the new package in:
Regards,
Daniel Folch
> Remove Solaris11 dependencies

- ova/README.md
Hello team,
This PR closes #264. I have changed the old combination of elastic and wazuh versions that didn't have a corresponding app version for one that does.
Regards,
Daniel Folch
> Wrong elastic version in OVA readme

- debs/SPECS/3.10.0/wazuh-agent/debian/postrm
- debs/SPECS/3.10.0/wazuh-manager/debian/postrm
- debs/SPECS/3.11.0/wazuh-agent/debian/postrm
- debs/SPECS/3.11.0/wazuh-manager/debian/postrm
Hello team,
This PR closes #262, I have added a find command that deletes the old .save files before creating the new ones:
https://github.com/wazuh/wazuh-packages/blob/d5415a37d6c72af58a920fa860c88a531ac3d473/debs/SPECS/3.10.0/wazuh-manager/debian/postrm#L57
I have generated packages and tested them in the following systems:
|                          | Ubuntu 14 LTS       |  Ubuntu 16 LTS       |  Ubuntu 18 LTS        |
|:--------------------|-------------------------:|:-------------------------:|:-------------------------:|  
|   Agent              |  <ul><li>- [x] </li>    |  <ul><li>- [x] </li>      |  <ul><li>- [x] </li>     |
|   Manager         |  <ul><li>- [x] </li>    |  <ul><li>- [x] </li>      |  <ul><li>- [x] </li>     |
Regards,
Daniel Folch
> Delete old .save files in Debian installation

- solaris/solaris11/generate_wazuh_packages.sh
Hello team, 
In this PR I have performed the followings changes:
Regards.
Jonathan M.V
> 273 redundant gmake

- debs/SPECS/3.10.0/wazuh-agent/debian/postinst
- debs/SPECS/3.10.0/wazuh-agent/debian/rules
- debs/SPECS/3.10.0/wazuh-manager/debian/postinst
- debs/SPECS/3.10.0/wazuh-manager/debian/rules
- debs/SPECS/3.11.0/wazuh-agent/debian/postinst
- debs/SPECS/3.11.0/wazuh-agent/debian/rules
- debs/SPECS/3.11.0/wazuh-manager/debian/postinst
- debs/SPECS/3.11.0/wazuh-manager/debian/rules
Hi team,
This issue closes #279. The fix consists of removing the logs file from the package and now, those logs files are created by the binaries. This makes the logs files unknown for the package, so they won't be overwritten by it.
In addition, this fix only will be applied if you upgrade the packages from 3.10.0 to a greater version.
Tests:
> Debian packages overwrite ossec.log file while upgrading

- wpk/unified/linux/Dockerfile
- wpk/windows/Dockerfile
Hi team
This PR closes #289 by removing the unnecessary ssh-keyscan from the Dockerfiles. This command was used to gather the GitHub's public ssh key, allowing the Docker image to clone the GitHub repository by using `git clone git@github:...`.
This wasn't necessary because the Docker images clone the repository using `git clone https://github...` and this method doesn't need any ssh key.
Regards.
> Removed unnecessary ssh-keyscan command

- solaris/solaris10/generate_wazuh_packages.sh
Hello team, in this PR I have fixed the error messages in the building of the Solaris 10 package.
The solution has been to eliminate the redundant lines and modify the position in which the file `/etc/ossec.init.conf` is deleted since this file must be deleted after stopping the Wazuh services.
These changes have been tested on Jenkins, and can be checked at the following link: https://jenkins-staging.wazuh.info/job/Packages_builder_solaris/41/console
In the following image, we can see how the errors indicated in the issue description are no longer shown
close #285 
Best regards.
> Fixed error messages in the building of the Solaris 10 package

- solaris/solaris10/generate_wazuh_packages.sh
- solaris/solaris11/generate_wazuh_packages.sh
Hi team,
This PR closes #292 by adding an `exit 1` if the build process of the agent fails.
Regards.
> Added error codes when compilation fails for Solaris

- aix/generate_wazuh_packages.sh
Hello team, in this PR I add the AIX resizing partitions for Site Ox boxes. It will be executed when the machine is provisioned with the `-e` parameter.
```
./generate_wazuh_packages-sh -e
```
closes #309 
Best regards.
> Added aix resizing partitions for Site Ox boxes

- macos/README.md
- macos/entitlements.plist
- macos/generate_wazuh_packages.sh
Hi team,
This PR closes #316 by adding to `macos/generate_wazuh_packages.sh` a new feature to sign binaries, packages and notarize them. 
You can find more info about this in the attached issue.
Regads.
> Add a tool to notarize macOS package

- rpms/SPECS/3.11.0/wazuh-agent-3.11.0.spec
- rpms/SPECS/3.11.0/wazuh-manager-3.11.0.spec
Hi team,
This PR closes #323 by installing the services files in `/usr/lib/systemd/system/`. This allows using systemd to manage the service of the manager and the agent in CentOS 8.
Tests:
Regards.
> Fixed service's installation path for CentOS 8

- solaris/solaris10/generate_wazuh_packages.sh
- solaris/solaris11/generate_wazuh_packages.sh
Hello team,
This PR reverts the changes done in #331 because that flag is needed for the noncommon packages, I have also added the DISABLE_SHARED=yes flag to the Solaris 11 compilation.
Regards, 
Daniel Folch
> Revert changes in Solaris 10 compilation flags and add new flag to Solaris 11

- solaris/solaris11/SPECS/template_agent_v3.11.0.json
Hello team,
This PR closes #341, I have updated the 3.11.0 SPECS that had outdated permissions.
Regards, 
Daniel Folch
> Update Solaris 11 SPECS for version 3.11.0

- debs/generate_debian_package.sh
- rpms/generate_rpm_package.sh
- splunkapp/generate_wazuh_splunk_app.sh
- wazuhapp/generate_wazuh_app.sh
- wpk/generate_wpk_package.sh
Hello team.
This PR closes  #320. I have added a new flag in `docker run` call to grant container write SELinux permission in the host.
Tests `generate_rpm_package.sh`, `generate_debian_package.sh`,  `generate_wazuh_splunk_app.sh`, `generate_wpk_package.sh` were done in:
Thanks to @timhughes.
Regards.
Alejandro Alguacil
> Added relabel file objects suffixe in docker run

- debs/Debian/amd64/Dockerfile
- debs/Debian/i386/Dockerfile
- debs/Debian/ppc64le/Dockerfile
Hello team,
This PR closes #293. I have added in the Dockerfile debian generation file new command for install  `ps` package.
Tests were done in:
Best regards,
Alejandro Alguacil
> Error executing 'ps' command when generating API package

- debs/generate_debian_package.sh
- macos/generate_wazuh_packages.sh
- rpms/generate_rpm_package.sh
- solaris/solaris10/generate_wazuh_packages.sh
- solaris/solaris11/generate_wazuh_packages.sh
- splunkapp/generate_wazuh_splunk_app.sh
- wazuhapp/generate_wazuh_app.sh
- wpk/generate_wpk_package.sh
Hello team,
This PR closes #326, I have added instruction to remove the folder repository if this exists in the startup build package deb and rpm.
The problem is if the repository folder exists, it caused problems to recreate the package. The solution was to manually delete the folder. Now, this is automatic.
Tests were done for:
Example:
Regards.
Alejandro Alguacil
> Remove repository folder in build package startup

- macos/generate_wazuh_packages.sh
Hello team,
This PR closes #347, I have changed the wrong REGEX for `^2\.` the expression to start with `2` and be followed by the literal `.` .
Regards,
Daniel Folch
> Fix regex that checks for 2.x version

- hpux/generate_wazuh_packages.sh
|Related issue comment|
|---|
|https://github.com/wazuh/wazuh/issues/3319#issuecomment-537429699|
This rework of FIM needs the C99 standard. GCC 4.2.3 (as installed in HP-UX) is compatible with it. However the library _regex_ needs to be updated.
This change aims to do that.
> Make HP-UX build compatible with C99

- debs/SPECS/3.12.0/wazuh-api/debian/postinst
- debs/SPECS/3.12.0/wazuh-api/debian/rules
- rpms/SPECS/3.12.0/wazuh-api-3.12.0.spec
Hi team,
This PR updates #297 to `3.12`. `HTTPS` will be enabled in Wazuh API from `3.12` version. 
Best regards,
Demetrio.
> Enable HTTPS by default in Wazuh API

- windows/generate_wazuh_msi.ps1
Hello team,
This PR adds the necessary changes to the `generate_wazuh_msi.ps1` file to perform the `build win packages` rework proposed in this issue https://github.com/wazuh/wazuh-jenkins/issues/885 and done in this PR https://github.com/wazuh/wazuh-jenkins/pull/994.
The changes made to this PR are as follows:
- Removed unused param `READY_TO_RELEASE`
- Added a new param to specify the path of the executables.
Best regards
> Rework to generate wazuh msi script

- aix/SPECS/3.12.0/wazuh-agent-3.12.0-aix.spec
- rpms/SPECS/3.12.0/wazuh-agent-3.12.0.spec
- rpms/SPECS/3.12.0/wazuh-manager-3.12.0.spec
- solaris/solaris11/SPECS/template_agent_v3.12.0.json
Hello team,
This PR added the new `GCP wodle` files indicated in the https://github.com/wazuh/wazuh-packages/issues/364 issue.
The files that have been modified are the following:
- RPM
-   wazuh-manager-3.12.0.spec 
-  wazuh-agent-3.12.0.spec
- AIX
+  wazuh-agent-3.12.0-aix.spec
- Solaris 11
+ template_agent_v3.12.0.json 
**Checks**
- Debian:
+ [x] manager
+ [x] agent
- RPM:
+ [x] manager
+ [x] agent
- Solaris 11:
+ [x] agent
- macOS:
+ [x] agent
> Added gcloud SPECS

- rpms/CentOS/7/ppc64le/Dockerfile
- rpms/SPECS/3.10.2/wazuh-agent-3.10.2.spec
- rpms/SPECS/3.10.2/wazuh-manager-3.10.2.spec
- rpms/SPECS/3.11.0/wazuh-agent-3.11.0.spec
- rpms/SPECS/3.11.0/wazuh-manager-3.11.0.spec
- rpms/SPECS/3.12.0/wazuh-agent-3.12.0.spec
- rpms/SPECS/3.12.0/wazuh-manager-3.12.0.spec
- rpms/generate_rpm_package.sh
Hi team,
This PR adds the possibility to build RPM packages for `ppc64le` architecture. Here you can find a brief summary of the new changes and additions:
- Added a new Dockerfile of CentOS 7 ppc64le.
- Modified the generation script to accept ppc64le architecture.
- Added the installation of the framework's libsqilte.so.
Also, we added a fix to the `%files` section regarding the permissions of the SCA files for SLES 12.
Thanks to @alberpilot for its contribution :)
> Added support to build RPM packges for ppc64le architecture

- debs/generate_debian_package.sh
- rpms/generate_rpm_package.sh
- windows/generate_compiled_windows_agent.sh
Hi team,
This PR closes #372 by changing the position of the arguments used by `ls`. Now, the arguments appear before the directory, improving the compatibility between Linux and other UNIX systems.
Regards.
> Fixed the line used to list the package name

- solaris/solaris10/generate_wazuh_packages.sh
Hello team,
We have added a little modification to Solaris 10 generation script to avoid user interaction while the package is being generated.
Regards.
> Added unattended process to Solaris 10 generation script

- debs/SPECS/3.11.3/wazuh-manager/debian/changelog
Hello Team, we've detected a typo in the changelog that is breaking the package generation. This PR aims to fix it.
> Update changelog to fix typo

- rpms/build.sh
Hi team,
This PR closes https://github.com/wazuh/wazuh/issues/4505 by adding the _dist macros_ to our custom `.rpmmacros` file. 
With this change, the generic wazuh-agent rpm package is properly compiled, fixing the issue related to whodata.
Regards.
> Added dist macros to our custom rpmmacros file

- solaris/solaris11/generate_wazuh_packages.sh
Hello team,
We have added on this PR a modification to avoid user input during package generation on Solaris 11.
Regards.
> Added unattended modification to solaris 11 Sparc generation script

- solaris/solaris10/generate_wazuh_packages.sh
Hello team,
Closes #394 
We have changed Solaris 10 gmake dependency to avoid failures related with the last version located on OpenCSW repository.
Regards.
> Changed gmake dependency to install older one

- debs/SPECS/3.12.0/wazuh-manager/debian/postinst
- rpms/SPECS/3.12.0/wazuh-manager-3.12.0.spec
Hi team,
This commit https://github.com/wazuh/wazuh/commit/f6dd306cf1a56b113924bc0b919106f190da1ac7 updated the owner, group and permissions of all the files stored in the Python's interpreter directory (`${WAZUH_HOME}/framework/python`). This also has to be changed in our binary packages to avoid bugs or inconsistencies.
Regards.
> Update owner, group and permissions of Python's directory

- aix/SPECS/3.12.0/wazuh-agent-3.12.0-aix.spec
- aix/SPECS/3.12.1/wazuh-agent-3.12.1-aix.spec
- rpms/SPECS/3.12.0/wazuh-agent-3.12.0.spec
- rpms/SPECS/3.12.1/wazuh-agent-3.12.1.spec
Hello team,
In this PR I changed make deps version in the AIX and  RPM SPECS from3.11 to 3.12
Regards,
Daniel Folch
> Change makedeps version in 3.12.x versions

- solaris/solaris10/postinstall.sh
- wpk/generate_wpk_package.sh
- wpk/run.sh
Hello team,
This PR closes #385, by fixing the cause of the error in the logs in Solaris10 clean installations, and add an option to the WPK generation to choose the installation path of Wazuh for the WPK.
Regards,
Daniel Folch
> Add option to create wpk for /opt and fix Solaris 10 log error

- debs/build.sh
- debs/generate_debian_package.sh
- rpms/build.sh
- rpms/generate_rpm_package.sh
Hi team,
This PR closes #358 by adding a new parameter `--sources` to the Debian and RPM build scripts. This parameter receives the path where the Wazuh or Wazuh API sources are stored and uses them to build the binary package instead of downloading it from GitHub.
Regards.
> Added a new parameter to build binary packages using local code

- solaris/solaris11/generate_wazuh_packages.sh
Hello team,
This PR closes #419 
We have added a system headers installation on Solaris 11 provision script.
Regards.
> Added installation of system headers

- rpms/SPECS/3.13.0/wazuh-manager-3.13.0.spec
| Related issue |
|---|
|#282|
Mitre database is created during the installation process and it has to be declared in the SPEC file in order to avoid errors concerning rpm packages building.
> Add Mitre database file to Manager 3.13.0 SPEC file

- rpms/SPECS/3.13.0/wazuh-agent-3.13.0.spec
- rpms/SPECS/3.13.0/wazuh-manager-3.13.0.spec
Hi team,
This PR references #426 and it implements the changes for the RPM packages.
Checks:
Regards.
> Remove OpenSCAP policies in RPM packages

- debs/SPECS/3.13.0/wazuh-agent/debian/postinst
- debs/SPECS/3.13.0/wazuh-agent/debian/preinst
- debs/SPECS/3.13.0/wazuh-agent/debian/rules
- debs/SPECS/3.13.0/wazuh-manager/debian/postinst
- debs/SPECS/3.13.0/wazuh-manager/debian/preinst
- debs/SPECS/3.13.0/wazuh-manager/debian/rules
Hi team,
This PR references #426 and it implements the changes for the Debian packages.
Checks:
Regards.
> Remove OpenSCAP policies in Debian packages

- debs/Debian/arm64/Dockerfile
- debs/Debian/armhf/Dockerfile
Hi team,
This PR solves some issues reported in #365 by @Corruptsector. Here you can see what is changed by this PR:
- Removed duplicated repositories: `debian stretch main` was duplicated in `sources.list` file. 
- Removed `apt` specific version.
- Removed `--allow-downgrades` and `--force-yes` flags.
- Fixed the addition of new repositories. `sources.list` file was overwritten previously, making mandatory setting `apt` version.
- Removed `apt` specific version.
- Removed `--allow-downgrades` and `--force-yes` flags.
Regards.
> Improve ARM build tools

- solaris/solaris11/generate_wazuh_packages.sh
Hello team,
This PR fixes the python problem we were having when upgrading wazuh on the siteox Solaris 11 SPARC machine.
The problem was the condition to install python since it always returned `True` and installed even though it was already installed. This corrupted the installation and caused the next failure:
```
Fatal Python error: PyThreadState_Get: no current thread
```
The condition has been corrected and the changes have been successfully checked.
```
root@sossp152:~# pkg install -g wazuh-agent_v3.13.0-sol11-sparc.p5p wazuh-agent
Packages to update:   1
Create boot environment:  No
Create backup boot environment: Yes
DOWNLOAD                                PKGS         FILES    XFER (MB)   SPEED
Completed                                1/1         13/13    13.9/13.9  108M/s
PHASE …
```
> Fix solaris 11 SPARC python provisioning

- wazuhapp/Docker/Dockerfile
- wazuhapp/Docker/build.sh
Hi team!
For some reason when the package was generated using the `generating_wazuh_app.sh` script some of the files are not included in the package.
I modified the build.sh script to clone the repository instead of downloading it as a zip file, this seems to fix the error.
Regards.
> Fix the wazuh app builder

- debs/SPECS/3.13.1/wazuh-agent/debian/preinst
- debs/SPECS/3.13.1/wazuh-manager/debian/preinst
- rpms/SPECS/3.13.1/wazuh-agent-3.13.1.spec
- rpms/SPECS/3.13.1/wazuh-manager-3.13.1.spec
Hello team, 
This PR redirects the stderr to avoid this message from showing when upgrading from 3.13.0 to 3.13.1 in Debian systems.
```
stat: cannot stat '/var/ossec/wodles/oscap/content/*': No such file or directory
```
Regards,
Daniel Folch
> Redirect stderr in deb SPECS

- wazuhapp/Docker/Dockerfile
- wazuhapp/Docker/build.sh
Hello team,
This PR improves the wazuh app package generation script. 
Now the script installs the exact `yarn` version that is extracted from the `elastic/kibana` repository, and also the script is more adaptable for future changes.
closes #463 
Best regards.
> Update Wazuh kibana app package generation

- rpms/SPECS/4.0.0/wazuh-manager-4.0.0.spec
Hello team,
This PR updates RPM spec file to not expect `migration` and `configure_api` files. Those were removed. Additionally, it ensures `{wazuh_path/logs/api/` folder is created.
Regards.
> Update RPM spec

- rpms/SPECS/4.0.0/wazuh-manager-4.0.0.spec
Hello team, 
In this PR we have added version to the obsolete wazuh-api and removed an unnecessary file from the 4.0.0 RPM SPECS.
Regards,
Daniel Folch
> Remove msu from 4.0.0 RPM SPECs

- aix/SPECS/4.0.0/wazuh-agent-4.0.0-aix.spec
- rpms/SPECS/4.0.0/wazuh-agent-4.0.0.spec
- rpms/SPECS/4.0.0/wazuh-manager-4.0.0.spec
Hi team,
This PRs implements a solution for #480. The installer will detect if the service is running, then stop it if necessary, upgrade and start the service again if it was previously running.
Regards.
> Fixed the stop and restart of the services of RPM packages

- debs/SPECS/4.0.0/wazuh-agent/debian/postinst
- debs/SPECS/4.0.0/wazuh-agent/debian/preinst
- debs/SPECS/4.0.0/wazuh-agent/debian/prerm
- debs/SPECS/4.0.0/wazuh-manager/debian/postinst
- debs/SPECS/4.0.0/wazuh-manager/debian/preinst
- debs/SPECS/4.0.0/wazuh-manager/debian/prerm
- macos/package_files/4.0.0/postinstall.sh
- macos/package_files/4.0.0/preinstall.sh
Hi team,
This in PRs we implemented a solution for #480 in Debian and macOS. The installer will detect if the service is running, then stop it if necessary, upgrade and start the service again if it was previously running.
Regards.
Daniel Folch
>  Fixed the stop and restart of the services of DEB and macOS packages

- rpms/SPECS/4.0.0/wazuh-manager-4.0.0.spec
|---|
| #488 |
Hi team,
This PR closes #488 by updating the permissions of the Wazuh API directory and its files.
```shellsession
[root@357d9f8e5ee6 /]# ls -l /var/ossec/api/configuration/
total 12
-rw-rw---- 1 root ossec 1255 Sep  9 13:47 api.yaml
drwxrwx--- 2 root ossec 4096 Sep  9 13:47 security
drwxrwx--- 2 root ossec 4096 Sep  9 13:47 ssl
[root@357d9f8e5ee6 /]# ls -la ^C
[root@357d9f8e5ee6 /]# ls -la /var/ossec/api/configuration/
total 20
drwxrwx--- 4 root ossec 4096 Sep  9 13:49 .
drwxr-x--- 4 root ossec 4096 Sep  9 13:49 ..
-rw-rw---- 1 root ossec 1255 Sep  9 13:47 api.yaml
drwxrwx--- 2 root ossec 4096 Sep  9 13:47 security
drwxrwx--- 2 root ossec 4096 Sep  9 13:47 ssl
[root@357d9f8e5ee6 /]# ls -l /var/ossec/api/scripts/wazuh-apid.py
-rw-r----- 1 root ossec 9294 Sep …
```
> Update Wazuh API permissions on rpm spec

- wpk/gen_versions.sh
- wpk/generate_wpk_package.sh
- wpk/linux/aarch64/Dockerfile
- wpk/linux/armv7hl/Dockerfile
- wpk/linux/x86_64/Dockerfile
- wpk/run.sh
- wpk/windows/Dockerfile
|---|
|https://github.com/wazuh/wazuh-jenkins/issues/1668|
Hello team,
We want to remove versions file generation from packages builder process.
This change is made because now this step is managed by Jenkins.
New versions log
```
./gen_versions.sh -n /one_path/wazuh_agent_v3.13.1_linux_x86_64.wpk -v 3.13.1 -o /one_path/versions -c /one_path/versions -r 1
Revision not set, skipping...
Versions file generated successfully at /one_path/versions
```
> Removed gen_versions.sh script and any reference to it

- debs/SPECS/4.0.0/wazuh-manager/debian/postinst
- rpms/SPECS/4.0.0/wazuh-manager-4.0.0.spec
|---|
| [Wazuh 6020](https://github.com/wazuh/wazuh/issues/6020) |
This PR adds the logic to move the `global.db` database to the new location during the upgrade scenario. It also sets the proper permissions and ownership of the file in order to make `Wazuh DB` be able to manage it.
> Adding upgrade logic for global database

- debs/SPECS/3.13.2/wazuh-manager/debian/postinst
- debs/SPECS/4.0.0/wazuh-manager/debian/postinst
- debs/SPECS/4.0.0/wazuh-manager/debian/preinst
- rpms/SPECS/4.0.0/wazuh-manager-4.0.0.spec
|---|
| [Wazuh 5367](https://github.com/wazuh/wazuh/issues/5367) |
This PR includes all the packages changes required after **[Migration agent-info data to Wazuh DB epic](https://github.com/wazuh/wazuh/issues/5367)** is integrated.
It basically includes a logic to do the next things:
- Remove the `agent-info` folder and all its content if exists.
- Relocate the `global.db` database from `var/db/` folder to `queue/db`.
- Assign proper permissions and ownership to `global.db` in order to make `Wazuh DB` be able to manage it.
> Migration agent-info data to Wazuh DB packages upgrade

- rpms/SPECS/4.0.0/wazuh-manager-4.0.0.spec
|---|
|closes #499 |
Hello team,
This PR updates the `wazuh-api` `3.13.2` obsolete version when upgrading to `4.0.0`
After applying this change, it is now possible to upgrade from `3.13.2` to `4.0.0` successfully.
```
[root@a9484a8bbf03 /]# cat /etc/ossec-init.conf 
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.13.2"
REVISION="31310"
DATE="Fri Sep 18 18:04:25 UTC 2020"
TYPE="server"
[root@a9484a8bbf03 /]# rpm -U wazuh-manager-4.0.0-jmv74211.release.x86_64.rpm 
warning: /var/ossec/etc/ossec.conf created as /var/ossec/etc/ossec.conf.rpmnew
warning: /var/ossec/api/configuration/config.js saved as /var/ossec/api/configuration/config.js.rpmsave
```
Best regards.
> Update obsolete wazuh-api 3.13.2 when upgrading to 4.0.0 in RPM

- debs/SPECS/4.1.0/wazuh-manager/debian/changelog
We've detected some failures on Debian manager SPECS for 4.1.0
This PR aims to fix them.
> Fix debian manager SPECS for 4.1.0

- debs/Debian/amd64/Dockerfile
- debs/Debian/arm64/Dockerfile
- debs/Debian/armhf/Dockerfile
- debs/Debian/i386/Dockerfile
- debs/Debian/ppc64le/Dockerfile
- debs/build.sh
|---|
| closes https://github.com/wazuh/wazuh-jenkins/issues/1775 |
Hi team, 
This PR removes the package `fakeroot` and uses `sudo` as the default tool to grant root permissions to `debuild`. This improves the build process and removes these logs:
```
14:27:37  ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
14:27:37  ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
14:27:37  ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
14:27:37  ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored. …
```
> Remove fakeroot package from deb build-tools

- debs/SPECS/4.0.0/wazuh-manager/debian/postinst
- debs/SPECS/4.1.0/wazuh-manager/debian/postinst
- rpms/SPECS/4.0.0/wazuh-manager-4.0.0.spec
- rpms/SPECS/4.1.0/wazuh-manager-4.1.0.spec
Hi team, 
DBs files from these versions are incompatible with wazuh-db daemon, who is in charge of migrating and maintaining Wazuh's DBs.
Due to this incompatibility, they must be removed to ensure the correct upgrade and migration processes.
Regards.
> Ensure DBs from Wazuh v3.6.1 or lower are deleted

- debs/SPECS/4.1.0/wazuh-manager/debian/postinst
|---|
| #515  |
Hello team, 
This PR closes #515, we have modified the Debian post installation script so the permissions of the ssl certificates are set correctly.
> Set ssl cetificates permissions in DEB packages

- aix/README.md
- debs/README.md
- macos/README.md
- ova/README.md
- rpms/README.md
- solaris/README.md
- solaris/package_generation/README.md
- solaris/packer/README.md
- splunkapp/README.md
- wazuhapp/README.md
- windows/README.md
- wpk/README.md
Hello team,
This PR fixes the HP-UX documentation links in `readme` files.
Best regards.
> Fix HP-UX documentation links

- debs/build.sh
- debs/generate_debian_package.sh
- rpms/build.sh
- rpms/generate_rpm_package.sh
|---|
|wj1844|
Hello team,
In this PR we add the necessary tools to build future packages for testing purposes.
```
Building dependency tree       
Note, selecting 'wazuh-manager' instead of '/vagrant/wazuh-manager_4.30.0-1_amd64.deb'
Suggested packages:
expect
The following NEW packages will be installed:
wazuh-manager
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/103 MB of archives.
After this operation, 386 MB of additional disk space will be used.
Get:1 /vagrant/wazuh-manager_4.30.0-1_amd64.deb wazuh-manager amd64 4.30.0-1 [103 MB]
Selecting previously unselected package wazuh-manager.
(Reading database ... 59775 files and directories currently installed.)
Preparing to …
```
> Add tools to generate future x.30.0 test packages

- ova/Libraries/provision-opendistro.sh
Hello team,
The pipeline that generates the ova never ended up executing the provisioning step in the instance. The provisioning script could not install Kibana correctly.
closes #527 
To solve the problem I have fixed  Kibana certificates 
Error: https://devel.ci.wazuh.info/job/1561-Packages-Builder-OVA/423/console
Fixed: https://devel.ci.wazuh.info/job/1561-Packages-Builder-OVA/428/console
> Solve provision script error installing Kibana

- debs/build.sh
- debs/generate_debian_package.sh
- rpms/build.sh
- rpms/generate_rpm_package.sh
|---|
|wj1844|
Hello team,
This PR fixes a problem with the future package generation of Debian packages where the x.30.0 package was not generated due to the changelog not being modified.
Regards,
Daniel Folch
> Fix problem with Debian future package generation

- rpms/SPECS/4.1.0/wazuh-manager-4.1.0.spec
|---|
|https://github.com/wazuh/wazuh/issues/6097|
This PR removes the rootcheck folder in the rpm manifiest since it is not needed anymore.
> Remove rootcheck directory RPM

- rpms/SPECS/4.1.0/wazuh-manager-4.1.0.spec
|---|
|[5337](https://github.com/wazuh/wazuh/issues/5337)|
Hello team!
New Logtest has a Python script to testing rules and decoders using the console. This PR adds it to the SPECS.
You have to merge it when we merge branch `feature/5337-logtest-enhancement`
Best regards,
Eva
> Add new wazuh-logtest script

- CHANGELOG.md
- aix/SPECS/4.0.2/wazuh-agent-4.0.2-aix.spec
- aix/SPECS/4.1.0/wazuh-agent-4.1.0-aix.spec
|---|
|#540|
Hi team,
This PR closes #540 by fixing the group of the `ossec.conf` file using a `chown` line in the post-install script.
NA
> Fix ossec.conf group in IBM AIX package

- rpms/SPECS/4.1.0/wazuh-manager-4.1.0.spec
|---|
| closes #542 |
Hello team,
We have added a little fix to wazuh-logtest group, changed from `root` to `ossec`. 
Regards.
> Changed wazuh-logtest group to ossec

- rpms/CentOS/6/i386/CentOS-Base.repo
- rpms/CentOS/6/i386/Dockerfile
- rpms/CentOS/6/x86_64/CentOS-Base.repo
- rpms/CentOS/6/x86_64/Dockerfile
|---|
| Closes #548 |
Hello team,
CentOS 6 repositories are down after November 30 so, we changed them to another mirror.
Regards!
> Changed CentOS 6 x86_64 and i386 base repositories

- debs/Debian/amd64/Dockerfile
- debs/Debian/arm64/Dockerfile
- debs/Debian/armhf/Dockerfile
- debs/Debian/i386/Dockerfile
- debs/Debian/ppc64le/Dockerfile
- debs/SPECS/4.1.0/wazuh-agent/debian/rules
- debs/SPECS/4.1.0/wazuh-manager/debian/rules
- debs/build.sh
- rpms/CentOS/5/i386/Dockerfile
- rpms/CentOS/5/x86_64/Dockerfile
- rpms/CentOS/6/i386/Dockerfile
- rpms/CentOS/6/x86_64/Dockerfile
- rpms/CentOS/7/aarch64/Dockerfile
- rpms/CentOS/7/armv7hl/Dockerfile
- rpms/CentOS/7/ppc64le/Dockerfile
- windows/Dockerfile
- wpk/linux/x86_64/CentOS-Base.repo
- wpk/linux/x86_64/Dockerfile
- wpk/windows/Dockerfile
Hi team,
Adding cmake and bumping GCC to newer versions need more testing. Some errors have been reported in CentOS 5 and to avoid any possible errors, we will roll back to the previous version and keep testing in elder OS.
Regards.
> Revert cmake addition

- debs/SPECS/4.1.0/wazuh-agent/debian/rules
- debs/SPECS/4.1.0/wazuh-manager/debian/postinst
- debs/SPECS/4.1.0/wazuh-manager/debian/rules
- rpms/SPECS/4.0.3/wazuh-manager-4.0.3.spec
- rpms/SPECS/4.1.0/wazuh-agent-4.1.0.spec
- rpms/SPECS/4.1.0/wazuh-manager-4.1.0.spec
- solaris/solaris11/SPECS/template_agent_v4.1.0.json
|---|
|  #536 |
Hi team,
This PR closes #536 by adding the new SCA policies to the SPECS files..
NA
> Add new SCA policies to the binary packages

- rpms/SPECS/4.0.3/wazuh-manager-4.0.3.spec
Hi guys,
This PR is to remove changes made to 4.0.3 SPEC files due to a problem when creating RPM packages:
```
sudo ./generate_rpm_package.sh -b v4.0.3 -t manager
cp: cannot stat `etc/templates/config/rhel/7/sca.files': No such file or directory
error: Bad exit status from /usr/local/var/tmp/rpm-tmp.bQID3C (%install)
```
After this changes, the error doesn't appear anymore:
```
+ find /build_wazuh/rpmbuild/RPMS/x86_64 -maxdepth 3 -type f -name 'wazuh-manager-4.0.3-1*' -exec mv '{}' /var/local/wazuh ';'
Package wazuh-manager-4.0.3-1.x86_64.rpm added to /home/victor/wazuh-packages/rpms/output/.
```
> Restore 4.0.3 SPECS with the release ones

- debs/SPECS/4.2.0/wazuh-agent/debian/postinst
- debs/SPECS/4.2.0/wazuh-agent/debian/preinst
- debs/SPECS/4.2.0/wazuh-agent/debian/prerm
- debs/SPECS/4.2.0/wazuh-manager/debian/postinst
- debs/SPECS/4.2.0/wazuh-manager/debian/preinst
- debs/SPECS/4.2.0/wazuh-manager/debian/prerm
- hp-ux/generate_wazuh_packages.sh
- macos/package_files/4.2.0/postinstall.sh
- macos/package_files/4.2.0/preinstall.sh
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
- solaris/solaris10/generate_wazuh_packages.sh
- solaris/solaris10/preremove.sh
- solaris/solaris10/solaris10_patch.sh
- solaris/solaris10/uninstall.sh
- solaris/solaris11/SPECS/template_agent_v4.2.0.json
- solaris/solaris11/generate_wazuh_packages.sh
- solaris/solaris11/uninstall.sh
|---|
|#547|
Hello team,
This PR makes the following changes in `4.2.0` SPECS:
**Renamed**
- `ossec-control` -> `wazuh-control`
- `ossec-regex` -> `wazuh-regex`
- `ossec-logtest` -> `wazuh-logtest`
**Removed**
- `rootcheck_control` 
- `syscheck_control` 
- `syscheck_update`
- `ossec-makelists`
- Manager RPM: https://devel.ci.wazuh.info/job/Packages_builder/5832/
- Agent RPM: https://devel.ci.wazuh.info/job/Packages_builder/5835/
- Manager DEB: https://devel.ci.wazuh.info/job/Packages_builder/5833/
- Agent DEB: https://devel.ci.wazuh.info/job/Packages_builder/5834/
- Agent macOS: https://ci.wazuh.info/job/Packages_builder_macos/278/
- Agent Solaris 10: https://ci.wazuh.info/job/Packages_builder_solaris/7163/
- Agent Solaris 11: …
> Update 4.2.0 SPECS files to rename and remove old wazuh tools

- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
|---|
|#565|
This PR updates the manager 4.2.0 and 5.0.0 SPEC files to contemplate the removal of the ruleset version file
Closes #565
> Remove ruleset version file from specs

- debs/SPECS/4.2.0/wazuh-agent/debian/rules
- debs/SPECS/4.2.0/wazuh-manager/debian/rules
- debs/SPECS/5.0.0/wazuh-agent/debian/rules
- debs/SPECS/5.0.0/wazuh-manager/debian/rules
- macos/package_files/4.2.0/build.sh
- macos/package_files/5.0.0/build.sh
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
- rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
|---|
|566|
This PR updates the `.specs` files to generate packages with the new location of the following ruleset components:
- **SCA**
Closes #566 
The following tests were performed manually, the rest of the operative systems supported are being tested in the Jenkins pipelines of the PR [6907](https://github.com/wazuh/wazuh/pull/6907) in the `wazuh/wazuh` repository 
> Updating packages generation scripts with the the new ruleset folder location

- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
|---|
|#574|
This PR eliminates update_ruleset from the spec files of 4.2 and 5.0 because is now obsolete.
> Remove obsolete update_ruleset from 4.2 and 5.0 spec files

- solaris/solaris10/generate_wazuh_packages.sh
|---|
| Closes #581 |
Hello team,
We have applied little fixes to get Solaris 10 package generation fully working.
We have removed all `solaris10_patch.sh` file references.
Added `RESOURCES_URL` parameter in deps compilation.
```
...
11:39:57  /export/home/jeijpn/solaris/wazuh-agent/install/checkinstall
11:39:57  /export/home/jeijpn/solaris/wazuh-agent/install/postinstall
11:39:57  /export/home/jeijpn/solaris/wazuh-agent/install/postremove
11:39:57  /export/home/jeijpn/solaris/wazuh-agent/install/preinstall
11:39:57  /export/home/jeijpn/solaris/wazuh-agent/install/preremove
11:39:57  ## Validating control scripts.
11:39:57  ## Packaging complete.
11:39:57  Transferring <wazuh-agent> package instance
```
> Fix Solaris 10 Sparc SSL issues

- solaris/solaris10/generate_wazuh_packages.sh
- solaris/solaris10/preremove.sh
|---|
| Closes #583 |
Hello team,
We have added a fix on Solaris 10 preremove script that left some files inside the installation path.
Regards!
> Fix SSL error (date) and preremove script

- debs/SPECS/4.1.0/wazuh-manager/debian/postinst
- debs/SPECS/4.2.0/wazuh-manager/debian/postinst
- debs/SPECS/5.0.0/wazuh-manager/debian/postinst
- rpms/SPECS/4.1.0/wazuh-manager-4.1.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
Hi team,
This PR removes the file `/var/ossec/var/db/.template.db ` from SPECS manager files of Wazuh >= 4.1.0.
This file 
Tests:
- Generated amd/rpm packages with custom revision:
-  https://devel.ci.wazuh.info/job/Packages_builder/5917/
-  https://devel.ci.wazuh.info/job/Packages_builder/5919/
-  https://devel.ci.wazuh.info/job/Packages_builder/5920/
-  https://devel.ci.wazuh.info/job/Packages_builder/5921/
- Test_upgrade_tier with those packages: 
- https://devel.ci.wazuh.info/job/Test_upgrade_tier/1456/
Reggards.
> Remove legacy .template.db in upgrades

- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
|---|
| closes #542 |
Hello team,
This PR aims to fix  wazuh-logtest group privilege from `root` to `ossec` in RPM SPECS for 4.2.0
Regards.
> Fix: ossec group privilege for wazuh-logtest

- hp-ux/generate_wazuh_packages.sh
|---|
|#589|
This PR closes #589 by fixing the checksum's file generation by parsing the output of the `openssl` command and unify it with the rest of the checksums' files generated by the scripts.
https://ci.wazuh.info/job/Packages_builder_special/146/console
```shellsession
....
b554bfdd6294c5cf38c04987e7d8063d2577d6b317317f9cae975e295ba358205e70880accba245b921bf43880110094e34ad4dddad490ef8254812da8d9dbac  wazuh-agent-4.1.0-1-hpux-11v3-ia64.tar
```
> Fixed HPUX checksum generation

- debs/SPECS/4.1.0/wazuh-manager/debian/postinst
- debs/SPECS/4.1.0/wazuh-manager/debian/preinst
- debs/SPECS/4.2.0/wazuh-manager/debian/postinst
- debs/SPECS/4.2.0/wazuh-manager/debian/preinst
- debs/SPECS/5.0.0/wazuh-manager/debian/postinst
- debs/SPECS/5.0.0/wazuh-manager/debian/preinst
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/591|
Hi team,
This PR adds the preservation of the `api.yaml` file after upgrading to the debs SPECS from 4.1.0. Before this PR the `api.yaml `file was overwritten by the upgrade.
- Built custom package with custom branch with fix: https://ci.wazuh.info/view/Packages/job/Packages_builder/30350
- Installed Wazuh manager 4.0.3.
- Edit `/var/ossec/api/configuration/api.yaml` and upgrade to custom built package.
- File `/var/ossec/api/configuration/api.yaml` is not overwritten.
> Backup api.yaml configuration file to restore it when upgrading

- aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
- aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
- debs/SPECS/4.2.0/wazuh-agent/debian/rules
- debs/SPECS/4.2.0/wazuh-manager/debian/rules
- debs/SPECS/5.0.0/wazuh-agent/debian/rules
- debs/SPECS/5.0.0/wazuh-manager/debian/rules
- macos/package_files/4.2.0/postinstall.sh
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
- rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
|---|
|7083|
As part of the removal of ossec-init.conf usage from package installation scripts, the following scripts and specs were modified to 
hand the installation path accordingly.
> Adapt packages installation files to use services from templates

- aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
- aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
- debs/SPECS/4.2.0/wazuh-agent/debian/postinst
- debs/SPECS/5.0.0/wazuh-agent/debian/postinst
- macos/package_files/4.2.0/postinstall.sh
- macos/package_files/5.0.0/postinstall.sh
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
|---|
|7124|
As part of the removal of ossec-init.conf usage from package installation scripts, the following scripts and specs were modified to 
hand the installation path accordingly.
> Modify package installation scripts to avoid the usage of ossec-init.conf

- ova/wazuh_ovf_template
Hello team,
I have changed ova name from `vm_wazuh` to `Wazuh v4.0.4 OVA`. This change is motivated due to `vm_wazuh` does not very descriptive.
closes #604
> Changed OVA name

- solaris/solaris11/SPECS/template_agent_v4.2.0.json
|---|
| #562  |
Hi team,
This PR aims to close #562 reopening by fixing `pid` and `state` files changed by the renaming of binaries.
NA
Regards,
Nico
> Fix solaris11: state and pid files for wazuh daemons renaming

- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
|---|
| https://github.com/wazuh/wazuh/issues/7090 |
This pull request implements a fix in the calls to `wazuh-control` when is used by the installers to get the Wazuh version. Basically there was a missing parameter called `info` that must be specified before the `-v` switch.
> Fixing wazuh-control parameters in the calls to get the Wazuh version

- debs/SPECS/4.2.0/wazuh-agent/debian/postinst
- debs/SPECS/4.2.0/wazuh-manager/debian/postinst
- debs/SPECS/5.0.0/wazuh-agent/debian/postinst
- debs/SPECS/5.0.0/wazuh-manager/debian/postinst
|---|
| https://github.com/wazuh/wazuh/issues/7090 |
This pull request implements a fix in **postinst** functions of **.deb** packages to remove **/etc/ossec-init.con** that wasn't being deleted after the upgrade.
> Make postinst functions of .deb packages remove /etc/ossec-init.conf

- aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
- aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
- debs/SPECS/4.2.0/wazuh-agent/debian/rules
- debs/SPECS/4.2.0/wazuh-manager/debian/rules
- debs/SPECS/5.0.0/wazuh-agent/debian/rules
- debs/SPECS/5.0.0/wazuh-manager/debian/rules
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
- rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
|---|
| https://github.com/wazuh/wazuh/issues/7090 |
As part of the exploratory testing that we made for the epic https://github.com/wazuh/wazuh/issues/7054 where we are removing the `ossec-init.conf` file from the Wazuh installations, we identified that we were using the `-i` switch in the `sed` command in some packages. This switch is not part of the standard of the `sed` command, so it doesn't work in AIX for example.
This PR removed the usage of that switch in all the packages.
> Removing the usage of the -i switch in the sed command for all the installers

- debs/SPECS/4.2.0/wazuh-agent/debian/rules
- debs/SPECS/4.2.0/wazuh-manager/debian/rules
- debs/SPECS/5.0.0/wazuh-agent/debian/rules
- debs/SPECS/5.0.0/wazuh-manager/debian/rules
- macos/package_files/4.2.0/build.sh
- macos/package_files/5.0.0/build.sh
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
- rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
|---|
|[#7017](https://github.com/wazuh/wazuh/issues/7017)|
Added yml file to support CIS checks for Darwing 19, macOS 10.15 Catalina
> Cis apple macos 10.15

- solaris/solaris11/SPECS/template_agent_v4.2.0.json
- solaris/solaris11/SPECS/template_agent_v5.0.0.json
|---|
|wazuh/wazuh#6159|
Hi team!
This PR aims to add `wazuh-logcollector.state` into Solaris SPECS
Regards,
Nico
> Add wazuh-logcollector.state to solaris SPECS

- debs/SPECS/4.2.0/wazuh-manager/debian/preinst
- debs/SPECS/5.0.0/wazuh-manager/debian/preinst
This PR fixes a problem with the upggrades from 4.2.0 for DEB packages where the version of the old package was not obtained correctly.
> Fix version in DEB preinstall

- debs/SPECS/4.2.0/wazuh-agent/debian/preinst
- debs/SPECS/4.2.0/wazuh-manager/debian/preinst
- debs/SPECS/5.0.0/wazuh-agent/debian/preinst
- debs/SPECS/5.0.0/wazuh-manager/debian/preinst
- macos/package_files/4.2.0/preinstall.sh
- macos/package_files/5.0.0/preinstall.sh
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
- rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
|---|
|#636|
This PR fixes a problem where wazuh-control was used when upgrading from versions lower than 4.2.0 causing the services to not be stopped propperly.
Regards,
Daniel Folch
> Use ossec control in preinstall  if necessary

- debs/SPECS/4.1.1/wazuh-agent/debian/rules
- debs/SPECS/4.1.1/wazuh-manager/debian/rules
- debs/SPECS/4.2.0/wazuh-manager/debian/rules
- debs/SPECS/5.0.0/wazuh-manager/debian/rules
- rpms/SPECS/4.1.1/wazuh-agent-4.1.1.spec
- rpms/SPECS/4.1.1/wazuh-manager-4.1.1.spec
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
- rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
|---|
|#644|
Hi team,
This PR closes #644. In this PR we have modified the path of the Wazuh dependencies in order to get them from the new versioning as explained in issue #644.
Regards.
> Update dependencies url

- macos/generate_wazuh_packages.sh
|---|
| #659 |
Closes #659
Updated the installation command to the one provided here: #https://github.com/Homebrew/install/blob/dee8df98bfb65588007c666034c6e1ad0733b1b6/install#L3
Installed x-code using updated command
```
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
#################################################################################################################################################################################################### 100.0%
==> Pouring portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
==> Installation successful!
```
> Updated homebrew install command

- debs/Debian/amd64/Dockerfile
- debs/SPECS/4.1.3/wazuh-manager/debian/rules
- debs/build.sh
- rpms/CentOS/6/x86_64/Dockerfile
- rpms/CentOS/7/aarch64/Dockerfile
- rpms/CentOS/7/ppc64le/Dockerfile
- rpms/SPECS/4.1.3/wazuh-manager-4.1.3.spec
|---|
| closes #669  |
Hi there,
We have added support to GCC5.5 on Debian and RPM containers:
- Added GCC5.5 compilation on x86_64/amd64/arm64/aarch64 only.
- Uploaded all containers to ECR.
- Package built and tested.
- Updated generation scripts in Debian.
**Warning** This modifications also affect to the agent build that have to be selected on building time
With this change the packages will built as follows:
- Manager rpm -> GCC5
- Manager deb -> GCC5
- Agent rpm -> GCC5
- Agent deb -> GCC4
- The rest of agents -> GCC4
X86_64 RPM manager -> https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/6261/
AMD64 Deb manager -> https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/6262/
X86_64 RPM agent GCC5.5 -> …
> Add GCC5 support to Manager build with Python 3.9

- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
|---|
|wazuh/wazuh#7806|
Hi team!
This PR aims to add `wazuh-logtest.legacy` (`ossec-logtest` renamed) to rpm SPECS.
Regards,
Nico
> Add wazuh-logtest.legacy tool to RPM SPECS

- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
|---|
|wazuh/wazuh#7806|
Hi team,
This PR is to add `wazuh-logtest-legacy` to rpm SPECS.
Regards.
> Add wazuh-logtest-legacy tool to RPM SPECS

- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
|---|
| Closes #682  |
Added `wazuh-logtest-legacy` to 5.0 RPM manager SPEC.
Regards.
> Added wazuh-logtest-legacy to 5.0 RPM SPECs

- aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
- debs/SPECS/4.2.0/wazuh-manager/debian/preinst
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
|---|
||
This PR fixes some errors when upgrading to 4.2.0.
```
09:44:19  2021/03/31 07:43:36 wazuh-agentd: ERROR: (1103): Could not open file 'queue/sockets/.agent_info' due to [(2)-(No such file or directory)].
09:44:19  
09:44:19  2021/03/31 07:43:36 wazuh-syscheckd: ERROR: (1103): Could not open file 'queue/sockets/.agent_info' due to [(2)-(No such file or directory)].
09:44:19  
09:44:19  2021/03/31 07:43:36 wazuh-syscheckd: ERROR: (1103): Could not open file 'queue/sockets/.agent_info' due to [(2)-(No such file or directory)].
09:44:19  
09:44:19  2021/03/31 07:43:36 wazuh-logcollector: ERROR: (1103): Could not open file 'queue/sockets/.agent_info' due to [(2)-(No such file or directory)].
09:44:19  
09:44:19  2021/03/31 07:43:36 wazuh-modulesd: ERROR: (1103): Could …
```
> Fix errors in 4.2.0 upgrade

- aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
- aix/SPECS/4.3.0/wazuh-agent-4.3.0-aix.spec
- aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
- debs/SPECS/4.2.0/wazuh-agent/debian/changelog
- debs/SPECS/4.2.0/wazuh-manager/debian/changelog
- debs/SPECS/4.2.0/wazuh-manager/debian/preinst
- debs/SPECS/4.3.0/wazuh-agent/debian/changelog
- debs/SPECS/4.3.0/wazuh-manager/debian/changelog
- debs/SPECS/4.3.0/wazuh-manager/debian/preinst
- debs/SPECS/5.0.0/wazuh-agent/debian/changelog
- debs/SPECS/5.0.0/wazuh-manager/debian/changelog
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
- rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
- rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec
- rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
|---|
||
This PR applies the changes done in #695 to versions 4.3 and 5.0
> Fix 5.0 and 4.3 SPECS

- ova/Libraries/provision-opendistro.sh
- ova/provision.sh
|---|
|#627|
Related #627 
Removed `addElasticRepo` function from `provision-opendistro.sh` library and the call from `provision.sh`
Also removed `Configure JVM options` in `installElasticsearch` from `provision-opendistro.sh` as those steps are not required on the Wazuh documentation installation guide.
After remove the listed code, I could run the script as follow: `sh provision.sh 4.1.2 1.12.0 7.10.0 dev 4.1.2 1 -d`
And got the following result:
```
Elasticsearch installation succeeded.
+ filebeat test output
elasticsearch: https://127.0.0.1:9200...
parse url... OK
connection...
parse host... OK
dns lookup... OK
addresses: 127.0.0.1
dial up... OK
TLS...
security: server's certificate chain verification is enabled
handshake... OK
TLS version: TLSv1.3
dial up... OK
talk …
```
> Removed  code from provision-opendistro.sh

- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
- solaris/solaris11/SPECS/template_agent_v5.0.0.json
|---|
https://github.com/wazuh/wazuh-packages/issues/700
https://github.com/wazuh/wazuh/issues/8029
Logcollector:
This issue points to the unification of processes on the agent side, in which it aims to only have wazuh-agentd and wazuh-modulesd.
One of the biggest challenges here is to decompose the main of the old module, separating what is the initialization, from the main processing loop, as well as the rearrangement of the configuration reading.
For this type of modification, the main thing is to normalize the module, to maintain the structure and design of wazuh-modulesd, as it is used in the pre-existing modules.
> 8029 logcollector as wazuh module

- ova/Libraries/provision-opendistro.sh
|---|
|#718|
This PR closes #718.
We have corrected tha naming of the opendistro-performance-analyzer plugin in the OVA provision scripts.
> Fix opendistro-performance-analyzer plugin name in OVA

- wpk/linux/x86_64/Dockerfile
- wpk/run.sh
|---|
| closes #717 |
Hi!
This PR solves an error related with the WPK package generation that doesn't copy the Syscollector compiled library required to a good performance of the Wazuh agent.
We have changed the `wazuh_modules` folder removal and added some removals of API and framework folders that aren't required.
Regards.
> Fix WPK compilation and library copy

- aix/SPECS/4.3.0/wazuh-agent-4.3.0-aix.spec
- aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
- debs/SPECS/4.3.0/wazuh-agent/debian/postinst
- debs/SPECS/4.3.0/wazuh-agent/debian/postrm
- debs/SPECS/4.3.0/wazuh-manager/debian/postinst
- debs/SPECS/4.3.0/wazuh-manager/debian/postrm
- debs/SPECS/5.0.0/wazuh-agent/debian/postinst
- debs/SPECS/5.0.0/wazuh-agent/debian/postrm
- debs/SPECS/5.0.0/wazuh-manager/debian/postinst
- debs/SPECS/5.0.0/wazuh-manager/debian/postrm
- hp-ux/generate_wazuh_packages.sh
- macos/package_files/4.3.0/postinstall.sh
- macos/package_files/4.3.0/preinstall.sh
- macos/package_files/5.0.0/postinstall.sh
- macos/package_files/5.0.0/preinstall.sh
- macos/uninstall.sh
- rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
- rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec
- rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
- solaris/solaris10/generate_wazuh_packages.sh
- solaris/solaris11/SPECS/template_agent_v4.3.0.json
- solaris/solaris11/SPECS/template_agent_v5.0.0.json
- solaris/solaris11/generate_wazuh_packages.sh
- solaris/solaris11/postinstall.sh
- solaris/solaris11/solaris_fix.py
|---|
|Closes #651|
This PR modifies the user and group used by the wazuh binaries acording to the specifications of the issue #651.
```
[root@centos7 vagrant]# ls -lah /var/ossec/            
total 4.0K
drwxr-x---. 19 root  ossec  242 Mar 16 15:34 .
drwxr-xr-x. 19 root  root   267 Mar 16 15:34 ..
drwxrwx---.  2 root  ossec    6 Nov 30 08:42 .ssh
drwxr-x---.  3 root  ossec   17 Mar 16 15:34 active-response
drwxr-x---.  2 root  ossec  286 Mar 16 15:34 agentless
drwxr-x---.  4 root  ossec   42 Mar 16 15:34 api
drwxr-x---.  5 root  ossec   48 Mar 16 15:34 backup
drwxr-x---.  2 root  ossec 4.0K Mar 16 15:34 bin
drwxrwx---.  7 ossec ossec  265 Mar 16 15:34 etc
drwxr-x---.  5 root  ossec   48 Mar 16 15:34 framework
drwxr-x---.  2 root  ossec   91 Mar 16 15:34 integrations …
```
>  Change default user and group 

- debs/SPECS/4.3.0/wazuh-manager/debian/postinst
- solaris/solaris10/postremove.sh
- solaris/solaris10/preinstall.sh
- solaris/solaris10/uninstall.sh
|---|
|#651|
This PR changes the user and group in the Solaris package generation. 
> Change sol group/user

- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
- solaris/solaris11/SPECS/template_agent_v5.0.0.json
|---|
https://github.com/wazuh/wazuh-packages/issues/700
https://github.com/wazuh/wazuh/issues/8028
Execd, active response:
This issue points to the unification of processes on the agent side, in which it aims to only have wazuh-agentd and wazuh-modulesd.
One of the biggest challenges here is to decompose the main of the old module, separating what is the initialization, from the main processing loop, as well as the rearrangement of the configuration reading.
For this type of modification, the main thing is to normalize the module, to maintain the structure and design of wazuh-modulesd, as it is used in the pre-existing modules.
- Tests for IBM …
> 8028 - execd as wazuh module.

- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
|---|
https://github.com/wazuh/wazuh/issues/8404
monitord:
This issue points to the unification of monitord on the server side. From now on there will not be a single `wazuh-monitord` process listed under wazuh-manager service but it will be part of the `wazuh-modules` one.
One of the biggest challenges here is to decompose the main of the old module, separating what is the initialization, from the main processing loop, as well as the rearrangement of the configuration reading.
For this type of modification, the main thing is to normalize the module, to maintain the structure and design of wazuh-modulesd, as it is used in the pre-existing modules.
**Destination branch:** dev-monitord-as-wmodule (it was created from 5.0-dev)
- …
> Removed wazuh-monitord from spec files based on current work

- debs/SPECS/4.2.0/wazuh-agent/debian/postinst
- debs/SPECS/4.2.0/wazuh-manager/debian/postinst
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
|---|
|#723 #724 |
This PR fixes several problems in upgrades to version 4.2.0 in DEB and RPM packages:
- Issue where old service was not removed on upgrade
- Issue where ossec-int.conf was required by 3.x packages postunintall
> Fix 4.2.0 DEB and RPM upgrade errors 

- aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
|---|
|#735|
This issue aims to solve a problem of initialization of syscollector when it is installed through a package.
The rca is already done and the problem here is the non-inclusion of the libraries in the spec files.
**Fix evidence:**
> Added lib files to AIX SPEC

- aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
- aix/SPECS/4.3.0/wazuh-agent-4.3.0-aix.spec
- aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
|---|
|https://github.com/wazuh/wazuh/issues/8417|
Such configuration must be applied by the configuration templates.
> Prevent SPECS from disabling Syscollector on AIX

- aix/generate_wazuh_packages.sh
|---|
| Related #738 |
Fixed path of `shasum` binary in AIX 6.1 script.
Regards.
> Fix aix 6.1 checksum generation

- solaris/solaris11/generate_wazuh_packages.sh
- solaris/solaris11/postinstall.sh
|---|
|#742|
This PR fixes a problem with `/var/ossec/queue/ossec` and `/var/ossec/logs/ossec`  not being included in the Solaris 11 package and improves the postinstall script.
> Fix solaris 11 postinstall service

- solaris/solaris10/generate_wazuh_packages.sh
- solaris/solaris11/SPECS/template_agent_v4.2.0.json
- solaris/solaris11/generate_wazuh_packages.sh
|---|
|Closes #725 |
Linking error during solaris build in sparc architecture.
```
12:23:07      CC manage_agents
12:23:07  ld: fatal: bad section layout: .SUNW_ldynsym must precede and be adjacent to .dynsym
12:23:07  collect2: error: ld returned 1 exit status
12:23:07  gmake[1]: *** [wazuh-syscheckd] Error 1
12:23:07  gmake[1]: *** Waiting for unfinished jobs....
12:23:07  gmake: *** [agent] Error 2
```
Solaris 10 SPARC error:
```
11:43:41  /usr/ccs/bin/as: "/var/tmp//ccdvfaxp.s", line 5848: warning: v8+ ABI violation: illegal use of %i or %l register as rs1 in "movrz" instruction
11:43:41  /usr/ccs/bin/as: "/var/tmp//ccdvfaxp.s", line 5849: warning: v8+ ABI violation: illegal use of %i or %l register as rs1 in "movrz" instruction
11:43:41  /usr/ccs/bin/as: …
```
> 725 Solaris sparc link error

- solaris/solaris10/generate_wazuh_packages.sh
- solaris/solaris11/generate_wazuh_packages.sh
|---|
| Closes #749 |
**Previous**
**With this change.**
10
11
This issue aims to remove the DISABLED_SHARED flag on compilation since it is not necessary for Solaris implementations. Besides that, in PoC this was tested and works fine with the dynamic library.
> Remove disabled shared option during compilation.

- debs/SPECS/4.2.0/wazuh-agent/debian/preinst
- debs/SPECS/4.2.0/wazuh-manager/debian/preinst
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
|---|
|Closes #625|
This PR fixes a problem where the Wazuh daemons did not stop correctly during an upgrade in some cases.
This  problem was caused by a mishandling of the services where the systemctl service was in stopped status but wazuh had been started using ossec-control.
> Make sure services are stopped during upgrade

- aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
- aix/generate_wazuh_packages.sh
Remove disable shared variable.
Increase partitions size to install g++
> Remove disable shared variable on AIX.

- hp-ux/generate_wazuh_packages.sh
|---|
| Closes wazuh#8513 |
Remove disable shared flag on package build.
> Remove DISABLE_SHARED on hpux

- aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
- debs/Debian/amd64/Dockerfile
- debs/SPECS/5.0.0/wazuh-agent/debian/postinst
- debs/SPECS/5.0.0/wazuh-agent/debian/preinst
- debs/SPECS/5.0.0/wazuh-agent/debian/prerm
- debs/SPECS/5.0.0/wazuh-agent/debian/rules
- debs/SPECS/5.0.0/wazuh-manager/debian/postinst
- debs/SPECS/5.0.0/wazuh-manager/debian/postrm
- debs/SPECS/5.0.0/wazuh-manager/debian/preinst
- debs/SPECS/5.0.0/wazuh-manager/debian/prerm
- debs/SPECS/5.0.0/wazuh-manager/debian/rules
- macos/package_files/5.0.0/build.sh
- macos/package_files/5.0.0/postinstall.sh
- macos/package_files/5.0.0/preinstall.sh
- macos/specs/5.x/wazuh-agent-5.0.0.pkgproj
- rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
- solaris/solaris10/postinstall.sh
- solaris/solaris10/preinstall.sh
- solaris/solaris11/SPECS/template_agent_v5.0.0.json
- solaris/solaris11/generate_wazuh_packages.sh
|---|
|Closes #658|
This PR changes the ossec.conf files to agent.conf and manager.conf following the guidelines given in #658.
> Rename Wazuh configuration files

- aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
- aix/generate_wazuh_packages.sh
- hp-ux/generate_wazuh_packages.sh
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
- solaris/solaris10/generate_wazuh_packages.sh
- solaris/solaris11/SPECS/template_agent_v4.2.0.json
- solaris/solaris11/generate_wazuh_packages.sh
|---|
|[#8525](https://github.com/wazuh/wazuh/issues/8525)|
This pr has the purpose of improving the size of the packages for 4.2, which was strongly impacted by the incorporated changes.
With these changes (4.2.0):
```
AIX -> 7 MB
DEB -> 6.6 MB
HPUX -> 18.9 MB
RPM -> 6.9 MB
RPM rhel 5 -> 6.7 MB
Windows -> 4.4 MB
Solaris 10-> 13.9 MB
Solaris 11-> 5.7MB
macOS-> 4.9 MB
```
Previous this change (4.2.0):
```
Modified: 2021-04-30 07:16:18	Size: 47.83 MB	Object: pre-release/aix/wazuh-agent-4.2.0-1.aix.ppc.rpm	
Modified: 2021-04-29 18:00:54	Size: 9.29 MB	Object: pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.2.0-1_amd64.deb	
Modified: 2021-04-29 18:38:55	Size: 3.78 MB	Object: pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.2.0-1_arm64.deb	
Modified: 2021-04-29 …
```
> Dev footprint reduction

- debs/Debian/amd64/Dockerfile
|---|
|Closes https://github.com/wazuh/wazuh-packages/issues/780|
Nodejs installation was no longer required on 4.1. Nevertheless, it is still present on our 4.1 Debian Dockerfile. This pull request removes it because it has started to cause an error due to invalid keys.
> Update 4.1 build Debian Dockerfile

- debs/SPECS/4.2.0/wazuh-agent/debian/rules
- debs/SPECS/4.2.0/wazuh-manager/debian/rules
|---|
|Closes #789|
This PR fixes an issue with the permissions set for the python files in Debian packages.
> Fix DEB packages wrong python permissions

- debs/SPECS/4.3.0/wazuh-agent/debian/rules
- debs/SPECS/4.3.0/wazuh-manager/debian/rules
- rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
- rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec
|---|
|closes #783|
This PR adds the new MS IIS, Oracle Database 19c, MongoDB 3.6, Nginx, SQL Server and SLES SCA files to the SPECS
> Add new sca files for MS IIS, Oracle Database 19c, MongoDB 3.6, Nginx, SQL Server and SLES

- aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
- debs/SPECS/4.2.0/wazuh-agent/debian/preinst
- debs/SPECS/4.2.0/wazuh-manager/debian/preinst
- macos/package_files/4.2.0/preinstall.sh
- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
|---|
||
This PR changes the behavior of the package during upgrades, forcing the stop of the daemons using wazuh-control.
> Force stop using wazuh-control during upgrade

- aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
This PR fixes a problem with the order of the versions in AIX 4.2.0 SPEC.
> Set AIX changelog in chronological order

- windows/Dockerfile
|---|
| closes #802 |
Hello team,
We have updated the docker of Windows package builder to use latest minGW version 9.3.0.
Regards.
> Update Windows compiler dockerfile to update minGW

- windows/Dockerfile
|---|
| closes #802 |
Hello team,
We have updated the docker of Windows package builder to use latest minGW version 9.3.0.
Regards.
> Update Windows compiler dockerfile to update minGW (Master branch)

- windows/Dockerfile
|---|
| closes #802 |
Hello team,
We have updated the docker of Windows package builder to use latest minGW version 9.3.0.
Regards.
> Update Windows compiler dockerfile to update minGW (5.0-dev branch) 

- debs/Debian/amd64/Dockerfile
- debs/SPECS/4.3.0/wazuh-agent/debian/rules
- debs/SPECS/4.3.0/wazuh-manager/debian/rules
- rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
- rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec
|---|
|Closes #758 |
This PR adds the new Ubuntu and Amazon linux SCA files to the SPECS
> Add Ubuntu and Amazon linux SCA files to SPECS

- rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
- rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec
This PR adds ossec-init to 4.3 rpm SPECS.
> Add ossec-init to 4.3 RPM SPECS

- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
This PR closes https://github.com/wazuh/wazuh-packages/issues/816. The `wazuh-api` version to be obsoleted is fixed.
> Fixed wazuh-api obsolete harcode

- aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
- rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
- solaris/solaris11/SPECS/template_agent_v5.0.0.json
|---|
|https://github.com/wazuh/wazuh/issues/9181|
This PR add azure wodle to rpm, aix and solaris spec files
> Add azure wodle to rpm, aix and solaris spec files

- debs/SPECS/5.0.0/wazuh-agent/debian/postinst
- debs/SPECS/5.0.0/wazuh-manager/debian/postinst
- macos/package_files/5.0.0/postinstall.sh
- macos/specs/5.x/wazuh-agent-5.0.0.pkgproj
- rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
- rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
- solaris/solaris11/SPECS/template_agent_v5.0.0.json
|---|
|https://github.com/wazuh/wazuh/issues/9178|
> Deleted localtime

- aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
|---|
|https://github.com/wazuh/wazuh/issues/8304|
This PR change the location of .agent_info and .wait files from queue/sockets to var/run directory in aix spec
> Change location of .agent_info and .wait files to /var/run/ in aix spec

- aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
|---|
|#824 |
This PR fixes a typo with the netstat command in ossec.conf
> Fix netstat aix 4.2

- aix/SPECS/4.3.0/wazuh-agent-4.3.0-aix.spec
|---|
|Closes #824 |
This PR fixes a typo with the netstat command in ossec.conf
> Fix netstat typo

- rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
- rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
|---|
|#828|
This PR fixes an error when upgrading from versions lower than 3.6.1
> Fix broken symlink in RPM upgrade

- aix/SPECS/4.3.0/wazuh-agent-4.3.0-aix.spec
- rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
- rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec
|---|
|#828 #827|
This PR applies the changes in PRs https://github.com/wazuh/wazuh-packages/pull/830 and https://github.com/wazuh/wazuh-packages/pull/829 to the master branch.
> Apply changes master

- wazuhapp/Docker/build.sh
Hi team, this PR resolves:
- Use Kibana 7.10.2 when Wazuh is lower than 4.2.2 even when Kibana is 7.11 o higher
- Seed `--allow-root` only for Kibana 7.10.2
<details>
<summary>Test `v4.1.5-7.11.2` should use Kibana `7.10.2`</summary> 
```bash
./generate_wazuh_app.sh -b v4.2.1-7.11.2 -r 1                                                                                                        [1]
Sending build context to Docker daemon  7.168kB
Step 1/6 : FROM centos:8
---> 300e315adb2f
Step 2/6 : RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-centostesting &&     curl -sL https://rpm.nodesource.com/setup_10.x | bash - &&     yum install nodejs git gcc gcc-c++ make sudo zip python3 -y &&     alternatives --set python /usr/bin/python3 &&     npm install -g n
---> Using cache
---> ee6279a1e23b …
```
> Wazuhapp update build script kibana 7.11

- rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
|---|
||
This PR removes the applications SCA directory from the Wazuh agent SPEC files section. This caused the following error when building the package:
```
RPM build errors:
Directory not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-agent-4.3.0-0.commit55f9741.x86_64/var/ossec/tmp/sca-4.3.0-0.commit55f9741-tmp/applications
File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-agent-4.3.0-0.commit55f9741.x86_64/var/ossec/tmp/sca-4.3.0-0.commit55f9741-tmp/applications/*
```
>  Remove applications SCA dir from RP; agent specs

- CHANGELOG.md
- debs/SPECS/4.2.2/wazuh-agent/debian/rules
- rpms/SPECS/4.2.2/wazuh-agent-4.2.2.spec
|---|
|#884|
This PR removes the applications SCA directory from the agent packges.
> Remove applications SCA directory form RPM/DEB agent packages

- CHANGELOG.md
- rpms/build.sh
|---|
|#887|
This PR adds a fix for an error that appeared with find when building CentOS 5 packages.
> Fix error with Find in CentOS 5 package building

- resources/open-distro/unattended-installation/unattended-installation.sh
this prevents the creation of  a new file of "-" in the home directory
|---|
|https://github.com/wazuh/wazuh-packages/issues/890|
When running the unattended installation, a new file "-" is created containing the repo which is useless
> remove "-" from tee command

- unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
|---|
| #947 |
I have removed the repeated argument in method getHelp() of the elasticsearch distributed installer of the unattended scripts.
```
echo -e "\t-k     | --install-kibana Install Kibana"
```
```
[vagrant@centos7 wazuh-packages]$ sudo bash unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh -h
Usage: unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh arguments
-e     | --install-elasticsearch Installs Open Distro for Elasticsearch (cannot be used together with option -k)
-k     | --install-kibana Installs Open Distro for Kibana (cannot be used together with option -e)
-n     | --node-name Name of the node
-c     | --create-certificates Generates the certificates for …
```
> Removed repeated argument in getHelp method in unattended script [stable]

- unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
|---|
| #947 |
I have removed the repeated argument in method getHelp() of the elasticsearch distributed installer of the unattended scripts.
```
echo -e "\t-k     | --install-kibana Install Kibana"
```
```
[vagrant@centos7 wazuh-packages]$ sudo bash unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh -h
Usage: unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh arguments
-e     | --install-elasticsearch Installs Open Distro for Elasticsearch (cannot be used together with option -k)
-k     | --install-kibana Installs Open Distro for Kibana (cannot be used together with option -e)
-n     | --node-name Name of the node
-c     | --create-certificates Generates the certificates for …
```
> Removed repeated argument in getHelp method in unattended script [4.2]

- unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
|---|
| closes #947 |
I have removed the repeated argument in method getHelp() of the elasticsearch distributed installer of the unattended scripts.
```
echo -e "\t-k     | --install-kibana Install Kibana"
```
```
[vagrant@centos7 wazuh-packages]$ sudo bash unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh -h
Usage: unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh arguments
-e     | --install-elasticsearch Installs Open Distro for Elasticsearch (cannot be used together with option -k)
-k     | --install-kibana Installs Open Distro for Kibana (cannot be used together with option -e)
-n     | --node-name Name of the node
-c     | --create-certificates Generates the certificates …
```
> Removed repeated argument in getHelp method in unattended script [master]

- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| #886 |
I removed the line 
```
echo "${resources}/open-distro/tools/certificate-utility/wazuh-cert-tool.sh --max-time 300" 
```
in the opendistro all in one unattended installation script that printed the download link corresponding to the next line: 
```
eval "curl -so ~/wazuh-cert-tool.sh ${resources}/open-distro/tools/certificate-utility/wazuh-cert-tool.sh --max-time 300 ${debug}"
```
```
[vagrant@centos7 wazuh-packages]$ sudo bash unattended_scripts/open-distro/unattended-installation/unattended-installation.sh 
Starting the installation...
Installing all necessary utilities for the installation...
Done
Adding the Wazuh repository...
Done
Installing the Wazuh manager...
Done
Wazuh-manager started
Installing Open Distro for Elasticsearch...
Done
Configuring …
```
> Removed echo corresponding to a download link in unattended installer [4.2]

- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| closes #886 |
I removed the line 
```
echo "${resources}/open-distro/tools/certificate-utility/wazuh-cert-tool.sh --max-time 300" 
```
in the opendistro all in one unattended installation script that printed the download link corresponding to the next line: 
```
eval "curl -so ~/wazuh-cert-tool.sh ${resources}/open-distro/tools/certificate-utility/wazuh-cert-tool.sh --max-time 300 ${debug}"
```
```
[vagrant@centos7 wazuh-packages]$ sudo bash unattended_scripts/open-distro/unattended-installation/unattended-installation.sh 
Starting the installation...
Installing all necessary utilities for the installation...
Done
Adding the Wazuh repository...
Done
Installing the Wazuh manager...
Done
Wazuh-manager started
Installing Open Distro for Elasticsearch...
Done …
```
> Removed echo corresponding to a download link in unattended installer [master]

- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| #886 |
I removed the line 
```
echo "${resources}/open-distro/tools/certificate-utility/wazuh-cert-tool.sh --max-time 300" 
```
in the opendistro all in one unattended installation script that printed the download link corresponding to the next line: 
```
eval "curl -so ~/wazuh-cert-tool.sh ${resources}/open-distro/tools/certificate-utility/wazuh-cert-tool.sh --max-time 300 ${debug}"
```
```
[vagrant@centos7 wazuh-packages]$ sudo bash unattended_scripts/open-distro/unattended-installation/unattended-installation.sh 
Starting the installation...
Installing all necessary utilities for the installation...
Done
Adding the Wazuh repository...
Done
Installing the Wazuh manager...
Done
Wazuh-manager started
Installing Open Distro for Elasticsearch...
Done
Configuring …
```
> Removed echo corresponding to a download link in unattended installer [stable]

- unattended_scripts/elastic-stack/unattended-installation/all-in-one-installation.sh
- unattended_scripts/elastic-stack/unattended-installation/distributed/wazuh-server-installation.sh
- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/distributed/wazuh-server-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| closes https://github.com/wazuh/wazuh-packages/issues/869|
I have  added an escape character before `$` in both the scripts for the opendistro and elastic unattended installs so that when the repo is created, the version of the release is shown correctly
It has been tested in CentOS 5,6,7 and 8
> Unattended script missing escape character[4.2]

- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/920|
I have changed wazuh-passwords-tool.sh so that it only changes the kibana.yml elasticsearch password if the user or one of the users changed is kibanaserver 
>
Checked on CentOS 7 and Ubuntu 18
> Fixed wazuh-passwords-tool.sh so it doesn't remove the password in kibana.yml [4.2]

- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/920|
I have changed wazuh-passwords-tool.sh so that it only changes the kibana.yml elasticsearch password if the user or one of the users changed is kibanaserver 
>
Checked on CentOS 7 and Ubuntu 18
> Fixed wazuh-passwords-tool.sh so it doesn't remove the password in kibana.yml [master]

- macos/package_files/4.3.0/postinstall.sh
|---|
|Closes #880|
This PR fixes an issue with the installation of 4.3.0 in macos systems.
> Fix macos problem with wazuh group

- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/920|
I have added a new parameter, '-f' with which you can give a file in this format:
```
User: 
name: wazuh
password: SecretPassword
User: 
name: elasticsearch
password: SecretPassword2
```
and the passwords of users Wazuh and elasticsearch will be changed to SecretPassword and SecretPassword2 respectively. If you  also use the argument '-a' all users will be changed to random passwords except the ones in the file, which will get the given passwords.
....
Tested on Ubuntu18, CentOS7 and CentOS8
> Added function to get passwords from file in wazuh-passwords-tool.sh[master]

- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/920|
I have added a new parameter, '-f' with which you can give a file in this format:
```
User: 
name: wazuh
password: SecretPassword
User: 
name: elasticsearch
password: SecretPassword2
```
and the passwords of users Wazuh and elasticsearch will be changed to SecretPassword and SecretPassword2 respectively. If you  also use the argument '-a' all users will be changed to random passwords except the ones in the file, which will get the given passwords.
....
Tested on Ubuntu18, CentOS7 and CentOS8
> Added function to get passwords from file in wazuh-passwords-tool.sh[4.2]

- rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
- rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec
|---|
|Closes #912|
This PR removes the unnecessary `chkconfig` dependency from RPM packages, which caused errors in OpenSUSE Tumbleweed installations. 
> Remove chkconfig from RPM SPECS

- unattended_scripts/open-distro/tools/wazuh-offline-download.sh
|---|
|No issue|
This PR adds a script to download all required files for an offline installation of a Wazuh server.
> Add script for downloading the required packages for an offline installation

- unattended_scripts/elastic-stack/unattended-installation/all-in-one-installation.sh
- unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
This PR updates the Elasticsearch version in the unattended scripts to 7.14.2.
> Bump ELK version to 7.14.2

- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| #916 |
The command used in wazuh-password-tool.sh to see if OpenDistro was installed in an OpenSUSE tumbleweed used an inexistent flag:
```
zypper packages --installed
```
I changed it for 
```
zypper packages --installed-only
```
I also removed `grep noarch` in command:
```
elasticinstalled=$(zypper packages --installed | grep opendistroforelasticsearch | grep i+ | grep noarch)
```
for opendistro and filebeat as both of them are installed as x86_64 packages
Log before:
Log after:
```
opensuse:/usr/share/kibana # bash wazuh-passwords-tool.sh -a
11/12/2021 16:56:48 INFO: Generating random passwords
11/12/2021 16:56:48 INFO: Done
11/12/2021 16:56:48 INFO: Creating backup...
11/12/2021 16:56:49 ERROR: The backup could not be created
opensuse:/usr/share/kibana # zypper …
```
> Fixed wazuh-passwords-tool.sh for opensuse tumbleweed [stable]

- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| closes #916 |
The command used in wazuh-password-tool.sh to see if OpenDistro was installed in an OpenSUSE tumbleweed used an inexistent flag:
```
zypper packages --installed
```
I changed it for 
```
zypper packages --installed-only
```
I also removed `grep noarch` in command:
```
elasticinstalled=$(zypper packages --installed | grep opendistroforelasticsearch | grep i+ | grep noarch)
```
for opendistro and filebeat as both of them are installed as x86_64 packages
Log before:
Log after:
```
opensuse:/usr/share/kibana # bash wazuh-passwords-tool.sh -a
11/12/2021 16:56:48 INFO: Generating random passwords
11/12/2021 16:56:48 INFO: Done
11/12/2021 16:56:48 INFO: Creating backup...
11/12/2021 16:56:49 ERROR: The backup could not be created
opensuse:/usr/share/kibana # …
```
> Fixed wazuh-passwords-tool.sh for opensuse tumbleweed [master]

- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| #916 |
The command used in wazuh-password-tool.sh to see if OpenDistro was installed in an OpenSUSE tumbleweed used an inexistent flag:
```
zypper packages --installed
```
I changed it for 
```
zypper packages --installed-only
```
I also removed `grep noarch` in command:
```
elasticinstalled=$(zypper packages --installed | grep opendistroforelasticsearch | grep i+ | grep noarch)
```
for opendistro and filebeat as both of them are installed as x86_64 packages
Log before:
Log after:
```
opensuse:/usr/share/kibana # bash wazuh-passwords-tool.sh -a
11/12/2021 16:56:48 INFO: Generating random passwords
11/12/2021 16:56:48 INFO: Done
11/12/2021 16:56:48 INFO: Creating backup...
11/12/2021 16:56:49 ERROR: The backup could not be created
opensuse:/usr/share/kibana # zypper …
```
> Fixed wazuh-passwords-tool.sh for opensuse tumbleweed [4.2]

- rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec
Due to https://github.com/wazuh/wazuh/pull/10863, this PR reverts wazuh/wazuh-packages#966
> Revert "Add new CDB lists to manager packages"

- CHANGELOG.md
- debs/SPECS/4.3.0/wazuh-agent/debian/postinst
- debs/SPECS/4.3.0/wazuh-manager/debian/postinst
|---|
|Closes #909 |
This PR fixes an error with the change to the new Wazuh user in Debian packages.
> Fix wazuh user error in Debian packages

- unattended_scripts/elastic-stack/unattended-installation/all-in-one-installation.sh
- unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
I have fixed the points in the unattended installer where the logger didn't work as expected. 
Firstly, in the initialization, the installer wrote some points as it waited for events. The next logger line appeared appended to the points. I added a new line with an `echo ""`. 
Secondly, in both installers, all messages for the changed passwords appeared in the same line or with the logger header. They are now printed on a different block, separated by a line, and without the logger header
Log before: 
```
11/15/2021 13:55:14 INFO: Starting the installation...
11/15/2021 13:55:14 INFO: Installing all necessary utilities for the installation...
11/15/2021 13:55:15 INFO: Done
11/15/2021 13:55:15 INFO: Adding the Elasticsearch repository...
11/15/2021 13:55:16 INFO: Done
11/15/2021 13:55:16 …
```
> Fixed the logger for the unattended installer [stable]

- unattended_scripts/elastic-stack/unattended-installation/all-in-one-installation.sh
- unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
I have fixed the points in the unattended installer where the logger didn't work as expected. 
Firstly, in the initialization, the installer wrote some points as it waited for events. The next logger line appeared appended to the points. I added a newline with a `echo ""`. 
Secondly, in both installers, all messages for the changed passwords appeared in the same line or with the logger header. They are now printed on a different block, separated by a line and without the logger header
Log before: 
```
11/15/2021 13:55:14 INFO: Starting the installation...
11/15/2021 13:55:14 INFO: Installing all necessary utilities for the installation...
11/15/2021 13:55:15 INFO: Done
11/15/2021 13:55:15 INFO: Adding the Elasticsearch repository...
11/15/2021 13:55:16 INFO: Done
11/15/2021 13:55:16 INFO: …
```
> Fixed the logger for the unattended installer [4.2]

- unattended_scripts/elastic-stack/unattended-installation/all-in-one-installation.sh
- unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
I have fixed the points in the unattended installer where the logger didn't work as expected. 
Firstly, in the initialization, the installer wrote some points as it waited for events. The next logger line appeared appended to the points. I added a new line with an `echo ""`. 
Secondly, in both installers, all messages for the changed passwords appeared in the same line or with the logger header. They are now printed on a different block, separated by a line, and without the logger header
Log before: 
```
11/15/2021 13:55:14 INFO: Starting the installation...
11/15/2021 13:55:14 INFO: Installing all necessary utilities for the installation...
11/15/2021 13:55:15 INFO: Done
11/15/2021 13:55:15 INFO: Adding the Elasticsearch repository...
11/15/2021 13:55:16 INFO: Done
11/15/2021 13:55:16 …
```
> Fixed the logger for the unattended installer [master]

- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| #898 |
I have removed the lines that created and populated the file instances.yml in the method installElasticsearch(). Instead, a template is downloaded and its values are changed using grep and sed, in a similar way as other files are downloaded and changed in the script.
Tested on CentOS 7 and Debian 9
The file instances.yml as left after the installation:
```
[vagrant@centos7 ~]$ sudo cat /root/instances.yml
elasticsearch-nodes:
- name: elasticsearch
ip:
- 127.0.0.1
wazuh-servers:
- name: filebeat
ip:
- 127.0.0.1      
kibana:
- name: kibana
ip:
- 127.0.0.1        
[vagrant@centos7 ~]$ 
```
> Removed usage of echo to populate instances.yml, changed for template and sed [4.2]

- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| #898 |
I have removed the lines that created and populated the file instances.yml in the method installElasticsearch(). Instead, a template is downloaded and its values are changed using grep and sed, in a similar way as other files are downloaded and changed in the script.
Tested on CentOS 7 and Debian 9
The file instances.yml as left after the installation:
```
[vagrant@centos7 ~]$ sudo cat /root/instances.yml
elasticsearch-nodes:
- name: elasticsearch
ip:
- 127.0.0.1
wazuh-servers:
- name: filebeat
ip:
- 127.0.0.1      
kibana:
- name: kibana
ip:
- 127.0.0.1        
[vagrant@centos7 ~]$ 
```
> Removed usage of echo to populate instances.yml, changed for template and sed [stable]

- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| closes #898 |
I have removed the lines that created and populated the file instances.yml in the method installElasticsearch(). Instead, a template is downloaded and its values are changed using grep and sed, in a similar way as other files are downloaded and changed in the script.
Tested on CentOS 7 and Debian 9
The file instances.yml as left after the installation:
```
[vagrant@centos7 ~]$ sudo cat /root/instances.yml
elasticsearch-nodes:
- name: elasticsearch
ip:
- 127.0.0.1
wazuh-servers:
- name: filebeat
ip:
- 127.0.0.1      
kibana:
- name: kibana
ip:
- 127.0.0.1        
[vagrant@centos7 ~]$ 
```
> Removed usage of echo to populate instances.yml, changed for template and sed [master]

- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
|---|
| #1015 |
I changed the wazuh-passwords-tool call to the logger and message so that the last message is not:
```
11/25/2021 08:21:34 WARNING: Passwords changed. Remember to update the password in /etc/filebeat/filebeat.yml and /etc/kibana/kibana.yml if necessary and restart the services.
```
but:
```
11/25/2021 08:21:34 INFO: Passwords changed. Remember to update the password in /etc/filebeat/filebeat.yml and /etc/kibana/kibana.yml if necessary and restart the services. More info: https://documentation.wazuh.com/current/user-manual/elasticsearch/elastic-tuning.html#change-users-password
```
```
[vagrant@centos7 wazuh-packages]$ sudo bash unattended_scripts/tools/wazuh-passwords-tool.sh -a
11/25/2021 15:53:11 INFO: Generating random passwords
11/25/2021 15:53:11 INFO: …
```
> Removed warning and added text in wazuh-passwords-tool.sh final message [4.3]

- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
|---|
| #1015 |
I changed the wazuh-passwords-tool call to the logger and message so that the last message is not:
```
11/25/2021 08:21:34 WARNING: Passwords changed. Remember to update the password in /etc/filebeat/filebeat.yml and /etc/kibana/kibana.yml if necessary and restart the services.
```
but:
```
11/25/2021 08:21:34 INFO: Passwords changed. Remember to update the password in /etc/filebeat/filebeat.yml and /etc/kibana/kibana.yml if necessary and restart the services. More info: https://documentation.wazuh.com/current/user-manual/elasticsearch/elastic-tuning.html#change-users-password
```
```
[vagrant@centos7 wazuh-packages]$ sudo bash unattended_scripts/tools/wazuh-passwords-tool.sh -a
11/25/2021 15:53:11 INFO: Generating random passwords
11/25/2021 15:53:11 INFO: …
```
> Removed warning and added text in wazuh-passwords-tool.sh final message [4.2]

- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
|---|
| #1015 |
I changed the wazuh-passwords-tool call to the logger and message so that the last message is not:
```
11/25/2021 08:21:34 WARNING: Passwords changed. Remember to update the password in /etc/filebeat/filebeat.yml and /etc/kibana/kibana.yml if necessary and restart the services.
```
but:
```
11/25/2021 08:21:34 INFO: Passwords changed. Remember to update the password in /etc/filebeat/filebeat.yml and /etc/kibana/kibana.yml if necessary and restart the services. More info: https://documentation.wazuh.com/current/user-manual/elasticsearch/elastic-tuning.html#change-users-password
```
```
[vagrant@centos7 wazuh-packages]$ sudo bash unattended_scripts/tools/wazuh-passwords-tool.sh -a
11/25/2021 15:53:11 INFO: Generating random passwords
11/25/2021 15:53:11 INFO: …
```
> Removed warning and added text in wazuh-passwords-tool.sh final message [stable]

- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
|---|
| closes #1015 |
I changed the wazuh-passwords-tool call to the logger and message so that the last message is not:
```
11/25/2021 08:21:34 WARNING: Passwords changed. Remember to update the password in /etc/filebeat/filebeat.yml and /etc/kibana/kibana.yml if necessary and restart the services.
```
but:
```
11/25/2021 08:21:34 INFO: Passwords changed. Remember to update the password in /etc/filebeat/filebeat.yml and /etc/kibana/kibana.yml if necessary and restart the services. More info: https://documentation.wazuh.com/current/user-manual/elasticsearch/elastic-tuning.html#change-users-password
```
```
[vagrant@centos7 wazuh-packages]$ sudo bash unattended_scripts/tools/wazuh-passwords-tool.sh -a
11/25/2021 15:53:11 INFO: Generating random passwords
11/25/2021 …
```
> Removed warning and added text in wazuh-passwords-tool.sh final message [master]

- solaris/solaris11/generate_wazuh_packages.sh
|---|
|Closes #1022 |
This PR adds the user and group ossec during the compilation to avoid error messages.
> Add ossec user and group during compilation

- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| #974, #839 |
When using the debugger option on the unattended installer all commands using `cd` didn't work, as `cd` doesn't work with pipelines. I removed all of them, making sure all paths were complete and not depending on the working directory.
I also changed the condition that made the uninstaller fail. It only worked when all components were installed. Now it only needs one component to function and it uninstalls all components there are.
```
11/24/2021 10:08:25 INFO: Starting the installation...
11/24/2021 10:08:25 INFO: Installing all necessary utilities for the installation...
* base: mirror.gadix.com
* extras: repo.ifca.es
* updates: repo.ifca.es
Package curl-7.29.0-59.el7_9.1.x86_64 …
```
> Removed cd usages from unattended installer and fixed uninstaller [master]

- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| #974, #839 |
When using the debugger option on the unattended installer all commands using `cd` didn't work, as `cd` doesn't work with pipelines. I removed all of them, making sure all paths were complete and not depending on the working directory.
I also changed the condition that made the uninstaller fail. It only worked when all components were installed. Now it only needs one component to function and it uninstalls all components there are.
```
11/24/2021 10:08:25 INFO: Starting the installation...
11/24/2021 10:08:25 INFO: Installing all necessary utilities for the installation...
* base: mirror.gadix.com
* extras: repo.ifca.es
* updates: repo.ifca.es
Package curl-7.29.0-59.el7_9.1.x86_64 …
```
> Removed cd usages in unattended installer and fixed uninstaller [4.2]

- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| #974, #839 |
When using the debugger option on the unattended installer all commands using `cd` didn't work, as `cd` doesn't work with pipelines. I removed all of them, making sure all paths were complete and not depending on the working directory.
I also changed the condition that made the uninstaller fail. It only worked when all components were installed. Now it only needs one component to function and it uninstalls all components there are.
```
11/24/2021 10:08:25 INFO: Starting the installation...
11/24/2021 10:08:25 INFO: Installing all necessary utilities for the installation...
* base: mirror.gadix.com
* extras: repo.ifca.es
* updates: repo.ifca.es
Package curl-7.29.0-59.el7_9.1.x86_64 …
```
> Removed cd usages in unattended installer and fixed uninstaller [stable]

- unattended_scripts/install_functions/opendistro/common.sh
- unattended_scripts/install_functions/opendistro/elasticsearch.sh
- unattended_scripts/install_functions/opendistro/filebeat.sh
- unattended_scripts/install_functions/opendistro/kibana.sh
- unattended_scripts/install_functions/opendistro/wazuh-cert-tool.sh
- unattended_scripts/unattended_installation.sh
|---|
|#1036|
This PR fixes the unattended installation using local files. The current installation does not fail if there is a file that is not found, so as there is no debug mode it is not detected.
The problem is in the directory from where we want to copy files, in the last phase of Elasticsearch configuration, it enter in (`/usr/share/elasticsearch/plugins/opendistro_security/tools/`) directory but it does not restore the previous path when finished
This PR changes the copy command to use an absolute path $(pwd) instead of relative one (./), so that if there is ever a problem in a path it is detectable if debug mode is used. To correct the path a `cd -` has been incorporated in the last phase of Elasticsarch configuration …
> Fix filebeat local install unify unattended

- unattended_scripts/unattended_installation.sh
|---|
|Related to https://github.com/wazuh/wazuh-packages/issues/1036#issuecomment-988321494|
The realpath command is not a native GNU command and is added in the coreutils-8.22 package, this is a problem since older systems like OL6 have coreutils-8.4, which does not provide this command.
The solution is to use a native GNU command, which is `readlink -f`
Added echo to debug path for readlink command
<details><summary>CentOS 7</summary>
[root@centos7 unattended_scripts]# bash unattended_installation.sh -A -l
`readlink:	/home/vagrant/wazuh-packages/unattended_scripts`
12/09/2021 13:40:51 INFO: Configuration file found. Creating certificates...
12/09/2021 13:40:51 INFO: Creating the Elasticsearch certificates...
12/09/2021 13:40:51 INFO: Creating Wazuh server …
> Change realpath to readlink command - Unify unattended

- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
This PR adds an additional configuration step to Opendistro for the Elasticsearch installation process. By adding this option we avoid the `log4j2` vulnerability until new Opendistro packages are released. 
```
[root@wazuh1 vagrant]# tree /etc/elasticsearch/
/etc/elasticsearch/
├── certs
│   ├── admin-key.pem
│   ├── admin.pem
│   ├── elasticsearch-key.pem
│   ├── elasticsearch.pem
│   └── root-ca.pem
├── elasticsearch.keystore
├── elasticsearch.yml
├── jvm.options
├── jvm.options.d
│   └── disabledlog4j.options
└── log4j2.properties
```
Elasticsearch status:
```
[root@wazuh1 vagrant]# systemctl status -l elasticsearch
● elasticsearch.service - Elasticsearch
Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
Active: active (running) since lun …
```
> Added mitigation function

- unattended_scripts/wazuh_install.sh
|---|
||
This PR fixes a wrong parameter used in the health check function which caused the function to not be executed when installing Elasticsearch
> Fix wrong healthcheck parameter

- unattended_scripts/install_functions/opendistro/elasticsearch.sh
- unattended_scripts/install_functions/opendistro/kibana.sh
|---|
|closes #1062 |
I fixed a couple of bugs in the distributed elasticsearch installation. 
- Added a missing `l` for `getConfig roles.yml`
- Corrected missing brackets in condition
- Removed unused parameters in `copyCertificatesElasticsearch einame pos`
`filebeat test output`:
```
[root@centos7 unattended_scripts]# filebeat test output
elasticsearch: https://192.168.56.16:9200...
parse url... OK
connection...
parse host... OK
dns lookup... OK
addresses: 192.168.56.16
dial up... OK
TLS...
security: server's certificate chain verification is enabled
handshake... OK
TLS version: TLSv1.3
dial up... OK
talk to server... OK
version: 7.10.2
```
> Fixed elasticsearch distributed installer

- rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
|---|
|https://github.com/wazuh/wazuh-packages/issues/1034|
I found that the groupdel ossec command would not be necessary, since with the userdel command the group is also deleted, since it is the only user that is part of that group, to avoid any inconvenience that may appear since someone can add another user to ossec group I add a validation.
Centos 7:
From agent:
From manager:
Fedora 32:
From Agent:
From Manager:
> Fix groupdel ossec error in upgrade to 4.3.0

- rpms/SPECS/4.4.0/wazuh-agent-4.4.0.spec
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1034|
I found that the groupdel ossec command would not be necessary, since with the userdel command the group is also deleted, since it is the only user that is part of that group, to avoid any inconvenience that may appear since someone can add another user to ossec group I add a validation.
Centos 7:
From agent:
From manager:
Fedora 32:
From Agent:
From Manager:
> Fix groupdel ossec error in upgrade to Master

- ova/assets/steps.sh
- ova/provision.sh
- unattended_scripts/config/opendistro/kibana/customWelcomeKibana.css
- unattended_scripts/install_functions/opendistro/kibana.sh
|---|
| closes #943 |
Before starting the kibana service we use the same code used previously in the ova to change the kibana interface parameters and files. When kibana is started, the wazuh logo is shown, instead of the opendistro one.
Login screen after all-in-one installation in centos 7:
The all-in-one installation runs correctly in Centos 7 and debian 9
> Unattended changes the login screen in kibana [unified]

- unattended_scripts/install_functions/opendistro/common.sh
- unattended_scripts/install_functions/opendistro/elasticsearch.sh
- unattended_scripts/install_functions/opendistro/filebeat.sh
- unattended_scripts/install_functions/opendistro/kibana.sh
- unattended_scripts/install_functions/opendistro/wazuh-cert-tool.sh
- unattended_scripts/tools/wazuh-passwords-tool.sh
- unattended_scripts/wazuh_install.sh
|---|
||
Added initialize option to kibana all-in-one so it waits for kibana to be up to continue the installation.
> Kibana all-in-one is initialized in the same way as the distributed installation

- ova/assets/custom/messages.sh
- ova/assets/custom/removeVagrant.service
- ova/assets/custom/removeVagrant.sh
- ova/assets/postProvision.sh
- ova/assets/steps.sh
- ova/provision.sh
- unattended_scripts/open-distro/elasticsearch/roles/internal_users.yml
- unattended_scripts/open-distro/elasticsearch/roles/roles_mapping.yml
- unattended_scripts/open-distro/filebeat/7.x/filebeat_unattended.yml
- unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
|Related https://github.com/wazuh/wazuh-packages/issues/952|
This PR remove the wazuh user from the unattended installer and removes its references in the OVA and AMI
This PR also add a development flag to use packages-dev repository and simplifies the main of unattended-installation.sh script
Logs and tests can be found in:
- https://github.com/wazuh/wazuh-packages/issues/952#issuecomment-992706967
- https://github.com/wazuh/wazuh-packages/issues/952#issuecomment-993688542
Related to race condition between elasticsearch and filebeat when services start:
```
ERROR        [publisher_pipeline_output]        pipeline/output.go:154        Failed to connect to backoff(elasticsearch(https://127.0.0.1:9200)): Get "https://127.0.0.1:9200": dial tcp 127.0.0.1:9200: connect: …
```
> Remove wazuh user from unattended/OVA/AMI 4.3

- unattended_scripts/open-distro/tools/certificate-utility/wazuh-cert-tool.sh
|---|
|Related https://github.com/wazuh/wazuh-jenkins/issues/3133|
This PR fixes a problem with the expiration date of the admin.pem certificate, which keeps its expiration date by default (1 month), this fix equates the date to the other certificates (3650 days)
Same changes and test as https://github.com/wazuh/wazuh-packages/pull/1083
> Increase admin.pem cert expiration date master

- unattended_scripts/open-distro/tools/certificate-utility/wazuh-cert-tool.sh
|---|
|Related https://github.com/wazuh/wazuh-jenkins/issues/3133|
This PR fixes a problem with the expiration date of the admin.pem certificate, which keeps its expiration date by default (1 month), this fix equates the date to the other certificates (3650 days)
Same changes and test as https://github.com/wazuh/wazuh-packages/pull/1083
> Increase admin.pem cert expiration date stable

- unattended_scripts/open-distro/tools/certificate-utility/wazuh-cert-tool.sh
|---|
|Related https://github.com/wazuh/wazuh-jenkins/issues/3133|
This PR fixes a problem with the expiration date of the admin.pem certificate, which keeps its expiration date by default (1 month), this fix equates the date to the other certificates (3650 days)
Same changes and test as https://github.com/wazuh/wazuh-packages/pull/1083
> Increase admin.pem cert expiration date 4.2

- unattended_scripts/install_functions/opendistro/wazuh-cert-tool.sh
- unattended_scripts/tools/wazuh-cert-tool.sh
|---|
|Related https://github.com/wazuh/wazuh-jenkins/issues/3133|
This PR fixes a problem with the expiration date of the admin.pem certificate, which keeps its expiration date by default (1 month), this fix equates the date to the other certificates (3650 days)
Before fix
```
[root@centos7 certs]# openssl x509 -enddate -noout -in admin.pem
notAfter=Dec 15 14:38:20 2021 GMT
[root@centos7 certs]# openssl x509 -enddate -noout -in elasticsearch.pem 
notAfter=Nov 13 14:38:20 2031 GMT
[root@centos7 certs]# openssl x509 -enddate -noout -in filebeat.pem 
notAfter=Nov 13 14:38:20 2031 GMT
[root@centos7 certs]# openssl x509 -enddate -noout -in kibana.pem 
notAfter=Nov 13 14:38:21 2031 GMT
[root@centos7 certs]# openssl x509 -enddate -noout -in root-ca.pem 
notAfter=Nov 13 14:38:20 …
```
> Increase admin.pem cert expiration date unify-unattended

- unattended_scripts/wazuh_install.sh
|---|
| closes #1071 |
This PR removes the parameters `-wn|--wazuh-node-name` and `-en|--elastic-node-name`. The names of the nodes must now be passed after the parameters `-w|--wazuh-server` and `-e|--elasticsearch`
```
[vagrant@centos7 unattended_scripts]$ bash wazuh_install.sh -h
NAME
wazuh_install.sh - Install and configure Wazuh All-In-One components.
SYNOPSIS
wazuh_install.sh [OPTIONS]
DESCRIPTION
-a,  --all-in-one
All-In-One installation.
-w,  --wazuh-server <wazuh-node-name>
Wazuh server installation. It includes Filebeat.
-e,  --elasticsearch <elasticsearch-node-name>
Elasticsearch installation.
-k,  --kibana
Kibana installation.
-c,  --create-certificates
Create certificates from instances.yml file.
-wk, --wazuh-key <wazuh-cluster-key>
Use this option as well as …
```
> Removed the parameters for node names in the unattended installer

- debs/Debian/amd64/Dockerfile
- debs/Debian/arm64/Dockerfile
- debs/Debian/armhf/Dockerfile
- debs/Debian/i386/Dockerfile
- debs/Debian/ppc64le/Dockerfile
- rpms/CentOS/5/i386/Dockerfile
- rpms/CentOS/5/x86_64/Dockerfile
- rpms/CentOS/6/i386/Dockerfile
- rpms/CentOS/6/x86_64/Dockerfile
- rpms/CentOS/7/aarch64/Dockerfile
- rpms/CentOS/7/armv7hl/Dockerfile
- rpms/CentOS/7/ppc64le/Dockerfile
- wpk/linux/x86_64/Dockerfile
|---|
|Closes [core#10967](https://github.com/wazuh/wazuh/issues/10967)|
This bug has been found to manifest itself when binaries are compiled with g ++ and then packed into an rpm, causing the problem of sometimes not starting the wazuh-modulesd process
> Update g++ to fix undefined behavior on opensuse tumbleweed

- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
Related https://github.com/wazuh/wazuh-packages/pull/1093
The command that adds the option to the .options file redirects the output to the debug file, this causes the content to not be added to the disabledlog4j.options file, so the fix is not applied. This PR corrects this redirection so that it is correctly added to the destination file
Malformed command:
```
eval 'echo '\''-Dlog4j2.formatMsgNoLookups=true'\'' > /etc/elasticsearch/jvm.options.d/disabledlog4j.options >> /var/log/wazuh-unattended-installation.log 2>&1'
```
Fixed command:
```
eval 'echo '\''-Dlog4j2.formatMsgNoLookups=true'\'' > /etc/elasticsearch/jvm.options.d/disabledlog4j.options 2>&1'
```
```
[root@centos7 vagrant]# cat /etc/elasticsearch/jvm.options.d/disabledlog4j.options 
-Dlog4j2.formatMsgNoLookups=true
```
AMI …
> Fix log4j mitigation options file stable

- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
Related https://github.com/wazuh/wazuh-packages/pull/1069
The command that adds the option to the .options file redirects the output to the debug file, this causes the content to not be added to the disabledlog4j.options file, so the fix is not applied. This PR corrects this redirection so that it is correctly added to the destination file
Malformed command:
```
eval 'echo '\''-Dlog4j2.formatMsgNoLookups=true'\'' > /etc/elasticsearch/jvm.options.d/disabledlog4j.options >> /var/log/wazuh-unattended-installation.log 2>&1'
```
Fixed command:
```
eval 'echo '\''-Dlog4j2.formatMsgNoLookups=true'\'' > /etc/elasticsearch/jvm.options.d/disabledlog4j.options 2>&1'
```
```
[root@centos7 vagrant]# cat /etc/elasticsearch/jvm.options.d/disabledlog4j.options 
-Dlog4j2.formatMsgNoLookups=true
```
AMI …
> Fix log4j mitigation options file 4.2

- unattended_scripts/install_functions/opendistro/elasticsearch.sh
Related https://github.com/wazuh/wazuh-packages/pull/1093
The command that adds the option to the .options file redirects the output to the debug file, this causes the content to not be added to the disabledlog4j.options file, so the fix is not applied. This PR corrects this redirection so that it is correctly added to the destination file
```
eval 'echo '\''-Dlog4j2.formatMsgNoLookups=true'\'' > /etc/elasticsearch/jvm.options.d/disabledlog4j.options 2>&1'
```
```
[root@centos7 vagrant]# cat /etc/elasticsearch/jvm.options.d/disabledlog4j.options 
-Dlog4j2.formatMsgNoLookups=true
```
> Fix log4j mitigation options file unify

- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
|https://github.com/wazuh/wazuh-kibana-app/issues/2664|
If you run the unattended-installation.sh script on a minimal CentOS8 system, it finished without a noticeable error, but the Filebeat modules for Wazuh are not extracted since it needs tar. Problem is described in the issue above. Added tar as a required package. 
- Run the installation script on following platforms:
**Did not tested in on a zypper or apt based OS!**
> Fix missing tar as dependency in unattended-installation.sh

- unattended_scripts/install_functions/opendistro/wazuh-passwords-tool.sh
Related https://github.com/wazuh/wazuh-packages/issues/1057
This PR fixes a problem in the wazuh-password-tool.sh script that prevents changing the passwords of opendistro users by specifying a file. Also, this PR add to password validation the character `-` to allow AMI-style passwords. Detection of elasticsearch package installation is also fixed.
<details><summary>Install stage</summary>
```
[root@centos8 vagrant]# bash wazuh_install.sh -a -l -d
12/21/2021 17:57:18 INFO: Configuration file found. Creating certificates...
12/21/2021 17:57:18 INFO: Creating the Elasticsearch certificates...
12/21/2021 17:57:18 INFO: Creating Wazuh server certificates...
12/21/2021 17:57:18 INFO: Creating Kibana certificate...
12/21/2021 17:57:18 INFO: Certificates creation finished. They can be found in …
```
> Fix wazuh password tool unify

- wpk/linux/x86_64/Dockerfile
With the update to gcc9 in the package creation containers, the pip3 botocore package has been updated to a higher version than supported. This causes the linux wpk to fail.
This PR fixes the botocore version in the linux wpk Dockerfile
Error: https://ci.wazuh.info/job/Packages_builder/78923/console
Fixed: https://ci.wazuh.info/view/Packages/job/Packages_builder/78980/
> Fix linux wpk generation 4.3

- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
|Related PR https://github.com/wazuh/wazuh-packages/pull/1104|
This PR adds a new mitigation to the log4j vulnerabilities since the current mitigation is not fully effective. This new mitigation updates the versions of the JAR to 2.17
See related PR.
> Added new log4j remediation stable

- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
| Related PR: https://github.com/wazuh/wazuh-packages/pull/1069 | 
This PR adds a new mitigation to the log4j vulnerabilities since the current mitigation is not fully effective. This new mitigation updates the versions of the JAR to 2.17
<details><summary>Install</summary>
```
[root@centos8 unattended-installation]# bash unattended-installation.sh 
12/22/2021 19:15:22 INFO: Starting the installation...
12/22/2021 19:15:22 INFO: Installing all necessary utilities for the installation...
12/22/2021 19:15:30 INFO: Done
12/22/2021 19:15:30 INFO: Adding the Wazuh repository...
12/22/2021 19:15:30 INFO: Done
12/22/2021 19:15:30 INFO: Installing the Wazuh manager...
12/22/2021 19:16:21 INFO: Done
12/22/2021 19:16:35 INFO: Wazuh-manager started
12/22/2021 19:16:35 INFO: …
```
> Added new log4j remediation 4.2

- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
|Related PR https://github.com/wazuh/wazuh-packages/pull/1104|
This PR adds a new mitigation to the log4j vulnerabilities since the current mitigation is not fully effective. This new mitigation updates the versions of the JAR to 2.17
See related PR.
> Added new log4j remediation 4.3

- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
|---|
|Related PR https://github.com/wazuh/wazuh-packages/pull/1104|
This PR adds a new mitigation to the log4j vulnerabilities since the current mitigation is not fully effective. This new mitigation updates the versions of the JAR to 2.17
See related PR.
> Added new log4j remediation master

- debs/SPECS/4.4.0/wazuh-manager/debian/preinst
- rpms/SPECS/4.4.0/wazuh-manager-4.4.0.spec
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1025|
The ownership change process is moved so that it is the last thing to do in the upgrade process
A validation is added for the ossec-authd daemon, if it is started, the process is eliminated before the upgrade
https://devel.ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1496/consoleFull
> Fix client keys Ownership for 3.7.x and previous versions to Master

- CHANGELOG.md
- rpms/SPECS/4.4.0/wazuh-agent-4.4.0.spec
- rpms/SPECS/4.4.0/wazuh-manager-4.4.0.spec
- solaris/solaris11/SPECS/template_agent_v4.4.0.json
|---|
|#989|
Hi team!
As part of the development of the issue https://github.com/wazuh/wazuh/issues/9103, we need to update the SPECS files to be able to generate properly the new packages.
The main branch of this development is the following https://github.com/wazuh/wazuh/tree/9103-replace-fim-db-dbsync
Closes #989 
> Add fimdblib to SPECS files

- unattended_scripts/install_functions/opendistro/common.sh
- unattended_scripts/wazuh_install.sh
|---|
||
This PR changes the condition that checks if the names of the nodes are in the configuration file. Previously, as it used a regex, it would detect `elasticsearch` was in the file if there was a node named `elasticsearch1` in the file.
> Changed condition to check node names

- debs/Debian/amd64/Dockerfile
- debs/Debian/arm64/Dockerfile
- debs/Debian/armhf/Dockerfile
- debs/Debian/ppc64le/Dockerfile
|---|
|Community issue|
Nodejs does not support Debian Wheezy and since the creation of the API is not supported, the installation of Nodejs is unnecessary.
> Remove nodejs from deb Dockerfiles 4.2

- CHANGELOG.md
- solaris/solaris11/SPECS/template_agent_v4.3.0.json
|---|
|Closes #1125 |
In this PR we add the files added in https://github.com/wazuh/wazuh/pull/9279 to the `wodles/gcloud` folder to the Solaris11 SPEC.
> Add new `wodles/gcloud` files and folders to Solaris11 SPEC

- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/distributed/wazuh-server-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
This PR corrects the check of the necessary requirements for the wazuh distributed installation, since 2GB of ram are necessary instead of 4GB.
The new parameter would return the memory value in Gigabytes, so even though the physically available memory in MB is always somewhat less than that total, we make sure that the physical requirements are met:
```
free --giga | awk '/^Mem:/{print $2}'
4
```
This fix is determined by the requirements established in: https://documentation.wazuh.com/current/installation-guide/requirements.html
> Fix unattended distributed check 4.2

- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/distributed/wazuh-server-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
This PR corrects the check of the necessary requirements for the wazuh distributed installation, since 2GB of ram are necessary instead of 4GB.
The new parameter would return the memory value in Gigabytes, so even though the physically available memory in MB is always somewhat less than that total, we make sure that the physical requirements are met:
```
free --giga | awk '/^Mem:/{print $2}'
4
```
This fix is determined by the requirements established in: https://documentation.wazuh.com/current/installation-guide/requirements.html
> Fix unattended distributed check 4.3

- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/distributed/wazuh-server-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
This PR corrects the check of the necessary requirements for the wazuh distributed installation, since 2GB of ram are necessary instead of 4GB.
The new parameter would return the memory value in Gigabytes, so even though the physically available memory in MB is always somewhat less than that total, we make sure that the physical requirements are met:
```
free --giga | awk '/^Mem:/{print $2}'
4
```
This fix is determined by the requirements established in: https://documentation.wazuh.com/current/installation-guide/requirements.html
> Fix unattended distributed check master

- unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
- unattended_scripts/open-distro/unattended-installation/distributed/wazuh-server-installation.sh
- unattended_scripts/open-distro/unattended-installation/unattended-installation.sh
This PR corrects the check of the necessary requirements for the wazuh distributed installation, since 2GB of ram are necessary instead of 4GB.
The new parameter would return the memory value in Gigabytes, so even though the physically available memory in MB is always somewhat less than that total, we make sure that the physical requirements are met:
```
free --giga | awk '/^Mem:/{print $2}'
4
```
This fix is determined by the requirements established in: https://documentation.wazuh.com/current/installation-guide/requirements.html
> Fix unattended distributed check stable

- unattended_scripts/wazuh_install.sh
This PR adds a new option: disable spinner output. If the unattended installer is used by Ansible and other deployment tools, it will produce an annoying output. We option `-ds` disable the spinner.
> Disable spinner option needed

- debs/SPECS/4.4.0/wazuh-agent/debian/postinst
- debs/SPECS/4.4.0/wazuh-manager/debian/postinst
|---|
|#1148|
This PR fixes a minor error in the posinstall script of Debian packages.
> Fix echo redirection in Debian in postinst

- debs/SPECS/4.3.0/wazuh-agent/debian/postinst
- debs/SPECS/4.3.0/wazuh-manager/debian/postinst
|---|
|#1148|
This PR fixes a minor error in the posinstall script of Debian packages.
> Fix echo redirection in Debian postinst

- unattended_scripts/open-distro/tools/certificate-utility/wazuh-cert-tool.sh
|---|
|-|
The use of parameters does not produce the reading of the instances.yml file, so it does not generate the certificates, this PR corrects this behavior
```
[root@wazuh-manager ~]# ls certs/
[root@wazuh-manager ~]# bash wazuh-cert-tool.sh -k -w
01/11/2022 21:43:25 INFO: Configuration file found. Creating certificates...
01/11/2022 21:43:25 INFO: Creating Wazuh server certificates...
01/11/2022 21:43:25 INFO: Wazuh server certificates created.
01/11/2022 21:43:25 INFO: Creating Kibana certificate...
01/11/2022 21:43:25 INFO: Kibana certificates created.
[root@wazuh-manager ~]# ls certs/
wazuh.conf  wazuh.csr  wazuh-key.pem  kibana.conf  kibana.csr  kibana-key.pem
```
> Fix certificates creation using parameters stable

- unattended_installer/install_functions/opendistro/wazuh-cert-tool.sh
|---|
|-|
The use of parameters does not produce the reading of the config.yml file, so it does not generate the certificates, this PR corrects this behavior
```
[root@wazuh-manager ~]# ls certs
ls: cannot access certs: No such file or directory
[root@wazuh-manager ~]# bash wazuh-cert-tool.sh -w -k
11/01/2022 22:15:00 INFO: Creating the Wazuh server certificates.
11/01/2022 22:15:00 INFO: Wazuh server certificates created.
11/01/2022 22:15:00 INFO: Creating the Kibana certificate.
11/01/2022 22:15:00 INFO: Kibana certificates created.
[root@wazuh-manager ~]# ls certs
filebeat.conf  filebeat.csr  filebeat-key.pem  kibana.conf  kibana.csr  kibana-key.pem
```
> Fix certificates creation using parameters unify

- unattended_installer/install_functions/opendistro/wazuh-passwords-tool.sh
|---|
|#1152|
Added the functionality to allows providing the name of an interface and then obtaining its associated IP, in the wazuh-passwords-tool.sh script
To do this, the value of network.host is taken from the file /etc/elasticsearch/elasticsearch.yml
> Obtain IP of an interface in wazuh passwords tools script

- unattended_installer/install_functions/opendistro/checks.sh
- unattended_installer/install_functions/opendistro/kibana.sh
- unattended_installer/install_functions/opendistro/wazuh-cert-tool.sh
- unattended_installer/install_functions/opendistro/wazuh-passwords-tool.sh
|---|
||
These PR ads multiple improvements to the installer script
> Unify unattended improvements

- tests/unattended/unit/suites/test-kibana.sh
- tests/unattended/unit/unit-tests.sh
closes https://github.com/wazuh/wazuh-packages/issues/1181
Used https://bach.sh/ to create unit tests for each function. In the directory tests/unattended there is a file called test-{script-name}.sh for each script in unattended installer. Inside that file are defined the unit tests for each function of {script-name}.sh. To call them we use the auxiliary script unit-test.sh, which creates a docker environment in which to run the tests.
Example of output:
```
[verdx@verdx unit]$ bash unit-tests.sh -f kibana
19/01/2022 14:49:33 INFO: Docker image found.
19/01/2022 14:49:33 INFO: Unit tests for kibana.sh.
1..20
ok 1 - installKibana zypper
ok 2 - configureKibana dist two kibana nodes two elastic nodes
ok 3 - ASSERT FAIL installKibana zypper error
ok 4 - ASSERT FAIL configureKibana dist error …
```
> Unit testing using Bach [kibana.sh]

- tests/unattended/unit/docker-unit-testing-tool/Dockerfile
- tests/unattended/unit/suites/test-kibana.sh
- unattended_installer/install_functions/opendistro/checks.sh
- unattended_installer/install_functions/opendistro/kibana.sh
- unattended_installer/install_functions/opendistro/wazuh-passwords-tool.sh
- unattended_installer/wazuh_install.sh
|---|
||
This PR adds check for the elasticsearch cluster to the kibana installation.
```
[root@centos repo]# ./wazuh_install.sh -l -k KI_C -d
20/01/2022 09:48:35 INFO: Check recommended minimum hardware requirements for Kibana done.
20/01/2022 09:48:35 INFO: Starting all necessary utility installation.
20/01/2022 09:48:35 INFO: All necessary utility installation finished.
20/01/2022 09:48:35 INFO: Adding the Wazuh repository.
20/01/2022 09:48:36 INFO: Wazuh repository added.
20/01/2022 09:48:36 INFO: Starting Kibana installation.
20/01/2022 09:50:02 INFO: Kibana installation finished.
20/01/2022 09:50:23 INFO: Wazuh Kibana plugin installed.
20/01/2022 09:50:24 INFO: Kibana certificate setup finished.
20/01/2022 09:50:24 INFO: Setting passwords.
20/01/2022 09:50:25 INFO: …
```
> Add cluster checks to kibana installation

- tests/unattended/unit/unit-tests.sh
- Argument `-f` took all files and the next argument.
- The shared volume being in the /tmp file could be a problem if some non-sudo user didn't have access to it, changed it to the directory where unit-tests.sh is executed.
> Fixes bugs in unit-tests.sh 

- CHANGELOG.md
- rpms/SPECS/4.4.0/wazuh-agent-4.4.0.spec
- solaris/solaris11/SPECS/template_agent_v4.4.0.json
|---|
|Closes #1122 |
In this PR we modify the Solaris11 and RPM SPEC files to consider the addition of the Azure integration to agents made for wazuh/wazuh#10662, which is expected to be released in `4.4.0`.
We tested the modified packages by creating a Solaris11 and a RPM package and installing them in a Solaris11 and a Centos 8 machine respectively. Everything worked as expected, as can be seen in the following output:
<details><summary>Package installation and file permissions in Solaris11</summary>
```
root@solaris-11:/tmp# pkg install -g ./wazuh-agent_v4.4.0-sol11-i386.p5p wazuh-agent
Services to change:  1
Create boot environment: No
Create backup boot environment: No
DOWNLOAD                                PKGS         FILES    XFER (MB) …
```
> Add azure wodle to Solaris11 and RPM agent SPEC files

- arch/generate_arch_package.sh
|---|
|Related #1191 |
This PR adds the parameter --packages-branch to the help message and include a check to force the use of the  
--branch and --packages-branch parameters before building the package.
- Tests for ArchLinux
> Fix archlinux package generation parameters 4.3

- tests/unattended/install/test_unattended.py
|---|
|https://github.com/wazuh/wazuh-jenkins/issues/3138|
This PR updates the unattended install tests to modify the exception for Fedora and OpenSuse distributions
> Exception updated

- unattended_installer/install_functions/opendistro/wazuh-cert-tool.sh
|Related PR|
|---|
|https://github.com/wazuh/wazuh-packages/pull/1197|
Some small changes to fix small errors detected by the unit testing in wazuh-cert-tool.sh
> Fixed errors detected by the unit testing [wazuh-cert-tool.sh]

- tests/unattended/unit/suites/test-checks.sh
- tests/unattended/unit/suites/test-common.sh
- tests/unattended/unit/suites/test-elasticsearch.sh
- tests/unattended/unit/suites/test-filebeat.sh
- tests/unattended/unit/suites/test-kibana.sh
- tests/unattended/unit/suites/test-wazuh-cert-tool.sh
- tests/unattended/unit/suites/test-wazuh.sh
closes #1197 
Used https://bach.sh/ to create unit tests for each function. In the directory tests/unattended there is a file called test-{script-name}.sh for each script in unattended installer. Inside that file are defined the unit tests for each function of {script-name}.sh. To call them we use the auxiliary script unit-test.sh, which creates a docker environment in which to run the tests.
Example of output:
```
[verdx@verdx unit]$ bash unit-tests.sh -f wazuh-cert-tool
24/01/2022 16:45:06 INFO: Docker image found.
24/01/2022 16:45:06 INFO: Unit tests for wazuh-cert-tool.sh.
1..28
ok 1 - 06 generateCertificateconfiguration DNS
ok 2 - 04 generateAdmincertificate
ok 3 - 01 cleanFiles
ok 4 - ASSERT FAIL 16 readConfig no file
ok 5 - ASSERT FAIL 19 readConfig duplicated wazuh node names
ok 6 …
```
> Unit testing using Bach [wazuh-cert-tool.sh]

- unattended_scripts/open-distro/tools/certificate-utility/wazuh-cert-tool.sh
|---|
|-|
The use of parameters does not produce the reading of the instances.yml file, so it does not generate the certificates, this PR corrects this behavior
```
[root@wazuh-manager ~]# ls certs/
[root@wazuh-manager ~]# bash wazuh-cert-tool.sh -k -w
01/11/2022 21:43:25 INFO: Configuration file found. Creating certificates...
01/11/2022 21:43:25 INFO: Creating Wazuh server certificates...
01/11/2022 21:43:25 INFO: Wazuh server certificates created.
01/11/2022 21:43:25 INFO: Creating Kibana certificate...
01/11/2022 21:43:25 INFO: Kibana certificates created.
[root@wazuh-manager ~]# ls certs/
wazuh.conf  wazuh.csr  wazuh-key.pem  kibana.conf  kibana.csr  kibana-key.pem
```
> Fix certificates creation using parameters 4.3

- unattended_scripts/open-distro/tools/certificate-utility/wazuh-cert-tool.sh
|---|
|-|
The use of parameters does not produce the reading of the instances.yml file, so it does not generate the certificates, this PR corrects this behavior
```
[root@wazuh-manager ~]# ls certs/
[root@wazuh-manager ~]# bash wazuh-cert-tool.sh -k -w
01/11/2022 21:43:25 INFO: Configuration file found. Creating certificates...
01/11/2022 21:43:25 INFO: Creating Wazuh server certificates...
01/11/2022 21:43:25 INFO: Wazuh server certificates created.
01/11/2022 21:43:25 INFO: Creating Kibana certificate...
01/11/2022 21:43:25 INFO: Kibana certificates created.
[root@wazuh-manager ~]# ls certs/
wazuh.conf  wazuh.csr  wazuh-key.pem  kibana.conf  kibana.csr  kibana-key.pem
```
> Fix certificates creation using parameters master

- unattended_scripts/open-distro/tools/certificate-utility/wazuh-cert-tool.sh
|---|
|-|
The use of parameters does not produce the reading of the instances.yml file, so it does not generate the certificates, this PR corrects this behavior
```
[root@wazuh-manager ~]# ls certs/
[root@wazuh-manager ~]# bash wazuh-cert-tool.sh -k -w
01/11/2022 21:43:25 INFO: Configuration file found. Creating certificates...
01/11/2022 21:43:25 INFO: Creating Wazuh server certificates...
01/11/2022 21:43:25 INFO: Wazuh server certificates created.
01/11/2022 21:43:25 INFO: Creating Kibana certificate...
01/11/2022 21:43:25 INFO: Kibana certificates created.
[root@wazuh-manager ~]# ls certs/
wazuh.conf  wazuh.csr  wazuh-key.pem  kibana.conf  kibana.csr  kibana-key.pem
```
> Fix certificates creation using parameters 4.2

- tests/unattended/unit/suites/test-wazuh-passwords-tool.sh
- tests/unattended/unit/unit-tests.sh
closes #1202
Used https://bach.sh/ to create unit tests for each function. In the directory tests/unattended there is a file called test-{script-name}.sh for each script in unattended installer. Inside that file are defined the unit tests for each function of {script-name}.sh. To call them we use the auxiliary script unit-test.sh, which creates a docker environment in which to run the tests.
Example of output:
```
[verdx@verdx unit]$ bash unit-tests.sh -f wazuh-passwords-tool
25/01/2022 15:32:53 INFO: Docker image found.
25/01/2022 15:32:53 INFO: Unit tests for wazuh-passwords-tool.sh.
1..39
ok 1 - 34 restartService initd error
ok 2 - 10 changePassword changeall all users nothing installed
ok 3 - 05 changePassword changeall all users all installed
ok 4 - 35 restartService rc.d/init.d
ok 5 …
```
> Unit testing using Bach [wazuh-passwords-tool.sh]

- wazuhapp/Docker/build.sh
|---|
| None |
This PR adds compatibility to use the `pluginPlatform.version` property `package.json`. It keeps the compatibility with previous versions that used `kibana.version`.
Starting with the Kibana apps for Wazuh `4.3.0`, the `kibana` property in the root of `package.json` was renamed to `pluginPlatform`.
- Build the Kibana app package:
> [Kibana app] Support `pluginPlatform.version` property in the app manifest

- unattended_installer/install_functions/common.sh
|---|
|https://github.com/wazuh/wazuh/issues/11936|
As shown in the issue above, @tonoitp reported that the unattended installer won't run on a minimal Debian system due to some missing packages that are not available by default.
In fact, the Wazuh installation documentation ([Wazuh server > step-by-step](https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/all-in-one.html)) reads that we need to install some packages that don't appear in the unattended installation script:
|Package|Assets provided|
|---|---|
|`software-properties-common`|`add-apt-repository` and repository validation|
|`lsb-release`|`lsb_release` (Debian package post-installation)|
|`gnupg`|`apt-key add` operation|
Seeing that packages `wazuh-manager` and …
> Add missing required packages to the unattended installation scripts

- unattended_installer/install_functions/common.sh
- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/filebeat.sh
- unattended_installer/install_functions/indexer.sh
- unattended_installer/install_functions/manager.sh
- unattended_installer/install_functions/wazuh-passwords-tool.sh
- unattended_installer/wazuh_install.sh
Signed-off-by: verdx <verdx@riseup.net>
|---|
|https://github.com/wazuh/wazuh-packages/pull/1222|
It changes de name of all functions of the modules to be preceded by the module name. For example, installIndexer is changed to indexer_install.
> Unattended installer modules functions must be prefixed by module name. 

- ova/assets/steps.sh
- tests/unattended/unit/suites/test-checks.sh
- tests/unattended/unit/suites/test-common.sh
- tests/unattended/unit/suites/test-elasticsearch.sh
- tests/unattended/unit/suites/test-filebeat.sh
- tests/unattended/unit/suites/test-kibana.sh
- tests/unattended/unit/suites/test-wazuh-passwords-tool.sh
- tests/unattended/unit/suites/test-wazuh.sh
- unattended_installer/install_functions/checks.sh
- unattended_installer/install_functions/common.sh
- unattended_installer/install_functions/dashboards.sh
- unattended_installer/install_functions/filebeat.sh
- unattended_installer/install_functions/indexer.sh
- unattended_installer/install_functions/manager.sh
- unattended_installer/install_functions/wazuh-cert-tool.sh
- unattended_installer/install_functions/wazuh-passwords-tool.sh
- unattended_installer/wazuh_install.sh
|---|
| #1231  |
Changed the names of all functions in checks.sh and common.sh to be preceded by the module name. For example `addWazuhrepo` to `common_addWazuhRepo`
> Changed names for checks.sh and common.sh functions, adding module name 

- unattended_installer/install_functions/common.sh
- unattended_installer/install_functions/wazuh-passwords-tool.sh
|---|
||
Added the output of journalctl -u -r to the logfile when the script fails to start or restart a service.
> Added journalctl output to log when starting or restarting service fails

- stack/dashboard/base/files/etc/http_service.js
- stack/dashboard/deb/debian/postinst
- stack/dashboard/deb/debian/preinst
- stack/dashboard/deb/debian/rules
- stack/dashboard/rpm/wazuh-dashboard.spec
- stack/indexer/base/files/etc/wazuh-indexer/opensearch.yml
- stack/indexer/deb/debian/rules
- stack/indexer/rpm/wazuh-indexer.spec
|---|
|https://github.com/wazuh/wazuh-packages/issues/1258|
- Wazuh plugin download path updated
- Changed error message from "Opensearch Dashboards server is not ready yet" to "Wazuh Dashboard server is not ready yet"
- A validation is added so that, in case of an upgrade, the Keystore is not replaced
```
{"type":"response","@timestamp":"2022-02-15T12:24:30Z","tags":[],"pid":18232,"method":"get","statusCode":200,"req":{"url":"/ui/wazuh_wazuh_bg.svg","method":"get","headers":{"host":"192.168.56.252","connection":"keep-alive","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36","accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","sec-gpc":"1","sec-fetch-site":"same-origin","sec-fetch-m …
```
> Merge Wazuh Dashboard v3 

- rpms/SPECS/4.4.0/wazuh-manager-4.4.0.spec
|---|
|wazuh/wazuh#10107|
This pr is intended to add a new library for packaging in the manager only.
> Add new shared library, to avoid memory fragmentation

- tests/unattended/install/test_unattended.py
- unattended_installer/config/certificate/config.yml
- unattended_installer/config/certificate/config_aio.yml
- unattended_installer/install_functions/checks.sh
- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/manager.sh
- unattended_installer/install_functions/wazuh-cert-tool.sh
- unattended_installer/wazuh_install.sh
|---|
||
This PR modifies the tags in `config.yml` substituting `wazuh_servers` with `server`.
```
nodes:
indexer:
name: node-1
ip: <indexer-node-ip>
server:
name: wazuh-1
ip: <wazuh-manager-ip>
dashboard:
name: dashboard
ip: <dashboard-node-ip>
```
Also, we have replaced elasticsearch with indexer in the install test function names.
```
[root@centos repo]# ./wazuh_install.sh -a -l
16/02/2022 15:39:23 INFO: Starting Wazuh unattended installer. Wazuh version: 4.3.0. Wazuh installer version: 0.1
16/02/2022 15:39:24 INFO: Check recommended minimum hardware requirements for AIO done.
16/02/2022 15:39:24 INFO: --------------------------------- Configuration files ---------------------------------
16/02/2022 15:39:25 INFO: Configuration files created: …
```
> Change wazuh_servers tag in config.yml

- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
| closes #1268 |
`wazuh-passwords-tool` now prints the changed passwords when used with option `-a`
```
root@debian-9:/vagrant/wazuh-packages/unattended_installer# bash wazuh-passwords-tool.sh -a
18/02/2022 14:46:51 INFO: The password for user admin is 1GKbzPf7RXxjZIJaLuJqVwjqlPu7jrUO
18/02/2022 14:46:51 INFO: The password for user kibanaserver is BAuiLidnjhinezBfsX3q88jvsmeBOyWI
18/02/2022 14:46:51 INFO: The password for user kibanaro is 5MiEfxnu2jvA827W0Om2l1aGTamLe2Ha
18/02/2022 14:46:51 INFO: The password for user logstash is sgjxbXYMc3fsBVniAZ4sBaKZ36msFLJG
18/02/2022 14:46:51 INFO: The password for user readall is muSvhPim62nDvHH5CfcnFIEtOrFc78wC
18/02/2022 14:46:51 INFO: The password for user snapshotrestore is XfKYiATVq3PSR7CGMo5J9Td4BIy48x1h
18/02/2022 …
```
> Wazuh Passwords tool prints password when all are changed

- debs/SPECS/4.3.0/wazuh-agent/debian/postinst
- debs/SPECS/4.3.0/wazuh-manager/debian/postinst
|---|
|Closes #1276|
This PR fixes an error where in some Debian systems the ossec group was deleted once all the users had been deleted causing the post install script to fail when upgrading.
```
root@ubuntu20LTS:/home/vagrant# apt install ./wazuh-agent_4.1.0-1_amd64.deb 
Building dependency tree       
Note, selecting 'wazuh-agent' instead of './wazuh-agent_4.1.0-1_amd64.deb'
The following NEW packages will be installed:
wazuh-agent
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/5310 kB of archives.
After this operation, 16.8 MB of additional disk space will be used.
Get:1 /home/vagrant/wazuh-agent_4.1.0-1_amd64.deb wazuh-agent amd64 4.1.0-1 [5310 kB]
Preconfiguring packages …
```
> Check if group exists before removing

- CHANGELOG.md
- aix/generate_wazuh_packages.sh
|---|
|https://github.com/wazuh/wazuh/issues/12201#issuecomment-1050268381|
This PR aims to fix the AIX package generation, since the partition is not resized correctly
Failed: https://ci.wazuh.info/view/Packages/job/Packages_builder_special/408/
```
18:28:09  installing package perl-5.28.0-1 needs 117Mb on the /opt filesystem
18:28:09  installing package gcc-6.3.0-1 needs 87Mb on the /opt filesystem
18:28:09  installing package libstdc++-6.3.0-1 needs 66Mb on the /opt filesystem
18:28:09  ./Configure[3118]: gcc:  not found
```
Success: https://ci.wazuh.info/view/Packages/job/Packages_builder_special/409/
Check related issue with testing
> Fix partition size in AIX package generation

- CHANGELOG.md
- debs/SPECS/4.3.0/wazuh-agent/debian/prerm
- debs/SPECS/4.3.0/wazuh-manager/debian/prerm
- rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
- rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec
|---|
|Closes #1279|
This PR fixes a behavior where Wazuh could continue running after uninstallation if the systemctl service was mishandled.
https://github.com/wazuh/wazuh-packages/issues/1279#issuecomment-1055599620
> Fix Wazuh not stopping after uninstalling

- tests/unattended/install/test_unattended.py
- tests/unattended/unit/suites/test-dashboard.sh
- tests/unattended/unit/suites/test-indexer.sh
- unattended_installer/config/dashboard/dashboard.yml
- unattended_installer/config/dashboard/dashboard_all_in_one.yml
- unattended_installer/config/dashboard/dashboard_unattended.yml
- unattended_installer/config/filebeat/filebeat.yml
- unattended_installer/config/filebeat/filebeat_all_in_one.yml
- unattended_installer/config/filebeat/filebeat_elastic_cluster.yml
- unattended_installer/config/filebeat/filebeat_unattended.yml
- unattended_installer/config/indexer/indexer_all_in_one.yml
- unattended_installer/config/indexer/indexer_unattended_distributed.yml
- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/filebeat.sh
- unattended_installer/install_functions/indexer.sh
- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
|Closes #1287|
This PR changes the ports used by wazuh-indexer to 9200 and 9300 and renames the wazuh-dashboard configuration file.
```
root@debian:/home/vagrant/repo# bash wazuh-install.sh -a
04/03/2022 14:18:09 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
04/03/2022 14:18:10 INFO: --- Configuration files ---
04/03/2022 14:18:10 INFO: Generating configuration files.
04/03/2022 14:18:10 INFO: Created /home/vagrant/repo/wazuh-install-files.tar. Contains Wazuh cluster key, certificates, and passwords necessary for installation.
04/03/2022 14:18:16 INFO: --- Wazuh indexer ---
04/03/2022 14:18:16 INFO: Initializing Wazuh indexer cluster security settings.
04/03/2022 14:19:25 INFO: Wazuh indexer installation finished.
04/03/2022 14:19:25 INFO: Wazuh …
```
> Change indexer port and rename dashboard configuration file

- stack/dashboard/base/builder.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1284|
Changes requested by the frontend team are made
> Dashboard v5

- CHANGELOG.md
- rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
- rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec
|---|
|Closes #1297|
This PR fixes a warning message that showed when upgrading the Wazuh manager related to user deletion.
https://github.com/wazuh/wazuh-packages/issues/1297#issuecomment-1060917614
> Fix user deletion warning RPM manager

- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/filebeat.sh
- unattended_installer/install_functions/indexer.sh
|---|
||
This PR fixes an error with the permissions of the wazuh-indexer when using the wazuh-install.sh script.
```
[root@centos repo]# bash wazuh-install.sh -a -o
09/03/2022 11:52:22 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
09/03/2022 11:52:23 INFO: --- Removing existing Wazuh installation ---
09/03/2022 11:52:23 INFO: Removing Wazuh manager.
09/03/2022 11:52:39 INFO: Wazuh manager removed.
09/03/2022 11:52:39 INFO: Removing Wazuh indexer.
09/03/2022 11:52:40 INFO: Wazuh indexer removed.
09/03/2022 11:52:40 INFO: Removing Filebeat.
09/03/2022 11:52:40 INFO: Filebeat removed.
09/03/2022 11:52:40 INFO: Removing Wazuh dashboard.
09/03/2022 11:52:45 INFO: Wazuh dashboard removed.
09/03/2022 11:52:45 INFO: Installation cleaned.
09/03/2022 11:52:45 …
```
> Fix unattended certificate permissions

- tests/unattended/install/test_unattended.py
|---|
|https://github.com/wazuh/wazuh-jenkins/issues/3321|
This PR fixes an error where the `get_password` function in `test_unattended.py` could not correctly read the password file.
This was caused by the inclusion of comments in the file.
https://devel.ci.wazuh.info/job/Test_unattended/451/
> Adapt test unattended to comments in password_file

- unattended_installer/builder.sh
- unattended_installer/install_functions/checks.sh
- unattended_installer/install_functions/installMain.sh
|---|
|Closes #1228 |
This PR adds the dist-detect.sh script as a function to the unattended script and uses it to check if the system is compatible. This can be ignored by using the -i flag
```
opensuse:/home/vagrant/repo # bash wazuh-install.sh -a -o
09/03/2022 16:28:24 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
09/03/2022 16:28:24 ERROR: The system is not supported, supported systems are: Red Hat Enterprise Linux 7, 8; CentOS 7, 8; Amazon Linux 2; Ubuntu 16.04, 18.04, 20.04
```
```
[root@centos repo]# ./wazuh-install.sh -a -o
09/03/2022 16:29:13 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
09/03/2022 16:29:14 INFO: --- Removing existing Wazuh installation ---
09/03/2022 16:29:14 INFO: Installation cleaned.
09/03/2022 16:29:14 …
```
> Check recommended OS in wazuh installation assistant

- wazuhapp/Docker/Dockerfile
|---|
|-|
Due to Centos 8 EOL, it is necessary to update the Wazuh app generation Dockerfile to use the Centos vault
```
info running @kbn/optimizer
│ info initialized, 0 bundles cached
│ info starting worker [1 bundle]
│ warn worker stderr Browserslist: caniuse-lite is outdated. Please run:
│ warn worker stderr npx browserslist@latest --update-db
│ succ 1 bundles compiled successfully after 134.3 sec
info copying assets from `public/assets` to build
info copying server source into the build and converting with babel
info running yarn to install dependencies
info compressing plugin into [wazuh-7.10.2.zip]
Done in 144.41s.
+ find /tmp/source/plugins/wazuh/build -name '*.zip' -exec mv '{}' /wazuh_app/wazuh_kibana-4.2.5_7.10.2-1.zip ';'
+ '[' no = yes ']'
+ exit 0 …
```
> Add centos8 vault repository due to EOL 4.2

- CHANGELOG.md
- wazuhapp/Docker/Dockerfile
|---|
|-|
Due to Centos 8 EOL, it is necessary to update the APP generation Dockerfile to use the Centos vault
```
info running @kbn/optimizer
│ info initialized, 0 bundles cached
│ info starting worker [1 bundle]
│ warn worker stderr Browserslist: caniuse-lite is outdated. Please run:
│ warn worker stderr npx browserslist@latest --update-db
│ succ 1 bundles compiled successfully after 134.3 sec
info copying assets from `public/assets` to build
info copying server source into the build and converting with babel
info running yarn to install dependencies
info compressing plugin into [wazuh-7.10.2.zip]
Done in 144.41s.
+ find /tmp/source/plugins/wazuh/build -name '*.zip' -exec mv '{}' /wazuh_app/wazuh_kibana-4.2.5_7.10.2-1.zip ';'
+ '[' no = yes ']'
+ exit 0 …
```
> Add centos8 vault repository due to EOL 4.3

- CHANGELOG.md
- wazuhapp/Docker/Dockerfile
|---|
|-|
Due to Centos 8 EOL, it is necessary to update the APP generation Dockerfile to use the Centos vault
```
info running @kbn/optimizer
│ info initialized, 0 bundles cached
│ info starting worker [1 bundle]
│ warn worker stderr Browserslist: caniuse-lite is outdated. Please run:
│ warn worker stderr npx browserslist@latest --update-db
│ succ 1 bundles compiled successfully after 134.3 sec
info copying assets from `public/assets` to build
info copying server source into the build and converting with babel
info running yarn to install dependencies
info compressing plugin into [wazuh-7.10.2.zip]
Done in 144.41s.
+ find /tmp/source/plugins/wazuh/build -name '*.zip' -exec mv '{}' /wazuh_app/wazuh_kibana-4.2.5_7.10.2-1.zip ';'
+ '[' no = yes ']'
+ exit 0 …
```
> Add centos8 vault repository due to EOL master

- solaris/solaris11/generate_wazuh_packages.sh
|---|
||
This PR removes the wazuh-agent.xml svc  from the Solaris 11 package this svc was not used and made the agent to try to start after installation, causing error to appear in the log.
```
root@solaris11:/export/home/vagrant# svcs -Lv svc:/application/wazuh-agent:default
svc:/application/wazuh-agent:default
[ Mar 15 11:09:48 Enabled. ]
[ Mar 15 11:09:48 Rereading configuration. ]
[ Mar 15 11:09:48 Executing start method ("/var/ossec/bin/wazuh-control start"). ]
2022/03/15 11:09:49 wazuh-agentd: ERROR: (4112): Invalid server address found: 'MANAGER_IP'
2022/03/15 11:09:49 wazuh-agentd: CRITICAL: (1215): No client configured. Exiting.
wazuh-agentd: Configuration error. Exiting
[ Mar 15 11:09:49 Method "start" exited with status 1. ]
[ Mar 15 11:09:49 Executing start …
```
> Remove unused svc from solaris 11 package generation

- tests/unattended/install/test_unattended.py
- unattended_installer/cert_tool/certVariables.sh
- unattended_installer/config/dashboard/dashboard_all_in_one.yml
- unattended_installer/config/dashboard/dashboard_unattended.yml
- unattended_installer/config/dashboard/dashboard_unattended_distributed.yml
- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/filebeat.sh
- unattended_installer/install_functions/indexer.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/install_functions/installMain.sh
- unattended_installer/install_functions/installVariables.sh
- unattended_installer/install_functions/manager.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1300|
A subdirectory is created inside the tar named wazuh-install-files.
it is tested on Centos 7 and Ubuntu 20.04 on both systems it works ok.
```
09/03/2022 20:33:56 INFO: --- Wazuh dashboard ---
09/03/2022 20:33:56 INFO: Starting Wazuh dashboard installation.
09/03/2022 20:35:17 INFO: Wazuh dashboard installation finished.
09/03/2022 20:35:17 INFO: Wazuh dashboard post-install configuration finished.
09/03/2022 20:35:17 INFO: Starting service wazuh-dashboard.
09/03/2022 20:35:17 INFO: Wazuh-dashboard service started.
09/03/2022 20:35:33 INFO: Starting Wazuh dashboard.
09/03/2022 20:35:45 INFO: Wazuh dashboard started.
09/03/2022 20:35:45 INFO: --- Summary ---
09/03/2022 20:35:45 INFO: You can access the web …
```
> Folder for tar file in Unnattended installer

- windows/generate_wazuh_msi.ps1
|---|
|Closes https://github.com/wazuh/wazuh/issues/12751|
This issue aims to sign the dynamic libraries, so that they can have a better evaluation, under different malware scanners, from third party vendors.
Many times calls to operating system libraries, or some intrusion to obtain information relevant to the need of the product may seem strange for a third party software, when this software tries to help security.
Dll files signed.
> Sign windows dll files.

- stack/indexer/deb/debian/rules
- stack/indexer/rpm/wazuh-indexer.spec
- unattended_installer/config/indexer/roles/internal_users.yml
|---|
|#1344|
Modify the build of the wazuh indexer package, so that it generates the wazuh-certs-tool.sh, and wazuh-passwords-tool.sh scripts, instead of copying them from the current repository where the package is being built.
To generate the scripts, the builder.sh was used with the -c and -p parameters, respectively.
```
$ sudo ./build_package.sh -s /tmp
...
/root/unattended_installer/builder.sh -c
/root/unattended_installer/builder.sh -p
cp /root/unattended_installer/wazuh-certs-tool.sh /build/wazuh-indexer/wazuh-indexer-4.3.0/debian/wazuh-indexer/usr/share/wazuh-indexer/plugins/opensearch-security/tools/
cp /root/unattended_installer/wazuh-passwords-tool.sh /build/wazuh-indexer/wazuh-indexer-4.3.0/debian/wazuh-indexer/usr/share/wazuh-indexer/plugins/opensearch-securi …
```
> Generate wazuh-certs-tool.sh and wazuh-passwords-tool.sh scripts instead of copying them from repository

- unattended_installer/builder.sh
|---|
|#1348|
- The permissions were only set once in the builder_main function, so it would only gave permission to the first parameter
- I've added the same command so every time a new script is generated it sets the right permissions.
As we can see, only the first parameter has the right permissions
After the change, every new generated script has read and execution permission
> Fixed builder.sh generated permissions

- unattended_installer/install_functions/installMain.sh
This PR aims to change the dependencies installation run prior to configuration files creation. 
```
22/03/2022 17:54:54 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
22/03/2022 17:54:54 INFO: The verbose logging will be redirected to the file: /var/log/wazuh-install.log
22/03/2022 17:55:00 INFO: --- Dependencies ---
22/03/2022 17:55:00 INFO: Installing unzip.
22/03/2022 17:55:01 INFO: Installing wget.
22/03/2022 17:55:04 INFO: --- Configuration files ---
22/03/2022 17:55:04 INFO: Generating configuration files.
22/03/2022 17:55:05 INFO: Created wazuh-install-files.tar. It contains Wazuh cluster key, certificates, and passwords necessary for installation.
22/03/2022 17:55:05 INFO: --- Wazuh indexer ---
```
> Change dependencies installation order

- unattended_installer/install_functions/dashboard.sh
This PR aims to change the Wazuh dashboard messages by other more descriptive.
> Changed starting application messages

- unattended_installer/install_functions/installCommon.sh
|---|
| closes https://github.com/wazuh/wazuh-packages/issues/1373|
Wazuh-install-files and wazuh-install-files.tar removal is added to the RollBack function
Centos 7: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/480/console
Ubuntu Bionic: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/481/console
Distributed: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended_distributed/364/console
> Add rm to wazuh-install-files in rollBack function

- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/filebeat.sh
- unattended_installer/install_functions/indexer.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/install_functions/installMain.sh
|---|
|#1336|
This PR modifies the way we use the certificates in the configuration files during in the installation assistant.
CentOS 7: https://ci.wazuh.info/view/Tests/job/Test_unattended/47/
Ubuntu bionic: https://ci.wazuh.info/view/Tests/job/Test_unattended/48/
Distributed: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended_distributed/380/
> Rename certificates in configuration files

- CHANGELOG.md
- solaris/solaris11/SPECS/template_agent_v4.4.0.json
|---|
|Closes #1316|
In this PR we add the `wodles/gcloud/exceptions.py` file, which was added for wazuh/wazuh#12140 to the Solaris11 SPECS file.
We tested the changes by creating a Solaris11 package using the instructions of the [Wazuh documentation](https://documentation.wazuh.com/current/development/packaging/generate-sol-package.html) and installing it in a Solaris11 machine. Everything worked as expected, as can be seen in the following output:
<details><summary>Package installation and file permissions in Solaris11</summary>
root@solaris11:/tmp# pkg install -g ./wazuh-agent_v4.4.0-sol11-i386.p5p wazuh-agent
Services to change:  1
Create boot environment: No
Create backup boot environment: No
DOWNLOAD                                PKGS …
> Add `wodles/gcloud/exceptions.py` file to Solaris11 SPECS

- documentation-templates/wazuh/filebeat/filebeat.yml
This PR sets the default Elasticsearch host as localhost, to be consistent with the Wazuh indexer and Wazuh dashboard default configuration files. This simplifies the installation instructions for all-in-one deployments.  
It also enables and configures the Filebeat logging system.
> Update Filebeat configuration template

- stack/dashboard/rpm/wazuh-dashboard.spec
|---|
| closes #1416|
The hardcoded value is replaced by the variable
https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7445/console
> Replace hardcoded group name to variable

- unattended_installer/cert_tool/certFunctions.sh
- unattended_installer/cert_tool/certMain.sh
- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/filebeat.sh
- unattended_installer/install_functions/indexer.sh
- unattended_installer/install_functions/installCommon.sh
|---|
|This PR closes #1402|
The certificate containing the folder should change the permissions to 500, and the certificates created by the script should have 400. The Wazuh installation assistant and Wazuh certs tool assign those permissions accordingly.
[centos8_unattende](https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/497)
[ubuntu-xenial_unattended](https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/496)
[Unattended Distributed](https://devel.ci.wazuh.info/view/Tests/job/Test_unattended_distributed/390)
Before changes:
After changes:
On the other hand, validation was added that if the temporary directory, used for the creation of the certificates, exists, it will not be created.
This is because if the same dir existed, it threw an error.
> Certificates permissions updated for unattended installer

- ova/assets/custom/messages.sh
|---|
|#1404|
The logo created when installing an ova image had some strange characters.
I've deleted this characters and try to make it as symmetrical and perfect as I could.
After deleting the characters
> Strange characters deleted for ova logo

- unattended_installer/install_functions/installCommon.sh
|---|
|Closes #1412 |
Hello team we have solved the problem related with APT locked during unattended installation
https://user-images.githubusercontent.com/10661307/161295066-9b8f4d44-6c24-4aac-82bf-18242ad9b4e9.mp4
```
01/04/2022 15:22:11 INFO: --- Wazuh indexer ---
01/04/2022 15:22:11 INFO: Starting Wazuh indexer installation.
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 4535 (apt)
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 4535 (apt)
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 4535 (apt)
01/04/2022 15:23:27 INFO: Wazuh indexer installation finished.
01/04/2022 15:23:27 INFO: Wazuh indexer post-install configuration finished.
```
> Fix APT lock detection and retry inside installCommon function in unattended installer

- macos/generate_wazuh_packages.sh
|---|
|Closes #1328 |
Enable the creation of macOS symbols compressed tar.gz file.
OUTPUT FILE NAME: wazuh-[agent/manager]-[os]-[architecture]-debug-info-${version}-{revision}.tar.gz
> Generation of .tar.gz file with all symbols for macOS on the package generation.

- unattended_installer/install_functions/checks.sh
- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/indexer.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/install_functions/installMain.sh
- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1411|
A validation is added so that before starting the Wazuh Indexer cluster it is verified that the nodes are listening on port 9300, a delay and a retry of 12 times are added to give time if it is due to some delay in the process of install
Example of an install where all nodes are listening on port 9300
Example with a node with port 9300 blocked by firewall-cmd
Centos: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/515/console
Ubuntu: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/516/console
Distributted: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended_distributed/403/parameters/
> Check if Indexer is listening on Port 9300 after install

- unattended_installer/cert_tool/certFunctions.sh
|---|
|closes #1437|
Modify certFunctions.sh to remove quotes in output of cert_parseYaml function. To use it on docker cert generations.
```
fcaffieri@Fede:~/repos/wazuh-packages/unattended_installer$ ./builder.sh -c
fcaffieri@Fede:~/repos/wazuh-packages/unattended_installer$ ls -la
total 76
drwxrwxr-x  7 fcaffieri fcaffieri  4096 abr  6 12:42 .
drwxrwxr-x 20 fcaffieri fcaffieri  4096 abr  6 12:38 ..
-rwxrwxr-x  1 fcaffieri fcaffieri  9345 mar 31 09:33 builder.sh
drwxrwxr-x  2 fcaffieri fcaffieri  4096 abr  6 12:38 cert_tool
drwxrwxr-x  2 fcaffieri fcaffieri  4096 mar 30 15:07 common_functions
drwxrwxr-x  6 fcaffieri fcaffieri  4096 mar 21 14:55 config
-rw-------  1 root      root        150 abr  4 09:35 config.yml
-rw-rw-r--  1 fcaffieri fcaffieri  2397 mar 21 14:55 …
```
> Remove quotes into cert_parseYaml tools

- aix/SPECS/4.3.0/wazuh-agent-4.3.0-aix.spec
- aix/generate_wazuh_packages.sh
|---|
|#1387|
This PR replaces the dependencies used for building the AIX package and sets the links pointing to our own s3 repository.
> Fix dependencies for AIX package building

- stack/indexer/deb/debian/postinst
- stack/indexer/rpm/wazuh-indexer.spec
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1454|
Build:
rpm: https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7511/console
deb: https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7512/console
Install:
Centos: https://devel.ci.wazuh.info/view/Tests/job/Test_install_stack/447/console
Debian: https://devel.ci.wazuh.info/view/Tests/job/Test_install_stack/448/console
> Fix permissions of .opensearch.keystore.initial_md5sum

- unattended_installer/install_functions/installVariables.sh
- unattended_installer/install_functions/wazuh-offline-download.sh
This PR fixes the filebeat template URL to be downloaded in offline mode.
> Fixed filebeat template URL using unattended assistant

- stack/indexer/indexer-security-init.sh
|---|
|#1409|
- Main function did not check that the host address and port number were valid.
- A checking has been added in order to only let a correct host and port number to run the script.
- Valid ports
- Port number out of the range
- IP
- DNS
- Execution with host and port
> Validation for host and port in main function

- stack/indexer/indexer-security-init.sh
|---|
|-|
This PR removes the double quotes when getting the network.host address from the opensearch.yml file. The given fix removes all encapsulation with double quotes, including more than one level (""192.168.57.102""), leaving the address clean
```
[root@centos7 vagrant]# /usr/share/wazuh-indexer/bin/indexer-security-init.sh
Security Admin v7
Will connect to 192.168.57.102:9300 ... done
Connected as CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US
OpenSearch Version: 1.2.4
OpenSearch Security Version: 1.2.4.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: YELLOW
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from …
```
> Remove double quotation mark from host address

- stack/indexer/indexer-security-init.sh
|---|
|-|
This PR improves the parsing of quotes of the values obtained from the opensearch.yml file allowing to add more encapsulation characters, it also takes into account not only double quotes but single quotes, the path of the root certificate and the port to use
- opensearch.yml file accept the following variations
```
- network.host: ip
- plugins.security.ssl.http.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
- transport.tcp.port: 9800
```
```
- network.host: "ip"
- plugins.security.ssl.http.pemtrustedcas_filepath: "/etc/wazuh-indexer/certs/root-ca.pem"
- transport.tcp.port: "9800"
```
```
- network.host: 'ip'
- plugins.security.ssl.http.pemtrustedcas_filepath: '/etc/wazuh-indexer/certs/root-ca.pem'
- transport.tcp.port: '9800'
```
- opensearch.yml …
> Remove quotation marks from host, port and certificate path

- unattended_installer/install_functions/indexer.sh
Hello team,
We have included a little fix into wazuh-indexer unattended installation to put `-Xms` parameter with MB instead of GB.
Regards.
> Changed jvm.options RAM size to MB

- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1466|
the variable is renamed
Centos: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/527/console
Ubuntu: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/528/console
Distributed: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended_distributed/444/console
> Fix dashboardinstalled variable

- CHANGELOG.md
- stack/dashboard/base/files/etc/opensearch_dashboards.yml
|---|
| Closes #1470 |
Hello!
We have disabled multitenancy option inside wazuh-dashboard default configuration. This option will disable the login pop-up that ask for select the dashboard tenant.
We have also changed the default UI route to remove tenant parameter.
Pop-up shown when switch tenant button is pressed:
> Disabled multitenancy by default in dashboard, changed the app default route

- stack/indexer/base/files/etc/wazuh-indexer/opensearch.yml
- unattended_installer/config/indexer/indexer.yml
- unattended_installer/config/indexer/indexer_all_in_one.yml
- unattended_installer/config/indexer/indexer_unattended_distributed.yml
|---|
|#1469|
This PR removes the setting `plugins.security.audit.type: internal_opensearch` from the indexer configuration files.
> Remove plugins.security.audit.type from opensearch.yml

- unattended_installer/install_functions/installCommon.sh
|---|
|#1448|
- An error message could appear if another process is running when installing wazuh
- With -q in grep command it does not write anything to standard output.
After including -q
> Added -q in grep to hide apt lock error message

- stack/indexer/indexer-security-init.sh
|---|
|#1409|
- Pressing ctrl+c did not end the execution of the securityadmin.sh
- This was happening because when indexer-security-index was executed it created 3 new processes and it did not exist a trap for ctrl-c
- The added code checks if there is more than one process with the name wazuh-indexer, if so, it deletes the newly created ones
Ctrl-c did not stop the execution
Even if it's press when it's almost finished, it does not kill the other wazuh-indexer process
> Added ctrl-c handler

- CHANGELOG.md
- debs/SPECS/4.3.0/wazuh-agent/debian/postrm
- debs/SPECS/4.3.0/wazuh-manager/debian/postrm
- rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
- rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec
|---|
|#1472|
According to Fedora packaging guidelines, the packages should not enable services that do not meet the following criteria:
- Must not alter other services
- Must not require manual configuration to function
- Must not fail under normal operating conditions
- Must not listen for outside connections
For more information: https://docs.fedoraproject.org/en-US/packaging-guidelines/DefaultServices/#_enabling_services_by_default
Since 4.0.0 the packages do not enable the services, and it does not make sense for the package to disable it either.
- x ] Linux
> Remove service disabling from packages

- windows/Dockerfile
- windows/entrypoint.sh
- windows/generate_compiled_windows_agent.sh
|---|
|#1332|
Hi team
This PR aims to build the zip with the debug symbols. The file should be built when we want to create a Windows package. After some testing, I was able to reach the following results.
- Generation and compression of debug symbols in a zip file
- Output then ran the script `sudo ./generate_compiled_windows_agent.sh -b dev-debug-symbols -c /home/hanes/wazuh-tools/utils/cv2pdb`
- Debug symbols compressed
Hanes
> Download cv2pdb, generate zip file with debug symbols for winagent

- debs/SPECS/4.4.0/wazuh-agent/debian/control
- debs/SPECS/4.4.0/wazuh-agent/debian/rules
- debs/SPECS/4.4.0/wazuh-manager/debian/control
- debs/SPECS/4.4.0/wazuh-manager/debian/rules
- debs/build.sh
- debs/generate_debian_package.sh
- rpms/SPECS/4.4.0/wazuh-agent-4.4.0.spec
- rpms/SPECS/4.4.0/wazuh-manager-4.4.0.spec
- rpms/build.sh
- rpms/generate_rpm_package.sh
|---|
|Closes #1310|
This PR aims to add RPM/DEB debuginfo packages
Defacto debuginfo packages names
- RPM: `<package_name>-debuginfo` Ref: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/developer_guide/intro.debuginfo
- DEB: `<package_name>-dbg` -> Ref: https://wiki.debian.org/DebugPackage
Packages constraints
- debuginfo package version (major,minor,release) and arch must exactly match with wazuh-<target> counterpart
- Generate agent/manager packages
```sh
./generate_rpm_package.sh --packages-branch "1310-rpm-dev-debuginfo-packages" -b "dev-debug-symbols" -t agent
./generate_rpm_package.sh --packages-branch "1310-rpm-dev-debuginfo-packages" -b "dev-debug-symbols" -t manager
./generate_debian_package.sh --packages-branch …
```
> Add support for RPM/DEB debuginfo packages

- unattended_installer/install_functions/installMain.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1481|
An additional validation is added to prevent the user from adding 2 arguments together and omitting the node name:
Example:
```
[root@centos7-1 ~]# ./wazuh-install.sh -wi -v
22/04/2022 15:15:16 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
22/04/2022 15:15:16 INFO: Verbose logging redirected to /var/log/wazuh-install.log
grep: invalid option -- '.'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
22/04/2022 15:15:17 ERROR: There is no certificate for the indexer node -v in /root/wazuh-install-files.tar.
```
After the Fix:
```
[root@centos7-1 unattended_installer]# ./wazuh-install.sh -wi -v
22/04/2022 18:42:05 ERROR: Error on argument -wi. Check the given …
```
> Valid node name validation

- unattended_installer/install_functions/dashboard.sh
|---|
||
In this PR we remove the message indicating that we can find the password to access Wazuh dashboard in the installation assistant log.
```
[root@centos repo]# ./wazuh-install.sh -a -o
28/04/2022 08:27:53 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
28/04/2022 08:27:53 INFO: Verbose logging redirected to /var/log/wazuh-install.log
28/04/2022 08:27:54 INFO: --- Removing existing Wazuh installation ---
28/04/2022 08:27:54 INFO: Removing Wazuh manager.
28/04/2022 08:28:10 INFO: Wazuh manager removed.
28/04/2022 08:28:10 INFO: Removing Wazuh indexer.
28/04/2022 08:28:11 INFO: Wazuh indexer removed.
28/04/2022 08:28:11 INFO: Removing Filebeat.
28/04/2022 08:28:11 INFO: Filebeat removed.
28/04/2022 08:28:11 INFO: Removing Wazuh dashboard.
28/04/2022 …
```
> Remove Wazuh dashboard password message

- unattended_installer/install_functions/installCommon.sh
- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1481|
Correct log's and check cluster status to be green.
---
```
[root@stack-centos7-2 vagrant]# curl -X GET -k -u admin:mTgsva4AXad7YYwcHlGMzPj9yh19X0Gm https://localhost:9200/_cluster/health?pretty
{
"cluster_name" : "wazuh-cluster",
"status" : "green",
"timed_out" : false,
"number_of_nodes" : 1,
"number_of_data_nodes" : 1,
"discovered_master" : true,
"active_primary_shards" : 9,
"active_shards" : 9,
"relocating_shards" : 0,
"initializing_shards" : 0,
"unassigned_shards" : 0,
"delayed_unassigned_shards" : 0,
"number_of_pending_tasks" : 0,
"number_of_in_flight_fetch" : 0,
"task_max_waiting_in_queue_millis" : 0,
"active_shards_percent_as_number" : 100.0
}
```
---
**Unattended**
centos 7: …
> Log's correction and cluster status check

- unattended_installer/install_functions/installCommon.sh
|---|
| #1493 |
Hello team,
We have added a better descriptive message among other code improvements, tested on Ubuntu 20
```
29/04/2022 12:16:44 INFO: --- Wazuh indexer ---
29/04/2022 12:16:44 INFO: Starting Wazuh indexer installation.
29/04/2022 12:16:44 INFO: An external process is using APT. This process has to end to proceed installation. Next retry in 30 seconds (1/10)
29/04/2022 12:17:14 INFO: An external process is using APT. This process has to end to proceed installation. Next retry in 30 seconds (2/10)
```
> Improved APT locked message and retry time

- CHANGELOG.md
- unattended_installer/install_functions/dashboard.sh
|---|
|-|
This PR fix dashboard messages related to the format (removes from ip messages the ending perdiod mark (".") and fix a typo)
https://devel.ci.wazuh.info/view/Tests/job/Test_unattended_distributed/458/
https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/546/
https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/545/c
> Fix dashboard ip messages

- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/filebeat.sh
- unattended_installer/install_functions/indexer.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/install_functions/installMain.sh
- unattended_installer/install_functions/installVariables.sh
- unattended_installer/install_functions/manager.sh
- unattended_installer/install_functions/wazuh-offline-download.sh
- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
||
This PR fixes an error that caused the verbose log to not show when using -v option.
```
[root@centos repo]# ./wazuh-install.sh -a -o -v
...
Security Admin v7
Will connect to 127.0.0.1:9300 ... done
Connected as CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US
OpenSearch Version: 1.2.4
OpenSearch Security Version: 1.2.4.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/
Will update '_doc/config' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/config.yml 
SUCC: …
```
> Fix error not showing verbose mode

- rpms/SPECS/4.4.0/wazuh-manager-4.4.0.spec
|---|
||
This PR adds the backup/db directory to the manager RPM SPEC file.
https://ci.wazuh.info/job/Packages_builder/95718/
https://ci.wazuh.info/job/Test_install/89954/
> Add backup/db to specs4.4

- rpms/SPECS/4.5.0/wazuh-manager-4.5.0.spec
|---|
||
This PR adds the backup/db directory to the manager RPM SPEC file.
https://ci.wazuh.info/job/Packages_builder/95718/
https://ci.wazuh.info/job/Test_install/89954/
> Add backup/db to specs

- rpms/SPECS/4.4.0/wazuh-agent-4.4.0.spec
- rpms/SPECS/4.4.0/wazuh-manager-4.4.0.spec
|---|
|wazuh/wazuh#13446|
This PR aims to allow symlinks inside every binary folder that create symbol files(`bin`, `active-response/bin/`and `libs`) necessary to GDB symbols autoload mechanism. Those links will point, in case debuginfo package is installed, to `.symbols` folder
> Fix SPECS to support GDB symbols autoloading

- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/installVariables.sh
|---|
|#1545|
This PR fixes an error that appeared in the installation log when the Wazuh dashboard failed to connect to Wazuh indexer.
```
13/05/2022 15:50:43 INFO: Wazuh dashboard installation finished.
13/05/2022 15:50:43 INFO: Wazuh dashboard post-install configuration finished.
13/05/2022 15:50:45 INFO: Starting service wazuh-dashboard.
Created symlink from /etc/systemd/system/multi-user.target.wants/wazuh-dashboard.service to /etc/systemd/system/wazuh-dashboard.service.
13/05/2022 15:50:45 INFO: wazuh-dashboard service started.
13/05/2022 15:50:45 INFO: Initializing Wazuh dashboard web application.
13/05/2022 15:52:46 ERROR: Cannot connect to Wazuh dashboard.
13/05/2022 15:52:46 ERROR: Failed to connect with indexer. Connection refused.
13/05/2022 15:52:46 INFO: If …
```
> Fix sed error dashboard installation

- debs/SPECS/4.4.0/wazuh-agent/debian/rules
- debs/SPECS/4.4.0/wazuh-manager/debian/rules
- macos/package_files/4.4.0/build.sh
- rpms/SPECS/4.4.0/wazuh-agent-4.4.0.spec
- rpms/SPECS/4.4.0/wazuh-manager-4.4.0.spec
|---|
|wazuh/wazuh#13532|
This PR aims to set `USER_DEBUG_SYMBOLS="y"` for GNU/Linux and macOS packages generation scripts. This will allow the creation of debuginfo packages/compressed zip files.
> Set `USER_DEBUG_SYMBOLS` option during packages generation

- stack/dashboard/base/builder.sh
- stack/dashboard/rpm/wazuh-dashboard.spec
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1564|
The plugins mentioned in the issue are removed and various changes are applied to the dashboard checkfiles database
Before uninstall:
After uninstall:
Builds:
RPM: https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7603/console
DEB: https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7605/console
Tests install:
Centos 7: https://devel.ci.wazuh.info/view/Tests/job/Test_install_stack/469/console
Ubuntu focal: https://devel.ci.wazuh.info/view/Tests/job/Test_install_stack/464/
> Remove unnecessary plugins from default Wazuh dashboard to 4.3

- stack/dashboard/base/builder.sh
- stack/dashboard/rpm/wazuh-dashboard.spec
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1564|
The plugins mentioned in the issue are removed and various changes are applied to the dashboard checkfiles database
Before uninstall:
After uninstall:
Builds:
RPM: https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7603/console
DEB: https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7605/console
Tests install:
Centos 7: https://devel.ci.wazuh.info/view/Tests/job/Test_install_stack/469/console
Ubuntu focal: https://devel.ci.wazuh.info/view/Tests/job/Test_install_stack/464/
> Remove unnecessary plugins from default Wazuh dashboard to 4.4

- unattended_installer/builder.sh
|---|
|Related https://github.com/wazuh/wazuh-packages/issues/1563|
This PR updates the version of the Filebeat module.
```
[root@centos repo]# ./wazuh-install.sh -a
27/05/2022 13:06:57 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.1
27/05/2022 13:06:57 INFO: Verbose logging redirected to /var/log/wazuh-install.log
27/05/2022 13:07:00 INFO: Wazuh repository added.
27/05/2022 13:07:00 INFO: --- Configuration files ---
27/05/2022 13:07:00 INFO: Generating configuration files.
27/05/2022 13:07:00 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
27/05/2022 13:07:00 INFO: --- Wazuh indexer ---
27/05/2022 13:07:00 INFO: Starting Wazuh indexer installation.
27/05/2022 13:08:05 INFO: …
```
> Update filebeat module version

- solaris/solaris11/generate_wazuh_packages.sh
|---|
||
This PR fixes an issue with the Solaris 11 package generation that caused that package not to generate properly.
> Fix solaris 11 generation 4.3

- solaris/solaris11/generate_wazuh_packages.sh
|---|
||
This PR fixes an issue with the Solaris 11 package generation that caused that package not to generate properly.
> Fix solaris 11 generation 4.4 branch

- solaris/solaris11/generate_wazuh_packages.sh
|---|
||
This PR fixes an issue with the Solaris 11 package generation that caused that package not to generate properly.
> Fix solaris 11 generation master branch 

- stack/dashboard/deb/builder.sh
- stack/dashboard/deb/debian/rules
- stack/dashboard/rpm/wazuh-dashboard.spec
|---|
| https://github.com/wazuh/wazuh-jenkins/issues/3551 |
Hello!
We have included a little changes to allow Wazuh dashboard app package to build as any other package
> Added release number to dashboard app package

- ova/assets/postProvision.sh
|---|
| Related https://github.com/wazuh/wazuh-packages/pull/1651 |
This PR fix the log clean up of /var/log and /var/ossec/logs files, to avoid inserting an empty line in each file.
<details><summary>End of local ova generation</summary>
```
default: 14/06/2022 12:32:43 INFO: --- Summary ---
default: 14/06/2022 12:32:43 INFO: You can access the web interface https://<wazuh-dashboard-ip>
default:     User: admin
default:     Password: *KpLR7.jdO?pye272+3a+VlgUXV9lTQ*
default: 14/06/2022 12:32:43 INFO: Installation finished.
default: Loaded plugins: fastestmirror
default: Cleaning repos: base extras updates wazuh
default: Cleaning up list of fastest mirrors
==> default: Running provisioner: shell...
default: Running: /tmp/vagrant-shell20220614-23697-1iugfck.sh
default: …
```
> Fix log clean command in ova generation 4.4

- ova/assets/postProvision.sh
|---|
| Related https://github.com/wazuh/wazuh-packages/pull/1651 |
This PR fix the log clean up of /var/log and /var/ossec/logs files, to avoid inserting an empty line in each file.
<details><summary>End of local ova generation</summary>
```
default: 14/06/2022 12:32:43 INFO: --- Summary ---
default: 14/06/2022 12:32:43 INFO: You can access the web interface https://<wazuh-dashboard-ip>
default:     User: admin
default:     Password: *KpLR7.jdO?pye272+3a+VlgUXV9lTQ*
default: 14/06/2022 12:32:43 INFO: Installation finished.
default: Loaded plugins: fastestmirror
default: Cleaning repos: base extras updates wazuh
default: Cleaning up list of fastest mirrors
==> default: Running provisioner: shell...
default: Running: /tmp/vagrant-shell20220614-23697-1iugfck.sh
default: …
```
> Fix log clean command in ova generation master

- ova/assets/postProvision.sh
|---|
| Related https://github.com/wazuh/wazuh/issues/13710 |
This PR fix the log clean up of /var/log and /var/ossec/logs files, to avoid inserting an empty line in each file.
<details><summary>End of local ova generation</summary>
```
default: 14/06/2022 12:32:43 INFO: --- Summary ---
default: 14/06/2022 12:32:43 INFO: You can access the web interface https://<wazuh-dashboard-ip>
default:     User: admin
default:     Password: *KpLR7.jdO?pye272+3a+VlgUXV9lTQ*
default: 14/06/2022 12:32:43 INFO: Installation finished.
default: Loaded plugins: fastestmirror
default: Cleaning repos: base extras updates wazuh
default: Cleaning up list of fastest mirrors
==> default: Running provisioner: shell...
default: Running: /tmp/vagrant-shell20220614-23697-1iugfck.sh
default: Created …
```
> Fix log clean command in ova generation

- unattended_installer/cert_tool/certFunctions.sh
|---|
|#1421|
This PR fixes an error that caused the scripts to return the following error:
```
ERROR: The given information does not match with an IP address or a DNS
```
If the domain names specified in the config.yml file contained a `-` after the `. `. Here there is an example of a failing config.yml:
```
nodes:
indexer:
- name: wazuh-elasticsearch-1-0
ip: wazuh-elasticsearch-1-0.wazuh-elasticsearch
- name: wazuh-elasticsearch-2-0
ip: wazuh-elasticsearch-2-0.wazuh-elasticsearch
- name: wazuh-elasticsearch-3-0
ip: wazuh-elasticsearch-3-0.wazuh-elasticsearch
server:
- name: wazuh-manager-master-0
ip: wazuh-manager-master-0.wazuh-clustera
node_type: master
- name: wazuh-manager-worker-1-0
ip: wazuh-manager-worker-1-0.wazuh-cluster
node_type: worker
- name: …
```
> Fix error when checking if domain name was valid in wazuh certs tool

- stack/indexer/deb/debian/preinst
- stack/indexer/rpm/wazuh-indexer.spec
|---|
| Related #1642 |
Improved the preinstall process to manage better the invoke-rc command
```
Building dependency tree       
Note, selecting 'wazuh-indexer' instead of './wazuh-indexer_4.3.3-1_amd64.deb'
The following NEW packages will be installed:
wazuh-indexer
0 upgraded, 1 newly installed, 0 to remove and 145 not upgraded.
Need to get 0 B/363 MB of archives.
After this operation, 639 MB of additional disk space will be used.
Get:1 /home/vagrant/wazuh-indexer_4.3.3-1_amd64.deb wazuh-indexer amd64 4.3.3-1 [363 MB]
Selecting previously unselected package wazuh-indexer.
(Reading database ... 63240 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.3.3-1_amd64.deb ... …
```
> Changed invoke-rc command preinst

- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
|---|
| Related #1626  |
Hello,
In this PR we propose a fix to the matter of enabling Wazuh service in RHEL 9 systems.
Error:
```
Synchronizing state of wazuh-agent.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable wazuh-agent
Failed to execute /usr/lib/systemd/systemd-sysv-install: No such file or directory
```
Fixed:
```
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-agent.service → /usr/lib/systemd/system/wazuh-agent.service.
```
> Fix RHEL9 init.d file installation

- arch/SPECS/wazuh-agent/arch/PKGBUILD
- arch/SPECS/wazuh-agent/arch/wazuh.install
- arch/build.sh
- arch/generate_arch_package.sh
Since a few versions ago, wazuh-packages is unable to create packages for Arch Linux. This commit fixes that.
(This is related to issue: #1649)
> Fixing package building for Arch that was broken a few versions ago

- ova/generate_ova.sh
|---|
|N/A|
Use 'bash', instead of 'sh' as interpreter (sh does not understand ```[[ ]]``` constructions) 
Use 'python3', instead of 'python'
Fix shellcheck warnings
> Fix Ubuntu compability in generate_ova.sh

- ova/assets/steps.sh
|---|
|N/A|
Install [open-vm-tools](https://github.com/vmware/open-vm-tools) in OVA to provide better integration with VMware hypervisor
> Install open-vm-tools in OVA

- stack/indexer/base/generate_base.sh
- stack/indexer/deb/build_package.sh
- stack/indexer/rpm/build_package.sh
|---|
||
I add the configuration of the generate_base.sh and build_package.sh scripts of indexer so that it accepts the possibility of saving the built packages in a custom path, in the same way that it is done in the dashboard scripts:
```
ls -la /tmp | grep wazuh*
-rw-r--r--  1 root    root    356166794 jun 28 08:38 wazuh-indexer_4.3.5-1_amd64.deb
-rw-r--r--  1 root    root          162 jun 28 08:38 wazuh-indexer_4.3.5-1_amd64.deb.sha512
-rw-r--r--  1 root    root    378831260 jun 28 08:33 wazuh-indexer-4.3.5-1.x86_64.rpm
-rw-r--r--  1 root    root          163 jun 28 08:33 wazuh-indexer-4.3.5-1.x86_64.rpm.sha512
-rw-r--r--  1 root    root    357530656 jun 28 08:30 wazuh-indexer-base-4.3.5-1-linux-x64.tar.xz
```
> Add custom path for indexer packages to 4.3

- stack/indexer/base/generate_base.sh
- stack/indexer/deb/build_package.sh
- stack/indexer/rpm/build_package.sh
|---|
||
I add the configuration of the generate_base.sh and build_package.sh scripts of indexer so that it accepts the possibility of saving the built packages in a custom path, in the same way, that it is done in the dashboard scripts:
```
ls -la /tmp | grep wazuh*
-rw-r--r--  1 root    root    356166794 jun 28 08:38 wazuh-indexer_4.3.5-1_amd64.deb
-rw-r--r--  1 root    root          162 jun 28 08:38 wazuh-indexer_4.3.5-1_amd64.deb.sha512
-rw-r--r--  1 root    root    378831260 jun 28 08:33 wazuh-indexer-4.3.5-1.x86_64.rpm
-rw-r--r--  1 root    root          163 jun 28 08:33 wazuh-indexer-4.3.5-1.x86_64.rpm.sha512
-rw-r--r--  1 root    root    357530656 jun 28 08:30 wazuh-indexer-base-4.3.5-1-linux-x64.tar.xz
```
> Add custom path for indexer packages to 4.4

- stack/indexer/deb/debian/postrm
- stack/indexer/rpm/wazuh-indexer.spec
|---|
| #1693 |
Uninstalling Wazuh indexer does not remove the /dev/shm/performanceanalyzer/ directory, it is expected to remove it with the uninstallation of the package.
Before:
<details><summary>RPM</summary>
```
[root@centos8stream shm]# ls -ld performanceanalyzer/
drwxr-xr-x. 2 wazuh-indexer wazuh-indexer 40 Jun 27 14:03 performanceanalyzer/
(bash wazuh-install.sh -u)
[root@centos8stream shm]# ls -ld performanceanalyzer/
drwxr-xr-x. 2 994 990 40 Jun 27 14:03 performanceanalyzer/
[root@centos8stream shm]# pwd
/dev/shm
[root@centos8stream shm]#
```
</details>
<details><summary>DEB</summary>
```
root@stack-ubuntu1804:/home/vagrant# ls -la /dev/shm/
total 0
drwxrwxrwt  3 root          root            60 Jun 28 13:33 .
drwxr-xr-x 18 root          root          3800 Jun 28 …
```
> Remove performanceanalyzer directory on uninstall

- stack/dashboard/deb/debian/rules
- stack/dashboard/rpm/wazuh-dashboard.spec
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1644|
A validation is added in the specs so that in the case of building the package in the future, the zip of the app is downloaded from a specific path
```
+ '[' 99.99.0 = 99.99.0 ']'
+ runuser wazuh-dashboard --shell=/bin/bash '--command=/build/rpmbuild/BUILDROOT/wazuh-dashboard-99.99.0-1.x86_64/usr/share/wazuh-dashboard/bin/opensearch-dashboards-plugin install https://packages-dev.wazuh.com/futures/ui/dashboard/wazuh-99.99.0-1.zip'
Attempting to transfer from https://packages-dev.wazuh.com/futures/ui/dashboard/wazuh-99.99.0-1.zip
Transferring 30605690 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation complete …
```
> The app path is changed for future packages to 4.3

- stack/dashboard/deb/debian/rules
- stack/dashboard/rpm/wazuh-dashboard.spec
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1644|
A validation is added in the specs so that in the case of building the package in the future, the zip of the app is downloaded from a specific path
```
+ '[' 99.99.0 = 99.99.0 ']'
+ runuser wazuh-dashboard --shell=/bin/bash '--command=/build/rpmbuild/BUILDROOT/wazuh-dashboard-99.99.0-1.x86_64/usr/share/wazuh-dashboard/bin/opensearch-dashboards-plugin install https://packages-dev.wazuh.com/futures/ui/dashboard/wazuh-99.99.0-1.zip'
Attempting to transfer from https://packages-dev.wazuh.com/futures/ui/dashboard/wazuh-99.99.0-1.zip
Transferring 30605690 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation complete …
```
> The app path is changed for future packages to 4.4

- stack/dashboard/deb/debian/rules
- stack/dashboard/rpm/wazuh-dashboard.spec
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1644|
A validation is added in the specs so that in the case of building the package in the future, the zip of the app is downloaded from a specific path
```
+ '[' 99.99.0 = 99.99.0 ']'
+ runuser wazuh-dashboard --shell=/bin/bash '--command=/build/rpmbuild/BUILDROOT/wazuh-dashboard-99.99.0-1.x86_64/usr/share/wazuh-dashboard/bin/opensearch-dashboards-plugin install https://packages-dev.wazuh.com/futures/ui/dashboard/wazuh-99.99.0-1.zip'
Attempting to transfer from https://packages-dev.wazuh.com/futures/ui/dashboard/wazuh-99.99.0-1.zip
Transferring 30605690 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation complete …
```
> The app path is changed for future packages to master

- aix/SPECS/wazuh-agent-aix.spec
- debs/SPECS/wazuh-agent/debian/postinst
- debs/SPECS/wazuh-manager/debian/postinst
- macos/package_files/postinstall.sh
- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
- solaris/solaris11/postinstall.sh
- stack/dashboard/rpm/wazuh-dashboard.spec
- stack/indexer/deb/debian/postrm
- stack/indexer/rpm/wazuh-indexer.spec
|---|
|#1695|
This  PR fixes a problem that appeared in rare cases when the user moves Wazuh from the default installation directory and then creates a symlink to the new path.
https://ci.wazuh.info/job/Packages_builder_tier/
> Fix error when upgrading using symlinks

- unattended_installer/install_functions/installCommon.sh
- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
||
This PR fixes an error where API passwords were not changed in Wazuh manager single-node installation-
```
root@ubuntu:/home/vagrant/repo# ./wazuh-install.sh -ws wazuh-server
04/07/2022 07:37:19 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.5
04/07/2022 07:37:19 INFO: Verbose logging redirected to /var/log/wazuh-install.log
04/07/2022 07:37:26 INFO: --- Dependencies ----
04/07/2022 07:37:26 INFO: Installing apt-transport-https.
04/07/2022 07:37:30 INFO: Wazuh repository added.
04/07/2022 07:37:30 INFO: --- Wazuh server ---
04/07/2022 07:37:30 INFO: Starting the Wazuh manager installation.
04/07/2022 07:38:03 INFO: Wazuh manager installation finished.
04/07/2022 07:38:03 INFO: Starting service wazuh-manager.
04/07/2022 07:38:19 INFO: wazuh-manager …
```
> Fix installation assistant API error in single Wazuh manager nodes

- windows/Dockerfile
|---|
|Fixes #1077|
This PR removes package `libssl1.1` from the Windows package builder image setup.
On Ubuntu 22.04, `libssl-dev` is enough as it depends on `libssl3`.
Here is the result of building branch `11025-win-dw2-dll` (related to https://github.com/wazuh/wazuh/pull/11354):
```
./generate_compiled_windows_agent.sh -b 11025-win-dw2-dll
```
[result.log](https://github.com/wazuh/wazuh-packages/files/9054604/result.log)
> Remove package libssl1.1 from Windows build image

- debs/SPECS/wazuh-agent/debian/rules
- debs/SPECS/wazuh-manager/debian/rules
- rpms/SPECS/wazuh-manager.spec
|---|
|#1670|
This PR adds the Ubuntu 22 SCA files to the specs.
> Addd Ubuntu 22 SCA

- unattended_installer/install_functions/installMain.sh
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1633|
The script ```wazuh-install.sh``` checks the OS always, this is not very useful when just downloading the files for offline installation. I  added a simple if condition to skip the check when performing the download. 
````
[root@localhost vagrant]# cat /etc/os-release 
NAME=Fedora
VERSION="32 (Cloud Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Cloud Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
````
- Before the change:
````
[root@localhost vagrant]# ./wazuh-install.sh -dw rpm
21/07/2022 13:42:42 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.6 …
```
> wazuh-install.sh skip check OS when downloading

- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/installVariables.sh
|---|
|#1529|
As mentioned in the issue, the installation fails if the distributed installation is carried out in the same host and ``wazuh-config.yml`` has the value ``127.0.0.1``. The variable ``server.host`` in ``/etc/wazuh-dashboard/opensearch_dashboards.yml`` takes the value ``127.0.0.1`` when it should be ``0.0.0.0``.
I have just added a simple check that changes the IP to ``0.0.0.0`` if the value is ``127.0.0.1``
<details><summary> Distributed installation all in the same host</summary>
````
[root@ip-172-31-31-229 ec2-user]# bash wazuh-install.sh -wi wazuh-indexer
07/07/2022 09:24:33 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.5
07/07/2022 09:24:33 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/07/2022 09:24:38 INFO: Wazuh …
```
> Fixed IP error in distributed configuration when installing every component in the same host

- unattended_installer/common_functions/common.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/install_functions/installMain.sh
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1682|
Wazuh GPG key is not removed when uninstalling all wazuh components with the installation assistant. This needs to be changed, the key has to be removed with all the others components.
- CentOS7
````
[root@localhost vagrant]# rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n' | grep "Wazuh"
gpg-pubkey-29111145-591cd381	gpg(Wazuh.com (Wazuh Signing Key) <support@wazuh.com>)
[root@localhost vagrant]# ./wazuh-install.sh -u
26/07/2022 10:34:35 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.6
26/07/2022 10:34:35 INFO: Verbose logging redirected to /var/log/wazuh-install.log
26/07/2022 10:34:38 INFO: Removing Wazuh manager.
26/07/2022 10:34:56 INFO: Wazuh manager removed. …
```
> Remove GPG key when uninstalling with wazuh assistant

- debs/build.sh
|---|
|related https://github.com/wazuh/wazuh-jenkins/issues/3289|
An error was detected while trying to generate future images:
```
12:30:44  {"name":"Build Linux amd64 manager deb package(future)","head_sha":"f1a77b6d5c43a8ae8a99e97b1878746a3dd0a8ac","status":"completed","conclusion":"failure","completed_at":"2022-08-10T15:30:30Z","started_at":"2022-08-10T15:28:05Z","details_url":"https://devel.ci.wazuh.info/job/Packages_builder/8156/","output":{"summary":"Below you have the stage output","title":"Packages_builder_debian","text":"```\n+ build_target=manager\n+ wazuh_branch=f1a77b6d5c43a8ae8a99e97b1878746a3dd0a8ac\n+ architecture_target=amd64\n+ package_release=0.40500.20220810\n+ jobs=4\n+ dir_path=/var/ossec\n+ debug=no\n+ checksum=no\n+ wazuh_packages_branch=master\n+ …
> Fix build.sh for future deb packages

- debs/build.sh
|---|
|related https://github.com/wazuh/wazuh-jenkins/issues/3289|
An error was detected while trying to generate future images:
```
sed -i 's/$(VERSION)/4.5/g' /build_wazuh/manager/wazuh-manager-4.30.0/src/Makefile\nsed: can't read /build_wazuh/manager/wazuh-manager-4.30.0/src/Makefile: No such file or directory\n\n```"}}
```
https://devel.ci.wazuh.info/job/Packages_builder/8392/
https://devel.ci.wazuh.info/job/Packages_builder/8393/
> Fix build.sh for future deb packages to 4.4

- debs/build.sh
|---|
|related https://github.com/wazuh/wazuh-jenkins/issues/3289|
An error was detected while trying to generate future images:
```
sed -i 's/$(VERSION)/4.5/g' /build_wazuh/manager/wazuh-manager-4.30.0/src/Makefile\nsed: can't read /build_wazuh/manager/wazuh-manager-4.30.0/src/Makefile: No such file or directory\n\n```"}}
```
https://devel.ci.wazuh.info/job/Packages_builder/8392/
https://devel.ci.wazuh.info/job/Packages_builder/8393/
> Fix build.sh for future deb packages to  master

- unattended_installer/cert_tool/certFunctions.sh
- unattended_installer/cert_tool/certMain.sh
- unattended_installer/common_functions/common.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1797|
The wazuh-certs-tool.sh has some errors that need to be fixed.
- Creating all certificates with -A
````
[root@centos7 vagrant]# cat config.yml 
nodes:
indexer:
- name: node-1
ip: 127.0.0.1
server:
- name: server
ip: 127.0.0.1
dashboard:
- name: dashboard
ip: 127.0.0.1
[root@centos7 vagrant]# bash wazuh-certs-tool.sh -A 
25/08/2022 07:57:27 INFO: Admin certificates created.
25/08/2022 07:57:27 INFO: Wazuh indexer certificates created.
25/08/2022 07:57:27 INFO: Wazuh server certificates created.
25/08/2022 07:57:28 INFO: Wazuh dashboard certificates created.
````
````
[root@centos7 vagrant]# cat config.yml 
nodes:
server:
- name: server
ip: 127.0.0.1
dashboard:
- name: dashboard
ip: 127.0.0.1
[root@centos7 vagrant]# …
```
> Fix cert-tool errors

- unattended_installer/install_functions/installCommon.sh
- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1804|
|https://github.com/wazuh/wazuh-packages/issues/1805|
Fix for those two issues, also I have seen a new error and fixed it.
The first issue is fixed by adding double quotes to the password. If the password started with * without the double quotes yaml treat it as an alias and produce the error. For the second issue, I have just added a single dot where it was missing. 
The third error that I found was this:
````
26/08/2022 11:35:13 DEBUG: The given user wazuh does not exist
26/08/2022 11:35:13 DEBUG: The given user wazuh-wui does not exist
````
````
[root@ip-172-31-8-198 ec2-user]# tail /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
hosts:
- default:
url: https://localhost
port: 55000
username: wazuh-wui …
```
> Fix wazuh-dashboard API error and typo

- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
|---|
||
This PR fixes an issue with the RHEL and CentOS SCA template generation.
> Copy rhel and centos SCA templates 4.4

- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
|---|
||
This PR fixes an issue with the RHEL and CentOS SCA template generation.
> Copy rhel and centos SCA templates master

- stack/indexer/indexer-security-init.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1789|
The ```indexer-security-init.sh``` script did not allow DNS names in ```network.host``` variable causing an error. This could be fixed by executing the script with the parameter -ho but this behavior is not right. Now there is no need to use the -ho parameter the script will use the DNS name just like it uses an IP.
https://github.com/wazuh/wazuh-packages/issues/1789#issuecomment-1234259270
> Allow DNS names in indexer-security-init.sh 

- unattended_installer/cert_tool/certFunctions.sh
- unattended_installer/cert_tool/certMain.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1802|
A function to remove rootCA certs has been added. This function removes rootCA certs when creating certs for a single component: indexer, server, dashboard, and admin certs. Also, it will raise an error if we try to use a component that is not in the config file.
https://github.com/wazuh/wazuh-packages/issues/1802#issuecomment-1235185230
> Fix wazuh-certs-tool.sh certs generation when it differs from the config.yml

- unattended_installer/cert_tool/certMain.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1803|
The --all parameter did not check if at least existed one node for indexer, manager, and dashboard. Now, if any of these nodes do not exist in the config.yml file the script will exit and display an error.
https://github.com/wazuh/wazuh-packages/issues/1803#issuecomment-1235371937
> Add check for every component with --all option

- unattended_installer/install_functions/installCommon.sh
|---|
| https://github.com/wazuh/wazuh-packages/issues/1773,  https://github.com/wazuh/wazuh-packages/issues/1822 |
During uninstallation, uninstalled services still kept running in-memory (https://github.com/wazuh/wazuh-packages/issues/1773). In order to remove them, first, I added a service removal method (https://github.com/wazuh/wazuh-packages/issues/1774). However, there was a better and simpler method to solve the issue as @DFolchA discovered (https://github.com/wazuh/wazuh-packages/issues/1822), adding a `systemctl daemon-reload` into the common rollback method. This PR does one thing, adds the said command and solves this issue.
- Tests …
> Added daemon-reload at the end of rollback

- unattended_installer/install_functions/installCommon.sh
|---|
| https://github.com/wazuh/wazuh-packages/issues/1773,  https://github.com/wazuh/wazuh-packages/issues/1822 |
> NB! This is an exact copy of the PR https://github.com/wazuh/wazuh-packages/pull/1824. It is merged to master whil this one targets 4.4.
During uninstallation, uninstalled services still kept running in-memory (https://github.com/wazuh/wazuh-packages/issues/1773). In order to remove them, first, I added a service removal method (https://github.com/wazuh/wazuh-packages/issues/1774). However, there was a better and simpler method to solve the issue as @DFolchA discovered (https://github.com/wazuh/wazuh-packages/issues/1822), adding a `systemctl daemon-reload` into the common rollback method. This PR does one thing, adds the said command and solves this issue. …
> Reload services on rollback

- unattended_installer/install_functions/wazuh-offline-download.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1799|
Two messages that appear when downloading the files for offline installation needed to be updated.
- The URL was outdated, now it has a new one.
- The message about where the configuration files and assets are stored was not accurate.
````
root@ubuntu2004:/home/vagrant# bash wazuh-install.sh -dw rpm
06/09/2022 14:02:52 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
06/09/2022 14:02:52 INFO: Verbose logging redirected to /var/log/wazuh-install.log
06/09/2022 14:02:53 INFO: --- Download Packages ---
06/09/2022 14:02:53 INFO: Starting Wazuh packages download.
06/09/2022 14:02:53 INFO: Downloading Wazuh rpm packages for x86_64.
06/09/2022 14:02:56 INFO: The manager package was downloaded.
06/09/2022 …
```
> Fix wazuh offline installation messages

- stack/dashboard/base/builder.sh
- stack/dashboard/base/generate_base.sh
- stack/dashboard/deb/build_package.sh
- stack/dashboard/deb/builder.sh
- stack/dashboard/deb/debian/rules
- stack/dashboard/rpm/build_package.sh
- stack/dashboard/rpm/builder.sh
- stack/dashboard/rpm/wazuh-dashboard.spec
- stack/indexer/base/builder.sh
- stack/indexer/base/generate_base.sh
- stack/indexer/deb/build_package.sh
- stack/indexer/deb/builder.sh
- stack/indexer/deb/debian/rules
- stack/indexer/rpm/build_package.sh
- stack/indexer/rpm/builder.sh
- stack/indexer/rpm/wazuh-indexer.spec
|---|
| Related https://github.com/wazuh/wazuh-jenkins/issues/3898 |
Changes are made in the build_packages.sh, a call is integrated so that the base is generated locally and both the base and the package are built in the same execution
```
-rw-r--r--  1 root    root    141650768 sep  2 16:29 wazuh-dashboard_4.4.0-1_amd64.deb
-rw-r--r--  1 root    root          164 sep  2 16:29 wazuh-dashboard_4.4.0-1_amd64.deb.sha512
-rw-r--r--  1 root    root    172479728 sep  2 16:20 wazuh-dashboard-4.4.0-1.x86_64.rpm
-rw-r--r--  1 root    root          165 sep  2 16:20 wazuh-dashboard-4.4.0-1.x86_64.rpm.sha512
-rw-r--r--  1 root    root    126598524 sep  2 16:27 wazuh-dashboard-base-4.4.0-1-linux-x64.tar.xz
-rw-r--r--  1 root    root    126602520 sep  2 12:52 …
```
> The creation of the base is integrated within the script build_packages.sh

- unattended_installer/install_functions/installCommon.sh
|---|
|closes #1756|
This PR changes the use of apt with apt-get to avoid warning messages.
```
WARNING : apt does not have a stable CLI interface. Use with caution in scripts.
```
<details><summary>Test logs</summary>
```
root@ubuntu:/home/vagrant/repo# ./wazuh-install.sh -a -v
05/09/2022 15:08:56 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.7
05/09/2022 15:08:56 INFO: Verbose logging redirected to /var/log/wazuh-install.log
Hit:1 http://in.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://in.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://in.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:4 http://in.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:5 http://in.archive.ubuntu.com/ubuntu …
```
> Use apt-get instead of apt

- ova/Libraries/elastic_functions.sh
- ova/generate_ova.sh
|---|
| Closes #1849 |
This PR change the pre-release repository used to build the legacy OVA.
Output log: [ova_log.txt](https://github.com/wazuh/wazuh-packages/files/9598946/ova_log.txt)
> Change legacy OVA pre-release repository

- rpms/SPECS/wazuh-manager.spec
|---|
|#1796|
We add a macro to the SPECS for the RPM generation for the `wazuh-manager` package. It prevents the installation of the package to create build ids, debugging links that may conflict with the installation of other packages, as `azure-cli`
```
[vagrant@centos-8 output]$ sudo dnf install wazuh-manager-4.4.0-1.x86_64.rpm 
Last metadata expiration check: 4:25:43 ago on Fri 07 Oct 2022 10:12:00 AM UTC.
Dependencies resolved.
=========================================================================
Package             Architecture Version       Repository          Size
=========================================================================
Installing:
wazuh-manager       x86_64       4.4.0-1       @commandline       116 M
Transaction Summary …
```
> Fix package conflicts between `wazuh-manager` and `azure-cli` on CentOS 8

- stack/dashboard/rpm/wazuh-dashboard.spec
- stack/indexer/rpm/wazuh-indexer.spec
This pull request removes the `init.d` service from the Wazuh indexer and Wazuh dashboard on the Red Hat 9 system since the Red Hat 9 system has withdrawn support for `init.d`.
Now, when using the `service` command, it is redirected to `systemctl`, also fixing the problem of showing the log by the terminal when using the `service` command.
See https://github.com/wazuh/wazuh-packages/issues/1880 comments. It can be seen in the comments of the issue the tests carried out with Vagrant, links to Jenkins with the package generation and tests carried out on different systems using the `Test_install_stack` pipeline
> Remove `Wazuh dashboard` and `Wazuh indexer` `init.d` service for `Red Hat 9` 4.4

- stack/dashboard/rpm/wazuh-dashboard.spec
- stack/indexer/rpm/wazuh-indexer.spec
This pull request removes the `init.d` service from the Wazuh indexer and Wazuh dashboard on the Red Hat 9 system since the Red Hat 9 system has withdrawn support for `init.d`.
Now, when using the `service` command, it is redirected to `systemctl`, also fixing the problem of showing the log by the terminal when using the `service` command.
See https://github.com/wazuh/wazuh-packages/issues/1880 comments. It can be seen in the comments of the issue the tests carried out with Vagrant, links to Jenkins with the package generation and tests carried out on different systems using the `Test_install_stack` pipeline
> Remove `Wazuh dashboard` and `Wazuh indexer` `init.d` service for `Red Hat 9` master

- unattended_installer/builder.sh
- unattended_installer/common_functions/common.sh
- unattended_installer/install_functions/installCommon.sh
|---|
|#1846|
All usages of apt-key have been removed. Instead, the script creates a file with the key as `/usr/share/keyrings/wazuh.gpg` and adds the path to it to the repository description in `sources.list.d`
>  Remove deprecated apt-key from the installation assistant

- wpk/run.sh
|---|
|https://github.com/wazuh/wazuh-documentation/issues/5681|
The changes in this PR are aimed at fixing different typos in folders found when deleting unnecessary files, as well as removing several removals that are no longer needed.
These fixes have been found in the following PR to the documentation: https://github.com/wazuh/wazuh-documentation/pull/5701
> Fixing different typos in WPK generation

- stack/dashboard/base/files/etc/styles.js
- stack/dashboard/base/files/etc/template.js
- stack/dashboard/deb/debian/changelog
- stack/dashboard/rpm/wazuh-dashboard.spec
- stack/indexer/deb/debian/changelog
- stack/indexer/rpm/wazuh-indexer.spec
This pull request modifies the `template.js` and `style.js` files of the Wazuh dashboard package to add a new light logo on the loading screen when the dark mode is activated, in addition, it reduces the size of the logo (both in light and dark mode) a 25%.
Additionally, the changelog of the Wazuh indexer and Wazuh dashboard is fixed to reflect the versions that have been released so far and avoid messages during the package generation like:
```
14:33:50  mk-build-deps: warning:     debian/changelog(l7): unrecognized line
14:33:50  LINE:  wazuh-dashboard (4.2.5-1) UN1D; urgency=low
```
- Wazuh dashboard
- DEB
- https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/8959/ 
- https://packages-dev.wazuh.com/warehouse/test/4.4/deb/wazuh-dashboard_4.4.0-wp.1924_amd64.deb
- RPM
- …
> Added Wazuh dashboard light loading screen logo in dark mode 4.4

- wpk/common/Dockerfile
|---|
| closes #1050 |
Hello!
We have included the fix to the Dockerfile.
```
./generate_wpk_package.sh -t windows -b v4.3.10 -pn /.../wazuh-packages-tmp/wpk/wazuh-agent-4.3.10-1.msi -o wazuh-agent.wpk -d /.../wazuh-packages-tmp/wpk/output -k /.../wazuh-packages-tmp/wpk/keys
.
.
.
+++ PRETTY_NAME='Debian GNU/Linux 9 (stretch)'
+++ NAME='Debian GNU/Linux'
+++ VERSION_ID=9
+++ VERSION='9 (stretch)'
+++ VERSION_CODENAME=stretch
+++ ID=debian
+++ HOME_URL=https://www.debian.org/
+++ SUPPORT_URL=https://www.debian.org/support
+++ BUG_REPORT_URL=https://bugs.debian.org/
++ DIST_NAME=debian
+++ echo 9
+++ sed -rn 's/[^0-9]*([0-9]+).*/\1/p'
++ DIST_VER=9
++ '[' X9 = X ']'
++ '[' debian = amzn ']'
+++ echo 9
+++ sed -rn 's/[^0-9]*[0-9]+\.([0-9]+).*/\1/p'
++ DIST_SUBVER=
++ '[' X = …
```
> Add libffi-dev to WPK package common builder

- debs/SPECS/wazuh-agent/debian/postrm
- solaris/solaris10/postremove.sh
- solaris/solaris10/preinstall.sh
|---|
|#1931|
This PR fixes an error that appeared when uninstalling the wazuh-agent if wazuh-dashboard or wazuh-indexer was installed.
> Remove grep from getent command

- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
|---|
| [#14924](https://github.com/wazuh/wazuh/issues/14924)  |
This report has for goal to make a summary of the implemented solution.
This issue is produced by a wrong symbolink in the openSUSE Leap 15.4 distribution in the RPM packages.
When post-installation, it try to enable the service (agent or manager). It raised an error because openSUSE try to create a symbolic link to `/etc/init.d/rc2.d` it doesn't exist. This problem has been found in this [forum thread](https://forums.opensuse.org/showthread.php/569830-Can-systemctl-start-elasticsearch-but-not-systemctl-enable-it), where the explain of the reason it's because the package it's an original openSUSE package so it tries to use `/etc/init.d/rc2.d` which directory belongs to the old SystemV ways of doing but in …
> Fixing service enablement in SUSE packages

- debs/SPECS/wazuh-manager/debian/postinst
- rpms/SPECS/wazuh-manager.spec
|---|
||
This PR fixes an error where `wazuh-authd` was being used to create the manager SSL certificates.
> Use openssl to create sslmanager.key and sslmanager.cert

- solaris/solaris10/postremove.sh
- solaris/solaris10/preinstall.sh
|---|
||
This PR fixes an error with the creation of the users in Solaris 10 agents.
```
The following packages are available:
1  wazuh-agent     Wazuh - Improved OSSEC agent for Intrusion Detection, File Integrity Monitoring, Policy Monitoring and Rootkits Detection.
(i386) 4.4.0
Select package(s) you wish to process (or 'all' to process
all packages). (default: all) [?,??,q]: 
Processing package instance <wazuh-agent> from </export/home/vagrant/wazuh-agent_v4.4.0-test.user-sol10-i386.pkg>
Wazuh - Improved OSSEC agent for Intrusion Detection, File Integrity Monitoring, Policy Monitoring and Rootkits Detection.(i386) 4.4.0
This appears to be an attempt to install the same architecture and
version of a package which is already installed.  This installation
will attempt to …
```
> Fix error when creating user in Solaris 10

- alpine/SPECS/wazuh-agent/APKBUILD
- alpine/SPECS/wazuh-agent/wazuh-agent.post-deinstall
- alpine/SPECS/wazuh-agent/wazuh-agent.post-install
- alpine/SPECS/wazuh-agent/wazuh-agent.post-upgrade
- alpine/SPECS/wazuh-agent/wazuh-agent.pre-deinstall
- alpine/SPECS/wazuh-agent/wazuh-agent.pre-install
- alpine/SPECS/wazuh-agent/wazuh-agent.pre-upgrade
|---|
|Related https://github.com/wazuh/wazuh-documentation/issues/5775 |
Hello! We have improved the Alpine packages.
Install
```
(1/10) Installing ncurses-terminfo-base (6.3_p20221119-r0)
(2/10) Installing ncurses-libs (6.3_p20221119-r0)
(3/10) Installing readline (8.2.0-r0)
(4/10) Installing bash (5.2.12-r0)
Executing bash-5.2.12-r0.post-install
(5/10) Installing libintl (0.21.1-r1)
(6/10) Installing libproc (3.3.17-r2)
(7/10) Installing procps (3.3.17-r2)
(8/10) Installing libgcc (12.2.1_git20220924-r4)
(9/10) Installing libstdc++ (12.2.1_git20220924-r4)
(10/10) Installing wazuh-agent (4.4.0-r1)
Executing wazuh-agent-4.4.0-r1.pre-install
Executing wazuh-agent-4.4.0-r1.post-install
Executing busybox-1.35.0-r29.trigger
OK: 29 MiB in 25 packages
```
Remove
```
(1/10) …
```
> Added ossec.conf file generation and improved SPECs

- stack/dashboard/rpm/wazuh-dashboard.spec
|---|
|https://github.com/wazuh/wazuh-packages/issues/1975|
| https://github.com/wazuh/wazuh-packages/issues/1206 |
Due to problems in managing services between init.d and systemd in RPM systems, especially in the use of `service wazuh-dashboard status`, it was decided to apply the same solution applied for Red Hat 9 in this [PR](https://github.com/wazuh/wazuh-packages/pull/1898/files).
Removing the /etc/init.d/wazuh-dashboard file forces the system to redirect calls from init.d to systemd.
https://github.com/wazuh/wazuh-packages/pull/1987#issuecomment-1352046355
https://github.com/wazuh/wazuh-packages/pull/1987#issuecomment-1352046526
- Tests for …
> Removed init.d service for Wazuh dashboard rpm

- stack/dashboard/rpm/wazuh-dashboard.spec
|---|
|https://github.com/wazuh/wazuh-packages/issues/1975|
| https://github.com/wazuh/wazuh-packages/issues/1206 |
Due to problems in managing services between init.d and systemd in RPM systems, especially in the use of `service wazuh-dashboard status`, it was decided to apply the same solution applied for Red Hat 9 in this [PR](https://github.com/wazuh/wazuh-packages/pull/1898/files).
Removing the /etc/init.d/wazuh-dashboard file forces the system to redirect calls from init.d to systemd.
https://github.com/wazuh/wazuh-packages/pull/1987#issuecomment-1352046355
https://github.com/wazuh/wazuh-packages/pull/1987#issuecomment-1352046526
- Tests for …
> Removed init.d service for Wazuh dashboard rpm to Master

- stack/dashboard/base/files/etc/opensearch_dashboards.yml
- unattended_installer/config/dashboard/dashboard.yml
- unattended_installer/config/dashboard/dashboard_all_in_one.yml
- unattended_installer/config/dashboard/dashboard_unattended.yml
- unattended_installer/config/dashboard/dashboard_unattended_distributed.yml
|---|
| #1969 |
This PR replaces setting `requestHeadersWhitelist` for `requestHeadersAllowlist` as per the deprecation seen in warning
```
Dec 07 14:45:54 ip-172-31-92-159 opensearch-dashboards[41195]: {"type":"log","@timestamp":"2022-12-07T14:45:54Z","tags":["warning","config","deprecation"],"pid":41195,"message":"\"opensearch.requestHeadersWhitelist\" is deprecated and has been replaced by \"opensearch.requestHeadersAllowlist\""}
```
> `requestHeadersWhitelist` is replaced by `requestHeadersAllowlist` because of deprecation

- macos/generate_wazuh_packages.sh
- macos/uninstall.sh
|---|
|#1965 |
The function previously removed all scripts inside `macos/package-files` which are part of the repository and are not changed during the generation of packages. 
Uninstall function is called as root, so there is no necessity of calling all lines with `sudo`. The uncommented line is necessary according to the [documentation](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-macos.html#uninstall-a-wazuh-agent).
Tested for macOS package creation with and without errors, and it gives no problem.
> Fixes in `clean_and_exit` function and `uninstall.sh` file for macOS package generation

- unattended_installer/cert_tool/certMain.sh
|---|
|#1988|
This PR removes the check for all types of nodes in the -A option of wazuh-certs-tool.sh.
<details><summary>config.yml</summary>
```
nodes:
indexer:
- name: indexer-1
ip: 1.1.1.1
- name: indexer-2
ip: 1.1.1.2
- name: indexer-3
ip: 1.1.1.3
```
</details>
```
dfolcha@pop-os:~/wazuh-packages/unattended_installer$ bash wazuh-certs-tool.sh -A
15/12/2022 13:19:12 INFO: Admin certificates created.
15/12/2022 13:19:13 INFO: Wazuh indexer certificates created.
```
> Remove check for node types in `-A` option of `wazuh-certs-tool.s`

- tests/unattended/install/test_unattended.py
|---|
|https://github.com/wazuh/wazuh-jenkins/issues/4507|
This PR fixes some errors with the PR tests:
- Fix error with cluster daemon changing name.
- Extend ignored errors from 4.5 to affect 4.4 too.
Test pipeline:
https://ci.wazuh.info/job/Test_unattended_distributed/319/
> Fix unattended test

- stack/dashboard/base/builder.sh
- stack/dashboard/base/files/etc/custom_welcome/Assets/default_branding/home.svg
- stack/dashboard/base/files/etc/custom_welcome/Assets/default_branding/home_dark_mode.svg
- stack/dashboard/base/files/etc/opensearch_dashboards.yml
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/2011|
The default configuration is modified so that the header is hidden by default, and in turn the Home icon that is displayed when the header is disabled is modified
Centos 7: https://ci.wazuh.info/view/Tests/job/Test_stack/213/console
Ubuntu Focal: https://ci.wazuh.info/view/Tests/job/Test_stack/214/console
Packages:
RPM:
- Wazuh dashboard: https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/wazuh-dashboard-4.4.0-0.0.0.2011.x86_64.rpm
- Wazuh indexer: https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/wazuh-indexer-4.4.0-0.0.0.2011.x86_64.rpm
DEB:
- Wazuh dashboard: https://packages-dev.wazuh.com/warehouse/test/4.4/deb/wazuh-dashboard_4.4.0-0.0.0.2011_amd64.deb
- Wazuh indexer: …
> Disable expanded header by default in Wazuh dashboard to  4.4

- hp-ux/generate_wazuh_packages.sh
|---|
|https://github.com/wazuh/wazuh-jenkins/issues/4486
Need to remove the parameter `-b 64` to  `depothelper`.
https://ci.wazuh.info/job/Packages_builder_special/644
> Remove parameter `-b` to `depothelper`

- stack/dashboard/base/builder.sh
- stack/dashboard/base/files/etc/custom_welcome/Assets/default_branding/home.svg
- stack/dashboard/base/files/etc/custom_welcome/Assets/default_branding/home_dark_mode.svg
- stack/dashboard/base/files/etc/opensearch_dashboards.yml
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/2011|
The default configuration is modified so that the header is hidden by default, and in turn the Home icon that is displayed when the header is disabled is modified
Centos 7: https://ci.wazuh.info/view/Tests/job/Test_stack/213/console
Ubuntu Focal: https://ci.wazuh.info/view/Tests/job/Test_stack/214/console
Packages:
RPM:
- Wazuh dashboard: https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/wazuh-dashboard-4.4.0-0.0.0.2011.x86_64.rpm
- Wazuh indexer: https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/wazuh-indexer-4.4.0-0.0.0.2011.x86_64.rpm
DEB:
- Wazuh dashboard: https://packages-dev.wazuh.com/warehouse/test/4.4/deb/wazuh-dashboard_4.4.0-0.0.0.2011_amd64.deb
- Wazuh indexer: …
> Disable expanded header by default in Wazuh dashboard to master

- tests/unattended/install/test_unattended.py
- unattended_installer/builder.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2000|
This PR modifies the `builder.sh` script of the unattended installer, adding a new function, `checkFilebeatURL`, that changes the URL of the Filebeat Wazuh template in case of the URL does not work. This is compulsory when `major` is the same branch as the `master` branch, and that `major` branch is not created in the bucket.
The function is:
https://github.com/wazuh/wazuh-packages/blob/5a42d306d9e5f105464a475f38ea546a0a4834b4/unattended_installer/builder.sh#L271-L291
> Added new function checkFilebeatURL

- tests/unattended/install/test_unattended.py
- unattended_installer/install_functions/checks.sh
- unattended_installer/install_functions/installCommon.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1857|
This pull request modifies how the unattended installer checks the used ports before installing.
It is a copy of PR: https://github.com/wazuh/wazuh-packages/pull/1942 because of renaming the branch to `1857-check-ports-change-grep-master`.
This modification consists of removing the `grep` command as an alternative to the `checks_ports()` function and keeping the `lsof` command as the only port command checker.
With this change, it is compulsory to make the `lsof` package a dependency of the unattended installer.
The tests are defined in the related issue, specifically in https://github.com/wazuh/wazuh-packages/issues/1857#issuecomment-1324943850
> Added lsof as a dependency of the unattended installer

- unattended_installer/builder.sh
|---|
| #2025 |
This PR changes a relative path for variable `resources_installer` to avoid errors coming from where the `builder.sh` is called.
```
readonly base_path_builder="$(dirname "$(readlink -f "$0")")"
readonly resources_installer="${base_path_builder}/install_functions"
```
```
[verdx@pop-os unattended_installer]$ bash builder.sh -i 
grep: unattended_installer/install_functions/installVariables.sh: No such file or directory
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
Changing Filebeat URL...
```
```
[verdx@pop-os unattended_installer]$ bash builder.sh -i 
Changing Filebeat URL...
[verdx@pop-os unattended_installer]$ 
```
> Change the relative path used in checkFilebeat for a defined path variable

- ova/provision.sh
|---|
|close https://github.com/wazuh/wazuh-packages/issues/1971|
After various tests, I was able to detect that the fact that wazuh-manager service was active before the VM was exported generated this error in the logs.
I managed to avoid this error in the logs by adding this service to the provision.sh
```console
[wazuh-user@wazuh-server ~]$ journalctl -r -u wazuh-indexer.service | grep -i -E "error|critical|warning|fatal" 
ene 04 16:00:35 wazuh-server systemd-entrypoint[965]: WARNING: System::setSecurityManager will be removed in a future release
ene 04 16:00:35 wazuh-server systemd-entrypoint[965]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
ene 04 16:00:35 wazuh-server systemd-entrypoint[965]: WARNING: …
```
> Removed errors logs from OVA to 4.4

- ova/provision.sh
|---|
|close https://github.com/wazuh/wazuh-packages/issues/1971|
After various tests, I was able to detect that the fact that wazuh-manager service was active before the VM was exported generated this error in the logs.
I managed to avoid this error in the logs by adding this service to the provision.sh
```console
[wazuh-user@wazuh-server ~]$ journalctl -r -u wazuh-indexer.service | grep -i -E "error|critical|warning|fatal" 
ene 04 16:00:35 wazuh-server systemd-entrypoint[965]: WARNING: System::setSecurityManager will be removed in a future release
ene 04 16:00:35 wazuh-server systemd-entrypoint[965]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
ene 04 16:00:35 wazuh-server systemd-entrypoint[965]: WARNING: …
```
> Removed errors logs from OVA to master

- hp-ux/generate_wazuh_packages.sh
|---|
|https://github.com/wazuh/wazuh-jenkins/issues/4486
Need to remove the parameter `-b 64` to  `depothelper`.
https://ci.wazuh.info/job/Packages_builder_special/644
> Remove parameter -b to depothelper

- windows/entrypoint.sh
- windows/generate_compiled_windows_agent.sh
- windows/generate_wazuh_msi.ps1
|---|
|Closes wazuh/wazuh#15327|
This pull request aims to add a new flag at compile time, to identify when the signature is done and when not in windows, so that based on this the trusted dll verification is activated or not.
> Add flag mechanism to configure the protection for untrusted libraries verification

- stack/indexer/base/files/usr/lib/systemd/system/wazuh-indexer.service
- unattended_installer/install_functions/indexer.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/install_functions/installMain.sh
- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
| #1962 |
To fix the error explained in #1962, this PR adds a new variable `no_indexer_backup` that specifies that the function `passwords_changePassword()` is being called from script `wazuh-install.sh`, but for an action that won't imply running the Indexer Security administrator. That way we isolate the cases in which `passwords_changePassword()` is called from `wazuh-install.sh` but function `passwords_runSecurityAdmin()` is not being called. In this cases, file `/etc/wazuh-indexer/backup` would be created with owner `root:root` and left after the action. If that file exists with those permissions, the Wazuh Indexer service would be unable to start.
All logs are written along the tests in the Issue.
> Avoid doing Wazuh Indexer backup if not necessary

- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
|#2034|
This PR  fixes an error that caused the passwords other users to be modified when changing a single password using the password tool.
```
[root@amazon2 vagrant]# cat wazuh-install-files/wazuh-passwords.txt
indexer_username: 'admin'
indexer_password: '6G7Gxz1kDLNIhsxO2Fn7LXituguj.u*6'
indexer_username: 'kibanaserver'
indexer_password: 'E80.zMnk3uBnTF29pW3Dp4yMJ+?29f5j'
indexer_username: 'kibanaro'
indexer_password: '16x6El*aew2is?t0zjXbaZC6A5AN59uA'
indexer_username: 'logstash'
indexer_password: 'kuqH9dyhL4YX?V.WIx*6ZWNWRRj8776g'
indexer_username: 'readall'
indexer_password: '9u35?Clwbg.jzBq2OzQV6Kg+6+a6KofM'
indexer_username: 'snapshotrestore'
indexer_password: '.ViUXN4yss*?KzTNokpwdEaNbQWhvFil'
api_username: 'wazuh'
api_password: …
```
> Create backup before changing password

- windows/entrypoint.sh
- windows/generate_compiled_windows_agent.sh
- windows/generate_wazuh_msi.ps1
|---|
|Closes wazuh/wazuh#15327|
This pull request aims to add a new flag at compile time, to identify when the signature is done and when not in windows, so that based on this the trusted dll verification is activated or not.
> 15327 add protection for untrusted libraries master

- stack/dashboard/base/builder.sh
- stack/dashboard/base/docker/Dockerfile
- stack/dashboard/base/generate_base.sh
- stack/dashboard/deb/build_package.sh
- stack/dashboard/deb/builder.sh
- stack/dashboard/rpm/build_package.sh
- stack/dashboard/rpm/builder.sh
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/2012|
A modification is made in the construction of the base so that the Wazuh dashboard package has the corresponding build_number included in its packages.json according to the Wazuh plugin that is installed in the package itself
```console
[root@centos7-1 ~]# cat /usr/share/wazuh-dashboard/package.json 
{
"name": "opensearch-dashboards",
"description": "OpenSearch Dashboards is a browser based analytics and search dashboard for OpenSearch. OpenSearch Dashboards is a snap to setup and start using. OpenSearch Dashboards strives to be easy to get started with, while also being flexible and powerful, just like OpenSearch.",
"keywords": [
"opensearch-dashboards",
"opensearch",
"logstash",
"analytics", …
```
> The Wazuh dashboard build_number is updated with the Wazuh app parameters  to 4.4

- stack/dashboard/base/builder.sh
- stack/dashboard/base/docker/Dockerfile
- stack/dashboard/base/generate_base.sh
- stack/dashboard/deb/build_package.sh
- stack/dashboard/deb/builder.sh
- stack/dashboard/rpm/build_package.sh
- stack/dashboard/rpm/builder.sh
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/2012|
A modification is made in the construction of the base so that the Wazuh dashboard package has the corresponding build_number included in its packages.json according to the Wazuh plugin that is installed in the package itself
```console
[root@centos7-1 ~]# cat /usr/share/wazuh-dashboard/package.json 
{
"name": "opensearch-dashboards",
"description": "OpenSearch Dashboards is a browser based analytics and search dashboard for OpenSearch. OpenSearch Dashboards is a snap to setup and start using. OpenSearch Dashboards strives to be easy to get started with, while also being flexible and powerful, just like OpenSearch.",
"keywords": [
"opensearch-dashboards",
"opensearch",
"logstash",
"analytics", …
```
> The Wazuh dashboard build_number is updated with the Wazuh app parameters to master

- rpms/SPECS/wazuh-manager.spec
|---|
|closes #1658 |
After adding a new CLI for the Wazuh API RBAC, we needed to update the RPM specs to include that file.
**IMPORTANT:** This PR cannot be merged until the branch [dev-13109-rbac-upgrade-migration](https://github.com/wazuh/wazuh/tree/dev-13109-rbac-upgrade-migration)
is merged into `master` (`4.5`).
[Manager package build (CentOS)](https://devel.ci.wazuh.info/job/Packages_builder/7748)
[Agent package build (CentOS)](https://devel.ci.wazuh.info/job/Packages_builder/7749/)
[Test install](https://devel.ci.wazuh.info/job/Test_install/20664/)
[Test upgrade 4.3.4 -> 4.5.0 (CentOS)](https://devel.ci.wazuh.info/job/Test_upgrade/57136)
> The upgrade test fails because it seems that some of the scripts were renamed and the team did not update the …
> Add RBAC CLI to RPM SPEC files check

- debs/Debian/amd64/Dockerfile
- debs/Debian/arm64/Dockerfile
- debs/Debian/armhf/Dockerfile
- debs/Debian/i386/Dockerfile
- debs/Debian/ppc64le/Dockerfile
- hp-ux/generate_wazuh_packages.sh
- rpms/CentOS/5/i386/Dockerfile
- rpms/CentOS/5/x86_64/Dockerfile
- rpms/CentOS/6/i386/Dockerfile
- rpms/CentOS/6/x86_64/Dockerfile
- rpms/CentOS/7/aarch64/Dockerfile
- rpms/CentOS/7/armv7hl/Dockerfile
- rpms/CentOS/7/ppc64le/Dockerfile
- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
- solaris/solaris11/SPECS/template_agent.json
- wpk/linux/x86_64/Dockerfile
|Related issue|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |
This pull request adds the following changes related to the FIM rework to support DBSync, and RSync.
- RPM specs have been updated to include the new library for FIM `libfimdb.so`
- Solaris specs have been updated to include the new library
- The script to generate the package for HP-UX has been updated to:
- Download and deploy the needed compiler GCC 9.4 and CMake 3.22.2
- GCC is no longer downloaded from the depothelper
- Standard libraries needed to run the agent are added to the installation directory
After the need to include two new libraries in the agent installation, the footprint of the package grows.
- `libstdc++.so`: 27MB
-  `libgcc_s.so`: 0.4MB
- Agent package: 55MB
- Build the package in …
> Change FIM database management using DBSync and RSync

- alpine/SPECS/wazuh-agent/APKBUILD
- alpine/SPECS/wazuh-agent/wazuh-agent.post-install
|---|
|https://github.com/wazuh/wazuh/issues/15858|
With the new support of Alpine Linux in 4.4, it has been needed to add a new template, `wazuh/wazuh/etc/templates/config/alpine/rootcheck.agent.template` for the `ossec.conf` creation in this SO in order to prevent false positive Trojans detection. First, it was tested with a compilation from sources and the expected changes were applied correctly, but when trying to create packages to install in Alpine Linux, the resulting package did not apply these changes as we wanted to. 
After researching the problem, it was detected that the `wazuh-packages/alpine/SPECS/wazuh-agent/APKBUILD` was missing some lines to correctly detect the new folder containing the Alpine template. Now, the built packages work properly and apply the …
> Fix Alpine package ossec.conf creation

- debs/SPECS/wazuh-manager/debian/postinst
- rpms/SPECS/wazuh-manager.spec
|---|
|Closes [#14175 Session timeout during YUM upgrade](https://github.com/wazuh/wazuh/issues/14175)|
This PR attempts to provide a solution to timeout that is generated when an update is made due to user and group change in the manager by improving the find command with xargs.
Previously, when the manager has many files with different user and group that `wazuh:wazuh`,  it took a long time for the find command to apply the change.
To solve this problem, two VMs with 2 cores and 1Gb of RAM, both from CentOS, were used, one locally and one being an AWS instance. First installed a manager version 4.2.7 in both VMs and take the time neccesary to update using the old version of installer, i.e that one with the command `find ./folder -user u -group g -exec chown nu:ng {} \;` …
> Improve command to change user and group from version 4.2.x to 4.x.x

- alpine/SPECS/wazuh-agent/wazuh-agent.post-install
|---|
|#2081|
This PR fixes the database error caused by removing the `packages_files` directory in the post-install script of the Alpine Linux packages.
```
/packages # apk add --allow-untrusted wazuh-agent-4.4.0-r1.apk
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/8) Installing libintl (0.21-r2)
(2/8) Installing ncurses-terminfo-base (6.3_p20220521-r0)
(3/8) Installing ncurses-libs (6.3_p20220521-r0)
(4/8) Installing libproc (3.3.17-r1)
(5/8) Installing procps (3.3.17-r1)
(6/8) Installing libgcc (11.2.1_git20220219-r2)
(7/8) Installing libstdc++ (11.2.1_git20220219-r2)
(8/8) Installing wazuh-agent (4.4.0-r1)
Executing wazuh-agent-4.4.0-r1.pre-install …
```
> Avoid error caused by the removal of `packages_files` directory in Alpine Linux packages

- alpine/SPECS/wazuh-agent/wazuh-agent.post-install
|---|
|#2081|
This PR fixes the database error caused by removing the `packages_files` directory in the post-install script of the Alpine Linux packages.
```
/packages # apk add --allow-untrusted wazuh-agent-4.4.0-r1.apk
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/8) Installing libintl (0.21-r2)
(2/8) Installing ncurses-terminfo-base (6.3_p20220521-r0)
(3/8) Installing ncurses-libs (6.3_p20220521-r0)
(4/8) Installing libproc (3.3.17-r1)
(5/8) Installing procps (3.3.17-r1)
(6/8) Installing libgcc (11.2.1_git20220219-r2)
(7/8) Installing libstdc++ (11.2.1_git20220219-r2)
(8/8) Installing wazuh-agent (4.4.0-r1)
Executing wazuh-agent-4.4.0-r1.pre-install …
```
> Do not remove packages_files directory

- unattended_installer/builder.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2031|
This PR modifies the builder of the Installation Assitant, adding a new function, `checkDistDetectURL`, which test the `curl` command of the `dist-detect.sh` file before adding it to the Installation Assistant.
This avoids adding the wrong content to the Installation Assistant in case the curl fails.
Logs are in the related issue https://github.com/wazuh/wazuh-packages/issues/2031#issuecomment-1432712317.
Logs are in the related issue https://github.com/wazuh/wazuh-packages/issues/2031#issuecomment-1432712317.
> Checking the `dist-detect` curl in the Installation Assistant builder

- debs/Debian/amd64/Dockerfile
- debs/Debian/arm64/Dockerfile
- debs/Debian/armhf/Dockerfile
- debs/Debian/i386/Dockerfile
- debs/Debian/ppc64le/Dockerfile
- stack/dashboard/deb/docker/amd64/Dockerfile
- stack/indexer/deb/docker/amd64/Dockerfile
- windows/Dockerfile
- wpk/common/Dockerfile
|---|
|https://github.com/wazuh/wazuh-packages/issues/1964|
This PR is a backport of the related issue to the `4.4` branch.
It fixes the generation of the Docker images based on Debian systems due to expired keys.
The changes are:
- Add `--force-yes` option to the `apt install` command in systems where the `apt` package is under `1.1` version.
- Add `--allow-change-held-packages` option to the `apt install` command in systems where the `apt` package is over `1.1` version. This change is to avoid the warning of the deprecated option `--force-yes` in versions over `1.1`
In other words, the new option `--allow-change-held-packages` is included in the Dockerfiles that use:
- Debian 9 system.
- Debian 10 system.
- Ubuntu 22.04 system.
The generation of the affected images are …
> Fixed Debian expired keys in Dockerfiles

- ova/provision.sh
|---|
|#1971|
This PR fixes an error that caused the logs from the Wazuh indexer to not be accessible after importing the OVA.
> Fix error with wazuh-indexer logs permissions in OVA

- unattended_installer/builder.sh
- unattended_installer/install_functions/dashboard.sh
- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
| #2111 |
This PR aims to fix the errors seen in the dashboard installation when an All-in-one installation is done in a system with less capabilities than the recommended ones. This errors have discovered some issues on the error treatment of the installation.
For now, function `passwords_getApiToken` now detects one more possible error and retries the Token downloading some number of times.
<details>
<summary> :green_circle: Ubuntu 18</summary>
```
root@ubuntu18:/home/vagrant# bash wazuh-install.sh -a 
08/03/2023 16:37:20 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.10
08/03/2023 16:37:20 INFO: Verbose logging redirected to /var/log/wazuh-install.log
08/03/2023 16:37:41 INFO: Wazuh development repository added.
08/03/2023 16:37:41 INFO: --- …
```
> Fix the errors in the dashboard for the AIO installation 

- unattended_installer/builder.sh
- unattended_installer/install_functions/dashboard.sh
- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
| #2111 |
This PR aims to fix the errors seen in the dashboard installation when an All-in-one installation is done in a system with less capabilities than the recommended ones. This errors have discovered some issues on the error treatment of the installation.
For now, function `passwords_getApiToken` now detects one more possible error and retries the Token downloading some number of times.
<details>
<summary> :green_circle: Ubuntu 22</summary>
```
root@ubuntu22:/home/vagrant# bash wazuh-install.sh -a -o
09/03/2023 09:55:52 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
09/03/2023 09:55:52 INFO: Verbose logging redirected to /var/log/wazuh-install.log
09/03/2023 09:55:53 INFO: --- Removing existing Wazuh installation ---
09/03/2023 09:55:53 INFO: …
```
> Fix the errors in the dashboard for the AIO installation

- alpine/SPECS/wazuh-agent/wazuh-agent.post-install
- debs/Debian/arm64/Dockerfile
- debs/Debian/armhf/Dockerfile
- debs/Debian/ppc64le/Dockerfile
- stack/dashboard/deb/docker/amd64/Dockerfile
- stack/indexer/deb/docker/amd64/Dockerfile
- unattended_installer/install_functions/installCommon.sh
- windows/Dockerfile
- wpk/common/Dockerfile
|---|
|#2024|
This PR fixes an error in the wazuh-install.sh script that caused it to fail if we had previously canceled the execution of the script.
The error could appear because of two reasons:
1. Some files from the wazuh-indexer were not deleted in the rollback function.
2. After canceling the execution some packages were installed but the script did not know it.
> Fix error when running `wazuh-install.sh` after canceling the execution

- debs/SPECS/wazuh-agent/debian/rules
- debs/SPECS/wazuh-manager/debian/rules
- rpms/SPECS/wazuh-manager.spec
|---|
|Closes #2134|
This PR adds the necessary changes to include the new Debian 11 SCA files to de SPECS.
> Add Debian 11 SCA files to specs

- .github/actions/upgrade-indexer/common.sh
- .github/actions/upgrade-indexer/upgrade-indexer.sh
- .github/workflows/test-indexer-debian.yml
- .github/workflows/test-indexer-rpm.yml
- stack/indexer/deb/debian/postinst
- stack/indexer/deb/debian/postrm
- stack/indexer/deb/debian/preinst
- stack/indexer/rpm/wazuh-indexer.spec
|---|
|https://github.com/wazuh/wazuh-packages/issues/2155|
This PR is the backport of https://github.com/wazuh/wazuh-packages/pull/1998 to `4.4`.
To summarize, the SPEC files of the Wazuh indexer of Debian and RPM have changed to preserve the securityconfig files upon upgrade.
Due to the lack of automatic tests, some GitHub Actions have been added, too.
> Preserved securityconfig files upon upgrade of the Wazuh indexer - 4.4

- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
|---|
|Closes #2161|
This PR aims to change the debug information deployment on RPM packages.
Currently, we've been delivering debug information on separate files, giving hard time to link them with their binaries. We are changing that approach to a built-in debug information approach.
> Add debug symbols to debug packages binary

- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
|---|
|Closes #2161|
This PR aims to change the debug information deployment on RPM packages.
Currently, we've been delivering debug information on separate files, giving hard time to link them with their binaries. We are changing that approach to a built-in debug information approach.
Packages: https://ci.wazuh.info/view/Packages/job/Packages_builder_tier/2924/
> Add debug symbols to debug packages binary - 4.4

- solaris/solaris10/postremove.sh
- solaris/solaris10/preinstall.sh
|---|
|Closes #2166|
This issue aims to backport some fixes from 4.4 to 4.3
> Backporting fixes from 4.4 to 4.3

- .github/actions/test-install-components/install_component.sh
|---|
|#2177|
In this PR we add the Archives repository to the Debian Stretch tests in GH actions.
> Add Archives repository to Debian Stretch tests

- debs/Debian/arm64/Dockerfile
- debs/Debian/armhf/Dockerfile
- debs/Debian/ppc64le/Dockerfile
|---|
|Closes #2175|
This PR aims to fix the generation of ARM64/ARM32/PPC64LE deb packages
- Images were uploaded with de _9 suffix
- deb_builder_arm64_gcc9_dev
- deb_builder_armhf_gcc9_dev 
- Package builder tier testing those new tags https://ci.wazuh.info/job/Packages_builder_tier/2944/
> Fix the generation of ARM64/ARM32/PPC64LE deb packages

- aix/SPECS/wazuh-agent-aix.spec
- debs/SPECS/wazuh-agent/debian/changelog
- debs/SPECS/wazuh-manager/debian/changelog
- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
|---|
|Related https://github.com/wazuh/wazuh-packages/pull/2187|
This PR fixes the release date of version 4.3.11 in the 4.3 branch
- https://ci.wazuh.info/view/Packages/job/Packages_builder_tier/2947/
- Debian Wazuh manager/agent
- RPM Wazuh manager/agent
```
[root@centos7 vagrant]# rpm -q --changelog wazuh-agent 
* Mon Apr 24 2023 2022 support <info@wazuh.com> - 4.3.11
- More info: https://documentation.wazuh.com/current/release-notes/
* Thu Nov 10 2022 support <info@wazuh.com> - 4.3.10
- More info: https://documentation.wazuh.com/current/release-notes/
```
```
root@debian11:/home/vagrant# apt changelog wazuh-manager
Get:1 store: wazuh-manager 4.3.11-0.0.0.todelete Changelog
Fetched 15.6 kB in 0s (0 B/s)
...
wazuh-manager (4.3.11-0.0.0.todelete) stable; urgency=low
* …
```
> Fix 4.3.11 changelog date

- macos/package_files/postinstall.sh
|---|
|closes #2204 #2201|
This PR fixes an error that caused the ossec.conf to be modified if deployment variables were used when upgrading macOS packages.
https://github.com/wazuh/wazuh-packages/issues/2201#issuecomment-1554678222
https://ci.wazuh.info/job/Packages_builder_macos/9829
https://ci.wazuh.info/job/Test_install/124263/
> Fix error with deployment variables on upgrade in macOS packages

- macos/package_files/postinstall.sh
|---|
|Closes https://github.com/wazuh/wazuh-packages/issues/2210|
This pull request fixes the `if` statements so that the encapsulation is correct, it also eliminates two if statements without use since the user `ossecr` and the user `ossecm` have never been part of the macOS agent installation
- See https://github.com/wazuh/wazuh-packages/issues/2210#issuecomment-1557641605
> Fixed macOS post-install user and group check

- macos/package_files/postinstall.sh
- macos/package_files/preinstall.sh
|---|
|#2205|
This PR removes the execution of launchctl commands from macOS installation scripts.
This PR must be merged in combination with:
https://github.com/wazuh/wazuh/pull/17195
https://github.com/wazuh/wazuh-packages/issues/2205#issuecomment-1560753346
> Replace launchctl variables from macOS installation scripts

- windows/generate_compiled_windows_agent.sh
- windows/generate_wazuh_msi.ps1
|---|
|#2227|
This PR aims to include the fixes needed by the new Wazuh certificates used during winagent signing procedure
Manual execution with Signing enabled https://ci.wazuh.info/job/Packages_builder_win/14161/
Package: https://packages-dev.wazuh.com/trash/windows/wazuh-agent-4.4.4-0.0.1.winsign.msi
> Fix winagent signing for new certs

- debs/SPECS/wazuh-agent/debian/postinst
- debs/SPECS/wazuh-manager/debian/postinst
Fixes #2196
Alter the chmod and chown lines to not assume there are files in the directory.
Impact if there are files is unchanged.
|---|
|#2196|
> Fix 2196, support empty ruleset/sca directories

- debs/SPECS/wazuh-agent/debian/postinst
- debs/SPECS/wazuh-manager/debian/postinst
|---|
|Closes #2196|
This PR is a port of #2197 by @lod. This replaces `chmod` on all the SCA policies available (`*`) with a recursive option (`--recursive`). This way, we avoid a "_No such file or directory_" error if the _sca_ folder contains no policy files.
> Support empty ruleset/sca directories

- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
|---|
|#2223|
This PR removes `service` from the requirements to install RPM packages due to its deprecation in newer systems.
> Remove service requirement from RPM packages 4.4.5

- debs/SPECS/wazuh-agent/debian/postinst
- debs/SPECS/wazuh-manager/debian/postinst
|---|
|https://github.com/wazuh/wazuh/issues/17840|
This PR fixes an error with the permissions of some SCA files.
<details><summary>Manager</summary>
```
root@debian12:/home/vagrant# apt install ./wazuh-manager_4.4.5-1_amd64.deb 
Building dependency tree... Done
Note, selecting 'wazuh-manager' instead of './wazuh-manager_4.4.5-1_amd64.deb'
Suggested packages:
expect
The following NEW packages will be installed:
wazuh-manager
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 0 B/171 MB of archives.
After this operation, 631 MB of additional disk space will be used.
Get:1 /home/vagrant/wazuh-manager_4.4.5-1_amd64.deb wazuh-manager amd64 4.4.5-1 [171 MB]
Selecting previously unselected …
```
> Fix SCA files permission error

- README.md
- debs/SPECS/wazuh-agent/debian/postinst
- debs/SPECS/wazuh-manager/debian/postinst
- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
|---|
|https://github.com/wazuh/wazuh-packages/issues/2263|
Merge 4.4 into 4.5.0
> Merge 4.4 into 4.5.0

- debs/SPECS/wazuh-manager/debian/rules
- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
|---|
|Closes #2283 |
This PR adds the necessary modifications to the SPECS to include the new Alma Linux 8 SCA policy.
> Include SCA policy for Alma Linux 8 in SPECS

- .github/workflows/build-deb-packages.yml
- .github/workflows/build-rpm-packages.yml
- CHANGELOG.md
- README.md
- aix/SPECS/wazuh-agent-aix.spec
- debs/SPECS/wazuh-agent/debian/changelog
- debs/SPECS/wazuh-manager/debian/changelog
- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
- stack/dashboard/deb/debian/changelog
- stack/dashboard/rpm/wazuh-dashboard.spec
- stack/indexer/deb/debian/changelog
- stack/indexer/rpm/wazuh-indexer.spec
- tests/unattended/unit/suites/test-dashboard.sh
- tests/unattended/unit/suites/test-indexer.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2306|
This PR merge 4.6.0 into 4.7.0
> Merge 4.6.0 into 4.7.0

- ova/Vagrantfile
- ova/assets/custom/enable_fips.sh
- ova/assets/custom/messages.sh
- ova/assets/steps.sh
- ova/generate_ova.sh
- ova/provision.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1575|
This PR modifies the base operating system of the OVA from Centos 7 to AmazonLinux 2. It also adds FIPS activation within the VM's operating system.
https://ci.wazuh.info/job/Packages_Builder_OVA/266/console
> OS modification of the OVA

- unattended_installer/cert_tool/certFunctions.sh
|---|
|#1627|
The aim of this PR is to add a check in the Unattended Installer to avoid using public IPs in the Wazuh installation.
When the configuration file is read, the IPs will be checked and the script will exit if a public IP exists.
This has been done by adding a new function `cert_checkPrivateIp` and modifying the `cert_readConfig` function. Some tests are in https://github.com/wazuh/wazuh-packages/issues/1627#issuecomment-1663439076.
> Added check to prohibit public IPs

- rpms/SPECS/wazuh-manager.spec
|---|
|Closing #2328|
This PR aims to fix #2328 by changing group ownership of `rbac_control` from `root` to `wazuh` on RPM packages in order to be aligned with other installation methods
**NOTE** checks fails because does not support a branch name with slashes
https://ci.wazuh.info/job/Packages_builder_tier/3079/
> Fix `rbac_control` group ownership for RPM package

- unattended_installer/install_functions/checks.sh
- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/installMain.sh
- unattended_installer/install_functions/installVariables.sh
|---|
|https://github.com/wazuh/wazuh/issues/18164|
The aim of this PR is to add a new optional parameter, `-p|--port` to allow choosing the Wazuh web interface port. This new option can only be used while performing an AIO installation or installing the Wazuh dashboard.
```
> bash wazuh-install.sh -a -p 8443
> bash wazuh-install.sh -wd dashboard --port 8443
```
Some tests have been done in the "Final tests" of the related issue: https://github.com/wazuh/wazuh/issues/18164#issuecomment-1667789913
Is compulsory to make the necessary changes in the documentation. https://github.com/wazuh/wazuh-documentation/pull/6322
> Provided port number option to `wazuh-install.sh` script

- macos/specs/wazuh-agent.pkgproj
|---|
|Closes #2340|
This pr fixes a problem caused by updating the macOS packaging software that produced an error when installing in machines with ARM architecture.
> Remove check for intel pkg due to changes in packaging software

- macos/specs/wazuh-agent.pkgproj
|---|
||
This PR removes the check for processor architecture completely for macOS packages.
> Remove processor check completely 

- macos/specs/wazuh-agent-intel64.pkgproj
|---|
|https://github.com/wazuh/wazuh-packages/issues/2339|
Spec version for MacOS INTEL is fixed to 4.5.2.
> Fix MacOS spec version for INTEL - 4.5.2

- macos/specs/wazuh-agent-intel64.pkgproj
|---|
|https://github.com/wazuh/wazuh-packages/issues/2339|
Spec version for MacOS INTEL is fixed to 4.5.2.
> Fix MacOS spec version for INTEL - 4.6.0

- unattended_installer/install_functions/filebeat.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/install_functions/wazuh-offline-download.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1896|
The aim of this PR is to improve the `curl` error message generation commands while downloading resources. Before, if this type of `curl` command failed, the error was not inserted into the log file or into the console (if the `verbose` option was enabled).
The testing of the affected curls is attached in the related issue.
> Improved `curl` error messages in downloads

- unattended_installer/builder.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2367|
This PR is a fix of https://github.com/wazuh/wazuh-packages/pull/2370. The `source_branch` has been replaced for the `4.8.0` value. Now, the `curl` command of the builder looks like:
https://raw.githubusercontent.com/wazuh/wazuh/4.8.0/src/init/dist-detect.sh
> Fixed `source_branch` variable in `master` branch

- unattended_installer/cert_tool/certFunctions.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2350|
The aim of this PR is to improve the regex to validate the DNS specified in the Wazuh cert tool, also used by the Installation Assistant.
Besides, a new improvement has been added to check the private IPs only if they are IPs.
<details><summary>Using valid DNS</summary>
`config.yml`:
```yml
nodes:
indexer:
- name: node-1
ip: www.google.es
#- name: node-2
#- name: node-3d
server:
- name: wazuh-1
ip: foo.bar1.com
```
Output:
```console
24/08/2023 09:40:13 DEBUG: Creating the Wazuh indexer certificates.
Ignoring -days without -x509; not generating a certificate
.....+...+..................+.....+.........+.+.....................+........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+..+....+..+.. …
```
> Fixed DNS validation in the Installation Assistant

- unattended_installer/install_functions/filebeat.sh
- unattended_installer/install_functions/indexer.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2363|
The aim of this PR is to fix the debug redirection in some complex commands of the Installation Assistant. These commands only redirected a part of the execution to the log file. With this change, the output of the whole command will be reported.
Testing has been performed in https://github.com/wazuh/wazuh-packages/issues/2363#issuecomment-1702609915
> Fixed debug redirection in Installation Assistant

- unattended_installer/builder.sh
- unattended_installer/install_functions/installVariables.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2404|
2 problems were found in the formation of the URL to download the Filebeat module, the first was the one indicated in the issue, it was trying to obtain from the major-minor branch, which was not correct, we need to obtain the module from major -minor-patch or from tag in the case of production.
And another problem that was found is in the URL validation method, in all cases it gave an error because the variable used in the URL was not in the same script, this generated that the master branch was always used
```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-packages/unattended_installer$ ./builder.sh -i
Error: Could not get the dist-detect file. …
```
> Fixed filebeat module URL

- unattended_installer/install_functions/installVariables.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2406|
The aim of this PR is to change the definition of the `wazuh_dashboard_port` variable, as it was not set correctly. This change solves an error that the `lsof` command was generating because it was receiving no port to check, as the variable did not exist.
> Fixed dashboard check port error

- unattended_installer/install_functions/checks.sh
- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2413|
This PR modifies the password tool, used in the Wazuh Installation Assistant, in order to silence the output of the Node version. This is due to the change of the OpenSearch version to 2.8.0.
The output of the version is not displayed anymore:
```console
04/09/2023 15:02:26 INFO: Starting service wazuh-dashboard.
04/09/2023 15:02:27 INFO: wazuh-dashboard service started.
04/09/2023 15:02:40 INFO: Initializing Wazuh dashboard web application.
```
> Silenced node version output

- README.md
- stack/dashboard/base/builder.sh
- stack/dashboard/base/docker/Dockerfile
- stack/dashboard/base/files/etc/services/wazuh-dashboard.service
- stack/dashboard/deb/debian/rules
- stack/dashboard/rpm/docker/x86_64/Dockerfile
- stack/dashboard/rpm/wazuh-dashboard.spec
|---|
|Closes https://github.com/wazuh/wazuh-packages/issues/2392|
This pull request bumps the Wazuh dashboard to OpenSearch 2.8.0
<details><summary>Upgrade - Debian 11</summary>
```
root@debian11:/home/vagrant# curl -sO https://packages.wazuh.com/4.5/wazuh-install.sh && sudo bash ./wazuh-install.sh -a -i
04/09/2023 15:36:51 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.1
04/09/2023 15:36:51 INFO: Verbose logging redirected to /var/log/wazuh-install.log
04/09/2023 15:36:59 WARNING: Hardware and system checks ignored.
04/09/2023 15:37:00 INFO: --- Dependencies ----
04/09/2023 15:37:00 INFO: Installing apt-transport-https.
04/09/2023 15:37:01 INFO: Installing software-properties-common.
04/09/2023 15:37:10 INFO: Wazuh repository added.
04/09/2023 15:37:10 …
```
> Bump Wazuh dashboard to 2.8.0

- stack/dashboard/base/builder.sh
- stack/dashboard/base/files/etc/services/wazuh-dashboard.service
- stack/dashboard/deb/debian/postinst
- stack/dashboard/deb/debian/rules
- stack/dashboard/rpm/wazuh-dashboard.spec
|---|
|Related https://github.com/wazuh/wazuh-packages/issues/2420#top|
This PR adds the necessary changes so that the Wazuh dashboard 4.6.0-2.8.0 package can use IPs in the `opensearch.hosts` configuration, and also moves the OpenSearch keystore to the Wazuh dashboard configuration directory
- https://ci.wazuh.info/view/Packages/job/Packages_builder_tier/3142/
- https://ci.wazuh.info/job/Packages_builder/164381/
- https://ci.wazuh.info/job/Packages_builder/164412/
- https://ci.wazuh.info/job/Packages_builder/164413/
- https://ci.wazuh.info/job/Test_stack_tier/83/
<details><summary>Upgrade in Debian 11 from 4.5.2 to 4.6.0</summary>
```
root@debian11:/home/vagrant# curl -sO https://packages.wazuh.com/4.5/wazuh-install.sh && sudo bash ./wazuh-install.sh -a -i
06/09/2023 …
```
> Improvements in Wazuh dahboard 4.6.0-2.8.0 package

- unattended_installer/cert_tool/certMain.sh
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/2441|
The changes applied to the cert-tools are rolled back, in the same way as was done in this [PR](https://github.com/wazuh/wazuh-packages/pull/1991)
```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/testing-cert-tool$ cat config.yml 
nodes:
indexer:
- name: demo.indexer
ip: demo.indexer
```
```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/testing-cert-tool$ bash wazuh-certs-tool.sh -h
NAME
wazuh-cert-tool.sh - Manages the creation of certificates of the Wazuh components.
SYNOPSIS
wazuh-cert-tool.sh [OPTIONS]
DESCRIPTION
-a,  --admin-certificates </path/to/root-ca.pem> </path/to/root-ca.key>
Creates the admin certificates, add root-ca.pem and root-ca.key.
-A, --all </path/to/root-ca.pem> …
```
> Reverted --all options for cert-tools

- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2414|
The aim of this PR is to modify the `wazuh-password-too.sh` script that had a bug managing the backup directory. This directory was created twice, and the second command generated an error. 
By checking the existence of the repository, the issue is fixed, and the errors are managed as expected.
Some testing has been done in the "Tests" part of the following comment: https://github.com/wazuh/wazuh-packages/issues/2414#issuecomment-1706347301
> Fixed `mkdir` error in passwords backup

- wpk/run.sh
|---|
|https://github.com/wazuh/wazuh/issues/18965|
This change avoids deleting the entire syscheckd folder when creating WPKs, it keeps the wazuh-syscheckd, libfimdb.dylib and libfimdb.so files.
After the changes, we can see how the necessary syscheckd files are preserved:
And the agent can be updated correctly:
```
2023/09/13 23:06:05 - Generating Backup.
tar: ./var/ossec/queue/sockets/upgrade: socket ignored
tar: ./var/ossec/queue/sockets/logcollector: socket ignored
tar: ./var/ossec/queue/sockets/syscheck: socket ignored
tar: ./var/ossec/queue/sockets/queue: socket ignored
tar: ./var/ossec/queue/sockets/com: socket ignored
tar: ./var/ossec/queue/sockets/control: socket ignored
tar: ./var/ossec/queue/sockets/wmodules: socket ignored
tar: ./var/ossec/queue/alerts/execq: …
```
> Avoids deleting the entire syscheckd folder when creating WPK

- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/installVariables.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2451|
The aim of this PR is to fix the Wazuh dashboard port check when the `-p|--port` option was specified in the Installation Assistant. This bug stopped the execution of the script if the default dashboard port was used, but a different port was specified.
The Installer has been modified by adding a debug line: `INFO: Checking port <port>` to know what port the Installer is checking
<details><summary>:green_circle: Installing Wazuh dashboard specifying the port</summary>
```console
root@ubuntu22:/home/vagrant# lsof -sTCP:LISTEN  -i:443
root@ubuntu22:/home/vagrant# 
root@ubuntu22:/home/vagrant# bash wazuh-install.sh -wd dashboard -i -p 8080
14/09/2023 10:08:07 INFO: Starting Wazuh installation assistant. Wazuh …
```
> Fixed dashboard port check

- unattended_installer/install_functions/installCommon.sh
|---|
|close https://github.com/wazuh/wazuh-packages/issues/2446|
I was able to verify that installing chromium in the previous way no longer works for Centos 7, so the way of installing is changed and the same exception that we used for Amazon Linux is used
<details>
<summary>Centos 7</summary>
```console
[root@centos7-1 ~]# git clone https://github.com/wazuh/wazuh-packages.git
Cloning into 'wazuh-packages'...
remote: Enumerating objects: 55492, done.
remote: Counting objects: 100% (5104/5104), done.
remote: Compressing objects: 100% (1925/1925), done.
remote: Total 55492 (delta 3128), reused 4812 (delta 2893), pack-reused 50388
Receiving objects: 100% (55492/55492), 16.52 MiB | 8.11 MiB/s, done.
Resolving deltas: 100% (34770/34770), done.
[root@centos7-1 ~]# cd …
```
> Adding Centos 7 to chromium installation exception

- windows/generate_wazuh_msi.ps1
|---|
|wazuh/wazuh#18952|
The objective of this PR is to enhance the security and trustworthiness of the `libfimdb.dll` library by implementing code signing, like the previous dll and executable in Wazuh.
- Add the library in the `wazuh-installer-sign-exes.bat` tool.
- Verify that the signed DLL functions correctly in the application. 
> [!NOTE]  
> The validation process was conducted using a generic certificate due to security concerns, which solely verifies the presence of a digital signature.
No test was added in this pull-request. Using a self-signed certificate, we attach `PoC` of the sign library
Not apply
> Implement code signing for `libfimdb.dll` for packages

- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2454|
The aim of this PR is to update the `internal_users.yml` file when the passwords are changed, whether in the Installation Assistant or in the Password tool.
The change consist in copy the `internal_users.yml` file into the `opensearch-security` folder before removing the backup done in the passwords change.
<details><summary>:green_circle: Step-by-step installation using the Installation Assistant</summary>
```console
root@ubuntu22:/home/vagrant# bash wazuh-install.sh -wi node-1 -o -i -t wazuh-install-files.tar && bash wazuh-install.sh -s
18/09/2023 13:18:52 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.2
18/09/2023 13:18:52 INFO: Verbose logging redirected to /var/log/wazuh-install.log …
```
> Update the `internal_users.yml` file when passwords change

- .github/actions/upgrade-indexer/common.sh
|---|
|Closes https://github.com/wazuh/wazuh-packages/issues/2429 |
This pull request fixes the Wazuh indexer update test since the files were not being modified correctly by not correctly redirecting to the tested file
<details><summary>Upgrade from 4.5.2 to 4.6.0</summary>
```
[root@centos7 vagrant]# bash upgrade-indexer.sh "wazuh-indexer-4.6.0-1.x86_64.rpm" "45"
New path detected (/etc).
Installing old version of Wazuh indexer...
[wazuh]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-$releasever - Wazuh
baseurl=https://packages.wazuh.com/4.x/yum/
protect=1
* base: mirror.tedra.es
* extras: mirror.tedra.es
* updates: mirror.tedra.es
wazuh …
```
> Fixed GHA test for Wazuh indexer upgrade

- stack/dashboard/deb/build_package.sh
- stack/dashboard/rpm/build_package.sh
- stack/indexer/deb/build_package.sh
- stack/indexer/rpm/build_package.sh
|---|
|Closes #2145 |
This PR Aims to handle the building the stack packages when the option to not build the base file is used. 
- When  the `-b no` option is passed, if no base is present it will stop the `build_package.sh` script with the expected file name and location.
```console
root@ubuntu-focal:/vagrant/wazuh-packages/stack/indexer/deb# ./build_package.sh -b no
Did not find expected Wazuh Indexer base file: /vagrant/wazuh-packages/stack/indexer/deb/output/wazuh-indexer-base-4.6.0-1-linux-x64.tar.xz found in output path. Exiting...
```
- If the expected file is present the build will continue normally:
```console
root@ubuntu-focal:/vagrant/wazuh-packages/stack/indexer/deb# ls /vagrant/wazuh-packages/stack/indexer/deb/output …
```
> Handle stack  base file not present during build

- .github/actions/upgrade-indexer/common.sh
- CHANGELOG.md
- README.md
- aix/SPECS/wazuh-agent-aix.spec
- debs/SPECS/wazuh-agent/debian/changelog
- debs/SPECS/wazuh-manager/debian/changelog
- macos/specs/wazuh-agent-intel64.pkgproj
- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
- stack/dashboard/deb/build_package.sh
- stack/dashboard/deb/debian/changelog
- stack/dashboard/rpm/build_package.sh
- stack/dashboard/rpm/wazuh-dashboard.spec
- stack/indexer/deb/build_package.sh
- stack/indexer/deb/debian/changelog
- stack/indexer/rpm/build_package.sh
- stack/indexer/rpm/wazuh-indexer.spec
- tests/unattended/install/test_unattended.py
- unattended_installer/cert_tool/certMain.sh
- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/install_functions/installVariables.sh
- unattended_installer/passwords_tool/passwordsFunctions.sh
- windows/generate_wazuh_msi.ps1
- wpk/run.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2472|
This PR aims to merge branch 4.7.1 into master.
> Merge 4.7.1 into master

- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/installCommon.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2482|
The aim of this PR is to fix the dashboard installation dependencies in RHEL systems. To perform this, the CentOS key and needed repositories are added temporarily, and then, when the dependencies are installed, this changes are removed.
Logs and testing is in https://github.com/wazuh/wazuh-packages/issues/2482#issuecomment-1742916290.
> Fixed dashboard dependencies in `RHEL` systems

- macos/specs/wazuh-agent-intel64.pkgproj
|---|
|https://github.com/wazuh/wazuh-packages/issues/2344|
This fix addresses an issue where Intel64 macOS packages were encountering installation failures on ARM-based machines. The update ensures seamless installation and compatibility across both Intel64 and ARM architectures
Installing using the graphics interface:
- [] Package remove
> Intel64 macos packages will fail to install on arm machines

- CHANGELOG.md
- solaris/solaris11/SPECS/template_agent.json
|---|
| #1997 |
Closes #1997. It modifies the Solaris11 SPEC file to include in the agents the latest modification of the AWS integration which separated the module in several files carried out in https://github.com/wazuh/wazuh/issues/13388, which is expected to be released in 4.8.0.
Tested the modified package by creating a Solaris11 package and installing it in a Solaris11 machine respectively. Everything worked as expected, as can be seen in the following output:
<details><summary>Package installation and file permissions</summary>
vagrant@solaris:/tmp$ sudo pkg install -g wazuh-agent_v4.8.0-sol11-i386.p5p wazuh-agent
Services to change:  1
Create boot environment: No
Create backup boot environment: No
DOWNLOAD                                PKGS …
> Add new AWS files to Solaris SPECS

- rpms/SPECS/wazuh-manager.spec
|---|
|https://github.com/wazuh/wazuh/issues/19045|
Adding a missing library to rpm specs.
> Adding flatccrt library to rpm SPECS

- stack/indexer/rpm/build_package.sh
|---|
|Closes https://github.com/wazuh/wazuh-packages/issues/2522|
This pull request fixes a bug condition that prevents searching the base file correctly if the `-b no` parameter is used.
```
╰─➤  bash build_package.sh -b no          
+ build
+ build_name=
+ file_path=
+ '[' x86_64 = x86_64 ']'
+ architecture=x86_64
+ build_name=rpm_indexer_builder_x86
+ file_path=/wazuh-packages/tags/stack/indexer/rpm/docker/x86_64
+ build_rpm rpm_indexer_builder_x86 /wazuh-packages/tags/stack/indexer/rpm/docker/x86_64
+ container_name=rpm_indexer_builder_x86
+ dockerfile_path=/wazuh-packages/tags/stack/indexer/rpm/docker/x86_64
+ cp /wazuh-packages/tags/stack/indexer/rpm/builder.sh /wazuh-packages/tags/stack/indexer/rpm/docker/x86_64
+ '[' no == yes ']'
+ '[' '' ']'
++ cat …
```
> Removed negation from the reference condition

- stack/dashboard/base/builder.sh
|---|
|https://github.com/wazuh/wazuh-kibana-app/issues/5893|
This pull request changes the category of built-in applications on the Wazuh dashboard, renames the category and hide some application.
- Add `Explore` category
- Rename the `Dashboards management` category to `Indexer/dashboard Management`
- Change to `Explore` category the following applications:
- Discover
- Dashboards
- Visualize
- Reporting
- Alerting
- Maps
- Notifications
- Change category to `Indexer/dashboard Management`:
- Index Management
- Snapshot management
- Security
- Change the order of the following applications:
- Discover
- Dashboards
- Visualize
- Dev tools
- Dashboards management
- Security
- Index management
- Snapshot management
- Avoid the Overview application of the Management category …
> Change the category of built-in applications on Wazuh dashboard

- CHANGELOG.md
- aix/SPECS/wazuh-agent-aix.spec
- bump_version.py
- debs/SPECS/wazuh-agent/debian/changelog
- debs/SPECS/wazuh-manager/debian/changelog
- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
- stack/dashboard/deb/debian/changelog
- stack/dashboard/rpm/wazuh-dashboard.spec
- stack/indexer/deb/debian/changelog
- stack/indexer/deb/debian/copyright
- stack/indexer/rpm/wazuh-indexer.spec
- tests/unattended/unit/suites/test-common.sh
- tests/unattended/unit/suites/test-dashboard.sh
Merge 4.5.4 to the 4.6.0 branch.
> Merge 4.5.4 into 4.6.0

- unattended_installer/config/dashboard/dashboard.yml
- unattended_installer/config/dashboard/dashboard_all_in_one.yml
- unattended_installer/config/dashboard/dashboard_unattended.yml
- unattended_installer/config/dashboard/dashboard_unattended_distributed.yml
This PR is related to https://github.com/wazuh/internal-devel-requests/issues/394.
The aim of this PR is to update the `/app/wazuh` value references in the Installation Assistant to the `/app/wz-home`. 
The change in `unattended_installer/config/dashboard/dashboard.yml` modifies the `server.defaultRoute` parameter instead of the `uiSettings.overrides.defaultRoute` parameter. However, this change is necessary to correctly manage the URL `https://<WAZUH_DASHBOARD_ADDRESS>/app/wz-home`.
This has been validated by @Desvelao.
> Updated Wazuh dashboard references in Installation Assistant

- .github/workflows/password-tool.yml
- unattended_installer/passwords_tool/passwordsFunctions.sh
Related issue: https://github.com/wazuh/wazuh-packages/issues/2503
The aim of this PR is to allow the Wazuh password tool to work for users created through the UI. Until now, these users were not in the `internal_users.yml` file so the Wazuh password tool did not recognize them. Using the `securityadmin` tool and updating the internal users before reading them fixes the problem.
Two more changes have been added:
- The new generated hash is fixed and now it is contained with double quotes in the `internal_users.yml` file.
- A backup of the internal users is made and saved in the `/etc/wazuh-indexer/internal_users_backup` with the following name: `internal_users_<datetime>.yml.bkp` before changing the passwords.
The testing has been done in: …
> Wazuh password tool now recognize UI created users

- unattended_installer/install_functions/checks.sh
|---|
|close https://github.com/wazuh/wazuh-packages/issues/2539|
Validations are created to detect if the system has Firewalld or UFW installed and enabled, to indicate by a Warning message which ports should be opened in the firewall
Firewalld: https://github.com/wazuh/wazuh-packages/issues/2539#issuecomment-1777142732
Without Firewalld: https://github.com/wazuh/wazuh-packages/issues/2539#issuecomment-1777131414
Firewalld and UFW: https://github.com/wazuh/wazuh-packages/issues/2539#issuecomment-1777448920
Firewalld: https://github.com/wazuh/wazuh-packages/issues/2539#issuecomment-1776009345
Without Firewalld: https://github.com/wazuh/wazuh-packages/issues/2539#issuecomment-1777122116
Firewalld and UFW: https://github.com/wazuh/wazuh-packages/issues/2539#issuecomment-17774 …
> Firewall validation in the installation assistant

- stack/dashboard/base/builder.sh
|---|
|https://github.com/wazuh/wazuh-dashboard-plugins/issues/5893|
This pull request fixes the navigation of home button to the home application (`wz-home`).
> Fix home button navigation on click

- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1958|
The aim of this PR is to improve the fetching of the network host value of the `opensearch.yml` file of the `passwords_getNetworkHost` function. If a commented line like `#network.host: "XXX.XXX.XXX.XXX"` was included in the file, and the function fetched it.
With this change, these kinds of lines are ignored.
The testing is in: https://github.com/wazuh/wazuh-packages/issues/1958#issuecomment-1780875983
> Fixed fetching network host in Password tool

- unattended_installer/install_functions/installMain.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1874|
The aim of this PR is to change the help of the Installation Assistant, specifically the Oflline download part. The `<deb|rpm>` value can lead to misunderstandings, so the options are split into two.
Also, the related PR has been opened in the `wazuh-documentation` repository: https://github.com/wazuh/wazuh-documentation/pull/6686
> Changed offline download in Assistant help

- unattended_installer/passwords_tool/passwordsFunctions.sh
Related issue: https://github.com/wazuh/wazuh-packages/issues/2503
The aim of this PR is to modify the changes done in https://github.com/wazuh/wazuh-packages/pull/2558. This PR changes the owner and the permissions of the new created folder `/etc/wazuh-indexer/internalusers-backup`. Without this changes, if the Wazuh indexer is restarted, it generated the following error because it does not have the correct owner and permissions:
```console
Exception in thread "main" org.opensearch.bootstrap.BootstrapException: java.nio.file.AccessDeniedException: /etc/wazuh-indexer/internal_users_backup
```
The following testing has been performed to ensure that the change is correct.
This test consist in generating an internal users backup, check the permissions and owners, and try to restart the …
> Fixed `internalusers-backup` directory owner and permissions

- alpine/build_package.sh
- alpine/builder.sh
- arch/build.sh
- arch/generate_arch_package.sh
- debs/build.sh
- rpms/build.sh
|---|
|#2409|
In this pull request, the '--future' flag also updates the package version in wazuh-control.
After generating a package with the --future flag and installing it, run:
`
/var/ossec/bin/wazuh-control info -v
`
`
[root@9ff26f398fb8 /]# /var/ossec/bin/wazuh-control info -v
v4.30.0
`
> Update future version on wazuh-control script

- debs/SPECS/wazuh-manager/debian/rules
- rpms/SPECS/wazuh-manager.spec
|---|
|#2499|
This issue aims to add support for Python 3.10 on Wazuh Manager packages (deb/rpm)
> Add Python 3.10 support

- unattended_installer/common_functions/common.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/install_functions/installVariables.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1493|
The aim of this PR is to add the YUM lock logic and improve the APT lock logic into the Wazuh Installation Assistant. This PR modifies the Installation Assistant with a check of the YUM and APT lock. If the lock exists, a message is generated and a retry code has been added.
The following tests have been performed. They are red because the Wazuh dashboard package for 4.8.0 does not work currently, but no errors were generated installing packages:
Ubuntu Focal: https://ci.wazuh.info/job/Test_unattended/4598
Ubuntu Bionic: https://ci.wazuh.info/job/Test_unattended/4597
<details><summary>:green_circle: CentOS 7</summary>
```console
[root@centos7 vagrant]# bash wazuh-install.sh -a -i
02/11/2023 17:37:41 INFO: Starting …
```
> APT and YUM lock logic added to WIA

- stack/indexer/deb/debian/rules
- stack/indexer/rpm/wazuh-indexer.spec
- unattended_installer/config/indexer/roles/action_groups.yml
- unattended_installer/config/indexer/roles/roles.yml
- unattended_installer/config/indexer/roles/roles_mapping.yml
|---|
| #2552  |
A new role has been added to grant ISM API permissions, required by the app to upload the ISM policy for auto-rollover. It's mapped to the `kibanaserver` internal user by default.
A new file has been created: `action_groups.yml`, used to group all permissions required by the ISM API.
Check the following:
```bash
curl -X GET https://<indexer_url>:9200/_plugins/_ism/explain/wazuh-alerts-* -k -u "kibanaserver:<password>"
```
> Add new role to grant ISM API permissions

- stack/indexer/base/builder.sh
- stack/indexer/deb/debian/rules
- stack/indexer/rpm/wazuh-indexer.spec
|---|
|related https://github.com/wazuh/internal-devel-requests/issues/425|
It was necessary to move the place where the new scripts are copied so that they are in the base, this is necessary for the implementation in wazuh-docker
<details>
<summary>Centos 7</summary>
```console
[root@centos-7 ~]# yum localinstall -y /home/vagrant/wazuh-indexer-4.8.0-40800.x86_64.rpm 
Examining /home/vagrant/wazuh-indexer-4.8.0-40800.x86_64.rpm: wazuh-indexer-4.8.0-40800.x86_64
Marking /home/vagrant/wazuh-indexer-4.8.0-40800.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package wazuh-indexer.x86_64 0:4.8.0-40800 will be installed
--> Finished Dependency Resolution
Dependencies Resolved …
```
> Moved ISM scripts from package to base

- stack/indexer/indexer-ism-init.sh
|---|
| #2583 |
This PR fixes a small bug when using the `-i` option of the `indexer-ism-init.sh` script.
It also adds the possibility of using a custom value for the policy. 
```
bash indexer-ism-init.sh -a 30d -d 1000 -i 192.168.56.10 -s 5 -p SecretPassword -P 1
Parameters:
-a|--min-index-age: 30d
-d|--min-doc-count: 1000
-i|--indexer-hostname: 192.168.56.10
-p|--indexer-password: SecretPassword
-P|--priority: 1
-s|--min-shard-size: 5
Global variable:
- INDEXER_URL: https://192.168.56.10:9200/
- C_AUTH: -u admin:SecretPassword
Constants:
- POLICY_NAME: rollover_policy
- ISM_INDEX_PATTERNS: ["wazuh-alerts-*", "wazuh-archives-*", "-wazuh-alerts-4.x-sample*"]
```
```
bash indexer-ism-init.sh                                                            
Parameters: …
```
> Fix bug with `-i` option

- unattended_installer/install_functions/installCommon.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2574|
The aim of this PR is to add the logic in the Wazuh Installation Assitant to check the removal of the central components. If the removal is not done correctly, a warning message is generated.
In case of RPM-based system, some new code has been added. In https://github.com/wazuh/wazuh-packages/issues/1493 it was observed that the YUM lock blocks the command, so it is necessary to check the YUM lock before the removal and the check of the package.
Some testing has been performed in https://github.com/wazuh/wazuh-packages/issues/2574#issuecomment-1803660683.
> Wazuh central components removal is now checked

- unattended_installer/install_functions/indexer.sh
|---|
|closes https://github.com/wazuh/internal-devel-requests/issues/425|
The execution of the indexer-ism-init.sh script is added to AIO installations and distributed to the installation assistant.
AIO: https://github.com/wazuh/internal-devel-requests/issues/425#issuecomment-1799521457
Distributed: https://github.com/wazuh/internal-devel-requests/issues/425#issuecomment-1801788574
> Add ISM script in installation assistant

- stack/indexer/indexer-init.sh
- stack/indexer/indexer-security-init.sh
|---|
| https://github.com/wazuh/internal-devel-requests/issues/425 |
This PR extends the `indexer-init.sh` script to accept arguments. The children scripts (`indexer-security-init.sh` and `indexer-ism-init.sh`) receive only the arguments that they accept / need.
This fixes the problem described in https://github.com/wazuh/internal-devel-requests/issues/425#issuecomment-1804171066.
Moreover, now the `indexer-ism-init.sh` script is only executed if the `indexer-security-init.sh` exits correctly (code 0). This is a requirement which was not handled before.
Test cases
1. Invalid arguments in `indexer-security-init.sh`
<details><summary>Details</summary>
<p>
```
bash /usr/share/wazuh-indexer/bin/indexer-init.sh -ho null
Executing Wazuh indexer security init script...
The given …
```
> Extend `indexer-init.sh` to accept arguments

- .github/actions/offline-installation/common.sh
- .github/workflows/offline-installation.yml
|---|
|Related https://github.com/wazuh/internal-devel-requests/issues/440|
This pull request updates the script used to initialize the Wazuh indexer cluster using the new script and adds the `workflow_dispatch` to the offline installation workflow
- https://github.com/wazuh/wazuh-packages/pull/2591/checks
> Update the initialize cluster script in the offline installation workflow

- unattended_installer/builder.sh
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/2604|
Updated Filebeat module version to 0.3
<details>
<summary>Installation</summary>
```console
root@ubuntu20:~# git clone https://github.com/wazuh/wazuh-packages.git
Cloning into 'wazuh-packages'...
remote: Enumerating objects: 57380, done.
remote: Counting objects: 100% (453/453), done.
remote: Compressing objects: 100% (258/258), done.
remote: Total 57380 (delta 225), reused 357 (delta 178), pack-reused 56927
Receiving objects: 100% (57380/57380), 16.86 MiB | 8.47 MiB/s, done.
Resolving deltas: 100% (36008/36008), done.
root@ubuntu20:~# cd wazuh-packages/
root@ubuntu20:~/wazuh-packages# git checkout change/2604-update-filebeat-module-to-03-version-in-unattended 
Branch …
```
> Updated Filebeat module version to 0.3

- stack/indexer/indexer-ism-init.sh
|---|
| https://github.com/wazuh/wazuh-indexer/issues/56 |
This PR fixes a bug in the ISM init script, and improves its logging to make it clearer and easier to debug.
See https://github.com/wazuh/wazuh-indexer/issues/56#issuecomment-1812818245
> Improve ISM init script

- .github/workflows/test-install-deb.yml
- .github/workflows/test-install-rpm.yml
- debs/SPECS/wazuh-manager/debian/postinst
- rpms/SPECS/wazuh-manager.spec
|---|
|https://github.com/wazuh/wazuh-jenkins/issues/5929|
This PR fixes a permissions discordance in the merged.mg files, when updating a manager using packages update. After this change, the merged.mg files will be set to `644` permissions.
<details>
<summary>Ubuntu22</summary>
```console
root@server-slave-ubu22:/home/vagrant# curl -sO https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.5.4-1_amd64.deb
root@server-slave-ubu22:/home/vagrant# dpkg -i wazuh-manager_4.5.4-1_amd64.deb 
Selecting previously unselected package wazuh-manager.
(Reading database ... 71284 files and directories currently installed.)
Preparing to unpack wazuh-manager_4.5.4-1_amd64.deb ...
Unpacking wazuh-manager (4.5.4-1) ...
Setting up wazuh-manager (4.5.4-1) ... …
```
> Added permissions change for merged.mg files in upgrade

- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/install_functions/installMain.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2616|
The aim of this PR is to remove the development related to the addition of the Wazuh dashboard PDF report dependencies of the Wazuh Installation Assistant.
With this change, the packages installed are reduced considerably. Testing is in: https://github.com/wazuh/internal-devel-requests/issues/493#issuecomment-1821232868
> Removed PDF report dependencies

- stack/dashboard/base/builder.sh
- stack/dashboard/base/generate_base.sh
- stack/dashboard/deb/build_package.sh
- stack/dashboard/deb/builder.sh
- stack/dashboard/deb/debian/rules
- stack/dashboard/rpm/build_package.sh
- stack/dashboard/rpm/builder.sh
- stack/dashboard/rpm/wazuh-dashboard.spec
- wazuhapp/opensearch-dashboards/Docker/Dockerfile
- wazuhapp/opensearch-dashboards/Docker/build.sh
- wazuhapp/opensearch-dashboards/generate_wazuh_app.sh
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/2589|
This pull request adapts the APP and Wazuh dashboard packages creation according to the new Wazuh plugins
See https://github.com/wazuh/wazuh-packages/issues/2589#issuecomment-1811347427
> Adapt wazuhapp and Wazuh dashboard to install the Wazuh CheckUpdates and Core plugins

- unattended_installer/builder.sh
- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/install_functions/installMain.sh
Due to https://github.com/wazuh/wazuh-packages/issues/2625, it is necessary to bump the 4.7.0 branch into the 4.7.1 branch to apply the Wazuh dashboard PDF dependencies removal.
> Merge 4.7.0 into 4.7.1

- unattended_installer/install_functions/installCommon.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2625|
The aim of this PR is to remove the remaining code of the [Wazuh dashboard PDF dependencies removal](https://github.com/wazuh/internal-devel-requests/issues/492).
This PR:
- Removes the unique occurrence of the `pdf_warning` variable.
- Improves the message of the CentOS GPG key import, removing the Chromium dependency mention.
With this, no code related to the PDF dependencies is in the Wazuh installation assistant.
> Improved message of CentOS key import failure

- debs/SPECS/wazuh-manager/debian/rules
- macos/package_files/build.sh
- rpms/SPECS/wazuh-manager.spec
|----|
|#2617|
Included new macOS 14 sonoma SCA files into packages scripts.
> Add SPECS to sca file macOS 14 sonoma

- .github/workflows/build-deb-packages.yml
- .github/workflows/build-rpm-packages.yml
- .github/workflows/test-install-deb.yml
- .github/workflows/test-install-rpm.yml
|---|
|https://github.com/wazuh/wazuh-packages/issues/2333|
This PR tests and solves the test fail problem when the development branch contains `/`.
To test this PR is mandatory to add a dummy commit that triggers the failing test in GH Actions, this dummy commit can simply add a whitespace in the `rpms/SPECS/wazuh-manager.spec` for test it in RPM and `debs/SPECS/wazuh-manager/debian/postinst` for DEB packages.
> Added package_release name modification

- unattended_installer/common_functions/common.sh
- unattended_installer/install_functions/installCommon.sh
|---|
|closes https://github.com/wazuh/wazuh-packages/issues/2638|
The place where the function is located is changed, to avoid errors in the different tools
```console
[root@centos-7 ~]# bash wazuh-install.sh -a
24/11/2023 18:00:26 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
24/11/2023 18:00:26 INFO: Verbose logging redirected to /var/log/wazuh-install.log
24/11/2023 18:00:30 INFO: --- Dependencies ---
24/11/2023 18:00:30 INFO: Installing lsof.
24/11/2023 18:00:47 INFO: Verifying that your system meets the recommended minimum hardware requirements.
24/11/2023 18:00:47 INFO: Wazuh web interface port will be 443.
24/11/2023 18:00:50 INFO: Wazuh development repository added.
24/11/2023 18:00:50 INFO: --- Configuration files ---
24/11/2023 18:00:50 INFO: …
```
> Changed check yum lock function

- .github/workflows/build-deb-packages.yml
- .github/workflows/build-rpm-packages.yml
- .github/workflows/test-install-deb.yml
- .github/workflows/test-install-rpm.yml
- aix/SPECS/wazuh-agent-aix.spec
- debs/SPECS/wazuh-agent/debian/changelog
- debs/SPECS/wazuh-agent/debian/copyright
- debs/SPECS/wazuh-manager/debian/changelog
- debs/SPECS/wazuh-manager/debian/copyright
- debs/SPECS/wazuh-manager/debian/postinst
- debs/SPECS/wazuh-manager/debian/rules
- macos/package_files/build.sh
- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
- stack/dashboard/deb/debian/changelog
- stack/dashboard/deb/debian/copyright
- stack/dashboard/rpm/wazuh-dashboard.spec
- stack/indexer/deb/debian/changelog
- stack/indexer/deb/debian/copyright
- stack/indexer/rpm/wazuh-indexer.spec
- unattended_installer/builder.sh
- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/install_functions/installMain.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2642|
This PR aims to merge branch 4.7.1 into 4.8.1.
> Merge 4.7.1 into 4.8.0

- stack/indexer/rpm/wazuh-indexer.spec
|--|
|[2637](https://github.com/wazuh/wazuh-packages/issues/2637)|
There was duplicate code stemming from a merge with a poorly resolved conflict.
The duplicated code is removed at https://github.com/wazuh/wazuh-packages/blame/v4.7.0/stack/indexer/rpm/wazuh-indexer.spec by deleting:
```bash
if [[ -d /run/systemd/system ]] ; then
rm -f /etc/init.d/%{name}
fi
if [ ${1} = 2 ]; then
if [ -d "%{INSTALL_DIR}"/plugins/opensearch-security/securityconfig ]; then
if [ ! -d "%{CONFIG_DIR}"/opensearch-security ]; then
mkdir "%{CONFIG_DIR}"/opensearch-security
fi
cp -r "%{INSTALL_DIR}"/plugins/opensearch-security/securityconfig/* "%{CONFIG_DIR}"/opensearch-security
fi
fi
```
https://github.com/wazuh/wazuh-packages/actions/runs/6979091415/job/18991690888?pr=2633
> Fixing wazuh-indexer.spec duplicated information

- stack/dashboard/base/builder.sh
|---|
|#2654|
This pull request collapses the application categories in the side menu of Wazuh dashboard.
> Screenshot taken from built of Wazuh dashboard 4.8.0 without dashboard plugins
> Collapse initially the application categories in the side menu of Wazuh dashboard

- wpk/linux/x86_64/Dockerfile
|---|
|#2668 |
This PR upgrade botocore dependency. This change is motivated by a unstable state of aws in the docker container used for the construction of the WPK packages. More information in https://github.com/wazuh/wazuh-packages/issues/2668
> [!NOTE]  
> Tasks and ECR were already upgraded with this change
> Upgrade botocore dependency in WPK package Docker containers

- unattended_installer/install_functions/installVariables.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2663|
The aim of this PR is to remove the `gnupg` package as a dependency of the Wazuh installation assistant in RPM-based systems. This package is not used neither in the installation nor in the Wazuh functionality.
Some automatic testing:
:green_circle: CentOS 7. https://ci.wazuh.info/job/Test_unattended/4715/
:green_circle: CentOS 8. https://ci.wazuh.info/job/Test_unattended/4714/
:green_circle: AL2. https://ci.wazuh.info/job/Test_unattended/4713/
:green_circle: RHEL 7. https://ci.wazuh.info/job/Test_unattended/4716/
:green_circle: RHEL 8. https://ci.wazuh.info/job/Test_unattended/4712/
A manual testing has been performed in:
> Removed `gnupg` package as RPM dependency in WIA

- unattended_installer/common_functions/common.sh
- unattended_installer/install_functions/installCommon.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2686|
The aim of this PR is to fix the 4.8.0 WIA. This PR adds the `common_checkAptLock` function which was missing from https://github.com/wazuh/wazuh-packages/pull/2648/files#diff-31d5f1eaa91b837b7f91a80dbee9b531e84575ff1fcc23280e484ef223b7cadaL183-L196
Testing is in: https://github.com/wazuh/wazuh-packages/issues/2686#issuecomment-1853664169
Automatic testing:
:green_circle: CentOS 8 https://ci.wazuh.info/job/Test_unattended/4719/
:green_circle: CentOS 7 https://ci.wazuh.info/job/Test_unattended/4718/
:green_circle: Ubuntu 18 https://ci.wazuh.info/job/Test_unattended/4720/
:green_circle: Ubuntu 16 https://ci.wazuh.info/job/Test_unattended/4721/
:green_circle: Ubuntu 20 https://ci.wazuh.info/job/Test_unattended/4722/ …
> Added `common_checkAptLock` function

- debs/SPECS/wazuh-agent/debian/rules
- debs/SPECS/wazuh-manager/debian/rules
- rpms/SPECS/wazuh-manager.spec
|---|
|https://github.com/wazuh/wazuh-packages/issues/2280|
This PR adds the necessary changes to include the new SCA policies in the SPECS for Debian 12.
<details><summary>Manager</summary>
**Manager package build:** https://ci.wazuh.info/job/Packages_builder/176215
**Package installation:**
```
root@debian-12:/home/vagrant# dpkg -i wazuh-manager_4.7.2-1_amd64.deb 
Selecting previously unselected package wazuh-manager.
(Reading database ... 30470 files and directories currently installed.)
Preparing to unpack wazuh-manager_4.7.2-1_amd64.deb ...
Unpacking wazuh-manager (4.7.2-1) ...
Setting up wazuh-manager (4.7.2-1) ...
```
**SCA file found:**
```
root@debian-12:/home/vagrant# cat /var/ossec/ruleset/sca/cis_debian
cis_debian10.yml.disabled  cis_debian7.yml.disabled …
```
> Add Debian12 SCA to SPECS

- .github/actions/offline-installation/common.sh
- unattended_installer/builder.sh
Related: https://github.com/wazuh/internal-devel-requests/issues/599
Related: https://github.com/wazuh/internal-devel-requests/issues/596
The aim of this PR is to update the Filebeat module version to 0.4 in the Wazuh installation assistant.
Also, the Filebeat module version has been updated in the Offline GitHub Action.
To test this change, the Wazuh stack has been deployed using the `wazuh-single.yml` playbook.
<details><summary>:green_circle: Show log</summary>
```console
root@ubuntu22:/home/vagrant# bash wazuh-install.sh -a -v
18/12/2023 15:23:38 DEBUG: Checking root permissions.
18/12/2023 15:23:38 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
18/12/2023 15:23:38 INFO: Verbose logging redirected to /var/log/wazuh-install.log
18/12/2023 15:23:38 DEBUG: APT package …
```
> Updated Filebeat module version to 0.4 in WIA

- unattended_installer/builder.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2702|
Related PR: https://github.com/wazuh/wazuh-packages/pull/2676
Related issue: https://github.com/wazuh/wazuh-packages/issues/2674
The aim of this PR is to change how the `source_branch` variable is defined. Before, it used the `source_directory` variable which used the `git` command. This is supposed a problem in the CI processes and when executing the script from a directory other than the location of the repository of scripts.
It has been tested that the `source_branch` variable is correctly fetched and the WIA is built:
From `wazuh-ppackages/unattended_installer`:
```console
~/Wazuh/packages/unattended_installer > bash builder.sh -i -d pre-release
+++ dirname builder.sh
++ cd .
++ pwd -P
+ readonly …
```
> Fixed `source_branch` variable definition

- aix/SPECS/wazuh-agent-aix.spec
- debs/SPECS/wazuh-agent/debian/changelog
- debs/SPECS/wazuh-agent/debian/rules
- debs/SPECS/wazuh-manager/debian/changelog
- debs/SPECS/wazuh-manager/debian/rules
- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
- stack/dashboard/deb/debian/changelog
- stack/dashboard/rpm/wazuh-dashboard.spec
- stack/indexer/deb/debian/changelog
- stack/indexer/rpm/wazuh-indexer.spec
- unattended_installer/builder.sh
- unattended_installer/install_functions/installVariables.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2704|
This PR aims to merge branch 4.7.2 into 4.8.0.
> Merge 4.7.2 into 4.8.0

- stack/indexer/base/builder.sh
- stack/indexer/base/generate_base.sh
- stack/indexer/deb/build_package.sh
- stack/indexer/deb/debian/rules
- stack/indexer/rpm/build_package.sh
- stack/indexer/rpm/wazuh-indexer.spec
|---|
|Closes https://github.com/wazuh/wazuh-packages/issues/2697|
This pull request adds the Wazuh Filebeat template to the Wazuh indexer package
https://github.com/wazuh/wazuh-packages/issues/2697#issuecomment-1864832047
https://github.com/wazuh/wazuh-indexer/issues/83#issuecomment-1866114592
> Added wazuh-filebeat template to Wazuh indexer

- debs/SPECS/wazuh-manager/debian/postinst
|---|
|#2683 |
This PR improves the `postinst` script of the Debian manager package generation process to ensure that after an upgrade the ossec.conf file contains the Indexer configuration section.
If the existing `ossec.conf` does not have an Indexer configuration section then the default Indexer configuration is appended at the end of `ossec.conf` as part of a new `<ossec_conf>` block.
If the existing `ossec.conf` does have an Indexer configuration then no changes are done to the `ossec.conf`.
The package has been generated by running
```bash
% ./generate_debian_package.sh -b dev-14153-vulndet-refactor -t manager -a amd64 -j 8 --packages-branch dev-2683-fix-upgrade-config-failure
ft@ft-nb:~/wazuh/repos/wazuh-packages/debs/output$ ls -lh
total 116M
-rw-r--r-- 1 root root …
```
>  Ensure <indexer> config is present in ossec.conf after upgrade via deb package

- rpms/SPECS/wazuh-manager.spec
|---|
|Closes #2706|
This PR modifies the `rpm` generation script to ensure that after an upgrade the ossec.conf file contains the Indexer configuration section.
If the existing `ossec.conf` does not have an Indexer configuration section then the default Indexer configuration is appended at the end of `ossec.conf` as part of a new `<ossec_conf>` block.
If the existing `ossec.conf` does have an Indexer configuration then no changes are done to the `ossec.conf`.
The package has been generated by running
```bash
./generate_rpm_package.sh -b dev-14153-vulndet-refactor -t manager -a x86_64 -j 8 --packages-branch dev-2706-fix-rpm-upgrade-config-failure
```
```
$ sha256sum wazuh-manager-4.8.0-1.x86_64.rpm 
69f0f941283e6d2e4802f433603e4696bb83ee639b8cb7e61a831aa45b4f6fa9 …
```
>  Ensure <indexer> config is present in ossec.conf after upgrade via rpm

- stack/indexer/base/builder.sh
|---|
|Closes https://github.com/wazuh/wazuh-packages/issues/2722|
This PR fixes the Filebeat template URL in the Wazuh indexer base package
<details><summary>Install, configuration and cluster check logs</summary>
```
[root@centos7 vagrant]# yum localinstall wazuh-indexer-4.8.0-1.x86_64.rpm -y
Examining wazuh-indexer-4.8.0-1.x86_64.rpm: wazuh-indexer-4.8.0-1.x86_64
Marking wazuh-indexer-4.8.0-1.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package wazuh-indexer.x86_64 0:4.8.0-1 will be installed
--> Finished Dependency Resolution
Dependencies Resolved
========================================================================================================
Package                Arch            Version …
```
> Fixed Filebeat template URL in Wazuh indexer

- unattended_installer/builder.sh
|---|
|close https://github.com/wazuh/wazuh-packages/issues/2724|
The change made to obtain the version from the VERSION file is returned, it is necessary to take this parameter into account when performing branch bumps on GitHub
Ubuntu Jammy:
```console
vagrant@ubuntu22:~$ sudo bash wazuh-install.sh -a
27/12/2023 17:51:10 INFO: Starting Wazuh installation assistant. Wazuh version: 4.7.2
27/12/2023 17:51:10 INFO: Verbose logging redirected to /var/log/wazuh-install.log
27/12/2023 17:51:31 INFO: Wazuh web interface port will be 443.
27/12/2023 17:51:35 INFO: --- Dependencies ----
27/12/2023 17:51:35 INFO: Installing apt-transport-https.
27/12/2023 17:51:44 INFO: Wazuh development repository added.
27/12/2023 17:51:44 INFO: --- Configuration files ---
27/12/2023 17:51:44 …
```
> The change was reverted to obtain the Wazuh version of the VERSION file

- debs/SPECS/wazuh-manager/debian/postinst
- debs/SPECS/wazuh-manager/debian/rules
- debs/build.sh
- debs/generate_debian_package.sh
- rpms/SPECS/wazuh-manager.spec
- rpms/build.sh
- rpms/generate_rpm_package.sh
|---|
|[#20747](https://github.com/wazuh/wazuh/issues/20747)|
Adds the option to download the vulnerability detector content, compress it into a tar.xz file, add it to the installer, and unzip it at installation.
* New flag --download-content in DEB
* New flag  --download-content in RPM
* Generation DEB package successful
* Installation from DEB packages successful
* Generation RPM package successful
* Installation from RPM packages successful
> Add content database in RPM and DEB packages

- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2705|
The aim of this PR is to remove the double quotes in the Wazuh indexer node, specified at the `/etc/wazuh-indexer/openseach.yml` file, if they exist.
Testing is in: https://github.com/wazuh/wazuh-packages/issues/2705#issuecomment-1866604241
> Double quotes removed in Indexer IP

- unattended_installer/common_functions/common.sh
- unattended_installer/install_functions/checks.sh
- unattended_installer/install_functions/dashboard.sh
- unattended_installer/install_functions/filebeat.sh
- unattended_installer/install_functions/indexer.sh
- unattended_installer/install_functions/installCommon.sh
- unattended_installer/install_functions/installMain.sh
- unattended_installer/install_functions/manager.sh
- unattended_installer/install_functions/wazuh-offline-installation.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/1422|
The aim of this PR is to add the offline installation option to the Wazuh installation assistant. This option complements the offline download option. With this, the Installation Assistant can automatically:
- Download the Wazuh packages with an internet connection.
- Install Wazuh (AIO or distributed) without an internet connection.
Now, with the packages installed, the WIA can be used as follows:
- `bash wazuh-install.sh -a -of`. AIO offline installation 
- `bash wazuh-install.sh -wi <node> -of`. Wazuh indexer offline installation 
- `bash wazuh-install.sh -ws <node> -of`. Wazuh manager offline installation 
- `bash wazuh-install.sh -wd <node> -of`. Wazuh dashboard offline installation 
Complete testing is in: …
> Added offline installation feature to Installation Assistant

- stack/indexer/base/files/usr/lib/systemd/system/wazuh-indexer-performance-analyzer.service
- stack/indexer/deb/debian/rules
|---|
|closes #2321|
This PR Fixes the Execution path for the `wazuh-indexer-performance-analyzer` binary and service.
- Build and Install Indexer package
```
dh_builddeb
dpkg-deb --build debian/wazuh-indexer ..
dpkg-deb: building package `wazuh-indexer' in `../wazuh-indexer_4.8.0-1_amd64.deb'.
dpkg-genchanges -b >../wazuh-indexer_4.8.0-1_amd64.changes
dpkg-genchanges: binary-only upload (no source code included)
dpkg-source --after-build wazuh-indexer-4.8.0
dpkg-buildpackage: binary-only upload (no source included)
WARNING generated by debuild:
Making debian/rules executable!
Package wazuh-indexer_4.8.0-1_amd64.deb.sha512 added to /home/qa/Descargas/wazuh-packages/stack/indexer/deb/output.
Leyendo lista de paquetes... Hecho
E: Se ha suministrado el fichero no admitido …
```
> Fix `wazuh-indexer-performance-analyzer-cli` binary startup

- stack/indexer/indexer-ism-init.sh
|---|
| #2657 |
This PR fixes the `wazuh-indexer` ism plugin log location from `tmp` to `/var/log.`
- Build package and install package
```
chmod 644 debian/wazuh-indexer/DEBIAN/md5sums
chown 0:0 debian/wazuh-indexer/DEBIAN/md5sums
dh_builddeb
dpkg-deb --build debian/wazuh-indexer ..
dpkg-deb: building package `wazuh-indexer' in `../wazuh-indexer_4.8.1-1_amd64.deb'.
dpkg-genchanges -b >../wazuh-indexer_4.8.1-1_amd64.changes
dpkg-genchanges: binary-only upload (no source code included)
dpkg-source --after-build wazuh-indexer-4.8.1
dpkg-buildpackage: binary-only upload (no source included)
WARNING generated by debuild:
Making debian/rules executable!
Package wazuh-indexer_4.8.1-1_amd64.deb.sha512 added to /home/vagrant/wazuh-packages-enhancement-2657-fix-indexder-ism-log-path …
```
> Fix wazuh-indexer ism  plugin log file path

- ova/generate_ova.sh
- ova/wazuh_ovf_template
|---|
|https://github.com/wazuh/wazuh-packages/issues/2729|
The aim of this PR is to change the OVA description message. In VMWare Cloud Director it throws an error due to it exceeded 255 characters. Now, the new text is the following:
**Wazuh enhances security visibility in your infrastructure by monitoring endpoints at the operating system and application levels. Its capabilities include log analysis, file integrity monitoring, intrusion detection, and compliance monitoring.**
> Changed OVA description message

- debs/SPECS/wazuh-manager/debian/rules
- debs/build.sh
- debs/generate_debian_package.sh
- rpms/SPECS/wazuh-manager.spec
- rpms/build.sh
- rpms/generate_rpm_package.sh
Always download content, it's mandatory
|---|
|#2747|
Remove flag `--download-content` from `generate_debian_package.sh` and `generate_rpm_package.sh`.
By default, always download the content.
> Remove flag --download-content

- debs/SPECS/wazuh-manager/debian/control
- rpms/SPECS/wazuh-manager.spec
|---|
|#2731|
Now the package needs to download and decompress the database content. Added `xz` dependency in RPM and `xz-utils` in DEB.
> Add xz utils as requirement

- ova/Vagrantfile
|---|
|Related https://github.com/wazuh/wazuh-packages/issues/2744|
The `Vagrantbox` used for local build and the `AMI` used for Jenkins build are modified. With this, the OVA is built without the `/etc/redhat-release` file, allowing the `SCA` template to be configured correctly
Build locally: https://github.com/wazuh/wazuh-packages/issues/2744#issuecomment-1885014453
> Updated Vagrantbox for OVA build

- debs/SPECS/wazuh-manager/debian/rules
- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
|---|
|Closes #2765 |
This PR adds the necessary modifications to the SPECS to include the new Alma Linux 8 SCA policy.
<details><summary>Manager</summary>
**Manager package build:** https://ci.wazuh.info/job/Packages_builder/180311
**Package installation:**
```
[root@localhost vagrant]# yum install -y https://packages-dev.wazuh.com/warehouse/test/4.8/rpm/var/wazuh-manager-4.8.1-ol9.x86_64.rpm
Oracle Linux 9 BaseOS Latest  (x86_64)                                                                  2.6 MB/s |  18 MB     00:07    
Oracle Linux 9 Application Stream Packages (x86_64) …
```
> Include SCA policy for Oracle Linux 9 in SPECS

- unattended_installer/install_functions/installMain.sh
- unattended_installer/install_functions/manager.sh
- unattended_installer/passwords_tool/passwordsFunctions.sh
|---|
|close https://github.com/wazuh/wazuh/issues/21413|
A function is added to modify the ossec.conf adding the necessary parameters for the Vulnerability detection configuration
AIO: https://github.com/wazuh/wazuh/issues/21413#issuecomment-1894268410
Distributed (3 nodes for Wazuh indexer): https://github.com/wazuh/wazuh/issues/21413#issuecomment-1894408237
Distributed (1 node for Wazuh indexer): https://github.com/wazuh/wazuh/issues/21413#issuecomment-1894081252
> Added support for Vulnerability detection in WIA

- unattended_installer/install_functions/indexer.sh
|---|
|close https://github.com/wazuh/wazuh-packages/issues/2781|
This PR adds the necessary roll backs in the event of failures in the execution of the security admin and the ISM policy. This improves waiting time and makes it easier to debug the installation without having to wait for the WIA to move forward with the rest of the components.
```console
vagrant@bookworm:~$ sudo bash wazuh-install.sh -i -a
18/01/2024 19:02:41 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
18/01/2024 19:02:41 INFO: Verbose logging redirected to /var/log/wazuh-install.log
18/01/2024 19:02:45 WARNING: Hardware and system checks ignored.
18/01/2024 19:02:45 INFO: Wazuh web interface port will be 443.
18/01/2024 19:02:51 INFO: Wazuh development repository added.
18/01/2024 …
```
> Added roll back and exit in case the Wazuh indexer security admin fails

- unattended_installer/install_functions/checks.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2778|
This PR splits the CentOS and RHEL version check, because is needed to check different versions for each OS.
Centos 9:
```
[root@server1 wazuh-packages]# git checkout 2778-wia-accepts-centos-9-as-a-recommended-system
branch '2778-wia-accepts-centos-9-as-a-recommended-system' set up to track 'origin/2778-wia-accepts-centos-9-as-a-recommended-system'.
Switched to a new branch '2778-wia-accepts-centos-9-as-a-recommended-system'
[root@server1 wazuh-packages]# bash unattended_installer/builder.sh -i -d
[root@server1 wazuh-packages]# cd unattended_installer/
[root@server1 unattended_installer]# ls -ltr
total 216
-rw-r--r--. 1 root root   2397 Jan 18 13:11 Development-guide.md
drwxr-xr-x. 6 root root     73 Jan 18 13:11 …
```
> Split CentOS and RHEL check

- unattended_installer/install_functions/checks.sh
|---|
|#2612|
Add Amazon Linux 1 and Amazon Linux 2023 support in the distribution check script.
This is implemented by two scripts in different repositories.
a. wazuh/wazuh
b. wazuh/wazuh-packages
Therefore merge must be done "atomically".
> Adding support for Amazon Linux 1, 2, and 2023

- bump_version.py
|---|
|https://github.com/wazuh/wazuh-packages/issues/2728|
This PR updates the bump_version.py file to update the variable `source_branch` in the `/unattended_installer/builder.sh` file.
The issue requested to track the `installVariables.sh` file, but it's already done by the script.
When the script is executed the `Bumping version in unattended_installer/builder.sh` log appears and the source_branch variable contained is properly updated.
> Update `bump_version.py` to track new variables

- unattended_installer/common_functions/common.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2776|
The aim of this PR is to add a check to the Wazuh installation assistant that ensures that the sudo package is installed in the system. We found that in some systems, the sudo is not installed by default and it is necessary for the Wazuh installation.
However, it has not been included as a depenency. Therefore, if this tool is not installed the Wazuh installation is stopped informing with an error
```console
root@debian11sudo:/home/vagrant# bash wazuh-install.sh -a -i -v
29/01/2024 16:40:00 DEBUG: Checking root permissions.
29/01/2024 16:40:00 DEBUG: Checking sudo package.
29/01/2024 16:40:00 ERROR: The sudo package is not installed and it is necessary for the installation.
```
:green_circle: CentOS 8: …
> Added sudo check to WIA

- unattended_installer/cert_tool/certFunctions.sh
- unattended_installer/cert_tool/certMain.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2787|
The aim of this PR is to add more debug messages and information to the certificate creation process. We decided to silence the output of the commands because they produced so much noise. 
As compensation for this, more information has been added to the log in order to understand and follow the script execution, and also if an error is generated it will be displayed in the output.
**Without verbose option:**
```console
> bash wazuh-certs-tool.sh -A
23/01/2024 18:13:41 INFO: Generating the root certificate.
23/01/2024 18:13:41 INFO: Generating Admin certificates.
23/01/2024 18:13:42 INFO: Admin certificates created.
23/01/2024 18:13:42 INFO: Generating Wazuh indexer certificates.
23/01/2024 18:13:43 INFO: Wazuh …
```
> Improved certificates generation output when using WIA/WCT

- unattended_installer/common_functions/common.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2776|
Complementary PR of https://github.com/wazuh/wazuh-packages/pull/2801.
The aim of this PR is to silence the output of the sudo packages check. I noticed that, when the sudo package is installed, the output of the `command -v` command is displayed in the prompt.
```console
root@ubuntu22:/home/vagrant# bash wazuh-install.sh -g -v
01/02/2024 12:07:58 DEBUG: Checking root permissions.
01/02/2024 12:07:58 DEBUG: Checking sudo package.
/usr/bin/sudo
01/02/2024 12:07:58 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
```
With this change, the output is the following:
```console
root@ubuntu22:/home/vagrant# bash wazuh-install.sh -g -v
01/02/2024 15:31:52 DEBUG: Checking root permissions.
01/02/2024 …
```
> Silenced sudo package check

- rpms/SPECS/wazuh-manager.spec
|---|
|Closes #2791|
The objective is to include the installation of the wazuh-keystore tool, which will be located in the bin directory. This tool is essential for managing the keystore within the Wazuh environment.
This PR is related to [#21680](https://github.com/wazuh/wazuh/pull/21680) which complies with the necessary changes in https://github.com/wazuh/wazuh/
Centos test
```shell
[root@44fc8ae8f64c /]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8" …
```
> keystore tool RPM and DEB packages creation

- unattended_installer/install_functions/manager.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2794|
The aim of this PR is to fix this warning:
```console
2024/02/02 12:57:20 indexer-connector: WARNING: Error initializing IndexerConnector: No available server, we will try again after 60 seconds.
2024/02/02 12:58:20 indexer-connector: WARNING: Error initializing IndexerConnector: No available server, we will try again after 60 seconds.
2024/02/02 12:59:20 indexer-connector: WARNING: Error initializing IndexerConnector: No available server, we will try again after 60 seconds.
2024/02/02 13:00:20 indexer-connector: WARNING: Error initializing IndexerConnector: No available server, we will try again after 60 seconds.
2024/02/02 13:01:20 indexer-connector: WARNING: Error initializing IndexerConnector: No available …
```
> Fixed VD-indexer configuration in AIO deployment

- unattended_installer/common_functions/common.sh
- unattended_installer/install_functions/checks.sh
- unattended_installer/install_functions/installCommon.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2587|
The aim of this PR is to make the WIA use the `rpm` command instead of the `yum` command to check the installed packages. This avoids the use the `yum` command, which is slower than the RPM tool in this cases, avoids the use of the `grep` command, and avoids the YUM lock.
Testing is in: https://github.com/wazuh/wazuh-packages/issues/2587#issuecomment-1921081066
:green_circle: CentOS 8: https://ci.wazuh.info/job/Test_unattended/5206/
:green_circle: CentOS 7: https://ci.wazuh.info/job/Test_unattended/5205/
:green_circle: Ubuntu 18: https://ci.wazuh.info/job/Test_unattended/5207/
:green_circle: Ubuntu 16: https://ci.wazuh.info/job/Test_unattended/5208/
:green_circle: Ubuntu 20: …
> WIA uses `rpm` instead of `yum` in packages check 

- unattended_installer/cert_tool/certFunctions.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2815|
The aim of this PR is to remove a `debug` variable added in the Admin certificate generation. This generated the `++--++` output which was silenced in: https://github.com/wazuh/wazuh-packages/issues/2787.
Before:
```console
07/02/2024 13:18:27 INFO: Generating Admin certificates.
Generating RSA private key, 2048 bit long modulus
..................+++
..+++
```
After:
```console
09/02/2024 11:07:17 INFO: Generating Admin certificates.
09/02/2024 11:07:17 INFO: Generating Wazuh indexer certificates.
```
Complete log:
```console
[root@al2 vagrant]# cat /var/log/wazuh-install.log 
09/02/2024 11:07:12 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
09/02/2024 11:07:12 INFO: Verbose logging redirected …
```
> Removed debug variable in Admin certificate generation

- .github/workflows/build-rpm-packages.yml
- rpms/SPECS/wazuh-manager.spec
|---|
|wazuh/wazuh#21955|
This PR aims to move the Vulnerability Detection template `vd_states_template.json` from `/var/ossec/queue/indexer/` to a `templates` folder located in `/var/ossec/` and update its references.
Related PR for Wazuh-Wazuh: https://github.com/wazuh/wazuh/pull/21985
```console
root@ubuntu:/# ls /var/ossec/
active-response  agentless  api  backup  bin  etc  framework  integrations  lib  logs  queue  ruleset  stats  templates  tmp  var  wodles
root@ubuntu:/# ls /var/ossec/templates/
vd_states_template.json
```
The workflow `build-rpm-packages.yml` was modified in a way that it takes the wazuh build branch with the same name as the current PR. If there is no branch, then it will take the name it was using before.
This change was necessary because the …
> Move Vulnerability Detection Template to Templates Folder

- debs/SPECS/wazuh-manager/debian/control
- debs/SPECS/wazuh-manager/debian/postinst
- debs/SPECS/wazuh-manager/debian/rules
- rpms/SPECS/wazuh-manager.spec
|---|
|https://github.com/wazuh/wazuh/issues/21800|
Decompression will take place once the vulnerability scanner module has started to avoid decompression during installation.
These are the implementation that were reverted/modified
https://github.com/wazuh/wazuh-packages/pull/2695
https://github.com/wazuh/wazuh-packages/pull/2738  
- RPM package 
- DEB package
> Do not decompress .tar.xz file, remove xz dependency

- .github/actions/passwords-tool/tests-stack-success.sh
|---|
|#2818|
regarding the gihub-actions tests referred to in the related issue
the parser that interprets the `wazuh-passwords-tool.sh` output is corrected in `tests-stack-success.sh`
```shell
$ tests-stack-success.sh 
::group:: Change indexer password, password providing it.
19/02/2024 17:47:04 INFO: Updating the internal users.
19/02/2024 17:47:06 INFO: A backup of the internal users has been saved in the /etc/wazuh-indexer/internalusers-backup folder.
19/02/2024 17:47:06 INFO: Generating password hash
19/02/2024 17:47:28 WARNING: Password changed. Remember to update the password in the Wazuh dashboard, Wazuh server, and Filebeat nodes if necessary, and restart the services.
::endgroup::
::group:: Change indexer password without providing it.
::endgroup::
::group:: …
```
> Fix passwords parser

- unattended_installer/cert_tool/certFunctions.sh
|---|
|https://github.com/wazuh/wazuh-packages/issues/2837|
The aim of this PR is to fix the output generated in the certificate generation using the Wazuh certificates tool. The bug consisted in showing generated certificates when they were not created.
1. :green_circle: Testing the reported case:
```console
root@ubuntu221:/home/vagrant# cat config.yml 
nodes:
indexer:
- name: node-1
ip: "192.168.56.44"
root@ubuntu221:/home/vagrant# bash wazuh-certs-tool.sh -A
23/02/2024 12:50:27 INFO: Generating the root certificate.
23/02/2024 12:50:27 INFO: Generating Admin certificates.
23/02/2024 12:50:28 INFO: Admin certificates created.
23/02/2024 12:50:28 INFO: Generating Wazuh indexer certificates.
23/02/2024 12:50:28 INFO: Wazuh indexer certificates created. …
```
> Fixed certificates generation output

- stack/dashboard/base/builder.sh
|---|
|[#6483](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6483)|
This pull request aims to change the order of the `Dashboard management` menu category. This category must be the last one listed in the Wazuh Dashboard global menu.
- Check the the Dashboard Management menu is the last category of the Wazuh Dashboard menu
> Change dashboard management category order

- .github/workflows/test-install-deb.yml
- debs/SPECS/wazuh-agent/debian/control
- debs/SPECS/wazuh-agent/debian/rules
- debs/SPECS/wazuh-manager/debian/control
- debs/SPECS/wazuh-manager/debian/rules
- debs/build.sh
|---|
|#2871|
It is intended to implement the necessary changes to create the new symbol packages for manager and agent, which can be installed on the endpoint when appropriate.
tail of build output
```shell
.
.
.
Finished running lintian.
WARNING generated by debuild:                                                                                                                                                                                      
Making debian/rules executable!
+ deb_file=wazuh-agent_4.9.0-test-local                                                                                                                                                                            
+ symbols_deb_file=wazuh-agent-dbg_4.9.0-test-local …
```
> add debug symbols to DEBs packages

- rpms/SPECS/wazuh-agent.spec
- rpms/SPECS/wazuh-manager.spec
- rpms/build.sh
- rpms/generate_rpm_package.sh
|---|
|#2866|
It is intended to implement the necessary changes to create the new symbol packages for manager and agent, which can be installed on the endpoint when appropriate.
tail of build output `./generate_rpm_package.sh -b 4.9.0 --packages-branch 2866-add-debug-symbols-to-rpms -t agent `
```shell
.
.
.
Wrote: /build_wazuh/rpmbuild/SRPMS/wazuh-agent-4.9.0-1.src.rpm
Wrote: /build_wazuh/rpmbuild/RPMS/x86_64/wazuh-agent-4.9.0-1.x86_64.rpm
Wrote: /build_wazuh/rpmbuild/RPMS/x86_64/wazuh-agent-debuginfo-4.9.0-1.x86_64.rpm
Executing(%clean): /bin/sh -e /usr/local/var/tmp/rpm-tmp.KmjjIm
+ umask 022
+ cd /build_wazuh/rpmbuild/BUILD
+ cd wazuh-agent-4.9.0
+ rm -fr /build_wazuh/rpmbuild/BUILDROOT/wazuh-agent-4.9.0-1.x86_64
+ RPM_EC=0
++ jobs -p
+ exit 0
+ [[ no == \y\e\s ]]
+ [[ …
```
> Add debug symbols to RPMs packages

- debs/SPECS/wazuh-agent/debian/postinst
- debs/SPECS/wazuh-agent/debian/postrm
- debs/SPECS/wazuh-agent/debian/prerm
- rpms/SPECS/wazuh-agent.spec
- wpk/generate_wpk_package.sh
- wpk/run.sh
|---|
|https://github.com/wazuh/wazuh/issues/22522|
This PR modifies RPM and DEB scripts for Wazuh agent's packages.
The modifications make it possible to downgrade Wazuh to earlier versions, allowing to rollback upgrades or to undo transactions via package managers across more versions.
> Allow downgrades using RPM and DEB packages

- rpms/SPECS/wazuh-manager.spec
|---|
| wazuh/wazuh-jenkins#6363|
This PR updates the permissions of the directories used on the new vulnerability detector, following the required specifications:
- https://github.com/wazuh/wazuh-jenkins/issues/6363#issuecomment-2020546725
> Update VD file permissions

- hp-ux/generate_wazuh_packages.sh
- rpms/SPECS/wazuh-manager.spec
- rpms/build.sh
- stack/dashboard/base/builder.sh
- unattended_installer/install_functions/dashboard.sh
> Merge 4.8.2 into 4.9.0

- alpine/SPECS/wazuh-agent/wazuh-agent.pre-upgrade
- debs/SPECS/wazuh-agent/debian/postrm
- debs/SPECS/wazuh-agent/debian/preinst
- debs/SPECS/wazuh-agent/debian/prerm
- rpms/SPECS/wazuh-agent.spec
|---|
|https://github.com/wazuh/wazuh/issues/22670|
This PR makes a small improvement in the upgrade process of RPM, DEB and APK packages: it checks that Wazuh's installation folder exists prior to attempting an upgrade.
> Check Wazuh installation folder exists before upgrading

- .github/workflows/password-tool.yml
|---|
|#2901|
This PR aims to temporarily disable the tests for the password tool script, so that we prevent those checks from running in the PR, so that they are not displayed in :red_circle: due to the dashboard and indexer migration.
- The tests for the password tool script, located at the path 'unattended_installer/passwords_tool/**', have been commented out and therefore will not run.
> Prevent failed checks related to dashboard and indexer

- aix/SPECS/wazuh-agent-aix.spec
|---|
https://github.com/wazuh/wazuh-packages/issues/2878
||
It was found that Wazuh agent RPM package for AIX has a runtime dependency on bash that shows the following error during package installation on a clean AIX 6.1 TL9 requested to SiteOx
```bash
Preparing...                          ################################# [100%]
Updating / installing...
1:wazuh-agent-4.7.3-1              ################################# [100%]
/var/tmp/rpm-tmp.teEaab[40]: /var/ossec/tmp/src/init/register_configure_agent.sh:  not found
```
```
error: failed dependencies:
bash is needed by wazuh-agent-4.9.0-1
Retrieving http://packages-dev.wazuh.com/deps/aix/bash-4.4-4.aix6.1.ppc.rpm
wazuh-agent                 ##################################################
package wazuh-agent-4.9.0-1 …
```
> Add bash dependency to Wazuh agent RPM for AIX

- macos/package_files/postinstall.sh
- macos/package_files/preinstall.sh
The motivation behind this addition of messages is to have more information if a installation using pkg packages fails.
|---|
|https://github.com/wazuh/wazuh/issues/22671|
We add echo messages to the pre and post install scripts for macOS PKG packages in the hope of providing more information in case an installation or upgrade fails.
> Add echo messages in PKG's pre and post install scripts.

- stack/dashboard/base/builder.sh
|---|
|https://github.com/wazuh/wazuh-dashboard/issues/173|
This PR modifies the Wazuh Dashboard to select the `v7` theme as default instead of the `Next`. 
A package was built using the tools. Testing it, the correct theme was selected
> Set v7 theme as default

- stack/dashboard/rpm/wazuh-dashboard.spec
|---|
|closes #2942|
This PR adds `chown` and `chmod` statements to modify the ownership and permission of the wazuh dashboard  `CheckUpdates` and `Core` plugins for the RPM package.
> Added chown and chmod to wazuhCheckUpdates and wazuhCore plugins.

- solaris/solaris11/SPECS/template_agent.json
|---|
| #2689 |
Closes #2689. It modifies the Solaris11 SPEC file to include in the agents the latest modification of the Azure integration which separated the module in several files carried out in wazuh/wazuh#19576, which is expected to be released in 4.9.0.
Tested the modified package by creating a [Solaris11](https://packages-dev.wazuh.com/warehouse/test/4.9/solaris/i386/11/wazuh-agent_v4.9.0-2689.azure.refactor.v2-sol11-i386.p5p) package and installing it in a Solaris11 machine respectively. Everything worked as expected, as can be seen in the following output:
<details><summary>Package installation and file permissions</summary>
<p>
```bash
root@solaris11:~# pkg install -g wazuh-agent_v4.9.0-2689.azure.refactor.v2-sol11-i386.p5p  wazuh-agent …
```
> Add new Azure module files

- unattended_installer/install_functions/checks.sh
|---|
|https://github.com/wazuh/wazuh-qa/issues/5435|
The OS was added to the supported systems of the Installation assistant.
<details><summary>:green_circle: Installation log</summary>
```console
[root@ip-172-31-92-255 rocky]# bash wazuh-install.sh -a -v
29/05/2024 14:01:13 DEBUG: Checking root permissions.
29/05/2024 14:01:13 DEBUG: Checking sudo package.
29/05/2024 14:01:13 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
29/05/2024 14:01:13 INFO: Verbose logging redirected to /var/log/wazuh-install.log
29/05/2024 14:01:13 DEBUG: YUM package manager will be used.
29/05/2024 14:01:13 DEBUG: Checking system distribution.
29/05/2024 14:01:13 DEBUG: Detected distribution name: rocky
29/05/2024 14:01:13 DEBUG: Detected distribution version: 9
29/05/2024 …
```
> Added support for Rocky Linux 9.4 in Installation assistant
