debs/gen_permissions.sh
debs/generate_api_master.sh
debs/generate_wazuh_master.sh
rpms/generate_api_master.sh
rpms/generate_wazuh_master.sh

Prevents from running script if something went wrong, better to catch errors

Ensure to fail bash script on error

---

debs/SPECS/3.7.0/wazuh-agent/debian/postinst
debs/SPECS/3.7.0/wazuh-agent/debian/postrm
debs/SPECS/3.7.0/wazuh-agent/debian/preinst
debs/SPECS/3.7.0/wazuh-agent/debian/prerm
debs/SPECS/3.7.0/wazuh-agent/debian/rules
debs/SPECS/3.7.0/wazuh-api/debian/postinst
debs/SPECS/3.7.0/wazuh-api/debian/postrm
debs/SPECS/3.7.0/wazuh-api/debian/preinst
debs/SPECS/3.7.0/wazuh-api/debian/rules
debs/SPECS/3.7.0/wazuh-manager/debian/postinst
debs/SPECS/3.7.0/wazuh-manager/debian/postrm
debs/SPECS/3.7.0/wazuh-manager/debian/preinst
debs/SPECS/3.7.0/wazuh-manager/debian/prerm
debs/SPECS/3.7.0/wazuh-manager/debian/rules

Hi team,
in this PR I made all the following changes:
- Remove all the files from `/tmp/` #16.
- Remove all the files from `/usr/share/wazuh-*` #24.
- Fix the installation from conffiles #62.
- Improve the `remove` option for the manager and the agent in order to save the configuration files.
- Remove unnecessary messages while installing the agent and the manager.
Regards,
Braulio.

Several fixes for Debian specs for Wazuh v3.7.0

---

rpms/SPECS/3.7.0/wazuh-agent-3.7.0.spec
rpms/SPECS/3.7.0/wazuh-manager-3.7.0.spec

I added woodle docker folder to the SPEC 3.7.0, fix check files of RPM packages generation.

Added wodle docker folder

---

debs/SPECS/3.7.0/wazuh-api/debian/control
rpms/SPECS/3.7.0/wazuh-api-3.7.0.spec

Hi team,
this PR solves the issue #81.
Regards,
Braulio.

Fix dependency graph for Wazuh API package

---

README.md
debs/generate_debian_package.sh
rpms/generate_rpm_package.sh

Hi team,
In this PR, I will try to solve some problems of package generation.
I refactor the code of Debian and RPM packages generation getting more simple and homogeneous scripts, also I added -d parameter to set the destination path of the package.
I tested both script but I need double check.
Regards.

Refactor generation scripts and added destiny path to package

---

rpms/SPECS/3.7.1/wazuh-agent-3.7.1.spec
rpms/SPECS/3.7.1/wazuh-manager-3.7.1.spec

Hi team,
this PR fixes #103. The fix consists on using the `dist-detect.sh` script only when installing the package in order to build the `ossec.conf` file and nothing else. This fix the error `/var/tmp/rpm-tmp.5DHtUt: line 3: /var/ossec/packages_files/manager_installation_scripts/src/init/dist-detect.sh: No such file or directory`.
Then, in order to add the SELinux policy when upgrading without using the `dist-detect.sh` script, I've refactorized the code of the RPM specs and make it more simple by using the rpm macros.
Regards,
Braulio.

Fix the upgrade from 3.7.0 to 3.7.1

---

debs/SPECS/3.9.0/wazuh-api/debian/postrm
debs/SPECS/3.9.0/wazuh-api/debian/prerm

Hi team,
this PR solves https://github.com/wazuh/wazuh/issues/2409.
Best regards,
Braulio.

Remove spurious ps output during package upgrade 

---

README.md
debs/SPECS/3.9.0/wazuh-agent/debian/changelog
debs/SPECS/3.9.0/wazuh-api/debian/changelog
debs/SPECS/3.9.0/wazuh-manager/debian/changelog
debs/build.sh
debs/gen_permissions.sh
debs/generate_debian_package.sh
debs/generate_wazuh_debs.sh
rpms/SPECS/3.9.0/wazuh-agent-3.9.0.spec
rpms/SPECS/3.9.0/wazuh-api-3.9.0.spec
rpms/SPECS/3.9.0/wazuh-manager-3.9.0.spec
rpms/build.sh
rpms/generate_rpm_package.sh
rpms/generate_wazuh_rpm.sh

Hi team,
On this PR we have added license to Debian and RPM scripts.
Also we have fixed the changelog of Debian and RPM SPECs.
Regards.

Update changelogs and licenses

---

rpms/SPECS/3.9.0/wazuh-agent-3.9.0.spec
rpms/SPECS/3.9.0/wazuh-manager-3.9.0.spec

Hi team,
this PR closes #127.
Regards,
Braulio.

Install only needed configuration assessment files

---

rpms/SPECS/3.9.0/wazuh-manager-3.9.0.spec

Hi team,
This PR closes #140.
Best regards.

Remove duplicated files from %files section.

---

macos/package_files/3.10.0/build.sh
macos/package_files/3.10.0/postinstall.sh
macos/package_files/3.10.0/preinstall.sh
macos/package_files/3.9.1/build.sh
macos/package_files/3.9.1/postinstall.sh
macos/package_files/3.9.1/preinstall.sh

Hello team
This PR adds the latest changes on macOS packages to the wazuh-packages repository. 
Best regards, 
Alberto R

Updated macOS package files

---

aix/README.md
debs/README.md
macos/README.md
ova/README.md
rpms/README.md
solaris/packer/README.md
solaris/packer/package_generation/vagrant/Vagrantfile
solaris/packer/package_generation/vagrant/src/generate_packages.sh
solaris/solaris10/README.md
solaris/solaris10/generate_wazuh_packages.sh
solaris/solaris11/README.md
solaris/solaris11/SPECS/template_agent_v3.10.0.json
solaris/solaris11/SPECS/template_agent_v3.8.0.json
solaris/solaris11/SPECS/template_agent_v3.8.1.json
solaris/solaris11/SPECS/template_agent_v3.8.2.json
solaris/solaris11/SPECS/template_agent_v3.9.0.json
solaris/solaris11/SPECS/template_agent_v3.9.1.json
solaris/solaris11/SPECS/template_agent_v3.9.2.json
solaris/solaris11/generate_wazuh_packages.sh
solaris/solaris11/solaris_fix.py
solaris/solaris11/uninstall.sh
solaris/solaris11/wazuh-agent.mog-template
splunkapp/README.md
wazuhapp/README.md
wpk/README.md

Hello team,
This PR includes the Solaris 11 package generation in the wazuh-packages repository.
Best regards,
Daniel Folch

Publish Solaris 11 package generation

---

aix/SPECS/3.10.0/wazuh-agent-3.10.0-aix.spec
aix/SPECS/3.9.2/wazuh-agent-3.9.2-aix.spec

Hi team,
This PR closes #216 .
Tested on AIX 5:
Regards.

Fix AIX startup service

---

solaris/solaris10/generate_wazuh_packages.sh

Hello team
This PR closes #218. The fix consists of adding the flag `DISABLE_SHARED=yes` in the compilation stage. 
Best regards, 
Alberto R

Build Solaris 10 packages using static Wazuh library

---

aix/README.md
aix/generate_wazuh_packages.sh
hpux/README.md
hpux/generate_wazuh_packages.sh
macos/README.md
rpms/README.md
solaris/solaris10/README.md
solaris/solaris10/generate_wazuh_packages.sh
solaris/solaris11/README.md
solaris/solaris11/generate_wazuh_packages.sh
wpk/README.md

Hello team,
This PR fixes some mistakes in the readmes such as wrong script names and unifies the help function format for all the scripts.
Regards,
Daniel Folch

Fix errors  in READMEs and unify help functions

---

debs/SPECS/3.10.0/wazuh-api/debian/postrm

Tolerate this directory being a mount

---

aix/SPECS/3.10.0/wazuh-agent-3.10.0-aix.spec
aix/SPECS/3.9.4/wazuh-agent-3.9.4-aix.spec
debs/SPECS/3.10.0/wazuh-manager/debian/postinst
debs/SPECS/3.9.4/wazuh-manager/debian/postinst
rpms/SPECS/3.10.0/wazuh-agent-3.10.0.spec
rpms/SPECS/3.10.0/wazuh-manager-3.10.0.spec
rpms/SPECS/3.9.4/wazuh-agent-3.9.4.spec
rpms/SPECS/3.9.4/wazuh-manager-3.9.4.spec
solaris/solaris11/SPECS/template_agent_v3.10.0.json
solaris/solaris11/SPECS/template_agent_v3.9.4.json

Hi team,
This PR closes #236.
Regards.

Update file permissions of wazuh-packages

---

aix/SPECS/3.10.0/wazuh-agent-3.10.0-aix.spec
aix/SPECS/3.9.4/wazuh-agent-3.9.4-aix.spec
debs/SPECS/3.10.0/wazuh-agent/debian/postinst
debs/SPECS/3.10.0/wazuh-manager/debian/postinst
debs/SPECS/3.9.4/wazuh-agent/debian/postinst
debs/SPECS/3.9.4/wazuh-manager/debian/postinst
macos/package_files/3.10.0/postinstall.sh
macos/package_files/3.9.4/postinstall.sh
rpms/SPECS/3.10.0/wazuh-agent-3.10.0.spec
rpms/SPECS/3.10.0/wazuh-manager-3.10.0.spec
rpms/SPECS/3.9.4/wazuh-agent-3.9.4.spec
rpms/SPECS/3.9.4/wazuh-manager-3.9.4.spec

Hi team,
This PR closes #240. 
Regards.

Restore the permissions of the files after upgrading the packages

---

ova/Config_files/ossec.conf
ova/Libraries/elastic_functions.sh
ova/Libraries/wazuh_functions.sh
ova/generate_ova.sh
ova/provision.sh

Hello team,
This PR closes #244 and #243 , in this PR I have that we detected with the ova.
I have tested the changes generating:
Regards, 
Daniel Folch

Fix minor issues in OVA

---

debs/generate_debian_package.sh
rpms/generate_rpm_package.sh
splunkapp/generate_wazuh_splunk_app.sh
wazuhapp/generate_wazuh_app.sh

Hello team,
This PR closes #200 and #199 by removing the -q and --single-branch from the git clone orders.
To test this I have generated the corresponding packages and checked if the had the proper version.
Regards, 
Daniel Folch

Enhance git clone orders

---

aix/generate_wazuh_packages.sh
debs/generate_debian_package.sh
macos/generate_wazuh_packages.sh
rpms/generate_rpm_package.sh
splunkapp/generate_wazuh_splunk_app.sh
wazuhapp/generate_wazuh_app.sh
wpk/generate_wpk_package.sh

Hello team,
This PR closes #203 By adding some checks to the generation scripts of:
- RPM
- DEB
- AIX
- SPLUNKAPP
- WAZUHAPP
- WPK
When parsing the arguments.
Regards,
Daniel Folch

Add conditional checks on script parameters 

---

ova/Config_files/ossec.conf

Hi team,
This PR closes #257.
Regards.

Fix Authd configuration file

---

.gitignore
ova/Libraries/elastic_functions.sh
ova/generate_ova.sh

Hello team,
This PR closes #271, by changing adding the correct URL to the filebeat module.
I have also changed some brackets that still used bash syntax instead of sh.
Regards,
Daniel Folch

Fix filebeat module in  OVA

---

aix/SPECS/3.10.0/wazuh-agent-3.10.0-aix.spec
aix/SPECS/3.11.0/wazuh-agent-3.11.0-aix.spec
debs/SPECS/3.10.0/wazuh-agent/debian/postrm
debs/SPECS/3.10.0/wazuh-agent/debian/prerm
debs/SPECS/3.10.0/wazuh-manager/debian/postrm
debs/SPECS/3.11.0/wazuh-agent/debian/postrm
debs/SPECS/3.11.0/wazuh-manager/debian/postrm
debs/SPECS/3.11.0/wazuh-manager/debian/prerm
rpms/SPECS/3.10.0/wazuh-agent-3.10.0.spec
rpms/SPECS/3.10.0/wazuh-manager-3.10.0.spec
rpms/SPECS/3.11.0/wazuh-agent-3.11.0.spec
rpms/SPECS/3.11.0/wazuh-manager-3.11.0.spec

Hi team, 
This PR closes #277. 
Tests:

Remove lingering files from packages

---

debs/SPECS/3.10.0/wazuh-agent/debian/rules
debs/SPECS/3.10.0/wazuh-manager/debian/rules
debs/SPECS/3.11.0/wazuh-agent/debian/rules
debs/SPECS/3.11.0/wazuh-manager/debian/rules
macos/package_files/3.10.0/build.sh
macos/package_files/3.11.0/build.sh
rpms/SPECS/3.10.0/wazuh-agent-3.10.0.spec
rpms/SPECS/3.10.0/wazuh-manager-3.10.0.spec
rpms/SPECS/3.11.0/wazuh-agent-3.11.0.spec
rpms/SPECS/3.11.0/wazuh-manager-3.11.0.spec

Hi team,
This PR closes #295 by including the new file SCA files for macOS. The changes are also ported to the RPM and Deb packages.
Regards.

Fix macOS SCA files inconsistency

---

solaris/solaris10/checkinstall.sh
solaris/solaris10/generate_wazuh_packages.sh

Hello team, 
This PR closes #296, I have changed the `checkinstall.sh` file so it produces the right output.
Best regards,
Daniel Folch

Solaris10 SPARC wrong installation output

---

ova/generate_ova.sh
ova/provision.sh

Hello team,
This PR closes #310.
To solve the issue I have added a few lines that stop the services.
Regards,
Daniel Folch

Stop services before exporting OVA 

---

solaris/solaris10/generate_wazuh_packages.sh

Closes https://github.com/wazuh/wazuh-packages/issues/330

Remove DISABLED_SHARED from Solaris 10 intel package generation

---

debs/SPECS/3.11.0/wazuh-manager/debian/postinst
rpms/SPECS/3.11.0/wazuh-manager-3.11.0.spec

Closes https://github.com/wazuh/wazuh-packages/issues/334

Fix vulnerability detector permissions

---

debs/SPECS/3.11.0/wazuh-manager/debian/postinst
debs/SPECS/3.12.0/wazuh-manager/debian/postinst
rpms/SPECS/3.11.0/wazuh-manager-3.11.0.spec
rpms/SPECS/3.12.0/wazuh-manager-3.12.0.spec

Change `msu.json` to `msu.json.gz`

Update deb post-install and rpm SPECS for Vulnerability Detector

---

aix/SPECS/3.11.0/wazuh-agent-3.11.0-aix.spec
aix/SPECS/3.12.0/wazuh-agent-3.12.0-aix.spec

Hello team
This PR aims to fix the upgrade problem in AIX with `rpm -U`. 
Best regards, 
Alberto R

Service stop fix AIX upgrades

---

debs/SPECS/3.11.2/wazuh-api/debian/postinst
debs/SPECS/3.12.0/wazuh-api/debian/postinst

Hi team,
This PR closes #375 by checking if the configuration files exist before copying them to the final destination.
Regards.

Fixed reinstall issues after configuring the api

---

rpms/CentOS/6/i386/Dockerfile
rpms/CentOS/6/x86_64/Dockerfile
rpms/build.sh
rpms/generate_rpm_package.sh

Hi team,
This issue closes #367. All the details can be found in the issue's comments.
Regards.

Add FIPS support for generic RPM package

---

aix/SPECS/3.12.0/wazuh-agent-3.12.0-aix.spec
rpms/SPECS/3.12.0/wazuh-manager-3.12.0.spec
solaris/solaris11/SPECS/template_agent_v3.12.0.json

Hi team,
This PR closes #389.
Regards.

Added new queue/fim directory to manager and agents specs

---

aix/README.md
debs/README.md
hp-ux/README.md
macos/README.md
ova/README.md
rpms/README.md
solaris/README.md
splunkapp/README.md
wazuhapp/README.md
windows/README.md
wpk/README.md

There are some URLs broken in our readmes. This PR aims to fix them.

Fix documentation urls

---

aix/SPECS/3.12.0/wazuh-agent-3.12.0-aix.spec
debs/SPECS/3.12.0/wazuh-agent/debian/changelog
debs/SPECS/3.12.0/wazuh-api/debian/changelog
debs/SPECS/3.12.0/wazuh-manager/debian/changelog
rpms/SPECS/3.12.0/wazuh-agent-3.12.0.spec
rpms/SPECS/3.12.0/wazuh-api-3.12.0.spec
rpms/SPECS/3.12.0/wazuh-manager-3.12.0.spec

Hello team,
This PR adds the missing versions to the 3.12.0 changelog.
Regards,
Daniel Folch

Add missing versions to 3.12.0 changelog

---

debs/SPECS/3.12.1/wazuh-agent/debian/changelog
debs/SPECS/3.12.1/wazuh-api/debian/changelog
debs/SPECS/3.12.1/wazuh-manager/debian/changelog
debs/SPECS/3.13.0/wazuh-agent/debian/changelog
debs/SPECS/3.13.0/wazuh-api/debian/changelog
debs/SPECS/3.13.0/wazuh-manager/debian/changelog

Hello team,
This PR fixes a problem in the changelog of the Debian spec files.
Regards,
Daniel Folch

Remove extra space from debian 3.12.1 and 3.13.0 changelog file

---

rpms/amzn/2/aarch64/Dockerfile
rpms/generate_rpm_package.sh

Tested with the wazuh-agent
`./generate_rpm_package.sh -b v3.11.3 -t agent -a aarch64`
Successfully builds and installs in my testing.

Package build for aarch64 on Amazon Linux 2

---

aix/SPECS/3.13.0/wazuh-agent-3.13.0-aix.spec
debs/SPECS/3.13.0/wazuh-agent/debian/changelog
debs/SPECS/3.13.0/wazuh-agent/debian/copyright
debs/SPECS/3.13.0/wazuh-api/debian/changelog
debs/SPECS/3.13.0/wazuh-api/debian/copyright
debs/SPECS/3.13.0/wazuh-manager/debian/changelog
debs/SPECS/3.13.0/wazuh-manager/debian/copyright
rpms/SPECS/3.13.0/wazuh-agent-3.13.0.spec
rpms/SPECS/3.13.0/wazuh-api-3.13.0.spec
rpms/SPECS/3.13.0/wazuh-manager-3.13.0.spec

This PR adds the specs files to build Wazuh 3.13.0

Add specs files to build Wazuh 3.13.0

---

debs/Debian/amd64/Dockerfile

Hi team,
This PR closes #430.
Regards

Fixed deb_builder_arm64 Docker image

---

debs/generate_debian_package.sh
rpms/generate_rpm_package.sh

This PR is required to build ARM packages using Jenkins.

Add -z parameter to rpm/deb build

---

wazuhapp/Docker/build.sh

Hello team,
We have fixed Kibana app package building, now we need to download elastic/kibana repository in order to generate all required plugin data.
Regards.

Added Kibana repository on app package generation

---

wazuhapp/Docker/Dockerfile
wazuhapp/Docker/build.sh

Hi team,
This PR closes #441 by previously downloading the `package.json` to set different variables and then, using them to download Wazuh's and Kibana's repository.
Regards.

Fixed build stage when using a branch instead of a tag

---

debs/Debian/amd64/Dockerfile
debs/Debian/arm64/Dockerfile
debs/Debian/armhf/Dockerfile
debs/Debian/i386/Dockerfile
debs/Debian/ppc64le/Dockerfile
rpms/CentOS/5/i386/docker_builder.sh
rpms/CentOS/5/x86_64/Dockerfile
rpms/CentOS/6/i386/Dockerfile
rpms/CentOS/6/x86_64/Dockerfile
rpms/CentOS/7/aarch64/Dockerfile
rpms/CentOS/7/armv7hl/build_deps.sh
rpms/CentOS/7/ppc64le/Dockerfile

Hello team,
This PR closes #471 
We have added CMake to all our Debian and RPM building containers in order to generate packages with DBSync support on manager side.
Regards!.

Added CMake to all containers

---

rpms/SPECS/4.0.0/wazuh-agent-4.0.0.spec
rpms/SPECS/4.0.0/wazuh-manager-4.0.0.spec

Hi team,
This PR solves an issue detected while testing the upgrade from 3.x to 4.0.0 packages using RPM packages for Linux OS.
Regards.

Ensure wazuh-services are stopped before upgrading the package

---

debs/SPECS/4.0.0/wazuh-manager/debian/postrm
debs/SPECS/4.0.0/wazuh-manager/debian/prerm

Hi team,
This PR fixes an issue related to the removal of the package. The postrm script failed while trying to back up the configuration files of the API. Now, this issue is solved.
Regards.

Fix the backup and removal of API files

---

splunkapp/Docker/build.sh
wazuhapp/Docker/build.sh

Hello team,
We want to change the Kibana and Splunk package name, we have also changed the way of add revision to such package.
Regards!.

Modify Kibana and Splunk package names and revision

---

.github/ISSUE_TEMPLATE/default.md
.github/pull_request_template.md
CHANGELOG.md

Hi team,
This PR adds a CHANGELOG file to this repository. Previously, this file didn't exist and it was difficult to track any changes in the Wazuh binary packages.
This PR closes #74.
Regards.

Added CHANGELOG.md file, issue and PR templates to the repository

---

debs/SPECS/4.0.0/wazuh-manager/debian/preinst

|---|
|closes #485  |
Hi team,
While testing @jmv74211 found the wazuh-manager .deb package for 4.0.0 didn't properly back up the shared configuration files. This PR fixes that.
```shellsession
root@988f34cba210:/# vim /opt/ossec/etc/shared/default/agent.conf
root@988f34cba210:/# md5sum /opt/ossec/etc/shared/default/agent.conf
b777c54e84c2cecf9d3eb682f7731b03  /opt/ossec/etc/shared/default/agent.conf
root@988f34cba210:/# apt install -y ./pkg/output/wazuh-manager_4.0.0-1_amd64.deb
Building dependency tree
Note, selecting 'wazuh-manager' instead of './pkg/output/wazuh-manager_4.0.0-1_amd64.deb'
Suggested packages:
expect
The following packages will be upgraded:
wazuh-manager
1 upgraded, 0 newly installed, 0 to …
```

[Development] Fixed the shared configuration files backup before upgrade

---

wpk/generate_wpk_package.sh
wpk/run.sh

|---|
|#496|
Hello team, 
This PR closes #496, we have replaced the `git clone` command with `curl`, this will avoid git related problems in the future.

Fix clone problem in WPK generation

---

debs/SPECS/4.0.0/wazuh-agent/debian/changelog
debs/SPECS/4.0.0/wazuh-manager/debian/changelog
debs/SPECS/4.1.0/wazuh-agent/debian/changelog
debs/SPECS/4.1.0/wazuh-manager/debian/changelog

Hello team,
This PR fixes an error in the 4.0.0 and 4.1.0 Debian packages changelog.
Regards,
Daniel Folch

Fix errors in deb changelog

---

ova/Libraries/automatic_set_ram.sh
ova/provision.sh

Hello team,
This PR closes #456 
I have changed the provision script in ova generation. Now it creates a cron daemon that changes elasticsearch jvm.options to update the heap size to the actual ram of the system.

Changes in ova provision

---

debs/SPECS/4.0.0/wazuh-agent/debian/postinst
debs/SPECS/4.0.0/wazuh-agent/debian/postrm
debs/SPECS/4.0.0/wazuh-agent/debian/preinst
debs/SPECS/4.0.0/wazuh-agent/debian/prerm
debs/SPECS/4.0.0/wazuh-manager/debian/postinst
debs/SPECS/4.0.0/wazuh-manager/debian/postrm
debs/SPECS/4.0.0/wazuh-manager/debian/preinst
debs/SPECS/4.0.0/wazuh-manager/debian/prerm
debs/SPECS/4.1.0/wazuh-agent/debian/postinst
debs/SPECS/4.1.0/wazuh-agent/debian/postrm
debs/SPECS/4.1.0/wazuh-agent/debian/preinst
debs/SPECS/4.1.0/wazuh-agent/debian/prerm
debs/SPECS/4.1.0/wazuh-manager/debian/postinst
debs/SPECS/4.1.0/wazuh-manager/debian/postrm
debs/SPECS/4.1.0/wazuh-manager/debian/preinst
debs/SPECS/4.1.0/wazuh-manager/debian/prerm
rpms/SPECS/4.0.0/wazuh-agent-4.0.0.spec
rpms/SPECS/4.0.0/wazuh-manager-4.0.0.spec
rpms/SPECS/4.1.0/wazuh-agent-4.1.0.spec
rpms/SPECS/4.1.0/wazuh-manager-4.1.0.spec

|---|
|https://github.com/wazuh/wazuh-packages/issues/506|
Closes https://github.com/wazuh/wazuh-packages/issues/506
Improves preinstall script for rpm packages by adding an alternative when service nor systemctl are not available.  Also fix a wrong error redirection. 
https://devel.ci.wazuh.info/job/Packages_builder/3735/
https://devel.ci.wazuh.info/job/Packages_builder/3734/
https://devel.ci.wazuh.info/job/Packages_builder/3733/
https://devel.ci.wazuh.info/job/Packages_builder/3732/
https://devel.ci.wazuh.info/job/Packages_builder/3731/

Improve service handling on specs scripts

---

.gitignore
solaris/packer/scripts/solaris/postinstall.sh
solaris/packer/solaris10.json
solaris/packer/solaris11_3.json

Closes https://github.com/wazuh/wazuh-packages/issues/511

Required changes on Solaris vagrant box generation.

---

debs/SPECS/4.0.1/wazuh-agent/debian/preinst
debs/SPECS/4.0.1/wazuh-manager/debian/preinst
debs/SPECS/4.1.0/wazuh-agent/debian/preinst
debs/SPECS/4.1.0/wazuh-manager/debian/preinst
rpms/SPECS/4.0.1/wazuh-agent-4.0.1.spec
rpms/SPECS/4.0.1/wazuh-manager-4.0.1.spec
rpms/SPECS/4.1.0/wazuh-agent-4.1.0.spec
rpms/SPECS/4.1.0/wazuh-manager-4.1.0.spec

|---|
| #517 |
Hi team,
This PR closes #517 by improving the checks to detect if the Wazuh daemons' are running or not. Then, if and only if the daemons are running, the temporary file used in the postinstall to start the daemons will be created.
```shellsession
[root@869cdb3c124f /]# yum install -y openssl wazuh-manager
Loaded plugins: fastestmirror, ovl
* base: mirror.librelabucm.org
* extras: mirror.tedra.es
* updates: mirror.tedra.es
Resolving Dependencies
--> Running transaction check
---> Package openssl.x86_64 1:1.0.2k-19.el7 will be installed
--> Processing Dependency: make for package: 1:openssl-1.0.2k-19.el7.x86_64
---> Package wazuh-manager.x86_64 0:3.13.2-1 will be installed
--> Processing Dependency: /sbin/service for …
```

Fix services' autostart when the manager is stopped

---

debs/SPECS/4.0.1/wazuh-manager/debian/postinst

|---|
|#515|
Hello team, 
This PR adds the changes in https://github.com/wazuh/wazuh-packages/pull/516 to the 4.0.1 SPECS.
Regards,
Daniel Folch

Change ssl cert permissions in 4.0.1 SPECS

---

debs/build.sh
debs/generate_debian_package.sh
rpms/build.sh
rpms/generate_rpm_package.sh

|---|
|wj1844|
Hello team,
This PR modifies the way the variable LOCAL_SOURCE_CODE is passed to the entrypoint of the docker image.
Regards,
Daniel Folch

Modify USE_LOCAL_SOURCE_CODE variable

---

ova/Libraries/provision-opendistro.sh

|---|
|https://github.com/wazuh/wazuh-jenkins/issues/1967|
Hi team,
This PR closes https://github.com/wazuh/wazuh-jenkins/issues/1967 by fixing the URL selector for the `wazuh-kibana` package and it also updates the Kibana certificates used to set up https access.

Fix wazuh_kibana package url and update Kibana certificates

---

ova/provision.sh

Added Welcome message to the OVA that provides direct information to access the web interface.
Using the `/etc/issue` file the OVA once run will provide the user with a Wazuh welcome message as well as the address to access the Kibana Web Interface.
Making the OVA even easier to use.

Added OVA welcome message

---

solaris/package_generation/Vagrantfile

|---|
| #498  |
Hello team,
We have fixed the links to download the latest Solaris10 and Solaris11 boxes.
Regards

Fix Solaris boxes URLs

---

debs/SPECS/4.1.0/wazuh-agent/debian/rules
debs/SPECS/4.1.0/wazuh-manager/debian/postinst
debs/SPECS/4.1.0/wazuh-manager/debian/rules
solaris/solaris11/SPECS/template_agent_v4.1.0.json

|---|
|#536|
Hi team, 
This PR introduces the changes for Debian and Solaris 11 packages.
NA

Add new SCA files for Debian and Solaris packages

---

rpms/SPECS/4.1.0/wazuh-agent-4.1.0.spec
rpms/SPECS/4.1.0/wazuh-manager-4.1.0.spec

|---|
|#536|
Hi team,
This PR introduces the changes for RPM packages.
NA

Add new SCA files to RPM SPECS

---

solaris/package_generation/Vagrantfile

|---|
| https://github.com/wazuh/wazuh-jenkins/issues/1721 |
Hello team,
We want to add CMake special boxes to our Solaris deployment process.
Regards.

Allow to deploy CMake special boxes

---

aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
solaris/solaris11/SPECS/template_agent_v4.2.0.json
solaris/solaris11/SPECS/template_agent_v5.0.0.json

|---|
| #562  |
Hi team,
This PR closes #562 by renaming the binaries and adding the necessary changes in the `%files` section of RPM packages. Also, it updates the changelogs of the packages.
NA

Rename Wazuh daemons

---

debs/SPECS/4.1.0/wazuh-manager/debian/postinst
debs/SPECS/4.1.0/wazuh-manager/debian/preinst
debs/SPECS/4.2.0/wazuh-manager/debian/postinst
debs/SPECS/4.2.0/wazuh-manager/debian/preinst
debs/SPECS/5.0.0/wazuh-manager/debian/postinst
debs/SPECS/5.0.0/wazuh-manager/debian/preinst
rpms/SPECS/4.1.0/wazuh-manager-4.1.0.spec
rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec

Hi team,
This PR updates the 4.1.0, 4.2.0, and 5.0.0 specs to match the changes done in `v4.1.0-alpha1`.
NA

Update global.db perms and removed rootcheck directory

---

debs/SPECS/4.2.0/wazuh-agent/debian/rules
debs/SPECS/4.2.0/wazuh-manager/debian/rules
debs/SPECS/5.0.0/wazuh-agent/debian/rules
debs/SPECS/5.0.0/wazuh-manager/debian/rules
macos/package_files/4.2.0/build.sh
macos/package_files/5.0.0/build.sh
rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec

|---|
| https://github.com/wazuh/wazuh-packages/issues/572 |
This pull request implements all the necessary changes for the epic https://github.com/wazuh/wazuh/issues/6898. For more details, check the description of the issue https://github.com/wazuh/wazuh-packages/issues/572.

Migration of the wazuh ruleset to the wazuh repository - Packages modifications implementation

---

debs/SPECS/4.2.0/wazuh-agent/debian/rules
debs/SPECS/4.2.0/wazuh-manager/debian/rules
debs/SPECS/5.0.0/wazuh-agent/debian/rules
debs/SPECS/5.0.0/wazuh-manager/debian/rules
macos/package_files/4.2.0/build.sh
macos/package_files/5.0.0/build.sh
rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec

Hi all,
This reverts the merge of #573. It must be merged lately, once the changes in wazuh/wazuh and other repositories are finished.

Revert 573-dev-deprecate-ruleset

---

aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
solaris/solaris11/SPECS/template_agent_v4.2.0.json

Hello team,
This PR adds the logcollector directory to RPM Spect. It must be add when merge PR number [6890](https://github.com/wazuh/wazuh/pull/6890)
Best regards,
Eva

Add directory logcollector to SPECs

---

debs/SPECS/4.0.4/wazuh-manager/debian/postinst
debs/SPECS/4.0.4/wazuh-manager/debian/preinst

Hi team,
This PR backports the changes from #592 to the v4.0.4 specs.

Back port changes from #592

---

debs/SPECS/4.2.0/wazuh-agent/debian/rules
debs/SPECS/4.2.0/wazuh-manager/debian/rules
debs/SPECS/5.0.0/wazuh-agent/debian/rules
debs/SPECS/5.0.0/wazuh-manager/debian/rules
macos/package_files/4.2.0/build.sh
macos/package_files/5.0.0/build.sh
rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec

|---|
|Related wazuh core issue: [#7266](https://github.com/wazuh/wazuh/issues/7266)|
Changes needed to get PR checks up and running
PR checks: https://github.com/wazuh/wazuh/pull/7281/checks

[7266] cmake min version update - wazuh core

---

debs/SPECS/4.2.0/wazuh-agent/debian/rules
debs/SPECS/4.2.0/wazuh-manager/debian/rules
debs/SPECS/5.0.0/wazuh-agent/debian/rules
debs/SPECS/5.0.0/wazuh-manager/debian/rules
macos/package_files/4.2.0/build.sh
macos/package_files/5.0.0/build.sh
rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec

|Related wazuh/wazuh PR|
|---|
|[#7037](https://github.com/wazuh/wazuh/pull/7037)|

Cis apple macos 11.01

---

debs/SPECS/5.0.0/wazuh-agent/debian/postinst
debs/SPECS/5.0.0/wazuh-agent/debian/preinst
debs/SPECS/5.0.0/wazuh-agent/debian/prerm
debs/SPECS/5.0.0/wazuh-agent/debian/rules
debs/SPECS/5.0.0/wazuh-manager/debian/postinst
debs/SPECS/5.0.0/wazuh-manager/debian/preinst
debs/SPECS/5.0.0/wazuh-manager/debian/prerm
debs/SPECS/5.0.0/wazuh-manager/debian/rules
macos/package_files/5.0.0/postinstall.sh
macos/package_files/5.0.0/preinstall.sh
rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
solaris/solaris11/SPECS/template_agent_v5.0.0.json

Hi all,
This PR updates the specs for Wazuh 5.0 with the latest changes from 4.2.
Regards.

Port the changes from Wazuh 4.2.x to 5.0

---

ova/provision.sh

This PR is a second iteration over the recently added MOTD ASCII art of the OVA.

2nd iteration over motd ASCII art

---

aix/SPECS/4.1.0/wazuh-agent-4.1.0-aix.spec
aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
debs/SPECS/4.1.0/wazuh-manager/debian/preinst
debs/SPECS/4.2.0/wazuh-manager/debian/preinst
debs/SPECS/5.0.0/wazuh-manager/debian/preinst

|---|
||
Hello team, 
In this PR we fix some issues with the ossec-control calls in AIX and DEB preinstall scripts.
Regards,
Daniel Folch

Fix ossec-control calls in DEB and AIX SPECS

---

debs/SPECS/5.0.0/wazuh-agent/debian/postinst
debs/SPECS/5.0.0/wazuh-agent/debian/rules
debs/SPECS/5.0.0/wazuh-manager/debian/postinst
debs/SPECS/5.0.0/wazuh-manager/debian/rules
macos/package_files/5.0.0/postinstall.sh
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec

|---|
| #638 |
Added last CMake changes of 4.2 to 5.0.0 SPECs.
Regards.

Fix 5.0.0 SPECs (CMake requirement)

---

ova/Libraries/provision-opendistro.sh

|---|
| Closes #640 |
We have added some changes to the provision script `kibana/data` folder must be created with specific permission.

Fix Kibana provision script

---

ova/Libraries/provision-opendistro.sh

|---|
| Related #640 |
We have applied the same fix as https://github.com/wazuh/wazuh-packages/pull/641 to 4.1 branch.

Changed provision to kibana/data folder

---

macos/package_files/introduction.txt

This PR aims to improve the content and english of the message shown when you install the Wazuh agent in macOS.

Improve message in macOS installer

---

aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
debs/SPECS/4.2.0/wazuh-agent/debian/rules
debs/SPECS/4.2.0/wazuh-manager/debian/rules
debs/SPECS/5.0.0/wazuh-agent/debian/rules
debs/SPECS/5.0.0/wazuh-manager/debian/rules
hp-ux/generate_wazuh_packages.sh
macos/package_files/4.2.0/build.sh
macos/package_files/5.0.0/build.sh
rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
solaris/solaris10/generate_wazuh_packages.sh
solaris/solaris11/generate_wazuh_packages.sh
windows/entrypoint.sh
wpk/run.sh

|---|
| #644 |
We want to include the 4.1.1 changes into the master branch.
Tested in https://github.com/wazuh/wazuh-packages/pull/646 and https://github.com/wazuh/wazuh-packages/pull/645
Regards!.

Added TARGET selector in make deps

---

ova/Config_files/ossec.conf

|---|
| https://github.com/wazuh/wazuh-packages/issues/620 |
This PR implements all the necessary changes in the Wazuh packages to adapt the config tag to the new Wazuh naming standard. For more details check the **description** section of the Epic https://github.com/wazuh/wazuh-packages/issues/620.

Configuration tags normalization to Wazuh standard - Packages changes implementation

---

debs/SPECS/4.2.0/wazuh-manager/debian/preinst
debs/SPECS/5.0.0/wazuh-manager/debian/preinst

|---|
|closes #673 |
This issue fixes the problem described in issue #673

Fix problem with conditional for obtaining version in DEB packages

---

debs/SPECS/4.2.0/wazuh-manager/debian/rules
debs/SPECS/5.0.0/wazuh-manager/debian/rules
rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec

|---|
| closes #676  |
Hello team,
On this PR we apply the 4.1.3 SPEC changes to 4.2.0 and 5.0.0 SPECs
https://github.com/wazuh/wazuh/pull/7944/checks?check_run_id=2167453196
https://github.com/wazuh/wazuh/pull/7944/checks?check_run_id=2167499465
Regards!

Change SPECs to use Python 3.9

---

wazuhapp/Docker/Dockerfile
wazuhapp/Docker/build.sh

Hi team
Hi team, 
this adapt the new build options for Wazuh APP with the new Kibana platform (^7.10.0)

Wazuhapp update build script allow root hack

---

aix/SPECS/4.3.0/wazuh-agent-4.3.0-aix.spec
debs/SPECS/4.3.0/wazuh-agent/debian/rules
debs/SPECS/4.3.0/wazuh-manager/debian/rules
macos/package_files/4.3.0/build.sh
rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec

|---|
| #611 |
Adding changes of #652 to the latest created SPECs for 4.3.0.

Update 4.3.0 SPECS with latest Wazuh building changes

---

debs/SPECS/4.2.0/wazuh-agent/debian/postinst
debs/SPECS/4.2.0/wazuh-manager/debian/postinst
debs/SPECS/5.0.0/wazuh-agent/debian/postinst
debs/SPECS/5.0.0/wazuh-manager/debian/postinst

|Related PR|
|---|
|https://github.com/wazuh/wazuh-packages/pull/703|
This PR applies the changes done in #703 to branch 4.2.

Fix installdir replacement in localfile generation for Debs packages 4.2

---

ova/Libraries/provision-opendistro.sh

|---|
|#718|
This PR adds the changes in https://github.com/wazuh/wazuh-packages/pull/719 to `master`.

Changed name of opendistro_performance_analyzer plugin

---

aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
aix/generate_wazuh_packages.sh
solaris/solaris10/generate_wazuh_packages.sh
solaris/solaris11/generate_wazuh_packages.sh

|---|
| closes #725 |
Hi team,
Thanks to @Dwordcito for taking part in this issue and apply some fixes over AIX and SPARC scripts.
We have added modification to such scripts. with the CMake tool it produces some compilation errors at package generation time.
Regards!

Fix AIX and SPARC package generation script

---

aix/generate_wazuh_packages.sh

|---|
| Closes #738 |
Applied same fix as https://github.com/wazuh/wazuh-packages/pull/739
Regards.

Fix aix 6.1 checksum generation

---

macos/package_files/4.1.5/postinstall.sh

This PR aims to solve temporarily the problem described: https://github.com/wazuh/wazuh/issues/7793

macOS Bigsur upgrade alerts folder removal fix

---

aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
debs/SPECS/4.2.0/wazuh-agent/debian/changelog
debs/SPECS/4.2.0/wazuh-manager/debian/changelog
rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec

|---|
|Closes #693 |
This PR does the same as https://github.com/wazuh/wazuh-packages/pull/760 but adding the required changes to 4.2

Update  4.2 specs changelog

---

README.md

|---|
|Related https://github.com/wazuh/wazuh-packages/issues/765|
Hello team,
This PR add a branch section in Readme.

4.2 Branch section in readme

---

aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
aix/generate_wazuh_packages.sh
hp-ux/generate_wazuh_packages.sh
rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
solaris/solaris10/generate_wazuh_packages.sh
solaris/solaris11/SPECS/template_agent_v4.2.0.json
solaris/solaris11/generate_wazuh_packages.sh

Reverts wazuh/wazuh-packages#773

Revert "Dev footprint reduction"

---

aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
debs/Debian/amd64/Dockerfile
debs/SPECS/5.0.0/wazuh-agent/debian/postinst
debs/SPECS/5.0.0/wazuh-agent/debian/preinst
debs/SPECS/5.0.0/wazuh-agent/debian/prerm
debs/SPECS/5.0.0/wazuh-agent/debian/rules
debs/SPECS/5.0.0/wazuh-manager/debian/postinst
debs/SPECS/5.0.0/wazuh-manager/debian/postrm
debs/SPECS/5.0.0/wazuh-manager/debian/preinst
debs/SPECS/5.0.0/wazuh-manager/debian/prerm
debs/SPECS/5.0.0/wazuh-manager/debian/rules
macos/package_files/5.0.0/build.sh
macos/package_files/5.0.0/postinstall.sh
macos/package_files/5.0.0/preinstall.sh
macos/specs/5.x/wazuh-agent-5.0.0.pkgproj
rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
solaris/solaris10/postinstall.sh
solaris/solaris10/preinstall.sh
solaris/solaris11/SPECS/template_agent_v5.0.0.json
solaris/solaris11/generate_wazuh_packages.sh

Reverts wazuh/wazuh-packages#748

Revert "Rename Wazuh configuration files"

---

README.md

|---|
|Related https://github.com/wazuh/wazuh-packages/issues/765|
Hello team,
This PR add a branch section in Readme.

Legacy branch section in readme

---

rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec
solaris/solaris11/SPECS/template_agent_v4.3.0.json

This PR adds libwazuhshared.so to master branch specs.

Add libwazuhshared to master

---

debs/SPECS/4.2.0/wazuh-agent/debian/changelog
debs/SPECS/4.2.0/wazuh-manager/debian/changelog

This PR adds missing versions to 4.2.0 debian changelog.

Fix Debian 4.2.0 changelog

---

aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
debs/SPECS/5.0.0/wazuh-agent/debian/changelog
debs/SPECS/5.0.0/wazuh-agent/debian/postinst
debs/SPECS/5.0.0/wazuh-agent/debian/preinst
debs/SPECS/5.0.0/wazuh-agent/debian/rules
debs/SPECS/5.0.0/wazuh-manager/debian/changelog
debs/SPECS/5.0.0/wazuh-manager/debian/postinst
debs/SPECS/5.0.0/wazuh-manager/debian/preinst
debs/SPECS/5.0.0/wazuh-manager/debian/rules
hp-ux/generate_wazuh_packages.sh
macos/package_files/5.0.0/postinstall.sh
rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
solaris/solaris10/generate_wazuh_packages.sh
solaris/solaris11/generate_wazuh_packages.sh
solaris/solaris11/postinstall.sh

|---|
|Closes #803 |
This PR merges the changes from branches master and 4.2 into5.0-dev branch

Merge master changes into 5.0-dev

---

aix/SPECS/4.3.0/wazuh-agent-4.3.0-aix.spec
debs/SPECS/4.3.0/wazuh-agent/debian/changelog
debs/SPECS/4.3.0/wazuh-agent/debian/postinst
debs/SPECS/4.3.0/wazuh-agent/debian/preinst
debs/SPECS/4.3.0/wazuh-agent/debian/rules
debs/SPECS/4.3.0/wazuh-manager/debian/changelog
debs/SPECS/4.3.0/wazuh-manager/debian/postinst
debs/SPECS/4.3.0/wazuh-manager/debian/preinst
debs/SPECS/4.3.0/wazuh-manager/debian/rules
hp-ux/generate_wazuh_packages.sh
macos/package_files/4.3.0/postinstall.sh
rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec
solaris/solaris10/generate_wazuh_packages.sh
solaris/solaris11/generate_wazuh_packages.sh
solaris/solaris11/postinstall.sh

|---|
| #803 |
This PR merges the changes from branch 4.2 into 5.0-dev branch

Merge 4.2 master

---

rpms/SPECS/4.3.0/wazuh-agent-4.3.0.spec
rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec

|---|
|#808|
This PR adds the new `sca.file` templates for Fedora systems.

Add fedora sca.files templates

---

debs/SPECS/5.0.0/wazuh-agent/debian/rules
debs/SPECS/5.0.0/wazuh-manager/debian/postinst
debs/SPECS/5.0.0/wazuh-manager/debian/rules
rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
solaris/solaris11/SPECS/template_agent_v5.0.0.json

|---|
|https://github.com/wazuh/wazuh/issues/9180|
Remove deprecated/unnecessary files from rootcheck and sca.

Dev new directory layout remove sca rootcheck

---

aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec

|---|
|Closes #827|
Problems fixed in this  PR
- Warning messages that appeared when the package tried to copy sockets during installation.
```
cp: /var/ossec/queue/ossec/com: Operation not supported on socket
cp: /var/ossec/queue/ossec/logcollector: Operation not supported on socket
cp: /var/ossec/queue/ossec/queue: Operation not supported on socket
cp: /var/ossec/queue/ossec/syscheck: Operation not supported on socket
cp: /var/ossec/queue/ossec/upgrade: Operation not supported on socket
cp: /var/ossec/queue/ossec/wmodules: Operation not supported on socket
```
- Message indicating that `/var/ossec/queue/ossec` could not be removed on upgrade
```
cannot remove /var/ossec/queue/ossec - directory not empty
```
- Problem with the `%posttrans` section, which will not appear …

Fix AIX package issues

---

aix/SPECS/4.2.1/wazuh-agent-4.2.1-aix.spec
rpms/SPECS/4.2.1/wazuh-agent-4.2.1.spec
rpms/SPECS/4.2.1/wazuh-manager-4.2.1.spec
solaris/solaris11/SPECS/template_agent_v4.2.1.json

This PR updates the necessary specs for the new wodles files.

Update specs with new wodle files

---

resources/elastic-stack/unattended-installation/all-in-one-installation.sh
resources/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh
resources/open-distro/unattended-installation/all-in-one-installation.sh
resources/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
resources/open-distro/unattended-installation/distributed/wazuh-server-installation.sh
resources/open-distro/unattended-installation/unattended-installation.sh

|---|
|closes https://github.com/wazuh/wazuh-packages/issues/852|
This PR bump unattended resources from 4.2.1 to 4.2.2

Bump unattended resources to 4.2.2

---

CHANGELOG.md

|---|
||
This PR updates the changelog in 4.2 branch

Update changelog 4.2

---

.gitignore
README.md
aix/README.md
arch/Arch/Dockerfile
arch/README.md
arch/SPECS/4.2.0/wazuh-agent/arch/PKGBUILD
arch/SPECS/4.2.0/wazuh-agent/arch/wazuh.install
arch/SPECS/4.2.0/wazuh-agent/arch/wazuh.sysusers
arch/build.sh
arch/generate_arch_package.sh
debs/README.md
hp-ux/README.md
macos/README.md
ova/README.md
rpms/README.md
solaris/README.md
splunkapp/README.md
wazuhapp/README.md
windows/README.md

#593
This commit should allow building Arch packages.
I've added a building script, Dockerfile and SPECS for the current version (4.2.0)

Adding some support for Arch Linux agent

---

resources/open-distro/unattended-installation/unattended-installation.sh

|---|
|#890|
When running the unattended installation, a new file "-" is created containing the repo which is useless

Remove "-" from tee command stable branch

---

unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

|---|
||
This PR changes the resources link so it uses AWS instead of github.

Change unattended resources link 4.2

---

unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

|---|
||
This PR changes the resources link so it uses AWS instead of github.

Change resources link

---

rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec

|---|
|Closes #954|
This PR adds the new CDB list files to the packages.

Add new CDB lists to manager packages

---

CHANGELOG.md
debs/Debian/ppc64le/Dockerfile
debs/build.sh
debs/generate_debian_package.sh
rpms/CentOS/7/ppc64le/Dockerfile
rpms/generate_rpm_package.sh

|---|
| closes #914 |
Hello team,
We have improved the ppc64le support package generation and we updated the Debian dockerfile

Add ppc64le packages little improvements

---

unattended_scripts/elastic-stack/unattended-installation/all-in-one-installation.sh
unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh
unattended_scripts/elastic-stack/unattended-installation/distributed/wazuh-server-installation.sh
unattended_scripts/open-distro/tools/certificate-utility/wazuh-cert-tool.sh
unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
unattended_scripts/open-distro/unattended-installation/distributed/wazuh-server-installation.sh
unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

|---|
| #984 |
The logger was only called sometimes in the unattended scripts, so I changed all bad usages of 'echo' to 'logger'. I didn't change them for the help (-h) option as it didn't seem that was needed in any log.
I also changed the logger so it displays the date, hour, and type of message, using the same format as the wazuh logs.
The calls to wazuh-cert-tool and wazuh-password-tool don't appear to use the logger in the first log because they are downloaded from the repositories, but I added the logs of both as called from this branch
Unattended open-distro installation: 
```
[root@centos8 ~]# bash unattended-installation.sh 
11/10/2021 11:45:16 INFO: Starting the installation...
11/10/2021 11:45:16 INFO: Installing all necessary utilities for the installation... …
```

Corrected logger usage [4.2]

---

unattended_scripts/elastic-stack/unattended-installation/all-in-one-installation.sh
unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh
unattended_scripts/elastic-stack/unattended-installation/distributed/wazuh-server-installation.sh
unattended_scripts/open-distro/tools/certificate-utility/wazuh-cert-tool.sh
unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
unattended_scripts/open-distro/unattended-installation/distributed/wazuh-server-installation.sh
unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

|---|
| closes #984 |
The logger was only called sometimes in the unattended scripts, so I changed all bad usages of 'echo' to 'logger'. I didn't change them for the help (-h) option as it didn't seem that was needed in any log.
I also changed the logger so it displays the date, hour, and type of message, using the same format as the wazuh logs.
The calls to wazuh-cert-tool and wazuh-password-tool don't appear to use the logger in the first log because they are downloaded from the repositories, but I added the logs of both as called from this branch
Unattended open-distro installation: 
```
[root@centos8 ~]# bash unattended-installation.sh 
11/10/2021 11:45:16 INFO: Starting the installation...
11/10/2021 11:45:16 INFO: Installing all necessary utilities for the …
```

Corrected logger usage [master]

---

unattended_scripts/elastic-stack/unattended-installation/all-in-one-installation.sh
unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh
unattended_scripts/elastic-stack/unattended-installation/distributed/wazuh-server-installation.sh
unattended_scripts/open-distro/tools/certificate-utility/wazuh-cert-tool.sh
unattended_scripts/open-distro/tools/wazuh-passwords-tool.sh
unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
unattended_scripts/open-distro/unattended-installation/distributed/wazuh-server-installation.sh
unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

|---|
|  #984 |
The logger was only called sometimes in the unattended scripts, so I changed all bad usages of 'echo' to 'logger'. I didn't change them for the help (-h) option as it didn't seem that was needed in any log.
I also changed the logger so it displays the date, hour, and type of message, using the same format as the wazuh logs.
The calls to wazuh-cert-tool and wazuh-password-tool don't appear to use the logger in the first log because they are downloaded from the repositories, but I added the logs of both as called from this branch
Unattended open-distro installation: 
```
[root@centos8 ~]# bash unattended-installation.sh 
11/10/2021 11:45:16 INFO: Starting the installation...
11/10/2021 11:45:16 INFO: Installing all necessary utilities for the installation... …
```

Corrected logger usage [stable]

---

ova/assets/steps.sh

This PR fix the wazuh repository in the OVA, now the ova has the production repository instead of the development repository.

Fix ova repository 4.2

---

rpms/SPECS/4.4.0/wazuh-agent-4.4.0.spec
rpms/SPECS/4.4.0/wazuh-manager-4.4.0.spec

|---|
||
This PR fixes the date format in 4.4.0 rpm changelog

Fix 4.3 date in master branch

---

unattended_scripts/elastic-stack/kibana/7.x/kibana.yml
unattended_scripts/elastic-stack/kibana/7.x/kibana_all_in_one.yml
unattended_scripts/open-distro/kibana/7.x/kibana.yml
unattended_scripts/open-distro/kibana/7.x/kibana_all_in_one.yml
unattended_scripts/open-distro/kibana/7.x/kibana_unattended.yml
unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

This PR removes the telemetry message from UI.

Changed telemetry value to false

---

debs/SPECS/4.3.0/wazuh-manager/debian/postinst

| --- |
|[#1044](https://github.com/wazuh/wazuh-packages/issues/1044)|
Removed the line where the script was copied to /var/ossec for debugging. 

Remove restore-permissions.sh from Debian Packages

---

debs/SPECS/4.4.0/wazuh-manager/debian/postinst

| --- |
|[#1044](https://github.com/wazuh/wazuh-packages/issues/1044)|
Removed the line where the script was copied to /var/ossec for debugging. 

Removed cp restore-permissions.sh added for debugin To Master

---

unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

This PR fixes the download of the kibana.yml file and removes the command used to test it locally

Fix curl kibana.yml 4.2

---

unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

This PR fixes the download of the kibana.yml file and removes the command used to test it locally

Fix curl kibana.yml 4.3

---

unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

This PR fixes the download of the kibana.yml file and removes the command used to test it locally

Fix curl kibana.yml master

---

unattended_scripts/install_functions/opendistro/common.sh
unattended_scripts/install_functions/opendistro/kibana.sh

|---|
|Related to https://github.com/wazuh/wazuh-packages/issues/943|
- This PR fixes the modification to the kibana css to modify the login page. In addition, the files that were downloaded in `~` are cleaned, now the download is in `/tmp/`.
- A functionality is added to use the css stored in the repository (local) or in s3.
- A fix is added to add the wazuh repository whenever the development flag is used, in this way the problem that this file already exists is avoided. If it is uninstalled and reinstalled with the development flag, it will force the repository change
Before fix
After fix
<details><summary>Install before fix</summary>
```
[root@centos7 unattended_scripts]# bash wazuh_install.sh -a -l -d
12/15/2021 15:14:14 INFO: Configuration file found. Creating …
```

Fix kibana login page unify

---

unattended_scripts/install_functions/opendistro/elasticsearch.sh

|---|
|closes #1063 |
This PR adds the remediation for the log4j vulnerability to the unattended installer of wazuh.

Add log4j remediation

---

unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

Related https://github.com/wazuh/wazuh-packages/pull/1069
This PR adds mitigation of the vulnerability found in log4j to 4.2 branch. In addition, mitigation is added to the distributed unattended installation.

Add mitigation log4j 4.2

---

unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

Related https://github.com/wazuh/wazuh-packages/pull/1069
This PR adds mitigation to the vulnerability found in log4j.

Add log4j mitigation 4.3

---

unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

Related https://github.com/wazuh/wazuh-packages/pull/1069
This PR adds mitigation to the vulnerability found in log4j.

Add log4j mitigation master

---

unattended_scripts/install_functions/opendistro/common.sh
unattended_scripts/install_functions/opendistro/elasticsearch.sh
unattended_scripts/install_functions/opendistro/filebeat.sh
unattended_scripts/install_functions/opendistro/kibana.sh
unattended_scripts/install_functions/opendistro/wazuh.sh
unattended_scripts/tools/wazuh-cert-tool.sh
unattended_scripts/tools/wazuh-passwords-tool.sh
unattended_scripts/wazuh_install.sh

|---|
| closes #865|
This PR adds a progress bar to the unattended installation. It only appears when no `-v|--verbose` option is specified on calling the installer. 
- The progress is counted with two variables. The variable `progressbar_total` is specified before each installation. The variable `progressbar_status` is updated on each of the big steps of the installation. 
- When more than one distributed option is called at the same time(for example: `bash wazuh_install.sh -c -e -en node1 -k` a progress bar for each of them is displayed.
- For the all-in-one installation, only one progress bar is displayed.
```
[root@centos7 unattended_scripts]# bash wazuh_install.sh -l -d -c -e -en node1 -k -w -wn wazuh1
12/16/2021 20:01:33 INFO: Configuration file found. Creating …
```

Add progress bar to unattended installation

---

unattended_scripts/install_functions/opendistro/common.sh
unattended_scripts/install_functions/opendistro/elasticsearch.sh
unattended_scripts/install_functions/opendistro/filebeat.sh
unattended_scripts/install_functions/opendistro/kibana.sh
unattended_scripts/install_functions/opendistro/wazuh.sh
unattended_scripts/wazuh_install.sh

This PR update `unify-config-yml` in order to make it mergeable.

Update unify config branch

---

unattended_scripts/install_functions/opendistro/common.sh
unattended_scripts/install_functions/opendistro/elasticsearch.sh
unattended_scripts/install_functions/opendistro/filebeat.sh
unattended_scripts/install_functions/opendistro/kibana.sh
unattended_scripts/install_functions/opendistro/wazuh-cert-tool.sh
unattended_scripts/install_functions/opendistro/wazuh.sh
unattended_scripts/wazuh_install.sh

|---|
| #1102 |
Added the option `-s|--start-cluster` to initialize the kibana cluster.

Added start cluster option to unattended

---

unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

|---|
||
This PR updates log4j version.

Update log4j version

---

unattended_scripts/install_functions/opendistro/common.sh
unattended_scripts/install_functions/opendistro/elasticsearch.sh
unattended_scripts/install_functions/opendistro/filebeat.sh
unattended_scripts/install_functions/opendistro/kibana.sh
unattended_scripts/install_functions/opendistro/wazuh-cert-tool.sh
unattended_scripts/install_functions/opendistro/wazuh.sh
unattended_scripts/wazuh_install.sh

|---|
||
Added the keyword `function` to all the functions in the installer. This is needed to create the unitary function tests using the tool https://bach.sh/

Added 'function' keyword to all functions in the installer

---

unattended_scripts/install_functions/opendistro/common.sh
unattended_scripts/install_functions/opendistro/elasticsearch.sh
unattended_scripts/install_functions/opendistro/filebeat.sh
unattended_scripts/install_functions/opendistro/kibana.sh
unattended_scripts/install_functions/opendistro/wazuh-cert-tool.sh
unattended_scripts/install_functions/opendistro/wazuh.sh
unattended_scripts/wazuh_install.sh

|---|
|#867|
This PR changes some output texts for the installer.

Make changes to help text and loggers output

---

unattended_scripts/install_functions/opendistro/common.sh

|---|
||
Fixes the calls to the logger in function checkPreviousCertificates

Fixes the calls to the logger in function checkPreviousCertificates

---

unattended_scripts/install_functions/opendistro/common.sh
unattended_scripts/install_functions/opendistro/kibana.sh
unattended_scripts/install_functions/opendistro/wazuh-cert-tool.sh
unattended_scripts/wazuh_install.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/1036|
- Fix checkOpenSSL, installPrerequisites, checkPreviousCertificates.
- Fix setupKibanacerts.
- Merge branch 'unify-unattended' into 1036-unattended-fix-openssl-install.

Unattended fix OpenSSL install

---

unattended_scripts/install_functions/opendistro/common.sh
unattended_scripts/install_functions/opendistro/wazuh-cert-tool.sh
unattended_scripts/wazuh_install.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/1036|
- Fix Creating certificates case
- Merge branch 'unify-unatteded-dev' into 1036-unattended-fix-dev-in-testing

Unattended fix dev in testing

---

.gitignore
unattended_installer/install_functions/opendistro/checks.sh
unattended_installer/install_functions/opendistro/common.sh
unattended_installer/install_functions/opendistro/wazuh-cert-tool.sh
unattended_installer/wazuh_install.sh

Internal improvements to `wazuh-install-improvements branch`

---

.gitignore
unattended_installer/README.md
unattended_installer/install_functions/opendistro/checks.sh
unattended_installer/install_functions/opendistro/common.sh
unattended_installer/install_functions/opendistro/elasticsearch.sh
unattended_installer/install_functions/opendistro/filebeat.sh
unattended_installer/install_functions/opendistro/kibana.sh
unattended_installer/install_functions/opendistro/wazuh-cert-tool.sh
unattended_installer/install_functions/opendistro/wazuh-passwords-tool.sh
unattended_installer/install_functions/opendistro/wazuh.sh
unattended_installer/wazuh_install.sh

|---|
||
This PR adds some improvements to the unattended install script.

Wazuh install improvements

---

unattended_installer/install_functions/opendistro/checks.sh
unattended_installer/install_functions/opendistro/common.sh
unattended_installer/install_functions/opendistro/wazuh-cert-tool.sh
unattended_installer/install_functions/opendistro/wazuh-passwords-tool.sh
unattended_installer/wazuh_install.sh

|---|
||
This PR fixes some issues with opensuse tumbleweed in the unattended installation.
```
localhost:/home/vagrant/wazuh-packages/unattended_installer # ./wazuh_install.sh -l -a -d -o
13/01/2022 15:50:02 INFO: Creating the Root certificate.
13/01/2022 15:50:02 INFO: Creating the Elasticsearch certificates.
13/01/2022 15:50:02 INFO: Creating the Wazuh server certificates.
13/01/2022 15:50:02 INFO: Creating the Kibana certificate.
13/01/2022 15:50:02 INFO: Generating random passwords.
13/01/2022 15:50:02 INFO: Configuration files created: /home/vagrant/wazuh-packages/unattended_installer/configurations.tar
13/01/2022 15:50:02 INFO: Starting all necessary utility installation.
13/01/2022 15:50:04 INFO: All necessary utility installation finished.
13/01/2022 15:50:04 …
```

Unify unattended tumbleweed

---

unattended_installer/install_functions/opendistro/common.sh
unattended_installer/wazuh_install.sh

|---|
||
This PR improves the treatment of errors after stoping the execution with contol+C
```
[root@centos repo]# ./wazuh_install.sh -l -a
13/01/2022 16:49:24 INFO: Creating the Root certificate.
13/01/2022 16:49:24 INFO: Creating the Elasticsearch certificates.
13/01/2022 16:49:24 INFO: Creating the Wazuh server certificates.
13/01/2022 16:49:24 INFO: Creating the Kibana certificate.
13/01/2022 16:49:25 INFO: Generating random passwords.
13/01/2022 16:49:25 INFO: Configuration files created: /home/vagrant/repo/configurations.tar
13/01/2022 16:49:25 INFO: Starting all necessary utility installation.
13/01/2022 16:49:25 INFO: All necessary utility installation finished.
13/01/2022 16:49:25 INFO: Adding the Wazuh repository.
^C
Do you want to clean the ongoing …
```

Unify unattended ctrl c

---

unattended_installer/README.md
unattended_installer/wazuh_install.sh

This PR adds diagrams to Readme and adds a Useful & acknowledgment section

Adding diagrams to readme

---

unattended_installer/install_functions/opendistro/checks.sh
unattended_installer/install_functions/opendistro/common.sh
unattended_installer/install_functions/opendistro/wazuh-passwords-tool.sh

|Related PR|
|---|
|https://github.com/wazuh/wazuh-packages/pull/1136|
Some small changes to fix small errors detected by the unit testing in checks.sh and common.sh

Fixed errors detected by the unit testing [checks.sh, common.sh]

---

tests/unattended/unit/suites/test-elasticsearch.sh
tests/unattended/unit/suites/test-kibana.sh
tests/unattended/unit/unit-tests.sh

closes https://github.com/wazuh/wazuh-packages/issues/1186
Used https://bach.sh/ to create unit tests for each function. In the directory tests/unattended there is a file called test-{script-name}.sh for each script in unattended installer. Inside that file are defined the unit tests for each function of {script-name}.sh. To call them we use the auxiliary script unit-test.sh, which creates a docker environment in which to run the tests.
Example of output:
```
[verdx@verdx unit]$ bash unit-tests.sh -f elasticsearch
20/01/2022 14:09:48 INFO: Docker image found.
20/01/2022 14:09:48 INFO: Unit tests for elasticsearch.sh.
1..15
ok 1 - configureElasticsearch dist one elastic node
ok 2 - ASSERT FAIL initializeElasticsearch error connecting
ok 3 - copyCertificatesElasticsearch
ok 4 - …
```

Unit testing using Bach [elasticsearch.sh]

---

tests/unattended/install/pytest.ini
tests/unattended/install/test_unattended.py

|---|
|https://github.com/wazuh/wazuh-jenkins/issues/3138|
This PR updates the unattended install tests to work with AIO and distributed install.

Unattended install tests update

---

arch/generate_arch_package.sh

|---|
|Related #1191 |
This PR adds the parameter --packages-branch to the help message and include a check to force the use of the  
--branch and --packages-branch parameters before building the package.
- Tests for ArchLinux

Fix archlinux package generation parameters 4.2

---

arch/generate_arch_package.sh

|---|
|Related #1191 |
This PR adds the parameter --packages-branch to the help message and include a check to force the use of the  
--branch and --packages-branch parameters before building the package.
- Tests for ArchLinux

Fix archlinux package generation parameters master

---

tests/unattended/unit/suites/test-checks.sh
tests/unattended/unit/suites/test-common.sh
tests/unattended/unit/suites/test-elasticsearch.sh
tests/unattended/unit/suites/test-filebeat.sh
tests/unattended/unit/suites/test-kibana.sh

Fixed tests after merging two branches with conflicts

Fixed tests 

---

tests/unattended/unit/suites/test-kibana.sh

Fix a kibana test after push to unify-unattended

Fix one kibana unit test

---

unattended_installer/install_functions/opendistro/wazuh-passwords-tool.sh

|Related PR|
|---|
|https://github.com/wazuh/wazuh-packages/pull/1203|
Some small changes to fix small errors detected by the unit testing in wazuh-passwords-tool.sh

Fixed errors detected by the unit testing [wazuh-passwords-tool.sh]

---

unattended_installer/install_functions/opendistro/common.sh
unattended_installer/install_functions/opendistro/elasticsearch.sh
unattended_installer/install_functions/opendistro/kibana.sh
unattended_installer/install_functions/opendistro/wazuh-cert-tool.sh
unattended_installer/install_functions/opendistro/wazuh-passwords-tool.sh
unattended_installer/wazuh_install.sh

|---|
|closes #1207|
This PR adds to the logger two new options:
- `-d`, which outputs the message only if the debug option is active
- `-dh`(disable header), which outputs the message without date or type of message
I have added changed mainly logger calls and added categories on the output of the installation.
```[root@centos8 unattended_installer]# bash wazuh_install.sh -a -l
27/01/2022 09:28:20 ERROR: Some the Wazuh components were found on this host. If you want to overwrite the current installation, run this script back using the option -o/--overwrite. NOTE: This will erase all the existing configuration and data.
[root@centos8 unattended_installer]# bash wazuh_install.sh -a -l -o
27/01/2022 09:28:26 INFO: Cleaning the installation.
27/01/2022 09:28:26 WARNING: …
```

Minor improvements to the unattended installer

---

solaris/package_generation/Vagrantfile

We want to fix the IP range of package generation on 4.2 packages.

Changed IP Range on Solaris

---

stack/dashboard/rpm/wazuh-dashboard.spec

Fixed dashboard permission in RPM

Fix certs permissions in RPM

---

stack/dashboard/base/files/etc/opensearch_dashboards.yml
stack/indexer/base/files/etc/wazuh-indexer/opensearch.yml

|---|
|https://github.com/wazuh/wazuh-packages/issues/1286|

Change indexer Port

---

stack/dashboard/base/builder.sh
stack/dashboard/base/files/etc/custom_welcome/Assets/default_branding/Solid_black.svg

|---|
|https://github.com/wazuh/wazuh-packages/issues/1293|

Replace Wazuh Logo

---

CHANGELOG.md
solaris/solaris11/generate_wazuh_packages.sh
solaris/solaris11/smf_manifest.xml

|---|
|Closes # #1281|
This PR fixes an issue with the Solaris 11 post installation SMF service where that caused the script to not run on new installations.
https://github.com/wazuh/wazuh-packages/issues/1281#issuecomment-1058212047

Allow Solaris 11 post install to run on installation

---

unattended_installer/install_functions/dashboard.sh
unattended_installer/install_functions/indexer.sh
unattended_installer/install_functions/installMain.sh

|---|
||
This PR changes some log messages in the installation assistant.

Improve log message installation assistant

---

unattended_installer/passwords_tool/passwordsFunctions.sh

|---|
|Closes #1303|
This PR modifies the password functions to use the keystone in filebeat.yml.

Use keystore to change filebeat password

---

documentation-templates/elastic-basic/elasticsearch.yml
documentation-templates/elastic-basic/elasticsearch_all_in_one.yml
documentation-templates/elastic-basic/elasticsearch_cluster.yml
documentation-templates/elastic-basic/elasticsearch_cluster_initial_node.yml
documentation-templates/elastic-basic/elasticsearch_cluster_subsequent_nodes.yml
documentation-templates/elastic-basic/filebeat.yml
documentation-templates/elastic-basic/filebeat_all_in_one.yml
documentation-templates/elastic-basic/instances_aio.yml
documentation-templates/elastic-basic/kibana.yml
documentation-templates/elastic-basic/kibana_all_in_one.yml
documentation-templates/wazuh/config.yml
documentation-templates/wazuh/filebeat/filebeat.yml

|---|
|https://github.com/wazuh/wazuh-packages/issues/1311|
The documentation-templates folder is created and the files indicated in the issue are added

Documentation templates folder created

---

stack/dashboard/base/files/etc/opensearch_dashboards.yml
stack/dashboard/deb/debian/postinst
stack/dashboard/deb/debian/postrm
stack/dashboard/deb/debian/preinst
stack/dashboard/deb/debian/rules
stack/dashboard/rpm/wazuh-dashboard.spec

|---|
|https://github.com/wazuh/wazuh-packages/issues/1321|

Removed log files for Wazuh-dashboard

---

unattended_installer/builder.sh
unattended_installer/downloader/wazuh-offline-download.sh
unattended_installer/install_functions/checks.sh
unattended_installer/install_functions/installMain.sh
unattended_installer/install_functions/installVariables.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/1322|
The scripts are created to download the packages necessary for the installation of Wazuh Offline.
builder.sh is also modified for the use of this script
```
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-packages/unattended_installer$ sudo ./wazuh-install.sh -dw deb
14/03/2022 12:53:14 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
14/03/2022 12:53:15 INFO: --- Download Packages ---
14/03/2022 12:53:15 INFO: Starting Wazuh packages download.
14/03/2022 12:53:15 INFO: Downloading Wazuh deb packages for x86_64...
14/03/2022 12:53:27 INFO: Wazuh deb package downloaded
14/03/2022 12:53:30 INFO: Filebeat deb package downloaded
14/03/2022 12:54:04 INFO: Wazuh Indexer deb package …
```

Add Offline Installation for Unattended

---

stack/dashboard/base/builder.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/1333|
Remove custom settings and leave default OpenSearch panel logos
Build rpm: https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7408/console
Build deb: https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7409/console

Removed Wazuh logo from opensearch dashboards menu

---

unattended_installer/cert_tool/certFunctions.sh
unattended_installer/cert_tool/certMain.sh
unattended_installer/install_functions/installCommon.sh
unattended_installer/install_functions/installMain.sh

|---|
|#1336|
In this PR we change the directory where the temporary files are created to tmp.
CentOS 7: https://ci.wazuh.info/view/Tests/job/Test_unattended/27/
Ubuntu Focal: https://ci.wazuh.info/view/Tests/job/Test_unattended/28/
Distributed: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended_distributed/366/

Create installation asistant temporary files in /tmp

---

unattended_installer/builder.sh
unattended_installer/install_functions/wazuh-offline-download.sh

|---|
|#1336|
This PR removes some copyright blocks that were added when generating the installation assistant.
CentOS 7: https://ci.wazuh.info/view/Tests/job/Test_unattended/25/
Ubuntu Bionic: https://ci.wazuh.info/view/Tests/job/Test_unattended/26/
Distributed: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended_distributed/365/

Remove extra copyright blocks from generated scripts

---

solaris/solaris11/SPECS/template_agent_v4.4.0.json

In this PR we add the changes introduced in #1126 -which pointed to the `4.3` branch-, to master. The change is already [in the changelog](https://github.com/wazuh/wazuh-packages/blob/88a6db9f53a9e095a9d3dc0f0db272ac6d7abcdb/CHANGELOG.md?plain=1#L19), so I didn't add anything referring to this in this PR.
To test that the package build was fixed we created a `4.3` package using the modified branch and then installed it in a Solaris11 machine. As can be seen in the following shell output, it's working as expected.
<details><summary>Installation and removal on Solaris11 output</summary>
root@solaris11:/tmp# pkg install -g ./wazuh-agent_v4.4.0-sol11-i386.p5p wazuh-agent
Services to change:  1
Create boot environment: No
Create backup boot environment: No
DOWNLOAD …

Add new `wodles/gcloud` files and folders to Solaris11 SPEC

---

tests/unattended/unit/suites/test-checks.sh
tests/unattended/unit/suites/test-common.sh
tests/unattended/unit/suites/test-installCommon.sh
tests/unattended/unit/suites/test-manager.sh
tests/unattended/unit/suites/test-passwordsFunctions.sh
unattended_installer/common_functions/common.sh
unattended_installer/install_functions/checks.sh
unattended_installer/install_functions/dashboard.sh
unattended_installer/install_functions/filebeat.sh
unattended_installer/install_functions/indexer.sh
unattended_installer/install_functions/installCommon.sh
unattended_installer/install_functions/installMain.sh
unattended_installer/install_functions/manager.sh
unattended_installer/passwords_tool/passwordsFunctions.sh

|---|
|Closes #1374|
This issue adds an extra check after installing the components to ensure that everything has been installed correctly.
Centos 7:https://ci.wazuh.info/view/Tests/job/Test_unattended/53/
Ubuntu Bionic: https://ci.wazuh.info/view/Tests/job/Test_unattended/54/
Distributed: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended_distributed/383/

Verify that components have been installed with common_checkInstalled

---

hp-ux/generate_wazuh_packages.sh

|---|
| https://github.com/wazuh/wazuh/issues/9815 |
The development of https://github.com/wazuh/wazuh/issues/9103 creates the need to build internal projects with CMake such as DBSync, RSync, or Syscheck.
In order to make it run, we need to deploy pre-built modern versions of GCC and CMake.
- **GCC 9.4**
- **CMake 3.22.2**
Since we deploy a prebuilt version of GCC, this should be located at `/home/okkam/bootstrap-gcc` to work properly.
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/home/zhxzx/gcc94_prefix/bin/../libexec/gcc/ia64-hp-hpux11.31/9.4.0/lto-wrapper
Target: ia64-hp-hpux11.31
Configured with: ../configure --enable-nls --with-included-gettext --enable-shared --with-gnu-as --with-as=/home/okkam/bootstrap-gcc/gcc94_prefix/ia64-hp-hpux11.31/bin/as …
```

Modify HP-UX generate packages script to update gcc and cmake

---

CHANGELOG.md
ova/assets/custom/messages.sh

|---|
| This PR closes https://github.com/wazuh/wazuh-jenkins/issues/2396 |
This PR removes the IP message from the OVA at startup
- OVA built correctly:
<details><summary>OVA log</summary>
```
default: Using dev packages
default: Upgrading the system. This may take a while ...
default: Adding user wazuh-user to group wheel
default: 28/03/2022 20:09:04 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
default: 28/03/2022 20:09:04 INFO: The verbose logging will be redirected to the file: /var/log/wazuh-install.log
default: 28/03/2022 20:09:07 INFO: --- Dependencies ---
default: 28/03/2022 20:09:07 INFO: Installing unzip.
default: 28/03/2022 20:09:09 INFO: Installing wget.
default: 28/03/2022 20:09:15 INFO: Wazuh development repository added.
default: …
```

Remove ip message from OVA 4.3

---

stack/dashboard/base/builder.sh
stack/dashboard/base/files/etc/custom_welcome/template.js.hbs
stack/dashboard/base/files/etc/custom_welcome/wazuh_logo_circle.svg

|---|
|https://github.com/wazuh/wazuh-packages/issues/1394|
The changes requested by the Frontend team are made
https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7444/console
https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7443/console

Preserve Wazuh Dashboard login customization

---

unattended_installer/install_functions/dashboard.sh
unattended_installer/install_functions/filebeat.sh
unattended_installer/install_functions/indexer.sh
unattended_installer/install_functions/installCommon.sh
unattended_installer/install_functions/manager.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/1388|
Add validation process and a loop that generates a sleep on error in apt
Log forcing the error
Log with the fix
Unattended:
Centos: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/492/console
Ubuntu: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/493/console
Unattended Distributed:
https://devel.ci.wazuh.info/view/Tests/job/Test_unattended_distributed/387/console

Resolved apt lock error

---

unattended_installer/install_functions/installMain.sh

This PR aims to improve the message about verbose logging.

Improved redirection message

---

unattended_installer/install_functions/dashboard.sh
unattended_installer/install_functions/installCommon.sh
unattended_installer/install_functions/installMain.sh
unattended_installer/passwords_tool/passwordsFunctions.sh

|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1436|
Various messages are updated based on what was requested in the issue
```
06/04/2022 20:23:05 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
06/04/2022 20:23:05 INFO: Verbose logging will be redirected to /var/log/wazuh-install.log
06/04/2022 20:23:05 WARNING: Hardware and system checks ignored.
06/04/2022 20:23:16 INFO: --- Dependencies ----
06/04/2022 20:23:16 INFO: Installing apt-transport-https.
06/04/2022 20:23:19 INFO: Installing unzip.
06/04/2022 20:23:26 INFO: Wazuh development repository added.
06/04/2022 20:23:26 INFO: --- Configuration files ---
06/04/2022 20:23:26 INFO: Generating configuration files.
06/04/2022 20:23:27 INFO: Created wazuh-install-files.tar. It contains the …
```

Changed some messages

---

stack/dashboard/base/files/etc/opensearch_dashboards.yml
unattended_installer/config/dashboard/dashboard.yml
unattended_installer/config/dashboard/dashboard_all_in_one.yml
unattended_installer/config/dashboard/dashboard_unattended.yml
unattended_installer/config/dashboard/dashboard_unattended_distributed.yml

|---|
| #1470 |
Hello team,
We have added default tenant to avoid no tenant selected popup.

Added default tenant to URL

---

stack/dashboard/base/builder.sh
stack/dashboard/base/files/etc/opensearch_dashboards.yml
unattended_installer/config/dashboard/dashboard.yml
unattended_installer/config/dashboard/dashboard_all_in_one.yml
unattended_installer/config/dashboard/dashboard_unattended.yml
unattended_installer/config/dashboard/dashboard_unattended_distributed.yml

|---|
| Closes #1470 |
Hello team,
We have applied a fix to remove tenancy popup on first launch.

Fix Pop up random show up

---

ova/assets/custom/messages.sh
ova/provision.sh
ova/setOVADefault.sh
ova/wazuh_ovf_template

Updated memory requirements for the OVA and fixed some bugs and messages:

Upgrade requirements OVA

---

stack/dashboard/base/builder.sh

|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1509|
Documentation links updated to point to Wazuh
Build:
rpm: https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7550/console
deb: https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7551/console
Install:
Centos: https://devel.ci.wazuh.info/view/Tests/job/Test_install_stack/459/console
Ubuntu: https://devel.ci.wazuh.info/view/Tests/job/Test_install_stack/460/console

Changed documentation links

---

ova/assets/custom/messages.sh

This PR aims to change the welcome OVA and AMI message

Changing welcome OVA and AMI message

---

unattended_installer/builder.sh
unattended_installer/install_functions/installVariables.sh

|---|
||
This PR changes how we set the repository for the offline installation.

Fix offline installation hardcoded repo

---

ova/assets/steps.sh

|---|
||
Install dependencies for reporting in OVA

Install dashboard reporting dependencies OVA

---

rpms/SPECS/4.5.0/wazuh-manager-4.5.0.spec

|---|
||
This PR removes the backup/db directory from the RPM specs

Remove backup/db from RPM SPECS

---

.github/actions/generate-artifacts/action.yml
.github/actions/get-tools/action.yml
.github/actions/shellcheck/action.yml
.github/actions/shellcheck/script.sh
.github/workflows/shellcheck.yml
unattended_installer/cert_tool/test.sh

|---|
| #1351 |
Run automatically shellcheck static code analyzer over wazuh-install.sh, wazuh-passwords-tool.sh, wazuh-certs-tool.sh and build.sh using Github Actions only if any change was made to sh files
View "conversation, files changes and checks tab" into #1406
https://github.com/wazuh/wazuh-packages/pull/1366
https://github.com/wazuh/wazuh-packages/pull/1406

Shellcheck github automation

---

.github/actions/generate-artifacts/action.yml
.github/actions/get-tools/action.yml
.github/actions/shellcheck/action.yml
.github/actions/shellcheck/script.sh
.github/workflows/shellcheck.yml

|---|
| #1351 |
Run automatically shellcheck static code analyzer over wazuh-install.sh, wazuh-passwords-tool.sh, wazuh-certs-tool.sh and build.sh using Github Actions only if any change was made to sh files
View "conversation, files changes and checks tab" into #1406
https://github.com/wazuh/wazuh-packages/pull/1366
https://github.com/wazuh/wazuh-packages/pull/1406

Shellcheck github automation 

---

unattended_installer/install_functions/installVariables.sh

|---|
||
This PR sets the wazuh dashboard revision to 1.

Set dashboard revision to 1

---

CHANGELOG.md
wazuhapp/opensearch-dashboards/Docker/build.sh

|---|
|Related https://github.com/wazuh/wazuh-jenkins/issues/3539#|
This PR fix the dashboard app name with the actual name. This need to be discussed in the future to contemplate the opensearch version and allow multiples versions with opensearch (4.3.1 with 1.2.0 and 4.3.1 with 1.3.0)
https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/7579/console
https://packages-dev.wazuh.com/trash/ui/dashboard/wazuh-4.3.1-0.0.0.todelete.3539.zip
https://packages-dev.wazuh.com/trash/checksums/wazuh/4.3.1/wazuh-4.3.1-0.0.0.todelete.3539.zip.sha512

Fix dashboard app name

---

unattended_installer/config/certificate/config_aio.yml
unattended_installer/install_functions/checks.sh
unattended_installer/install_functions/dashboard.sh
unattended_installer/install_functions/installMain.sh

|---|
|Closes #1561 #1560 #1559 #1558 |
This PR fixes multiple issues in the Wazuh installation assistant.
https://devel.ci.wazuh.info/job/Test_unattended_distributed/467/
https://ci.wazuh.info/job/Test_unattended/83/
https://ci.wazuh.info/job/Test_unattended/84/

Unattended improvements 4 3

---

aix/SPECS/4.3.2/wazuh-agent-4.3.2-aix.spec
debs/SPECS/4.3.2/wazuh-agent/debian/changelog
debs/SPECS/4.3.2/wazuh-manager/debian/changelog
rpms/SPECS/4.3.2/wazuh-agent-4.3.2.spec
rpms/SPECS/4.3.2/wazuh-manager-4.3.2.spec

This PR updates the date for 4.3.2 release.

Update changelog date

---

unattended_scripts/elastic-stack/unattended-installation/all-in-one-installation.sh
unattended_scripts/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh
unattended_scripts/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
unattended_scripts/open-distro/unattended-installation/distributed/wazuh-server-installation.sh
unattended_scripts/open-distro/unattended-installation/unattended-installation.sh

|---|
|Release related|
This PR bumps the unattended from 4.2.6 to 4.2.7

Bump unattended 4.2.7

---

aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

|---|
|-|
This PR sorts the changelogs dates

Fix changelogs dates 4.3

---

splunkapp/Docker/build.sh

|---|
|#3530|
Modify Splunk to obtain the version of Wazuh and Splunk from the package.conf file.
This need to build and upload a new image of splunk_builder_noarch
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/169/console

Simplified splunk packages builder

---

unattended_installer/install_functions/checks.sh

This PR aims to add Ubuntu 22 to recommended OS list as requested here: https://github.com/wazuh/wazuh-packages/issues/1622

Added Ubuntu 22 support

---

stack/indexer/deb/debian/preinst
stack/indexer/rpm/wazuh-indexer.spec

|---|
| Related #1642 |
Coming from https://github.com/wazuh/wazuh-packages/pull/1647

Fixed invoke.rc call

---

stack/indexer/deb/debian/preinst
stack/indexer/rpm/wazuh-indexer.spec

|---|
| Closes #1642 |
https://github.com/wazuh/wazuh-packages/pull/1661

Fixed invoke call

---

rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

Same as https://github.com/wazuh/wazuh-packages/pull/1673
Related #1626

Fix RHEL9 init.d file installation

---

rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

Same as https://github.com/wazuh/wazuh-packages/pull/1673
Closes #1626

Fix error sysv-init rhel9

---

tests/unattended/install/test_unattended.py
tests/unattended/unit/suites/test-common.sh
tests/unattended/unit/suites/test-dashboard.sh

This PR update the Wazuh assistant tests from 4.3.4 to 4.3.5

Bump Wazuh assistant tests to 4.3.5

---

CHANGELOG.md
aix/SPECS/wazuh-agent-aix.spec
rpms/SPECS/wazuh-agent.spec

This PR update the changelog with minor fixes and update the changelog.md file with release urls.

Update changelog with releases

---

documentation-templates/elastic-basic/filebeat.yml
documentation-templates/elastic-basic/filebeat_all_in_one.yml
documentation-templates/wazuh/filebeat/filebeat.yml
unattended_installer/config/filebeat/filebeat.yml
unattended_installer/config/filebeat/filebeat_all_in_one.yml
unattended_installer/config/filebeat/filebeat_distributed.yml
unattended_installer/config/filebeat/filebeat_elastic_cluster.yml
unattended_installer/config/filebeat/filebeat_unattended.yml

|---|
| [#1665](https://github.com/wazuh/wazuh-packages/issues/1665) |
Some users have reported problems with Filebeat after installing wazuh related to SIGABRT.
The error it throws is "filebeat[21584]: SIGABRT: abort"
Until now, the error could only be reproduced on systems that have GLIBC v2.35 installed.
After an analysis it was found that the way to solve it is to add the following to the Filebeat template:
```
seccomp:
default_action: allow
syscalls:
- action: allow
names:
- rseq
```
Tests were performed on all recommended systems and a few more. The tests consisted of trying to reproduce the error and then applying the changes to the Filebeat template. Then check, if the error could be reproduced, it is not generated anymore; and if it couldn't be reproduced, that …

Add fix to avoid GLIBC crash

---

tests/unattended/install/test_unattended.py

|---|
| https://github.com/wazuh/wazuh-jenkins/issues/3776 |
We have modified the unattended tests to allow distributed specific cases

Improved unattended distributed tests

---

unattended_installer/config/indexer/roles/roles.yml
unattended_installer/config/indexer/roles/roles_mapping.yml

Hello team,
This PR solves a problem related with #1668 and https://github.com/wazuh/wazuh/issues/14289
Closes https://github.com/wazuh/wazuh-packages/issues/1747

Fix role to create wazuh-monitoring and statistics indices

---

stack/dashboard/base/builder.sh
stack/dashboard/base/files/etc/styles.js
stack/dashboard/base/files/etc/template.js

|---|
| closes #1730  |
Hello team,
We have changed the Wazuh loading logo to make it bigger.
Before:
After:

Increase logo text and size

---

unattended_installer/config/dashboard/dashboard.yml
unattended_installer/config/dashboard/dashboard_all_in_one.yml
unattended_installer/config/dashboard/dashboard_unattended.yml
unattended_installer/config/dashboard/dashboard_unattended_distributed.yml
unattended_installer/config/indexer/indexer.yml
unattended_installer/config/indexer/indexer_all_in_one.yml
unattended_installer/config/indexer/indexer_unattended_distributed.yml

|---|
|https://github.com/wazuh/wazuh-packages/issues/1694|
https://github.com/wazuh/wazuh-packages/issues/1694#issuecomment-1190382510
The ciphers and TLS versions are negotiated between the browser and the Security plugin automatically, which in some cases can lead to a weaker cipher suite being used. That's why we need strong ciphers.
- Indexer:
- Dashboard:
- [OpenSearch Documentation](https://opensearch.org/docs/1.3/security-plugin/configuration/tls/#advanced-enabled-ciphers-and-protocols) about this.
Installation with this parameters:
````
[root@localhost vagrant]# ./wazuh-install.sh -a
21/07/2022 09:14:52 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.5
21/07/2022 09:14:52 INFO: Verbose logging redirected to /var/log/wazuh-install.log
21/07/2022 …
```

Disable lower versions than TLSv1.2

---

ova/assets/custom/functions.sh
ova/assets/steps.sh

|---|
||
This PR modifies the OVA generation scripts to adapt them to the newest changes in `wazuh-passwords-tool.sh`
https://ci.wazuh.info/job/Packages_Builder_OVA/174/

Adapt OVA generation to new passwords tool

---

unattended_installer/install_functions/filebeat.sh

|---|
|#1736|
This PR fixes adds error handling for filebeat downloaded files and fixes an error that didn't rollback the installation when it failed

Fix errors in filebeat installation

---

stack/dashboard/base/builder.sh
stack/dashboard/base/docker/Dockerfile

|---|
| closes #1761  |
Hello!
We have included modifications to manage build number version on each Wazuh version

Increase build number in package.json

---

rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

|---|
||
This PR fixes a path error when copying SCA files.

Change versions in fedora SCA files

---

rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

|---|
||
This PR adds the latest fixes for 4.3.7-2:
https://github.com/wazuh/wazuh-packages/releases/tag/v4.3.7-2
To the 4.3 branch.

Merge 4.3.7-2 changes in 4.3 branch

---

rpms/SPECS/wazuh-manager.spec

|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1789|
Update master branch with the latest changes in 4.4

Master update with 4.4

---

debs/SPECS/wazuh-manager/debian/postinst
rpms/SPECS/wazuh-manager.spec

Reverts wazuh/wazuh-packages#1814

Revert "Adapt the manager package to use wazuh-authd"

---

aix/SPECS/wazuh-agent-aix.spec
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

|---|
||
This PR fixes an error that appeared when building RPM5 packages due to the changelog not being in chronological order.
https://ci.wazuh.info/job/Packages_builder/111610/console
https://ci.wazuh.info/job/Packages_builder_tier/2508/
https://ci.wazuh.info/job/Packages_builder_tier/2509/

Order RPM specs chronologicaly

---

.github/actions/passwords-tool/tests-stack-failure.sh
.github/actions/passwords-tool/tests-stack-success.sh
tests/unattended/install/test_unattended.py
unattended_installer/passwords_tool/passwordsFunctions.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/1359|
This PR closes https://github.com/wazuh/wazuh-packages/issues/1359.
The HTTP method used when requesting the API login endpoint has been changed from GET to POST.

Change method from `GET` to `POST` in API login requests

---

CHANGELOG.md
aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
macos/specs/wazuh-agent.pkgproj
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

This PR aims to update `4.4` branch with `4.3` latest changes. 
Pipeline (green): https://ci.wazuh.info/view/Packages/job/Packages_builder_tier/2521/console

Update 4.4 with 4.3 changes

---

debs/SPECS/wazuh-manager/debian/postinst
rpms/SPECS/wazuh-manager.spec

|---|
|closes https://github.com/wazuh/wazuh-packages/issues/1676|
|https://github.com/wazuh/wazuh-packages/pull/1830|
This PR is the same as https://github.com/wazuh/wazuh-packages/pull/1814
PR https://github.com/wazuh/wazuh-packages/pull/1814 was reverted because it was causing a problem since the issue https://github.com/wazuh/wazuh-packages/issues/1676 is not merged in wazuh master branch yet.

Adapt the manager packages to use wazuh-authd

---

rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

|---|
||
This PR adds the necessary changes to wazuh-packages for the changes made here:
https://github.com/wazuh/wazuh/pull/14190

Add changes to distribute the libstdc++ and libgcc_s to wazuh-packages

---

rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

|---|
| https://github.com/wazuh/wazuh/issues/14018 |
This pr aims to incorporate into the specs the new libraries recently added to the 4.4 branch.

Merge new libraries specs from 4.4 to master branch.

---

CHANGELOG.md
rpms/SPECS/wazuh-agent.spec

This pull request adds and fixes the changelog for the missing v4.3.9 version.

Fix 4.3.9 release changelog 4.4

---

README.md

Markdown fixed following https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md

4.3 md markdownlint

---

README.md
arch/README.md
debs/README.md
hp-ux/README.md
macos/README.md
ova/README.md
rpms/README.md
solaris/README.md
splunkapp/README.md
wazuhapp/opensearch-dashboards/README.md
windows/README.md
wpk/README.md

According to https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md, there are some fixes to apply.

Fixes according md003

---

README.md

|---|
|https://github.com/wazuh/wazuh-packages/issues/1928|
Update README.md of wazuh-packages adding the "Compatibility matrix" section.
https://github.com/wazuh/wazuh-packages/tree/1928-add-a-version-reference-in-this-repository

1928 add a version reference in this repository

---

documentation-templates/learning-wazuh/suricata.yaml

Added new template

---

CHANGELOG.md
README.md
aix/SPECS/wazuh-agent-aix.spec
arch/README.md
debs/README.md
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
documentation-templates/learning-wazuh/suricata.yaml
documentation-templates/wazuh/config.yml
hp-ux/README.md
macos/README.md
ova/README.md
rpms/README.md
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
solaris/README.md
splunkapp/README.md
wazuhapp/opensearch-dashboards/README.md
windows/README.md
wpk/README.md
wpk/common/Dockerfile
wpk/run.sh

Merge 4.3 into 4.4 branch

---

aix/SPECS/wazuh-agent-aix.spec
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

Hello!
We want to fix the master changelog including 4.3.10 and 4.4.0 updates.

Fix changelog of master branch

---

debs/SPECS/wazuh-agent/debian/postrm
solaris/solaris10/postremove.sh
solaris/solaris10/preinstall.sh

|---|
||
This PR merges the latest changes in 4.3 into 4.4.

Merge 4.3 4.4

---

stack/dashboard/base/builder.sh
stack/dashboard/deb/debian/rules

|---|
|https://github.com/wazuh/wazuh-jenkins/issues/4508 |
The same changes were applied for the 4.3.11 package and can be seen in this PR
https://github.com/wazuh/wazuh-packages/pull/1967
-->

Wazuh dashboard 4.4.0 with Opensearch dashboards 2.4.1 to 4.4

---

stack/dashboard/base/builder.sh
stack/dashboard/deb/debian/rules

|---|
|https://github.com/wazuh/wazuh-jenkins/issues/4508 |
The same changes were applied for the 4.3.11 package and can be seen in this PR
https://github.com/wazuh/wazuh-packages/pull/1967
-->

Wazuh dashboard 4.4.0 with Opensearch dashboards 2.4.1 to master

---

README.md
stack/indexer/base/files/usr/lib/systemd/system/wazuh-indexer.service
unattended_installer/install_functions/indexer.sh
unattended_installer/install_functions/installCommon.sh
unattended_installer/install_functions/installMain.sh
unattended_installer/passwords_tool/passwordsFunctions.sh

|---|
||
This PR merges the latest changes in 4.4 into master.

Merge 4.4 into master

---

stack/dashboard/base/files/etc/template.js

|---|
|closes https://github.com/wazuh/wazuh-packages/issues/2052|
An override is made so that the loading page message is "Loading ..." instead of "Loading <title>"
Builders:
- rpm: https://ci.wazuh.info/job/Packages_builder/127760/console
- deb: https://ci.wazuh.info/job/Packages_builder/127759/console
Tests:
- Centos 7: https://ci.wazuh.info/job/Test_stack/357/
- Ubuntu Focal: https://ci.wazuh.info/job/Test_stack/358/

Updated loading page message to master

---

stack/indexer/base/files/usr/lib/systemd/system/wazuh-indexer.service
unattended_installer/install_functions/indexer.sh
unattended_installer/install_functions/installCommon.sh
unattended_installer/install_functions/installMain.sh
unattended_installer/passwords_tool/passwordsFunctions.sh
windows/entrypoint.sh
windows/generate_compiled_windows_agent.sh
windows/generate_wazuh_msi.ps1

Changes in 4.4 have been merged to 4.5, master branch

Update master with 4.4 changes

---

debs/Debian/amd64/Dockerfile
debs/Debian/arm64/Dockerfile
debs/Debian/armhf/Dockerfile
debs/Debian/i386/Dockerfile
debs/Debian/ppc64le/Dockerfile
hp-ux/generate_wazuh_packages.sh
rpms/CentOS/5/i386/Dockerfile
rpms/CentOS/5/x86_64/Dockerfile
rpms/CentOS/6/i386/Dockerfile
rpms/CentOS/6/x86_64/Dockerfile
rpms/CentOS/7/aarch64/Dockerfile
rpms/CentOS/7/armv7hl/Dockerfile
rpms/CentOS/7/ppc64le/Dockerfile
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
solaris/solaris11/SPECS/template_agent.json
wpk/linux/x86_64/Dockerfile

This reverts commit 1c874c45f3424ca2d1c2867d2635486fdf0f045c.
This PR reverts changes introduced at https://github.com/wazuh/wazuh-packages/pull/1275 since the rest of the components are not ready to be merged.

Revert "Change FIM database management using DBSync and RSync (#1275)"

---

.github/actions/offline-installation/common.sh
.github/actions/offline-installation/offline-installation.sh
.github/workflows/offline-installation.yml
unattended_installer/builder.sh
unattended_installer/install_functions/wazuh-offline-download.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2049|
This PR modifies all the `curl` commands that fetch big resources, mainly those included in the Offline Installation, using the `-I` parameter of `curl` to perform a `HEAD` request instead of a `GET` request.
This modification makes the Offline Installation to take less time, avoiding downloading the resources twice.
A Github Action has been added to test the Offline Installation. The action is in the `actions/offline-installation` folder.
The action has been debugged in https://github.com/davidcr01/wazuh-packages/actions.

Improval of the curl tool in the Offline Installation

---

alpine/SPECS/wazuh-agent/wazuh-agent.post-install
solaris/solaris10/pkginfo

|---|
|#2102 |
This PR updates the version of Wazuh in the Solaris 10 pkginfo file.

Update solaris10 pkginfo 4.4.0

---

unattended_installer/builder.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2103|
This PR updates the `source_branch` variable of the Installation Assistant builder from `4.4` to `4.5.`
The tests are in the related issue https://github.com/wazuh/wazuh-packages/issues/2103#issuecomment-1432841314.

Updated source_branch variable

---

wpk/linux/x86_64/Dockerfile

|---|
|closes https://github.com/wazuh/wazuh-packages/issues/2124|
Python has been updated to 3.7 in the WPK build container to fix some issues with the AWS CLI.
```console
[root@centos7-1 ~]# /var/ossec/bin/agent_control -i 011
Wazuh agent_control. Agent information:
Agent ID:   011
Agent Name: cc85ce8319b8
IP address: any
Status:     Active
Operating system:    Linux |cc85ce8319b8 |5.19.0-35-generic |#36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 |x86_64
Client version:      Wazuh v4.3.10
Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
Shared file hash:    4a8724b20dee0124ff9656783c490c4e
Last keep alive:     1678450685
Syscheck last started at:  Fri Mar 10 12:17:36 2023
Syscheck last ended at:    Fri Mar 10 12:17:36 2023
[root@centos7-1 ~]# …
```

Updated Python 3.4 to 3.7 to resolve AWS CLI issues in WPK build container

---

unattended_installer/install_functions/dashboard.sh
unattended_installer/install_functions/installCommon.sh
unattended_installer/install_functions/installMain.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/1840|
This PR modifies the dependencies of the Installation Assistant, specifically the dependencies related to the Wazuh dashboard to generate PDF reports. These dependencies are listed here: https://github.com/opensearch-project/reporting/tree/2.4.1.0/dashboards-reports/rendering-engine/headless-chrome#additional-libaries.
A summary of the done tasks is in: https://github.com/wazuh/wazuh-packages/issues/1840#issuecomment-1461569918
As the OpenSearch documentation is not very clear and some issues have been found in the process, exhausting testing has been necessary to validate this development.
**Manual** testing is in: https://github.com/wazuh/wazuh-packages/issues/1840#issuecomment-1441654661
**Jenkins** testing: …

Added dashboard dependencies to generate PDF reports

---

README.md

|---|
|#2171|
The distribution version matrix was updated as requested in the issue.

Distribution version matrix update

---

CHANGELOG.md
aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

|---|
|Related https://github.com/wazuh/wazuh-packages/pull/2187|
This PR fixes the release date of version 4.3.11 and 4.4.2 in the 4.4 branch
- https://ci.wazuh.info/view/Packages/job/Packages_builder_tier/2949/
- Debian Wazuh manager/agent
- RPM Wazuh manager/agent
```
[root@centos7 vagrant]# rpm -q --changelog wazuh-agent 
* Mon May 08 2023 support <info@wazuh.com> - 4.4.2
- More info: https://documentation.wazuh.com/current/release-notes/
* Mon Apr 24 2023 support <info@wazuh.com> - 4.3.11
- More info: https://documentation.wazuh.com/current/release-notes/
* Mon Apr 17 2023 support <info@wazuh.com> - 4.4.1
- More info: https://documentation.wazuh.com/current/release-notes/
```
```
root@debian11:/home/vagrant# apt changelog wazuh-agent
Get:1 store: wazuh-agent …
```

Fix 4.3.11 changelog date 4.4

---

solaris/solaris10/pkginfo

|---|
|Related https://github.com/wazuh/wazuh-packages/issues/2185|
This PR updates the version information for the Solaris 10 4.5.0 package.

Fix solaris 10 pkg info- 4.5

---

debs/SPECS/wazuh-manager/debian/rules
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

|---|
|https://github.com/wazuh/wazuh-packages/issues/2136|
This PR adds the Amazon Linux 2023 files to the specs.

Added Amazon Linux 2023 SCA

---

CHANGELOG.md
README.md
aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-agent/debian/copyright
debs/SPECS/wazuh-manager/debian/changelog
debs/SPECS/wazuh-manager/debian/copyright
puppet_module/Docker/Dockerfile
puppet_module/build.sh
puppet_module/build_module.sh
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/deb/debian/copyright
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/deb/debian/copyright
stack/indexer/rpm/wazuh-indexer.spec
windows/generate_compiled_windows_agent.sh
windows/generate_wazuh_msi.ps1

|---|
|Related https://github.com/wazuh/wazuh/issues/17574|
This pull request merges the 4.4.5 branch into the 4.5 branch.

Merge 4.4.5 into 4.5

---

CHANGELOG.md
README.md
aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-agent/debian/copyright
debs/SPECS/wazuh-manager/debian/changelog
debs/SPECS/wazuh-manager/debian/copyright
puppet_module/Docker/Dockerfile
puppet_module/build.sh
puppet_module/build_module.sh
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/deb/debian/copyright
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/deb/debian/copyright
stack/indexer/rpm/wazuh-indexer.spec
windows/generate_compiled_windows_agent.sh
windows/generate_wazuh_msi.ps1

|---|
|Related https://github.com/wazuh/wazuh/issues/17574|
This pull request merges the `4.5` branch into the `master` branch.

Merge 4.5 into master

---

stack/dashboard/deb/debian/changelog
stack/indexer/deb/debian/changelog
unattended_installer/install_functions/installVariables.sh

|Related issue|Related PR|
|---|---|
|https://github.com/wazuh/wazuh/issues/17639|https://github.com/wazuh/wazuh-packages/pull/2241|
This PR aims to fix some versions that https://github.com/wazuh/wazuh-packages/pull/2241 did not include.

Bump Stack packages' changelog to 4.6.0

---

CHANGELOG.md
aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/rpm/wazuh-indexer.spec

|---|
|https://github.com/wazuh/wazuh-packages/issues/2306|
This PR merge 4.5.0 into 4.5.1

Merge 4.5.0 into 4.5.1

---

CHANGELOG.md
aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/rpm/wazuh-indexer.spec

|---|
|https://github.com/wazuh/wazuh-packages/issues/2306|
This PR merge 4.5.1 into 4.5.2

Merge 4.5.1 into 4.5.2

---

CHANGELOG.md
README.md
aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/rpm/wazuh-indexer.spec
tests/unattended/unit/suites/test-dashboard.sh
tests/unattended/unit/suites/test-indexer.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2306|
This PR merge 4.5.1 into 4.5.2

Merge 4.5.2 into 4.6.0

---

CHANGELOG.md
aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/rpm/wazuh-indexer.spec
tests/unattended/unit/suites/test-indexer.sh

Merge 4.7.0 into master

---

ova/assets/custom/enable_fips.sh
ova/assets/steps.sh

This PR adds scripts to enable FIPS compliance for the OVA operating system

Add script for enable fips

---

wazuhapp/kibana/Docker/build.sh
wazuhapp/opensearch-dashboards/Docker/build.sh

|---|
|closes #2247 |
This PR updates the `package.json` path for the Wazuh Kibana app.

Update kibana app package.json path

---

ova/Vagrantfile
ova/assets/custom/enable_fips.sh
ova/assets/custom/messages.sh
ova/assets/steps.sh
ova/generate_ova.sh
ova/provision.sh

|---|
|related https://github.com/wazuh/wazuh/issues/18190|
This PR brings the changes made to the OS from the OVA to the 4.4 branch.

Merge 4.4.5 into 4.4

---

ova/Vagrantfile
ova/assets/custom/enable_fips.sh
ova/assets/custom/messages.sh
ova/assets/steps.sh
ova/generate_ova.sh
ova/provision.sh

|---|
|Closes #2330|
This PR merges branch 4.4.5 into 4.5.0.

Merge 4.4.5 into 4.5.0

---

macos/specs/wazuh-agent-intel64.pkgproj
ova/Vagrantfile
ova/assets/custom/enable_fips.sh
ova/assets/custom/messages.sh
ova/assets/steps.sh
ova/generate_ova.sh
ova/provision.sh

|---|
|https://github.com/wazuh/wazuh/issues/18343|
This PR merge branch 4.5 into 4.5.1.

Merge 4.5 into 4.5.1

---

ova/wazuh_ovf_template

| -|
|https://github.com/wazuh/wazuh-packages/issues/2359|
This PR modifies the name that appears in the VM description after importing the OVA file into the virtualizer

Change OS name

---

unattended_installer/builder.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2367|
The aim of this PR is to update the `source_branch` variable of the `builder.sh` script in the `master` branch, `4.8.0`.

Updated `source_branch` variable - `master`

---

aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
ova/assets/steps.sh
ova/wazuh_ovf_template
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/rpm/wazuh-indexer.spec

|---|
|https://github.com/wazuh/wazuh-packages/issues/2375|
This PR merge branch 4.6.0 into 4.7.0.

Merge 4.6.0 into 4.7.0

---

unattended_installer/builder.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2367|
The aim of this PR is to update the `source_branch` variable of the `builder.sh` script in the `4.6.0` branch.

Updated `source_branch` variable - `4.6.0`

---

unattended_installer/builder.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2367|
The aim of this PR is to update the `source_branch` variable of the `builder.sh` script in the `4.7.0` branch.

Updated `source_branch` variable - `4.7.0`

---

ova/assets/custom/grub/grub

Issue Related https://github.com/wazuh/internal-devel-requests/issues/151

Change GRUB options into build OVA process

---

tests/unattended/install/test_unattended.py

|---|
|close https://github.com/wazuh/wazuh-jenkins/issues/5611|
The stack services validation string is replaced
Centos 7: https://ci.wazuh.info/view/Tests/job/Test_unattended/4378/console
Centos 8: https://ci.wazuh.info/view/Tests/job/Test_unattended/4379/console
Ubuntu Bionic: https://ci.wazuh.info/view/Tests/job/Test_unattended/4380/console
Ubuntu Jammy: https://ci.wazuh.info/view/Tests/job/Test_unattended/4381/console
Red Hat 7: https://ci.wazuh.info/view/Tests/job/Test_unattended/4382/console

Fixed wazuh-dashboad and wazuh-indexer service validation

---

README.md

|---|
|Related https://github.com/wazuh/wazuh-packages/issues/2387|
This PR adds the missing versions to the Readme.md file

Bump readme to 4.5.3

---

unattended_installer/cert_tool/certFunctions.sh
unattended_installer/common_functions/common.sh
unattended_installer/install_functions/checks.sh
unattended_installer/install_functions/dashboard.sh
unattended_installer/install_functions/filebeat.sh
unattended_installer/install_functions/indexer.sh
unattended_installer/install_functions/installCommon.sh
unattended_installer/install_functions/manager.sh
unattended_installer/install_functions/wazuh-offline-download.sh
unattended_installer/passwords_tool/passwordsFunctions.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/1632|
The aim of this PR is to improve the debug output of the Installation Assistant. With this change, the execution of the script will be easier to follow, in order to easily identify possible problems.
Some testing has been performed in https://github.com/wazuh/wazuh-packages/issues/1632#issuecomment-1729811344

Improved debug output in Installation Assistant

---

README.md
unattended_installer/install_functions/dashboard.sh
unattended_installer/install_functions/installVariables.sh
unattended_installer/passwords_tool/passwordsFunctions.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2472|
This PR aims to merge branch 4.5.3 into 4.6.0.

Merge 4.5.3 into 4.6.0

---

unattended_installer/install_functions/installCommon.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2488|
The aim of this PR is to fix the debug redirection when installing packages in the Installation Assistant. Before, a bug provoked to continue the installation if a package installation failed when using the verbose option.
Both cases RPM-based and DEB-based have been contemplated.
<details><summary>:green_circle: RPM-based (AL2023) with and without verbose</summary>
Both options do not install the `curl` tool and the script execution is stopped.
```console
[root@ip-172-31-66-117 ec2-user]# bash wazuh-install.sh -a
03/10/2023 09:53:49 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.2
03/10/2023 09:53:49 INFO: Verbose logging redirected to /var/log/wazuh-install.log
03/10/2023 09:53:54 INFO: --- …
```

Fixed debug redirection in packages installation in the Assistant

---

aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/base/files/etc/opensearch_dashboards.yml
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/rpm/wazuh-indexer.spec
unattended_installer/config/dashboard/dashboard.yml
unattended_installer/config/dashboard/dashboard_all_in_one.yml
unattended_installer/config/dashboard/dashboard_unattended.yml
unattended_installer/config/dashboard/dashboard_unattended_distributed.yml
unattended_installer/install_functions/dashboard.sh
unattended_installer/install_functions/installCommon.sh
wpk/common/Dockerfile

Merge 4.7.0 into 4.7.1

---

aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
macos/specs/wazuh-agent-intel64.pkgproj
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/base/files/etc/opensearch_dashboards.yml
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/rpm/wazuh-indexer.spec
unattended_installer/config/dashboard/dashboard.yml
unattended_installer/config/dashboard/dashboard_all_in_one.yml
unattended_installer/config/dashboard/dashboard_unattended.yml
unattended_installer/config/dashboard/dashboard_unattended_distributed.yml
unattended_installer/install_functions/dashboard.sh
unattended_installer/install_functions/installCommon.sh
wpk/common/Dockerfile

|---|
|#2516|
Merge 4.7.0 into 4.7.1

Merge 4.7.1 into master

---

aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-agent/debian/copyright
debs/SPECS/wazuh-manager/debian/changelog
debs/SPECS/wazuh-manager/debian/copyright
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/deb/debian/copyright
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/deb/debian/copyright
stack/indexer/rpm/wazuh-indexer.spec

|---|
|#2525|
This PR updates the release date of 4.7.0 in the SPEC files.

Update 4.7.0 release date

---

unattended_installer/cert_tool/certFunctions.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2524|
The eval is added to prevent mkdir from trying to create the directory `>> /dev/null 2>&1`
```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-packages/unattended_installer$ bash wazuh-certs-tool.sh -A
18/10/2023 08:29:09 INFO: Admin certificates created.
18/10/2023 08:29:09 INFO: Wazuh indexer certificates created.
18/10/2023 08:29:10 INFO: Wazuh server certificates created.
18/10/2023 08:29:10 INFO: Wazuh dashboard certificates created.
```
```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-packages/unattended_installer$ bash wazuh-certs-tool.sh -A -v
18/10/2023 10:34:19 DEBUG: Reading configuration file.
18/10/2023 10:34:19 DEBUG: Checking if 127.0.0.1 is private. …
```

Fixed mkdir wazuh-install-files error

---

bump_version.py
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
stack/dashboard/deb/debian/changelog
stack/indexer/deb/debian/changelog

|---|
|#2534|
This PR fixes an error in the DEB packages for 4.5.4, and adds the bump script to 4.5.4.

Fix 4.5.4 changelog and include bump script in branch 4.5.4

---

.github/workflows/build-deb-packages.yml
.github/workflows/build-rpm-packages.yml
CHANGELOG.md
aix/SPECS/wazuh-agent-aix.spec
bump_version.py
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/rpm/build_package.sh
stack/indexer/rpm/wazuh-indexer.spec

|---|
|https://github.com/wazuh/wazuh-packages/issues/2541|
This PR aims merge branch 4.7.1 into 4.8.0.

Merge 4.7.1 into 4.8.0

---

debs/SPECS/wazuh-manager/debian/rules
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

|---|
|https://github.com/wazuh/wazuh-packages/issues/2136|
Closes #2285
This PR adds the Amazon Linux 2023 files to the specs.

Add SPECS for SCA Amazon Linux 2023

---

macos/generate_wazuh_packages.sh

|---|
|#2233|
This PR updates the deprecated altool used to notarize macos packages to notarytool.
https://ci.wazuh.info/job/Packages_builder_macos/12184/

Update altool to notarytool

---

wazuhapp/kibana/Docker/build.sh
wazuhapp/opensearch-dashboards/Docker/build.sh

Change occurrences of ```wazuh-kibana-app``` to ```wazuh-dashboard-plugins```
[Issue #337](https://github.com/wazuh/internal-devel-requests/issues/337)

Update links to wazuh-kibana-app repo

---

stack/dashboard/base/builder.sh

|---|
|https://github.com/wazuh/wazuh-dashboard/issues/94|
Change the order of the Explore section in the side menu

Change the order of Explore category and Indexer/dashboard management title on dashboard

---

debs/SPECS/wazuh-agent/debian/copyright
debs/SPECS/wazuh-manager/debian/copyright
stack/dashboard/deb/debian/copyright
stack/indexer/deb/debian/copyright
tests/unattended/unit/suites/test-dashboard.sh
tests/unattended/unit/suites/test-indexer.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2595|
This PR will change the ETA of the 4.7.0 release.

Updated 4.7.0 release date

---

stack/indexer/indexer-ism-init.sh

This PR increases the default value for the `min_doc_count` rollover condition.
https://github.com/wazuh/internal-devel-requests/issues/474

Update `min_doc_count` value

---

unattended_installer/install_functions/dashboard.sh
unattended_installer/install_functions/installCommon.sh
unattended_installer/install_functions/installMain.sh

|---|
|https://github.com/wazuh/internal-devel-requests/issues/493|
The aim of this PR is to remove the development related to the addition of the Wazuh dashboard PDF report dependencies of the Wazuh Installation Assistant.
With this change, the packages installed are reduced considerably. Testing is in: https://github.com/wazuh/internal-devel-requests/issues/493#issuecomment-1821232868

Removed PDF report dependencies - 4.6.0

---

aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-agent/debian/copyright
debs/SPECS/wazuh-manager/debian/changelog
debs/SPECS/wazuh-manager/debian/copyright
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/deb/debian/copyright
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/deb/debian/copyright
stack/indexer/rpm/wazuh-indexer.spec

Update the release ETA for 4.7.0

---

aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/rpm/wazuh-indexer.spec

Update ETA date for 4.7.1

---

unattended_installer/builder.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2674|
This PR aims to fix the `source_branch` value, which was outdated. In 4.7.2, this variable is going to be set dynamically, so it won't be necessary to bump it anymore.

Fixed source branch value

---

unattended_installer/builder.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2674|
The aim of this PR is to add a function that sets the `source_branch` value dynamically. This variable uses the numbered branch or the tag of the repository. As the numbered branches are deleted when the new versions are released, the bumps are no longer necessary.
The function tries with 3 different URLs and chooses the first successful occurrence for the variable:
- Using the numbered branch.
- Using the tag.
- Using the master branch.
The new function is debugged to see the variable values. Notice how the `source_branch` value is set.
```console
> cat ../VERSION                                         
4.7.2
> bash builder.sh -i -d pre-release                      
+ …
```

The `source_branch` variable is set dynamically

---

aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/rpm/wazuh-indexer.spec

|---|
|https://github.com/wazuh/wazuh-packages/issues/2704|
This PR aims merge branch 4.7.1 into 4.7.2.

Merge 4.7.1 into 4.7.2

---

aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-agent/debian/copyright
debs/SPECS/wazuh-manager/debian/changelog
debs/SPECS/wazuh-manager/debian/copyright
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/deb/debian/copyright
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/deb/debian/copyright
stack/indexer/rpm/wazuh-indexer.spec

|---|
|#2719|
This PR aims to update the release date of v4.7.2 to Jan 9, 2024.

Update release date for 4.7.2

---

aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/base/builder.sh
stack/indexer/base/generate_base.sh
stack/indexer/deb/build_package.sh
stack/indexer/deb/debian/changelog
stack/indexer/deb/debian/rules
stack/indexer/indexer-ism-init.sh
stack/indexer/rpm/build_package.sh
stack/indexer/rpm/wazuh-indexer.spec
unattended_installer/builder.sh

|---|
|#2740|
This PR aims to merge branch 4.8.0 into 4.8.1.

Merge 4.8.0 into 4.8.1

---

aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
ova/generate_ova.sh
ova/wazuh_ovf_template
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/base/builder.sh
stack/indexer/base/generate_base.sh
stack/indexer/deb/build_package.sh
stack/indexer/deb/debian/changelog
stack/indexer/deb/debian/rules
stack/indexer/indexer-ism-init.sh
stack/indexer/rpm/build_package.sh
stack/indexer/rpm/wazuh-indexer.spec
unattended_installer/builder.sh

|---|
|#2740|
This PR aims to merge branch 4.8.1 into 4.8.2.

Merge 4.8.1 into 4.8.2

---

CHANGELOG.md
aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
ova/generate_ova.sh
ova/wazuh_ovf_template
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/base/builder.sh
stack/indexer/base/files/usr/lib/systemd/system/wazuh-indexer-performance-analyzer.service
stack/indexer/base/generate_base.sh
stack/indexer/deb/build_package.sh
stack/indexer/deb/debian/changelog
stack/indexer/deb/debian/rules
stack/indexer/indexer-ism-init.sh
stack/indexer/rpm/build_package.sh
stack/indexer/rpm/wazuh-indexer.spec
unattended_installer/builder.sh
unattended_installer/passwords_tool/passwordsFunctions.sh

|---|
|#2740|
This PR aims to merge branch 4.8.2 into master.

Merge 4.8.2 into master

---

ova/Vagrantfile
ova/assets/postProvision.sh
ova/assets/steps.sh
ova/provision.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2816|
The aim of this PR is to improve the clean-up stage of the OVA generation. To achieve this, a `postProvision.sh` script has been added and some steps (such as removing Wazuh indices and logs) have been included.
Related PR: https://github.com/wazuh/wazuh-jenkins/pull/6268
Complete testing is in: https://github.com/wazuh/wazuh-packages/issues/2816#issuecomment-1943654802

Improved clean-up in OVA generation

---

.github/actions/offline-installation/common.sh
unattended_installer/install_functions/indexer.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2833|
The aim of this PR is to roll back the ISM development that was performed in the Wazuh installation assistant. This also affects the Offline installation GHA.
It must be considered that this PR depends on: https://github.com/wazuh/wazuh/pull/21968. These changes have been performed manually in order to speed up the process.
Testing is in: https://github.com/wazuh/wazuh-packages/issues/2833#issuecomment-1954284822
GHA is being tested in: https://github.com/wazuh/wazuh-packages/actions/runs/7976672784

Rollback ISM changes in Installation Assistant

---

.github/actions/offline-installation/common.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2833|
The aim of this PR is to fix the Offline GHA that presented some syntax errors. This PR is complementary to https://github.com/wazuh/wazuh-packages/pull/2835
The workflow has been tested here: https://github.com/wazuh/wazuh-packages/actions/runs/7988481431

Fix Offline GHA

---

ova/provision.sh

|---|
|https://github.com/wazuh/wazuh-packages/issues/2833|
The aim of this PR is to roll back the changes of ISM in the case of OVA generation.
Testing is in: https://github.com/wazuh/wazuh-packages/issues/2833#issuecomment-1959277751

Rollback ISM changes in OVA

---

debs/SPECS/wazuh-manager/debian/rules
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec

|---|
|https://github.com/wazuh/wazuh-packages/issues/2845|
This PR reverts changes related to the SCA files for Amazon Linux 2023 and Rocky Linux 8.

Revert changes related to amazon linux 2023 and rocky linux 8 sca files

---

hp-ux/generate_wazuh_packages.sh

|---|
|https://github.com/wazuh/wazuh/issues/19251|
From 4.5 to 4.6 there was a considerable increase in size for HP-UX due to this change https://github.com/wazuh/wazuh-packages/commit/943eef91749f312ba4c9a21c315c5777c74ae5be related to this implementation https://github.com/wazuh/wazuh/pull/12745
Compilation successful
Package created
Installation
[wazuh-agent-4.8.0-1-hpux-11v3-ia64.tar.gz](https://github.com/wazuh/wazuh-packages/files/14515115/wazuh-agent-4.8.0-1-hpux-11v3-ia64.tar.gz)
[wazuh-agent-4.8.0-1-hpux-11v3-ia64.tar.gz.sha512.txt](https://github.com/wazuh/wazuh-packages/files/14515121/wazuh-agent-4.8.0-1-hpux-11v3-ia64.tar.gz.sha512.txt)
Documentation changes branch 
https://github.com/wazuh/wazuh-documentation/tree/enhancement/19251-reduce-hp-ux-package-size

Compress HPUX package to reduce size without any extra dependencies

---

unattended_installer/install_functions/dashboard.sh

|---|
| #2888 |
The variable name was fixed.
Test results are [here](https://github.com/wazuh/wazuh-packages/issues/2888#issuecomment-2023413533).

Port variable name fixed

---

hp-ux/generate_wazuh_packages.sh
rpms/SPECS/wazuh-manager.spec
rpms/build.sh
stack/dashboard/base/builder.sh
unattended_installer/install_functions/dashboard.sh
unattended_installer/install_functions/filebeat.sh
unattended_installer/install_functions/installCommon.sh
unattended_installer/passwords_tool/passwordsFunctions.sh

Merge 4.9.0 into master

---

aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-agent/debian/copyright
debs/SPECS/wazuh-manager/debian/changelog
debs/SPECS/wazuh-manager/debian/copyright
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/deb/debian/copyright
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/deb/debian/copyright
stack/indexer/rpm/wazuh-indexer.spec

Change ETA for 4.7.4

---

CHANGELOG.md
aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-agent/debian/copyright
debs/SPECS/wazuh-manager/debian/changelog
debs/SPECS/wazuh-manager/debian/copyright
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/deb/debian/copyright
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/deb/debian/copyright
stack/indexer/rpm/wazuh-indexer.spec

Merge 4.7.4 into 4.8.0

---

rpms/SPECS/wazuh-manager.spec
tests/unattended/install/test_unattended.py

|---|
| Closes https://github.com/wazuh/wazuh/issues/22608 |
Updates the API script file name.
Checks from the main PR: https://github.com/wazuh/wazuh/pull/23222
amd64: https://ci.wazuh.info/job/Packages_builder/197205
arm64v8: https://ci.wazuh.info/job/Packages_builder/197206

Update API script file name

---

CHANGELOG.md
aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/rpm/wazuh-indexer.spec

|---|
|https://github.com/wazuh/wazuh-packages/issues/2959|

Merge 4.7.5 into 4.8.0

---

aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-agent/debian/copyright
debs/SPECS/wazuh-manager/debian/changelog
debs/SPECS/wazuh-manager/debian/copyright
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/deb/debian/copyright
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/deb/debian/copyright
stack/indexer/rpm/wazuh-indexer.spec

Update 4.7.5 release date

---

CHANGELOG.md
aix/SPECS/wazuh-agent-aix.spec
debs/SPECS/wazuh-agent/debian/changelog
debs/SPECS/wazuh-manager/debian/changelog
rpms/SPECS/wazuh-agent.spec
rpms/SPECS/wazuh-manager.spec
stack/dashboard/deb/debian/changelog
stack/dashboard/rpm/wazuh-dashboard.spec
stack/indexer/deb/debian/changelog
stack/indexer/rpm/wazuh-indexer.spec

|---|
|https://github.com/wazuh/wazuh-packages/issues/2997|

Merge 4.8.1 into 4.9.0

---

unattended_installer/passwords_tool/passwordsFunctions.sh

close https://github.com/wazuh/wazuh-packages/issues/3013
An update is made to the execution of the hash.sh script so that it does not display the script deprecation message.
<details>
<summary>Test without changes</summary>
```console
[root@centos8 ~]# bash wazuh-install.sh -a
24/06/2024 17:08:55 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
24/06/2024 17:08:55 INFO: Verbose logging redirected to /var/log/wazuh-install.log
24/06/2024 17:08:55 INFO: Verifying that your system meets the recommended minimum hardware requirements.
24/06/2024 17:08:55 INFO: Wazuh web interface port will be 443.
24/06/2024 17:08:56 WARNING: The system has Firewalld enabled. Please ensure that traffic is allowed on these ports: 1515, 1514, 443.
24/06/2024 17:08:57 INFO: Wazuh development …
```

Fixed deprecation message for hash.sh script
